- bytedance/.gitignore
- bytedance/README.md
- bytedance/config/crd/kustomization.yaml
- bytedance/config/default/kustomization.yaml
- bytedance/config/manager/kustomization.yaml
- bytedance/config/manager/manager.yaml
- bytedance/config/rbac/kustomization.yaml
- bytedance/config/rbac/leader_election_role.yaml
- bytedance/config/rbac/leader_election_role_binding.yaml
- bytedance/config/rbac/role_binding.yaml
- bytedance/config/rbac/service_account.yaml
Kubebuilder generated files naming are messy and I did some clean ups.
> Clean up kustomization manifests

- .github/workflows/test-job.yaml
- ray-operator/.dockerignore
- ray-operator/.gitignore
- ray-operator/Dockerfile
- ray-operator/Makefile
- ray-operator/api/v1alpha1/raycluster_types.go
- ray-operator/config/manager/manager.yaml
- ray-operator/controllers/raycluster_controller.go
- ray-operator/main.go
Address #30 #25 https://github.com/ray-project/ray-contrib/issues/24 This change helps resolve CI problem. check #30 for more details.
1. Deprecate genclient and deepcopy-gen markers
2. Add health/ready check and use nonroot user in deployment
3. Fix github workflow issue
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
/cc @akanso @chenk008 @chaomengyuan
> Upgrade Kubebuilder to 3.0.0 and optimize Github workflow

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/pull_request_template.md
> Add issue and pr templates

- .github/ISSUE_TEMPLATE/bug-report.yml
Add "ci" and "apiserver" options in bug template
#120 
> [Feature] add more options in bug template

- .github/workflows/test-job.yaml
add docker build actions to ci
#69 
> [Feature]add docker build stage to ci workflow

- ray-operator/controllers/raycluster_controller.go
Fix potential issue of index out of range crash
#124
> fix issue that modifies the list while iterating through it

- apiserver/Dockerfile
- apiserver/deploy/base/apiserver.yaml
- apiserver/deploy/base/kustomization.yaml
With this change, user can easily deploy the kuberay apiserver.
resolve #88 
> Add deploy manifests for apiserver

- README.md
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/templates/_helpers.tpl
- helm-chart/kuberay-operator/templates/deployment.yaml
- helm-chart/kuberay-operator/templates/role.yaml
- helm-chart/kuberay-operator/templates/rolebinding.yaml
- helm-chart/kuberay-operator/templates/service.yaml
- helm-chart/kuberay-operator/templates/serviceaccount.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/README.md
s/kubray/kuberay across all files
> refactor: rename kubray -> kuberay

- .github/workflows/test-job.yaml
add nightly docker build workflow
add workflow for nightly operator build
#70 
> add nightly docker build workflow

- .github/workflows/test-job.yaml
More debug information for goimport failure
#150 
> add more debug info for bug-150: goimport issue

- .github/workflows/test-job.yaml
CI doesn't cover new components, since we plan to cut a v0.2.0 release soon, this should be definitely improved.
Address https://github.com/ray-project/kuberay/issues/117
> Setup ci for apiserver

- docs/release/README.md
Container images and artifacts should be well tagged and distributed along each release. I add this guideline to clearly show the release steps and it has been used in v0.1.0 and we will apply it to v0.2.0 as well and keep improving it.
part of https://github.com/ray-project/kuberay/issues/70
> Add KubeRay release guideline

- cli/pkg/cmd/cluster/create.go
1. Fix a little typo.
2. `worker-group-name` is required
> Fix cli typo

- docs/guidance/autoscaler.md
- ray-operator/config/samples/ray-cluster.autoscaler.yaml
Give user better guidance on enabling autoscaling.
> Add documentation for autoscaling feature

- manifests/base/kustomization.yaml
Pin release tag to v0.2.0
#193 
> Pin release tag to v0.2.0

- .github/workflows/test-job.yaml
- helm-chart/ray-cluster/values.yaml
- ray-operator/config/samples/ray-cluster.autoscaler.yaml
- ray-operator/config/samples/ray-cluster.complete.yaml
- ray-operator/config/samples/ray-cluster.getting-started.yaml
- ray-operator/config/samples/ray-cluster.heterogeneous.yaml
- ray-operator/config/samples/ray-cluster.ingress.yaml
- ray-operator/config/samples/ray-cluster.mini.yaml
- ray-operator/config/samples/ray-cluster.without-block.yaml
- tests/config/ray-cluster.mini.yaml.template
add ray 1.11 to compatibility test
#185 
> add 1.11 to compatibility test and update comment

- .github/workflows/site.yaml
Use a new github action to test doc CI.
#228 
> Use mhausenblas/mkdocs-deploy-gh-pages action for docs

- README.md
- config/grafana/dashboard_default.json
- config/prometheus/monitor.yaml
- install/prometheus/install.sh
- ray-operator/controllers/common/constant.go
- ray-operator/controllers/common/pod.go
- ray-operator/controllers/common/pod_test.go
- ray-operator/controllers/common/service.go
@Jeffwan 
This pr will enable the specific prometheus stack for kuberay, including some setting for service monitor and the configurations for the grafana dashboard.
> Enable metrics-export-port by default and configure prometheus monitoring

- .github/workflows/test-job.yaml
This replaced 1.8.0 compatibility test with 1.12.0 compatibility test
#226 
> Support ray 1.12

- README.md
Add the documentation link from repo readme, otherwise it is really hard to find it.
> Add documention link in readme

- ray-operator/controllers/raycluster_controller_test.go
some of the tests are flaky, i updated the timeout time.
N/A
> [bugfix]update flaky test timeout

- ray-operator/controllers/common/pod.go
- ray-operator/controllers/common/rbac.go
- ray-operator/controllers/raycluster_controller.go
- ray-operator/controllers/raycluster_controller_fake_test.go
- ray-operator/controllers/raycluster_controller_test.go
- ray-operator/controllers/utils/util.go
- ray-operator/controllers/utils/util_test.go
> fix: use configured RayCluster service account when autoscaling

- ray-operator/Makefile
> Fix the image name in deploy cmd

- apiserver/pkg/util/cluster.go
> Fix gpu-accelerator in template

- cli/README.md
- cli/pkg/cmd/cluster/create.go
- proto/config.proto
- proto/go_client/config_grpc.pb.go
- proto/swagger/config.swagger.json
s/compuate/compute/g
No-op otherwise
> fix typos in comments and help messages

- README.md
update readme and fix bug
#286 
> update readme and address issue #286

- docs/guidance/autoscaler.md
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
Updates the autoscaler image to reflect changes from https://github.com/ray-project/ray/pull/25386
> [minor] Update autoscaler image.

- tests/compatibility-test.py
print more information for compatibility test failures.
#351 
> provide more detailed information in case of test failures

- mkdocs.yml
Add gcs ha doc to public website.
> Add gcs ha doc into mkdocs

- ray-operator/controllers/ray/common/pod.go
enable ray external storage namespace environment variable
#294 
> enable ray external storage namespace

- apiserver/pkg/util/cluster.go
fix: typo RAY_DISABLE_DOCKER_CPU_WRARNING -> RAY_DISABLE_DOCKER_CPU_WARNING
> fix: typo RAY_DISABLE_DOCKER_CPU_WRARNING -> RAY_DISABLE_DOCKER_CPU_WARNING

- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/values.yaml
- manifests/base/kustomization.yaml
```
docker pull kuberay/apiserver:eaa75fa
docker pull kuberay/operator:eaa75fa
docker tag kuberay/apiserver:eaa75fa kuberay/apiserver:v0.3.0-rc.0
docker tag kuberay/operator:eaa75fa kuberay/operator:v0.3.0-rc.0
```
I update images to use in release branch and then I will cut a new PR to update README.md
> Update docker images to v0.3.0-rc.0

- apiserver/pkg/util/cluster.go
- apiserver/pkg/util/job.go
> Fix master branch build error.

- ray-operator/controllers/ray/common/pod.go
add timeout to wget command
N/A
> add wget timeout to probes

- .github/workflows/test-job.yaml
- docs/guidance/rayservice.md
- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
- ray-operator/config/samples/ray-cluster.autoscaler.large.yaml
- ray-operator/config/samples/ray-cluster.autoscaler.yaml
- ray-operator/config/samples/ray-cluster.complete.large.yaml
- ray-operator/config/samples/ray-cluster.complete.yaml
- ray-operator/controllers/ray/common/constant.go
- ray-operator/controllers/ray/common/ingress.go
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/utils/dashboard_httpclient.go
- ray-operator/controllers/ray/utils/httpproxy_httpclient.go
- ray-operator/controllers/ray/utils/util.go
I cherry-pick recent master fixes and minor features to `release-0.3`. Please have a check. I will cut a `v0.3.0-rc.1` for final testing after this is merged. If there's no additional feedback, we will cut v0.3.0 official release. 
Please help checking anything PRs need to be cherry-picked. 
/cc @DmitriGekhtman @pingsutw @brucez-anyscale @iycheng @wilsonwang371 
https://github.com/ray-project/kuberay/issues/349
> Cherry pick master fixes to 0.3 release

- helm-chart/kuberay-operator/values.yaml
- manifests/base/kustomization.yaml
To release v0.3.0-rc.1
- [x ] Manual tests
> Update docker images to v0.3.0-rc.1

- .github/workflows/test-job.yaml
> Fix docker image push against release-0.3 branch

- docs/guidance/observability.md
Add document for the `raycluster` status.
#454 
> document the raycluster status

- docs/best-practice/worker-head-reconnection.md
- docs/guidance/gcs-ft.md
- mkdocs.yml
- ray-operator/config/samples/ray-cluster.external-redis.yaml
- ray-operator/controllers/ray/common/constant.go
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/raycluster_controller.go
- tests/compatibility-test.py
- tests/config/ray-cluster.ray-ft.yaml.template
> correct gcs ha to gcs ft (#482)

- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/utils/dashboard_httpclient.go
- ray-operator/controllers/ray/utils/util.go
> Cherry pick bug fixes to 0.3 release

- apiserver/deploy/base/kustomization.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/values.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
> Update docker images to v0.3.0-rc.2

- .github/workflows/test-job.yaml
> Update latest image tag to push in release-branch

- apiserver/deploy/base/kustomization.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/values.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
> Update docker images to v0.3.0

- apiserver/README.md
Add docs for new apis in apiserver.
Following of #456 and #416 
> apiserver add new api docs

- .github/workflows/test-job.yaml
support ray 2.0.0 compatibility test
N/A
> support ray 2.0.0 in compatibility test

- docs/deploy/installation.md
- docs/guidance/rayservice.md
- docs/notebook/kuberay-on-kind.ipynb
- ray-operator/README.md
I followed the [document](https://github.com/ray-project/kuberay/tree/master/ray-operator), and failed to deploy operator. I tried to revisit all documents about operator deployment, and summarized it in issue #524.
#524 
- [v] I've made sure the tests are passing. 
- [v] Manual tests
> Failure happened when install operator with kubectl apply

- helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml
- helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml
Closes https://github.com/ray-project/kuberay/issues/538 by syncing CRDs in Helm chart with CRDs in ray-operator config directory -- I ran
```
cp ray-operator/config/crd/bases/* helm-chart/kuberay-operator/crds/
```
Long-term potential solutions here are:
- Have the CI sync the CRDs
- Delete the CRDs in the ray-operator Helm chart, ask users to install the CRDs separately.
> Sync Helm chart CRDS

- helm-chart/kuberay-operator/README.md
Ref: https://github.com/ray-project/kuberay/issues/271#issuecomment-1238287621
docs only
> docs: Add instructions for working with Argo CD

- ray-operator/controllers/ray/rayservice_controller.go
> Fix initial health check not obeying deploymentUnhealthySecondThreshold

- ray-operator/README.md
- ray-operator/config/samples/ray-cluster.heterogeneous.yaml
The example program doesn't get executed as specified in the readme. This PR updated the readme to give users instructions to execute the example program and show what the result should look like. Besides, this PR upgrades the image to 2.0.0 to allow submitting jobs to Ray cluster, and removes object-manager-port and node-manager-port configuration to avoid port conflicts.
Closes https://github.com/ray-project/kuberay/issues/583
> Update ray-operator documentation and image version in ray-cluster.heterogeneous.yaml

- docs/deploy/docker.md
- docs/development/development.md
- mkdocs.yml
- Adds a bit of info on docker images to the docs.
- Tweaks dev instructions on doc development. (The current instructions don't quite work for me.)
> [doc] Add a tip on docker images

- docs/guidance/rayjob.md
- The bullet points are not parsed correctly in rayjob doc
- before
- after
> [minor] Add newline to enable bullet point parsing

- mkdocs.yml
Feature documentation of KubeRay Integration with MCAD shows 404
> fix mkdocs URL

- README.md
Revises the main README for clarity and consistency with [other documentation](https://ray-project.github.io/kuberay/deploy/installation/).
FYI @Jeffwan :)
Closes #515 
N/A
> [doc] Reformat README.md

- tests/framework/prototype.py
Refactor the framework by following Pylint conventions to improve readability.
```bash
cd tests/framework
python3 prototype.py # Expected result: 3 passes; 3 failures
```
> Refactor configuration test framework to follow Pylint conventions

- helm-chart/kuberay-operator/templates/deployment.yaml
- helm-chart/kuberay-operator/values.yaml
> Change Kuberay operator Deployment strategy type to Recreate

- README.md
- docs/index.md
Adds links to the official Ray docs.
This complements the KubeRay links in the Ray docs: https://docs.ray.io/en/latest/cluster/kubernetes/index.html#about-kuberay
> Cross-reference docs.

- docs/guidance/rayservice.md
The [content](https://ray-project.github.io/kuberay/guidance/rayservice/#what-is-a-rayservice) format is displayed incorrectly. 
> [docs] Fix markdown in ray services

- docs/guidance/volcano-integration.md
- ray-operator/controllers/ray/batchscheduler/interface/interface.go
> [docs] Updated Volcano integration documentation

- README.md
- docs/guidance/autoscaler.md
- docs/index.md
Minor improvements to the docs ahead of the release.
I verified that all instructions in the edited files works as expected with master branch configs.
> [0.4.0 Release] Minor doc improvements

- .github/workflows/consistency-check.yaml
Pin Go 1.17 in CRD consistency check.
Picks the CI fix #794 into the 0.4 branch.
> [CI] Pin go version in CRD consistency check (#794)

- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/values.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
Update image tags in the KubeRay 0.4.0 release branch in preparation for an rc release.
> Update image tags.

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/ray-cluster/Chart.yaml
Update Helm chart versions for KubeRay 0.4.0 release. This is a PR for the release branch.
I think it's fine to use the same version string for all fields.
Dunno how best to set these things in master (set them all to "nightly"?).
> Update chart versions for 0.4.0-rc.0

- ray-operator/config/samples/ray-cluster.ingress.yaml
- ray-operator/config/samples/ray-cluster.separate-ingress.yaml
- ray-operator/config/samples/ray_v1alpha1_rayjob.yaml
- ray-operator/config/samples/ray_v1alpha1_rayservice.yaml
- tests/config/ray-service.yaml.template
Closes https://github.com/ray-project/kuberay/issues/805 which was caused by incomplete config cleanup in https://github.com/ray-project/kuberay/pull/761 .
> [RayJob][Doc] Fix RayJob sample config.

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
This PR updates version tags in the release branch to 0.4.0.
Once this PR is committed to the release branch, final 0.4.0 artifacts will be built from the branch.
This PR should only be merged once we're ready to go through with the final release.
I've made a decision here to remove appVersions for the Helm charts. 
appVersion is optional and I don't believe we need an extra version string floating around.
I'm open to keeping appVersion if anyone thinks it's needed.
> [0.4.0 Release] Update tags to 0.4.0

- ray-operator/controllers/ray/rayservice_controller.go
Skip RayService reconcile when there is no config/label/annotation change
Signed-off-by: Sihan Wang <sihanwang41@gmail.com>
Pick https://github.com/ray-project/kuberay/pull/811 into 0.4.0 release branch.
> [RayService] Skip update events without change (#811)

- tests/compatibility-test.py
Currently, some tests create docker containers to communicate with Kubernetes via a NodePort service. It is complex and unstable. Hence, this PR executes commands in the head Pod via `kubectl exec` instead of creating a docker container. See #764 for more details.
Part of #764 
> Remove Docker from BasicRayTestCase

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
This PR is Step 3.a in [release.md](https://github.com/ray-project/kuberay/blob/00dc45aec34fc3ae54962361221b41aaa4c338da/docs/development/release.md). The similar PRs in 0.4.0 are https://github.com/ray-project/kuberay/pull/784 and https://github.com/ray-project/kuberay/pull/804.
> [release v0.5.0-rc.0] Update tags and versions

- .github/workflows/test-job.yaml
- clients/python-client/python_client/utils/kuberay_cluster_utils.py
- clients/python-client/requirements.txt
- clients/python-client/setup.cfg
> [Cherrypick] Fix compatibility between Python client and KubeRay

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
> [release v0.5.0] Update tags and versions 

- CHANGELOG.md
Update CHANGELOG.md
Step 8 in [release.md](https://github.com/ray-project/kuberay/blob/6c0fbbefd92e55d393524f5d90895974d90029b0/docs/development/release.md)
> [Post release v0.5.0] Update CHANGELOG.md

- ray-operator/README.md
Fix the link error of operator document.
The issue is:
https://github.com/ray-project/kuberay/issues/1045
Only change the document, didn't change the code
> [Bug][Doc] fix the link error of operator document

- README.md
- docs/index.md
Just a one word typo that I noticed while browsing the docs for this project.
N/A it's just a typo fix
> [Docs][Website] One word typo fix in docs and README

- helm-chart/kuberay-operator/values.yaml
- ray-operator/config/manager/manager.yaml
There are some envs in kuberay to configure its behavior. However, we currently lack the documentation. I add the env and comments in both helm and customization.
> Add env variable comment to kuberay-operator

- README.md
Adding KubeRay related articles
- [ x] This PR is not tested :(
> Add KubeRay related blogs

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
This PR is Step 3.a in [release.md](https://github.com/ray-project/kuberay/blob/00dc45aec34fc3ae54962361221b41aaa4c338da/docs/development/release.md). 
Compare with the analogous PR for 0.5.0 (should be exactly the same except for the version number): https://github.com/ray-project/kuberay/pull/1001
> [release v0.5.2] Update tags and versions to 0.5.2

- docs/release/helm-chart.md
Without this change, `helm search repo kuberay` may just print the old versions (at least, that's what it did for me.)
> [Doc] Add `helm update` command to chart validation step in release process

- docs/deploy/installation.md
The current install instruction for single namepsace installation uses nightly image.
This pins it to a released version
Closes #1193
> Pin operator version in single namespace installation(#1193)

- docs/guidance/rayservice.md
> [RayService][docs] Improve explanation for config file and in-place updates

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
This PR is Step 3 in [release.md](https://github.com/ray-project/kuberay/blob/release-0.6/docs/development/release.md). The similar PRs in 0.5.0 are #1001.
> [release v0.6.0-rc.0] Update tags and versions

- helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml
- helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml
- helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml
- ray-operator/apis/ray/v1alpha1/raycluster_types.go
- ray-operator/config/crd/bases/ray.io_rayclusters.yaml
- ray-operator/config/crd/bases/ray.io_rayjobs.yaml
- ray-operator/config/crd/bases/ray.io_rayservices.yaml
> [cherry-pick][0.6.0] Fix typo (#1241)

- ray-operator/config/samples/ray_v1alpha1_rayjob.yaml
> [cherry-pick][0.6.0][Doc] Fix the order of comments in sample Job YAML file (#1242)

- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/raycluster_controller_fake_test.go
- ray-operator/main.go
> [cherry-pick][0.6.0][Autoscaler] Randomly delete Pods when scaling down the cluster (#1251)

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
This PR is Step 3 in [release.md](https://github.com/ray-project/kuberay/blob/release-0.6/docs/development/release.md). The similar PRs in 0.5.0 are https://github.com/ray-project/kuberay/pull/1001.
> [release v0.6.0-rc.1] Update tags and versions

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
> [release v0.6.0] Update tags and versions

- CHANGELOG.md
> [Post release v0.6.0] Update CHANGELOG.md

- ray-operator/config/samples/ray-cluster.gke-bucket.yaml
- ray-operator/config/samples/ray-job.batch-inference.yaml
- tests/test_sample_raycluster_yamls.py
Adds a new YAML file for the GKE bucket tutorial.  Resolves https://github.com/ray-project/ray/pull/38858#discussion_r1309139598
> [Doc] Add gke bucket yaml

- tests/compatibility-test.py
There are thorough RayService tests in [test_sample_rayservice_yamls.py](https://github.com/ray-project/kuberay/blob/master/tests/test_sample_rayservice_yamls.py). We can remove the sanity check test for RayService in `compatibility-test.py`.
> [CI] Remove RayService tests from comopatibility-test.py

- ray-operator/config/samples/ray-cluster.autoscaler.yaml
This PR is required for https://github.com/ray-project/ray/pull/39345.
https://github.com/ray-project/ray/pull/39345
> Update Autoscaler YAML for the Autoscaler tutorial

- ray-operator/config/samples/ray-service.text-ml.yaml
Use french in user config because that's what all the examples in the docs start with.
> [serve] Change text ml yaml to use french in user config

- apiserver/cmd/main.go
- apiserver/deploy/base/apiserver.yaml
- helm-chart/kuberay-apiserver/templates/deployment.yaml
- helm-chart/kuberay-apiserver/values.yaml
Current implementation of the API server does not provide health endpoint and as a result does not provide liveness/readiness probe for the deployment
- [ X] I've made sure the tests are passing. 
- [ X] Manual tests
> implemented liveness/readyness probe for the API server

- ray-operator/config/samples/ray-cluster.external-redis.yaml
https://github.com/ray-project/ray/pull/39450
https://github.com/ray-project/ray/pull/39450
> Update GCS fault tolerance YAML

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
This PR is similar to https://github.com/ray-project/kuberay/pull/1001.
> [release v1.0.0-rc.0] Update tags and versions

- .github/workflows/image-release.yaml
- README.md
- docs/deploy/images.md
Typically, we do not update docs for release candidates, but v1.0 is crucial. Therefore, we have decided to update the documentation to encourage users to use v1.0.0-rc.0 as much as possible.
Check https://github.com/kevin85421/kuberay/tree/update-readme-v1
> [Doc] Update README

- docs/deploy/installation.md
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/README.md
- helm-chart/ray-cluster/Chart.yaml
- helm-chart/ray-cluster/README.md
> Update Kuberay doc to version 1.0.0 rc.0

- docs/components/media/create-ray-cluster.gif
- docs/components/media/logs-ray-cluster.gif
- docs/components/media/overview.png
- docs/components/media/update-ray-cluster.gif
- docs/components/operator.md
* https://github.com/ray-project/kuberay/actions/runs/6304250017/job/17115207709
```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```
> Fix mkDocs

- ray-operator/controllers/ray/rayservice_controller.go
> doc: fix moved link

- .buildkite/test-sample-yamls.yml
- tests/framework/utils.py
> [CI] Update latest release to v1.0.0-rc.0 in tests

- README.md
- ray-operator/DEVELOPMENT.md
- ray-operator/Makefile
Update local operator development instruction
> Update operator development instruction

- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
See https://github.com/ray-project/ray/pull/40357 for more details.
#1481
#1492 
> [CRD] Inject CRD version to the Autoscaler sidecar container

- .github/workflows/image-release.yaml
- README.md
- docs/deploy/images.md
> [Cherry-pick][Doc] Update README (#1433)

- docs/deploy/installation.md
- helm-chart/kuberay-operator/README.md
- helm-chart/ray-cluster/README.md
> [Cherry-pick] Update Kuberay doc to version 1.0.0 rc.0

- ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go
- ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler_test.go
> use raycluster app's name as podgroup name key word (#1446)

- docs/components/media/create-ray-cluster.gif
- docs/components/media/logs-ray-cluster.gif
- docs/components/media/overview.png
- docs/components/media/update-ray-cluster.gif
- docs/components/operator.md
> Fix mkDocs (#1448)

- helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml
- helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml
- helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml
- ray-operator/apis/ray/v1alpha1/raycluster_types.go
- ray-operator/config/crd/bases/ray.io_rayclusters.yaml
- ray-operator/config/crd/bases/ray.io_rayjobs.yaml
- ray-operator/config/crd/bases/ray.io_rayservices.yaml
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/raycluster_controller_fake_test.go
- ray-operator/controllers/ray/utils/util.go
- ray-operator/controllers/ray/utils/util_test.go
> [Cherry-pick][Feature] Make replicas optional for WorkerGroupSpec (#1443)

- apiserver/README.md
> [Cherry-pick] Updated API server documentation (#1435)

- ray-operator/apis/ray/v1alpha1/rayjob_types.go
- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/rayjob_controller_test.go
- ray-operator/controllers/ray/rayservice_controller_test.go
- ray-operator/controllers/ray/utils/fake_serve_httpclient.go
- tests/framework/prototype.py
> [Cherry-pick][Bug][RayJob] Check dashboard readiness before creating job pod (#1429)

- tests/test_sample_raycluster_yamls.py
> [CI] Skip redis raycluster test (#1465)

- ray-operator/controllers/ray/rayservice_controller.go
> [Cherry-pick] doc: fix moved link (#1462)

- .buildkite/test-sample-yamls.yml
> [Cherry-pick][CI] Reenable rayjob sample yaml latest test (#1464)

- .buildkite/test-sample-yamls.yml
- tests/framework/utils.py
> [Cherry-pick] Update latest release to v1.0.0-rc.0 in tests (#1467)

- ray-operator/controllers/ray/rayservice_controller_unit_test.go
> [Cherry-pick][Refactor] Parameterize TestGetAndCheckServeStatus (#1450)

- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
> [Cherry-pick][Enhancement] GPU RayCluster doesn't work on GKE Autopilot (#1470)

- ray-operator/controllers/ray/common/constant.go
> [Cherry-pick][Enhancement] Remove unused variables in constant.go (#1474)

- tests/framework/prototype.py
> [Cherry-pick][Test][GCS FT] End-to-end test for cleanup_redis_storage (#1466)

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
> [Cherry-pick] Helm chart ray-cluster template reference fix (#1469)

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
> [Cherry-pick] Remove miniReplicas in raycluster-cluster.yaml (#1473)

- README.md
- ray-operator/DEVELOPMENT.md
- ray-operator/Makefile
> [Cherry-pick] Update operator development instruction (#1458)

- ray-operator/Dockerfile
> [Cherry-pick] Update Dockerfile to address closed CVEs (#1488)

- ray-operator/Dockerfile
- ray-operator/Makefile
> [Cherry-pick] Remove GOARCH in ray-operator/Dockfile to support multi-arch images (#1442)

- tests/test_sample_raycluster_yamls.py
> [Cherry-pick] Revert "[CI] Skip redis raycluster test" (#1490)

- config/prometheus/serviceMonitor.yaml
- ray-operator/config/samples/ray-cluster.embed-grafana.yaml
> [Cherry-pick][Feature][Observability] Scrape Autoscaler and Dashboard metrics (#1493)

- apiserver/pkg/util/cluster_test.go
> [Cherry-pick] fixed volumes test in cluster test (#1498)

- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
> [Cherry-pick][CRD] Inject CRD version to the Autoscaler sidecar container (#1496)

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.0.0-rc.1] Update tags and versions

- docs/development/release.md
#1574 accidentally removed ` ``` ` and caused the following format issue.
> [Doc] Fix release doc format

- apiserver/Dockerfile
- proto/Dockerfile
- ray-operator/Dockerfile
> [Cherry-pick] Update Dockerfiles to address CVE-2023-44487 (HTTP/2 Rapid Reset) (#1540)

- docs/development/release.md
> [Cherry-pick][Release][Doc] Add instructions to release Go modules. (#1546)

- ray-operator/controllers/ray/common/job.go
- ray-operator/controllers/ray/common/job_test.go
- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/rayjob_controller_unit_test.go
> [Cherry-pick][RayJob] Always use target RayCluster image as default RayJob submitter image (#1548)

- ray-operator/controllers/ray/rayjob_controller_test.go
> [Cherry-pick][Test][Bug] Update worker replias idempotently in rayjob autoscaler envtest (#1471) (#1543)

- README.md
- docs/guidance/kuberay-with-MCAD.md
> [Cherry-pick] Update kuberay mcad integration doc (#1373)

- ray-operator/config/samples/ray-service.mobilenet.yaml
> [Cherry-pick][Bug] RayService with GCS FT HA issue (#1551)

- apiserver/README.md
- apiserver/pkg/util/job.go
- apiserver/pkg/util/job_test.go
> [Cherry-pick] Fixed processing of job submitter (#1562)

- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/main.go
> [Cherry-pick][RayJob] Fix RayJob status reconciliation (#1539)

- helm-chart/kuberay-operator/values.yaml
- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/rayservice_controller_test.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
> [Cherry-pick][Feature] Add a flag to make zero downtime upgrades optional (#1564)

- ray-operator/config/samples/ray-service.high-availability.yaml
> [Cherry-pick][Feature] Add an example for RayService high availability (#1566)

- .github/workflows/image-release.yaml
- docs/development/release.md
> [Cherry-pick][CI] Create release tag for ray-operator Go module (#1574)

- ray-operator/config/samples/ray-cluster.external-redis-uri.yaml
- ray-operator/controllers/ray/raycluster_controller.go
> [Cherry-pick][Bug][RayCluster] Fix RAY_REDIS_ADDRESS parsing with redis scheme and multiple addresses (#1556)

- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
> [Cherry-pick][Hotfix][Bug] Avoid unnecessary zero-downtime upgrade (#1581)

- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/rayjob_controller_unit_test.go
> [Cherry-pick][Bug][RayJob] Fix FailedToGetJobStatus by allowing transition to Running (#1583)

- tests/compatibility-test.py
- tests/framework/prototype.py
- tests/framework/utils.py
- tests/test_sample_raycluster_yamls.py
- tests/test_sample_rayjob_yamls.py
- tests/test_sample_rayservice_yamls.py
- tests/test_security.py
> [Cherry-pick] Allow to install and remove operator via scripts (#1545)

- tests/framework/prototype.py
> [Cherry-pick][Bug] Fix flaky sample YAML tests (#1590)

- ray-operator/controllers/ray/raycluster_controller.go
> [Cherry-pick][GCS FT] Improve GCS FT cleanup UX (#1592)

- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/rayjob_controller_test.go
> [Cherry-pick][Feature] Improve observability for flaky RayJob test (#1587)

- ray-operator/main.go
> [Cherry-pick] fix: odd number of arguments (#1594)

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.0.0-rc.2] Update tags and versions

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.0.0] Update tags and versions

- apiserver/pkg/model/converter.go
- apiserver/pkg/model/converter_test.go
> Flip Min and max replicas for apiserver workerNodeSpec

- ray-operator/test/e2e/rayjob_test.go
- ray-operator/test/e2e/support.go
- ray-operator/test/support/batch.go
- ray-operator/test/support/ray.go
- ray-operator/test/support/support.go
This PR adds e2e test following up #1539 and leverages #1575.
It also factorises configuration across the RayJob e2e tests.
> [RayJob]: Add RayJob with RayCluster spec e2e test

- ray-operator/Dockerfile
cc @kevin85421  This is a cherry-pick PR for the FIPS changes
> Make KubeRay Operator Image FIPS compliant (#1633)

- ray-operator/config/samples/ray_v1alpha1_rayservice.yaml
- tests/test_sample_rayservice_yamls.py
> [rayservice] Remove dagdriver from ray_v1alpha1_rayservice.yaml

- .gitattributes
using `.gitattributes` so they appear as collapsed in GitHub PRs. [See docs][1].
[1]: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
> chore: mark generated files as such

- apiserver/CreatingServe.md
- apiserver/pkg/util/cluster.go
- apiserver/pkg/util/cluster_test.go
- apiserver/pkg/util/job.go
- apiserver/pkg/util/service.go
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/common/service.go
- ray-operator/controllers/ray/common/service_test.go
- ray-operator/controllers/ray/raycluster_controller.go
This is a clean-up of https://github.com/ray-project/kuberay/pull/1582
refer to https://github.com/ray-project/kuberay/pull/1582
> Adding capability to create ray cluster with serve support -clean

- README.md
This PR adds more blog posts and talks to the README.
> [Doc] Add blogs and talks to readme

- ray-operator/DEVELOPMENT.md
> Fix typo in DEVELOPMENT.md

- ray-operator/config/samples/ray-cluster.overwrite-command.yaml
See https://github.com/ray-project/ray/pull/41651/files#r1419787783 for more details.
> Update overwrite-container-cmd example

- .github/workflows/test-job.yaml
As title. This saves around 100 seconds for CI runs.
> Only build/push Multi Arch images when merging to master

- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/raycluster_controller_fake_test.go
This PR uses the `DeleteAllOf` helper to simplify the deletion of head pods and worker pods before Redis cleanup.
Note that we have to use two separate `DeleteAllOf` calls to delete heads and workers respectively to avoid accidentally deleting cleanup pods.
Also, there is no need to check the `DeletionTimestamp` of a resource before deleting it. Kubernetes will not change the resource if its `DeletionTimestamp` is set.
> [Refactor][GCS FT] Use DeleteAllOf to delete cluster pods before cleaning up redis

- ray-operator/controllers/ray/rayjob_controller.go
Move the code related to `Running` to the `switch` statement.
> [RayJob][Status][16/n] Refactor `Running` status

- ray-operator/pkg/client/applyconfiguration/ray/v1/rayservicestatus.go
- ray-operator/pkg/client/applyconfiguration/utils.go
https://github.com/ray-project/kuberay/pull/1818 and https://github.com/ray-project/kuberay/pull/1839 merged around the same time, so applyconfiguration needs to be updated. 
> fix applyconfiguration generated code

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- manifests/base/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.1.0-alpha.0] Update tags and versions

- .github/workflows/image-release.yaml
> [CI] Fix image release pipeline

- .github/workflows/image-release.yaml
Fix https://github.com/ray-project/kuberay/actions/runs/7675203709/job/20921092395.
> [CI] Fix apiserver test in image-release process

- ray-operator/controllers/ray/rayjob_controller_unit_test.go
- ray-operator/controllers/ray/utils/util.go
Very minor refactor based on https://github.com/ray-project/kuberay/pull/1852#discussion_r1462194366. 
> rayjob controller: refactor environment variable check in unit tests

- ray-operator/controllers/ray/rayjob_controller.go
I merged #1894 after all CI tests passed and GitHub reported no conflicts with #1893. However, the rebase mechanism doesn't seem to work well, resulting in CI failures.
> [Bug] Fix rebase error

- ray-operator/config/samples/pytorch-text-classifier/ray-job.pytorch-distributed-training.yaml
Add the missing CPU limit to ensure that the RayJob is not rejected if the namespace has a ResourceQuota.
> [RayJob] Set missing CPU limit

- .github/workflows/image-release.yaml
- .github/workflows/test-job.yaml
> [CI] Stop publishing images to DockerHub

- ray-operator/test/e2e/rayjob_cluster_selector_test.go
- ray-operator/test/e2e/rayjob_lightweight_test.go
- ray-operator/test/e2e/rayjob_suspend_test.go
- ray-operator/test/e2e/rayjob_test.go
- ray-operator/test/e2e/support.go
> [RayJob] Refactor Rayjob E2E Tests to Use Server-Side Apply

- ray-operator/controllers/ray/utils/util.go
- ray-operator/controllers/ray/utils/util_test.go
by using a table test and covering all code paths in the function.
> chore: improve coverage for `util.go:CheckAllPodsRunning()`

- ray-operator/config/samples/ray-job.kueue-toy-sample.yaml
This YAML is for https://github.com/ray-project/ray/pull/43585.
> [Kueue] Add a sample YAML for Kueue toy sample

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- ray-operator/config/default/kustomization.yaml
This PR refers to https://github.com/ray-project/kuberay/pull/1001.
> [release v1.1.0-rc.0] Update tags and versions

- README.md
@kevin85421 
add best practices for ray cluster
> add best practices for ray cluster on ACK from Alibaba Cloud blog

- docs/release/helm-chart.md
- helm-chart/kuberay-apiserver/values.yaml
> [Cherry-pick][release][v1.1.0] Improve release doc and update KubeRay API server chart's repository (#1960)

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
> [Cherry-pick] Add NumOfHosts to RayCluster helm-chart template (#1969)

- ray-operator/config/samples/ray-cluster.tpu-v4-multihost.yaml
- ray-operator/config/samples/ray-cluster.tpu-v4-singlehost.yaml
- tests/test_sample_raycluster_yamls.py
> [Cherry-pick] Add v4 TPU manifests samples (#1968)

- apiserver/pkg/model/converter_test.go
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/common/service_test.go
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/raycluster_controller_fake_test.go
- ray-operator/controllers/ray/raycluster_controller_test.go
- ray-operator/controllers/ray/rayjob_controller_suspended_test.go
- ray-operator/controllers/ray/rayjob_controller_test.go
- ray-operator/controllers/ray/rayservice_controller_test.go
- ray-operator/controllers/ray/utils/constant.go
> [Cherry-pick][Refactor][RayCluster] Make ray.io/group=headgroup be constant (#1970)

- helm-chart/ray-cluster/values.yaml
> [Cherry-pick] Exposing min/max replica counts for default worker group (#1963)

- helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml
- ray-operator/apis/ray/v1/rayservice_types.go
- ray-operator/config/crd/bases/ray.io_rayservices.yaml
> [Cherry-pick][RayService] fix kubebuilder printcolumn annotations for RayService (#1981)

- ray-operator/config/samples/ray-job.kueue-toy-sample.yaml
> [Cherry-pick] chore: remove ConfigMap from ray-job.kueue-toy-sample.yaml (#1976)

- tests/test_sample_rayservice_yamls.py
> [Cherry-pick][RayService] Address Recent Flakiness in RayService Zero Downtime Rollout Test (#1979)

- README.md
> [Cherry-pick] add best practices for ray cluster on ACK from Alibaba Cloud blog (#1985)

- ray-operator/main.go
> [Cherry-pick] Use a default user agent 'kuberay-operator' instead of the default user-agent from controller-runtime (#1982)

- ray-operator/config/samples/ray-cluster.tpu-v4-multihost.yaml
- ray-operator/config/samples/ray-cluster.tpu-v4-singlehost.yaml
> [Cherry-pick] Add missing labels on RayCluster TPU manifests (#1987)

- ray-operator/Makefile
> [Cherry-pick][CI] Pin crd-ref-docs to v0.0.10 (#1988)

- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/raycluster_controller_fake_test.go
> [Cherry-pick][Bug][GCS FT] Clean up the Redis key before the head Pod is deleted (#1989)

- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/utils/constant.go
> [Cherry-pick] Fix Log to indicate we are Using DashboardPort in RayService (#2001)

- helm-chart/ray-cluster/values.yaml
> [Cherry-pick][Fix][HelmChart] Move service.headService -> head.headService in values.yaml (#1998)

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.1.0-rc.1] Update tags and versions

- ray-operator/controllers/ray/raycluster_controller_fake_test.go
> [Cherry-pick] ray-operator: parameterize Test_ShouldDeletePod (#2000)

- helm-chart/kuberay-operator/values.yaml
> [Cherry-pick] Add seccompProfile.type=RuntimeDefault to kuberay-operator. (#1955)

- docs/development/release.md
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/utils/constant.go
- ray-operator/controllers/ray/utils/util.go
- ray-operator/main.go
> [Cherry-pick][Telemetry] KubeRay version and CRD (#2024)

- helm-chart/ray-cluster/templates/_helpers.tpl
> [Cherry-pick][Bug] Reconciler error when changing the value of nameOverride in values.yaml of helm installation for Ray Cluster (#1966)

- tests/compatibility-test.py
- tests/framework/prototype.py
- tests/framework/utils.py
> [Cherry-pick][Test][RayCluster] Test redis cleanup job in the e2e compatibility test (#2026)

- ray-operator/controllers/ray/common/association.go
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/raycluster_controller_fake_test.go
- ray-operator/controllers/ray/raycluster_controller_test.go
- ray-operator/controllers/ray/suite_helpers_test.go
> [Cherry-pick][Refactor][RayCluster] RayClusterHeadPodsAssociationOptions and RayClusterWorkerPodsAssociationOptions (#2023)

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
> [release v1.1.0] Update tags and versions

- cli/Makefile
- docs/development/release.md
```sh
VERSION := $(shell git describe --tags $(shell git rev-list --tags --max-count=1))
```
* `VERSION` will be ray-operator/v1.1.0 instead of v1.1.0. This PR fixes the issue.
> [Release] Update release Makefile

- ray-operator/config/samples/ray-cluster.autoscaler.large.yaml
- ray-operator/config/samples/ray-cluster.autoscaler.yaml
- ray-operator/config/samples/ray-cluster.complete.yaml
- ray-operator/config/samples/ray-cluster.custom-head-service.yaml
- ray-operator/config/samples/ray-cluster.heterogeneous.yaml
- ray-operator/config/samples/ray-cluster.mini.yaml
- ray-operator/config/samples/ray-cluster.separate-ingress.yaml
- ray-operator/config/samples/ray-job.kueue-toy-sample.yaml
- ray-operator/config/samples/ray-job.sample.yaml
- ray-operator/config/samples/ray-job.shutdown.yaml
I found some typos in yaml that this pr will fix.
> [Doc] Fix Yaml Typos

- ray-operator/config/samples/ray-cluster.autoscaler-v2.yaml
> [Autoscaler V2] Polish Autoscaler V2 YAML

- apiserver/pkg/server/ray_job_submission_service_server.go
- helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml
- helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml
- helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml
- ray-operator/apis/ray/v1/raycluster_types.go
- ray-operator/config/crd/bases/ray.io_rayclusters.yaml
- ray-operator/config/crd/bases/ray.io_rayjobs.yaml
- ray-operator/config/crd/bases/ray.io_rayservices.yaml
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/utils/dashboard_httpclient.go
- ray-operator/controllers/ray/utils/dashboard_httpclient_test.go
- ray-operator/controllers/ray/utils/fake_serve_httpclient.go
- ray-operator/pkg/client/applyconfiguration/ray/v1/headinfo.go
> [RayCluster] Add serviceName to status.headInfo

- ray-operator/controllers/ray/raycluster_controller.go
The names of the head and worker pods are generated, so the names are different every time. It is useless to check whether the previous pods are still terminating because we cannot even know their names based on the current names.
https://github.com/ray-project/kuberay/blob/b5f237dcbf222d23faa8cdecf4862693f6429454/ray-operator/controllers/ray/common/pod.go#L95
https://github.com/ray-project/kuberay/blob/b5f237dcbf222d23faa8cdecf4862693f6429454/ray-operator/controllers/ray/common/pod.go#L155
N/A
> [Chore] Delete redundant pod existance checking

- ray-operator/controllers/ray/raycluster_controller_test.go
- ray-operator/controllers/ray/utils/util.go
> [Cherry-pick][Bug] Ray operator crashes when specifying RayCluster with resources.limits but no resources.requests (#2077)

- docs/components/config/samples/ray-cluster.autoscaler.large.yaml
- docs/components/config/samples/ray-cluster.autoscaler.yaml
- docs/components/config/samples/ray-cluster.complete.large.yaml
- docs/components/config/samples/ray-cluster.complete.yaml
- docs/components/config/samples/ray-cluster.heterogeneous.yaml
- docs/components/config/samples/ray-cluster.mini.yaml
Fix the issue at https://github.com/ray-project/kuberay/actions/runs/8945694943/job/24575079930 that prevents the KubeRay website from being deployed with the latest commit.
> [CI] Remove unnecessary sample YAML symbolic links

- .github/workflows/consistency-check.yaml
- .github/workflows/image-release.yaml
- .github/workflows/test-job.yaml
- ray-operator/Makefile
> [Cherry-pick][CI] Pin kustomize to v5.3.0 (#2067)

- ray-operator/controllers/ray/utils/constant.go
> [Telemetry] Update KUBERAY_VERSION

- ray-operator/Makefile
> [Cherry-pick][Hotfix][CI] Pin setup-envtest dep (#2038)

- ray-operator/controllers/ray/utils/util.go
Follow-up for https://github.com/ray-project/kuberay/pull/1930#pullrequestreview-2044141001
N/A
> [Refactor] Follow-up for PR 1930

- ray-operator/controllers/ray/rayjob_controller_test.go
> Add test for configurable k8s job backoff limit

- ray-operator/config/samples/ray-data-image-resize/ray-job.image-resize.yaml
- ray-operator/config/samples/ray-data-image-resize/ray_data_image_resize.py
> [Perf] Add a CPU-based image resizing workload using Ray Data

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
Similar to #181 we add priorityClassName and priority to the template
N/A
> add priority and priorityClassName to ray-cluster template

- ray-operator/config/samples/ray-service.high-availability-locust.yaml
- ray-operator/test/e2e/locust_runner.py
- ray-operator/test/e2e/locustfile.py
- ray-operator/test/e2e/rayservice_ha_test.go
- ray-operator/test/e2e/support.go
- ray-operator/test/support/core.go
- ray-operator/test/support/ray.go
See https://github.com/ray-project/kuberay/issues/2177 for more details.
> [Test][HA] RayService high-availability test without autoscaling enabled

- docs/index.md
fix invalid link. some links is not found.
None
> fix invalid link in docs/index.md

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
- helm-chart/ray-cluster/values.yaml
To resolve issue #2174 
#2174 
> Properly set env field based on containerEnv values

- ray-operator/test/e2e/raycluster_autoscaler_test.go
- ray-operator/test/e2e/rayservice_ha_test.go
> [Fix][CI] Fix revive error

- ray-operator/test/e2e/create_detached_actor.py
- ray-operator/test/e2e/raycluster_autoscaler_test.go
This is a subtask for the umbrella issue #2173 
See #2173 for details
> [Test][Autoscaling] Add custom resource test

- ray-operator/config/samples/ray-job.modin.yaml
This PR creates an example RayJob for Modin tasks.
Related PR: https://github.com/ray-project/ray/pull/46345
Resolves: #2190
> [Chore] Create example Modin RayJob

- helm-chart/kuberay-operator/values.yaml
- ray-operator/apis/config/v1alpha1/configuration_types.go
- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/rayjob_controller_test.go
- ray-operator/controllers/ray/utils/constant.go
- ray-operator/main.go
Resolves: ray-project/kuberay#1944
> [Feat][RayJob] Delete RayJob CR after job termination

- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/utils/util.go
- ray-operator/controllers/ray/utils/util_test.go
https://github.com/ray-project/kuberay/issues/2227
> [RayCluster] improve generated pod names for Ray clusters

- ray-operator/controllers/ray/raycluster_controller.go
> [Minor] Remove redundant variable

- ray-operator/controllers/ray/raycluster_controller_test.go
Currently, RayCluster conditions only have unit tests. This PR adds envtests for RayCluster conditions.
Note that this PR needs https://github.com/ray-project/kuberay/pull/2282 to work properly, otherwise the tests will fail.
N/A
> [Test][RayCluster] Add envtests for RayCluster conditions

- ray-operator/controllers/ray/raycluster_controller_test.go
- ray-operator/controllers/ray/rayjob_controller_suspended_test.go
- ray-operator/controllers/ray/rayjob_controller_test.go
- ray-operator/controllers/ray/rayservice_controller_test.go
Resolves: ray-project/kuberay#2280
> [Fix][Envtest] Decorate container nodes with Ordered

- .github/workflows/e2e-tests-reusable-workflow.yaml
- .github/workflows/e2e-tests.yaml
- kubectl-plugin/go.mod
- kubectl-plugin/test/e2e/kubectl_ray_test.go
This adds the basic e2e test for the Kubectl Plugin directory. 
> Add basic e2e test for kubectl plugin

- ray-operator/config/samples/vllm/ray-service.vllm.yaml
- ray-operator/config/samples/vllm/serve.py
Add a sample RayService that deploys Llama 3 8B using vLLM.
This will be used for a future guide in the Ray documentation.
> add vLLM + RayService sample

- ray-operator/controllers/ray/raycluster_controller_unit_test.go
This is a follow-up PR for https://github.com/ray-project/kuberay/pull/2217 to fix wrong comment.
N/A
> [Minor][Chore] Fix wrong comment

- ray-operator/controllers/ray/raycluster_controller_unit_test.go
This is a follow-up PR for https://github.com/ray-project/kuberay/pull/2217. This PR adds `RestartPolicyOnFailure` case for eviction unit test.
N/A
> [Test][RayCluster] Add tests for RestartPolicyOnFailure for eviction

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.2.0-rc.0] Update tags and versions

- ray-operator/controllers/ray/utils/constant.go
> [Telemetry][v1.2.0] Update KUBERAY_VERSION

- ray-operator/config/samples/ray-service.high-availability.yaml
> [cherry-pick][release blocker][v1.2.0] Fix HA OOM issue (#2313)

- helm-chart/kuberay-operator/templates/_helpers.tpl
- helm-chart/kuberay-operator/templates/deployment.yaml
- helm-chart/kuberay-operator/values.yaml
- ray-operator/config/rbac/role.yaml
- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/utils/dashboard_httpclient.go
> [cherry-pick][RayJob] allow create verb for services/proxy, which is required for HTTPMode (#2321)

- apiserver/go.mod
- ray-operator/go.mod
> [cherry-pick] Bump go to 1.22.4 to fix ray-operator vulnerabilities (#2325)

- ray-operator/config/samples/pytorch-mnist/ray-job.pytorch-mnist.yaml
> [cherry-pick][Fix][Sample-Yaml] Increase ray head CPU resource for pytorch minst (#2330)

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.2.0-rc.1] Update tags and versions

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.2.0] Update tags and versions

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.2.1] Update tags and versions

- ray-operator/controllers/ray/utils/constant.go
> [Telemetry][v1.2.1] Update KUBERAY_VERSION

- .buildkite/test-sample-yamls.yml
- ray-operator/Makefile
- ray-operator/test/sampleyaml/support.go
Closes: ray-project/kuberay#2311
> [Refactor][sample-yaml-test] Create sampleyaml package and run tests in CI

- .github/workflows/test-job.yaml
- .pre-commit-config.yaml
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/utils/util.go
- ray-operator/test/support/meta.go
- ray-operator/test/support/test.go
Upgrade `golangci-lint` to 1.60.3
N/A
> [Chore][Linter] Upgrade golangci-lint to 1.60.3

- helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml
- ray-operator/apis/ray/v1/rayjob_types.go
- ray-operator/config/crd/bases/ray.io_rayjobs.yaml
- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/rayjob_controller_test.go
- ray-operator/controllers/ray/suite_helpers_test.go
- ray-operator/controllers/ray/utils/constant.go
This PR implements the `None` SubmissionMode in [this design doc](https://docs.google.com/document/d/1hCJsrCFYPJLS3Zusdr8N_4Y5leWUMy4bQEbsqSQp2mw/edit). But after discussion we decided to rename it to `UserMode`.
N/A
> [Feat][RayJob] UserMode SubmissionMode

- kubectl-plugin/pkg/cmd/log/log.go
Closes: ray-project/kuberay#2404
> [Feat][kubectl-plugin] Add Long, Example, shell completion for kubectl ray log

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.2.2] Update tags and versions

- ray-operator/controllers/ray/utils/constant.go
> [v1.2.2] Update KUBERAY_VERSION

- kubectl-plugin/.goreleaser.yaml
Closes: ray-project/kuberay#2421
> [Feat][kubectl-plugin] Include LICENSE file into kubectl plugin tar

- ray-operator/config/samples/ray-cluster.yunikorn-scheduler.yaml
Closes: ray-project/kuberay#2411
> [Chore][YuniKorn] Add sample yaml file for Apache YuniKorn

- ray-operator/config/samples/ray-cluster.yunikorn-scheduler.yaml
See the section "Don’t use Ray versions between 2.11.0 and 2.37.0." in [this doc](https://docs.ray.io/en/master/cluster/kubernetes/troubleshooting/troubleshooting.html#use-the-right-version-of-ray) for more details.
> [Chore] Use Ray 2.9.0 for Apache YuniKorn example

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
- helm-chart/ray-cluster/values.yaml
To allow customisation of the dnsConfig for ray pods.
N/A
> Add dnsConfig to head, worker and additional workers

- apiserver/pkg/util/cluster.go
This PR returns error when marshaling tolerations fails in NewComputeTemplate.
> [Fix] Return error when marshaling tolerations fails in NewComputeTemplate

- ray-operator/config/samples/ray-cluster.tpu-v6e-16-multihost.yaml
- ray-operator/config/samples/ray-cluster.tpu-v6e-256-multihost.yaml
- ray-operator/config/samples/ray-job.tpu-v6e-16-multihost.yaml
- ray-operator/config/samples/ray-job.tpu-v6e-256-multihost.yaml
- ray-operator/config/samples/ray-job.tpu-v6e-singlehost.yaml
- tests/test_sample_raycluster_yamls.py
This PR updates the v6e TPU Ray CR samples based on feedback from the v6e example guide. This PR also adds a v6e-16 example manifest.
> Update V6e TPU Ray Samples

- .buildkite/test-sample-yamls.yml
- ray-operator/config/samples/ray-cluster.external-redis-uri.yaml
- ray-operator/config/samples/ray-cluster.external-redis.yaml
- ray-operator/config/samples/ray-cluster.heterogeneous.yaml
- ray-operator/config/samples/ray-cluster.separate-ingress.yaml
- ray-operator/test/sampleyaml/raycluster_test.go
- ray-operator/test/sampleyaml/support.go
- ray-operator/test/support/ray.go
- ray-operator/test/support/support.go
Note:
- Tests are changed into whitelist manner, only those sample yaml files that need to be checked are listed.
- Currently I find it hard to decode yaml files containing multiple resources, so I moved `RayCluster` resource to the top if there are multiple resources declared in a yaml file. 
Closes: ray-project/kuberay#2431
> [Test][sample-yaml] Check RayCluster create correct number of pods

- .krew.yaml
Closes: ray-project/kuberay#2460
> [Chore][kubectl-plugin] Fix wrong homepage link in krew template file

- kubectl-plugin/pkg/cmd/job/job_submit.go
Followup for https://github.com/ray-project/kuberay/pull/2446
Status on ray-operator:
Run:
RayJob:
> [Feature][kubectl-plugin] Fix for setting job submission ID in `kubectl ray job submit`

- helm-chart/kuberay-operator/templates/_helpers.tpl
- helm-chart/kuberay-operator/templates/role.yaml
Closes: ray-project/kuberay#2428
> [Fix][Helm] Fix ClusterRole for volcano if .Values.batchScheduler.name is set

- ray-operator/test/sampleyaml/rayservice_test.go
- ray-operator/test/sampleyaml/support.go
- add test for RayService to check if all applications are running
Closes #2482
> [Test] Check all applications in Ray Serve are running

- ray-operator/test/sampleyaml/rayservice_test.go
- ray-operator/test/sampleyaml/support.go
- ray-operator/test/support/core.go
- ray-operator/test/support/ray.go
- ray-operator/test/support/utils.go
- Add the testcase to query dashboard to get the serve application status in head pod
Closes #2481 
> [Test] Query dashboard to get the serve application status in head pod

- ray-operator/config/samples/ray-job.use-existing-raycluster.yaml
Related doc PR: https://github.com/ray-project/ray/pull/48596
Related issue: #2429
Closes: ray-project/kuberay#2504
> [Feat] Add sample yaml for RayJob clusterSelector config

- kubectl-plugin/pkg/cmd/get/get.go
- kubectl-plugin/pkg/cmd/get/get_cluster.go
- kubectl-plugin/pkg/cmd/get/get_cluster_test.go
- kubectl-plugin/pkg/cmd/ray.go
- kubectl-plugin/test/e2e/kubectl_ray_test.go
Closes: ray-project/kuberay#2492
> [Refactor][kubectl-plugin] Change kubectl ray cluster get to get cluster

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
- helm-chart/ray-cluster/values.yaml
It fixes the topology spread constraints for custom worker pools
Closes #2632 
> fix: update topology spread constraints for custom worker pools

- docs/reference/api.md
- helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml
- ray-operator/apis/ray/v1/rayservice_types.go
- ray-operator/config/crd/bases/ray.io_rayservices.yaml
- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
- ray-operator/pkg/client/applyconfiguration/ray/v1/rayservicespec.go
> This will reduce the failure rate of #2590  during the Locust test.
- Add `AddProxyActorOnHeadPod` field in `rayservice_types.go`
- Add field in `ray.io_rayservices.yaml`
-  Add an additional parameter in `labelHeadPodForServeStatus`  function
Closes #2593 
> [Feat]: Add a field to configure whether to add a proxy actor on the head Pod to the K8s serve service or not

- docs/reference/api.md
- ray-operator/apis/ray/v1/rayservice_types.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
- ray-operator/controllers/ray/utils/fake_httpproxy_httpclient.go
update comments for the new API, and refactor tests a bit
#2598 
> [RayService] follow up for #2598

- ray-operator/test/e2e/rayservice_in_place_update_test.go
> [CI] Jail flaky test: TestRayServiceInPlaceUpdate

- kubectl-plugin/pkg/cmd/log/log.go
Fixes the issue where if there are more than 1 container in the ray pod, it doesn't know which log to retrieve. 
Since the ray container is always the first container in the pod, we used that to only retrieve the ray specific logs.
https://github.com/ray-project/kuberay/issues/2647
> [kubectl-plugin] Make sure kubectl ray logs only get ray container logs

- .buildkite/test-e2e.yml
- ray-operator/test/e2e/rayservice_in_place_update_test.go
I logged into the Buildkite runner and ran the test 20 times. All tests passed.
Closes #2617
> [CI] Unjail TestRayServiceInPlaceUpdate

- kubectl-plugin/pkg/cmd/delete/delete.go
- kubectl-plugin/pkg/cmd/delete/delete_test.go
- kubectl-plugin/pkg/cmd/ray.go
Kubectl-plugin `ray delete` ray resources.
Part of https://github.com/ray-project/kuberay/issues/2608 
> [kubectl-plugin] Add kubectl ray delete rayservice/job/cluster

- ray-operator/DEVELOPMENT.md
The original example suggested adding a log message in the RayCluster controller's `Reconcile` function. However, this log would only be triggered when reconciling a RayCluster, making it difficult to verify if the operator is running correctly during initial setup.
Changed the example to add a log message in the main function instead, which will be triggered immediately when the operator starts.
> [Fix][Doc] Fix development markdown example

- ray-operator/controllers/ray/raycluster_controller.go
It seems not necessary to have line break into multiple lines in a short log line.
> [Chore] remove unnecessary line break in log

- .github/workflows/consistency-check.yaml
- .github/workflows/helm-lint.yaml
- .github/workflows/image-release.yaml
- .github/workflows/test-job.yaml
Refer to -> [Bug] CI failed with "/etc/docker/daemon.json: No such file or directory" #2713
Closes #2713 
> [CI] Downgrade runner image from ubuntu-latest to ubuntu-22.04

- ray-operator/controllers/ray/rayservice_controller.go
refactor validateServiceSpec
Closes ray-project/kuberay#2710
> Refactor validateRayServiceSpec

- ray-operator/controllers/ray/raycluster_controller.go
Make the `err` as local variable in if-statement because they are used in the if-statement only.
> [Chore] make err as local variable in if-statement

- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
Closes: ray-project/kuberay#2706
> [Refactor][RayService] Unify ClusterAction decision to single function

- kubectl-plugin/pkg/cmd/log/log.go
- kubectl-plugin/pkg/cmd/log/log_test.go
Add support for the other ray resources: rayservice and rayjob
Closes: https://github.com/ray-project/kuberay/issues/2419
Part of: #2608 
> [kubectl-plugin] Add support for retrieving logs for different ray resource types

- .github/workflows/kubectl-plugin-e2e-tests.yaml
- kubectl-plugin/pkg/cmd/session/session.go
- kubectl-plugin/test/e2e/kubectl_ray_session_test.go
Closes: ray-project/kuberay#2388
> [Feat][kubectl-plugin] Retry port-forward when connection lost

- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
> [RayCluster] Validate GCSFaultToleranceOptions and redis password

- ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/rayjob_controller.go
- ray-operator/controllers/ray/rayjob_controller_unit_test.go
- ray-operator/controllers/ray/utils/util.go
- ray-operator/controllers/ray/utils/util_test.go
This is a follow up of #2771.
1. Refactor the validation logic of RayJob deletion policy.
2. Add a util function `IsAutoscalingEnabled`
> [Refactor] Add a util function `IsAutoscalingEnabled` and refactor validations of RayJob deletion policy

- ray-operator/controllers/ray/rayservice_controller.go
> [RayService] Move the cluster switch logic from `reconcileServe` to `Reconcile`

- ray-operator/controllers/ray/rayservice_controller.go
> [RayService] Add a safeguard and remove the dead code to ensure that both clusters are not empty before reconciling serve

- ray-operator/controllers/ray/rayjob_controller.go
Make the `err` as local variable in if-statement because they are used in the scope only.
> [RayJob][Chore] make err as a local variable

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
> [release v1.3.0-alpha.0] Update tags and versions

- ray-operator/controllers/ray/utils/constant.go
> [Telemetry][v1.3.0-alpha.0] Update KUBERAY_VERSION

- kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go
As title
follow-up issue: https://github.com/ray-project/kuberay/issues/2801
> [CI] Skip kubectl plugin flaky e2e tests

- ray-operator/controllers/ray/rayservice_controller.go
Resolves https://github.com/ray-project/kuberay/issues/2786
Before:
After:
This is just refactoring and no actual functional changes.
> [RayService] Unify the cluster switch over logic together

- ray-operator/test/e2erayservice/rayservice_upgrade_test.go
> [RayService] Add logs and remove in-place update for the TestOldHeadPodFailDuringUpgrade e2e test

- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
> [RayService] make `checkIfNeedSubmitServeApplications` more unit testable

- ray-operator/controllers/ray/rayservice_controller.go
Move the update of `RayClusterStatus` to `calculateStatus`.
> [RayService] Move the update of `RayClusterStatus` to `calculateStatus`

- ray-operator/controllers/ray/rayservice_controller_test.go
1. Add a utility function `rayServiceTemplate` to return a new RayService CR for each function call, avoiding updates to the CR spec that could cause side effects in other tests.
2. Replace `myRayService` with `rayService`.
> [RayService] refactor envtest by adding a util function `rayServiceTemplate`

- ray-operator/controllers/ray/rayservice_controller.go
I plan to refactor `reconcileRayCluster` to avoid it updating CR status directly. This PR moves `cleanUpRayClusterInstance` to the top-level function `Reconcile` to reduce `reconcileRayCluster`'s complexity.
> [RayService] Move `cleanUpRayClusterInstance` from `reconcileRayCluster` to `Reconcile`

- apiserver/test/cluster/redis/redis.yaml
- ray-operator/config/samples/ray-cluster.external-redis-uri.yaml
- ray-operator/config/samples/ray-cluster.external-redis.yaml
- ray-operator/config/samples/ray-service.high-availability.yaml
- ray-operator/controllers/ray/rayservice_controller.go
- tests/config/ray-cluster.ray-ft.yaml.template
> [RayService] reword the comment on `ServiceStatus = rayv1.Running`

- ray-operator/controllers/ray/utils/dashboard_httpclient.go
Make the `err` as local variable in if-statement because they are used in the scope only.
> [Chore] Make error as a local variable

- ray-operator/test/e2erayservice/testdata/ray-service.ft.yaml
I missed this one in the last PR https://github.com/ray-project/kuberay/pull/2848/commits/cc04528ce1a064052f8197fcd84c15eb626f58e3
> [Compatibility] Update Redis image for compatibility tests

- ray-operator/test/e2erayservice/rayservice_ha_test.go
- ray-operator/test/e2erayservice/rayservice_in_place_update_test.go
- ray-operator/test/e2erayservice/rayservice_upgrade_test.go
- ray-operator/test/sampleyaml/rayservice_test.go
> [RayService] Use Ready condition in e2e tests

- ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler_test.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/common/service_test.go
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
> Refactor multiple cases in single test function with array

- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
> [RayService] Refactor `reconcileRayCluster` to avoid updating CR status in the function

- ray-operator/test/e2erayservice/rayservice_ha_test.go
- ray-operator/test/e2erayservice/rayservice_upgrade_test.go
- ray-operator/test/support/ray.go
> [RayService] Add checks of RayService conditions in e2e tests

- ray-operator/controllers/ray/common/rbac_test.go
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
- ray-operator/controllers/ray/rayjob_controller_unit_test.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
- ray-operator/controllers/ray/utils/util_test.go
- ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
https://github.com/ray-project/kuberay/issues/2810
Closes #2810
> [Refactor] Move test name from map key to struct field

- ray-operator/controllers/ray/rayservice_controller_test.go
Currently, RayService envtest is pretty messy. Every test coupling together. I plan to separate them into different tests. This PR adds a test for RayService happy path.
> [RayService] Add an envtest for RayService happy path

- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/rayservice_controller_test.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
Replace env test with unit tests which have higher coverage and much faster.
> [RayService] Add unit tests for `isZeroDowntimeUpgradeEnabled`

- ray-operator/controllers/ray/rayservice_controller_test.go
> [RayService] Add an envtest for autoscaler

- ray-operator/controllers/ray/rayservice_controller.go
Currently, `createRayClusterInstance` retrieves the RayCluster from the informer cache and deletes it if it already exists. However, this is unnecessary because the function is only called when the cluster does not exist in the informer cache.
https://github.com/ray-project/kuberay/blob/5a5534f843644a6c4fd9a2e38fc106762e2b1d18/ray-operator/controllers/ray/rayservice_controller.go#L503
In addition, deleting the cluster with the given name if it exists is also a very strange behavior. For example, if a RayCluster was created in the last reconciliation but the RayService CR status failed to update, the next reconciliation loop will delete it. This doesn't happen because the function is only called when the cluster doesn't exist in the informer cache.
> [RayService] Refactor `createRayClusterInstance`

- ray-operator/controllers/ray/rayservice_controller.go
This is a follow up of #2873. This PR refactors `updateRayClusterInstance` to avoid passing RayService into the function only for K8s events.
> [RayService] Refactor `updateRayClusterInstance`

- kubectl-plugin/pkg/cmd/create/create_cluster_test.go
- kubectl-plugin/pkg/cmd/job/job_submit_test.go
- kubectl-plugin/pkg/cmd/log/log_test.go
> [kubectl-plugin] fix minor typo

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
update versions for v1.3.0-rc.0
> update versions for v1.3.0-rc.0

- .golangci.yml
Followup for https://github.com/ray-project/kuberay/pull/2892
https://github.com/ray-project/kuberay/issues/2897
> [CI] Enable testifylint rule

- .golangci.yml
- kubectl-plugin/pkg/cmd/create/create_cluster_test.go
- kubectl-plugin/pkg/cmd/delete/delete_test.go
- kubectl-plugin/pkg/cmd/get/get_cluster_test.go
- kubectl-plugin/pkg/cmd/job/job_submit_test.go
- kubectl-plugin/pkg/cmd/log/log_test.go
- kubectl-plugin/pkg/cmd/session/session_test.go
- kubectl-plugin/pkg/util/client/client_test.go
- kubectl-plugin/pkg/util/generation/generation_test.go
- ray-operator/controllers/ray/common/association_test.go
- ray-operator/controllers/ray/common/ingress_test.go
- ray-operator/controllers/ray/common/rbac_test.go
- ray-operator/controllers/ray/common/route_test.go
- ray-operator/controllers/ray/common/service_test.go
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
- ray-operator/controllers/ray/rayjob_controller_unit_test.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
- ray-operator/controllers/ray/utils/util_test.go
- ray-operator/controllers/ray/utils/validation_test.go
As title
Closes: ray-project/kuberay#2902
> [CI] Enable `testifylint` `error-nil` rule

- .golangci.yml
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
> [CI] Enable `testifylint` `empty` rule

- .golangci.yml
- ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler_test.go
- ray-operator/controllers/ray/expectations/scale_expectations_test.go
> [CI] Enable `testifylint` `bool-compare` rule

- .github/workflows/test-job.yaml
- .pre-commit-config.yaml
- ray-operator/DEVELOPMENT.md
- scripts/lint.sh
Automatically install correct version of `golangci-lint` and `kubeconform` for developers.
N/A
> [CI] Auto download golang tools in pre-commit

- ray-operator/controllers/ray/rayservice_controller.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
Fixes https://github.com/ray-project/kuberay/issues/2877.
Currently, a pending cluster will only be overridden if it is unhealthy, which is safe, but this behavior implicitly relies on the current implementation. This PR introduces an explicit check to prevent the overriding of a pending cluster that is actively serving.
> [RayService] Add a safeguard to prevent overriding the pending cluster during a upgrade

- ray-operator/controllers/ray/rayservice_controller_unit_test.go
> [RayService] Refactor unit tests for ShouldPrepareNewCluster

- kubectl-plugin/pkg/cmd/version/version_test.go
> [CI] Fix lint error (require-error)

- .golangci.yml
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
As title
Closes: ray-project/kuberay#2899
> [CI] Enable `testifylint` `float-compare` rule

- .golangci.yml
- kubectl-plugin/pkg/cmd/job/job_submit_test.go
- ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler_test.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/common/test_utils.go
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
- ray-operator/controllers/ray/utils/util_test.go
> [CI] Enable `testifylint` `expected-actual` rule

- helm-chart/ray-cluster/values.yaml
> [release][2/N] Update RayCluster Helm chart from Ray 2.9 to Ray 2.41

- kubectl-plugin/pkg/cmd/create/create_cluster.go
- kubectl-plugin/pkg/cmd/create/create_workergroup.go
- kubectl-plugin/pkg/cmd/job/job_submit.go
- kubectl-plugin/pkg/util/generation/generation_test.go
- kubectl-plugin/test/e2e/testdata/ray-job.interactive-mode-no-runtime-env.yaml
- kubectl-plugin/test/e2e/testdata/ray-job.interactive-mode.yaml
- ray-operator/config/samples/ray-cluster.auth.yaml
> [release][4/N] Update Ray images / versions in kubectl plugin

- ray-operator/config/samples/ray-job.custom-head-svc.yaml
- ray-operator/config/samples/ray-job.kueue-toy-sample.yaml
- ray-operator/config/samples/ray-job.modin.yaml
- ray-operator/config/samples/ray-job.resources.yaml
- ray-operator/config/samples/ray-job.sample.yaml
- ray-operator/config/samples/ray-job.shutdown.yaml
Only the YAML of Kueue is not tested in CI.
> [release][5/N] Update some RayJob YAMLs from Ray 2.9 to Ray 2.41

- docs/development/development.md
- kubectl-plugin/DEVELOPMENT.md
* add plugin section to main `docs/development/development.md`
* describe plugin dev pre-reqs and how to run tests
> [docs][kubectl-plugin] add dev docs

- .buildkite/setup-env.sh
- .pre-commit-config.yaml
- apiserver/hack/update-swagger-ui.bash
- helm-chart/script/chart-test.sh
- install/prometheus/install.sh
- ray-operator/hack/update-codegen.sh
- scripts/helm-render-yaml.sh
- scripts/lint.sh
Pre-commit only failed on error.
Closes #2932 
> [CI] Add shellcheck and fix error of it

- .golangci.yml
- kubectl-plugin/pkg/cmd/log/log_test.go
- ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler_test.go
- ray-operator/controllers/ray/common/ingress_test.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/common/test_utils.go
- ray-operator/controllers/ray/raycluster_controller_unit_test.go
- ray-operator/controllers/ray/rayservice_controller_unit_test.go
> [CI] Enable `testifylint` `len` rule

- ray-operator/config/samples/ray-service.stable-diffusion.yaml
https://github.com/ray-project/serve_config_examples/pull/13 This PR fixes Ray Serve breaking changes.
https://docs.ray.io/en/latest/cluster/kubernetes/examples/stable-diffusion-rayservice.html#kuberay-stable-diffusion-rayservice-example
> [release][8/N] Upgrade Stable Diffusion RayService to Ray 2.41

- ray-operator/test/e2e/rayjob_test.go
[Example CI failure](https://buildkite.com/organizations/ray-project/pipelines/ray-ecosystem-ci-kuberay-ci/builds/6702/jobs/0194dd72-c417-4ca5-a0d3-fe262223f680/log)
> [RayJob] Deflaky RayJob e2e tests

- ray-operator/config/samples/vllm/ray-service.vllm.yaml
- ray-operator/config/samples/vllm/serve.py
@andrewsykim 
vllm is evolving rapidly, with some api changes in versions 0.6 and 0.5. We used version 0.6.1.post2 of vllm on ray in production practice, so I made a change to this fit
> [RayService] adapter vllm 0.6.1.post2

- ray-operator/config/samples/ray-job.batch-inference.yaml
> [Release] Upgrade ray-job.batch-inference.yaml image to 2.41

- ci/markdownlint.yaml
- docs/guidance/rayclient-nginx-ingress.md
- ray-operator/DEVELOPMENT.md
that [prohibits hard tabs][1] and fix violations.
[1]: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md010---hard-tabs
> [chore][docs] enable Markdownlint rule MD010

- ray-operator/config/samples/ray-cluster.yunikorn-scheduler.yaml
Update Ray image version from 2.9.0 to 2.41.0 in Kuberay integration with Apache Yunikorn.
Closes #2968 
> [release] Update Yunikorn YAML file to Ray 2.41

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
> update version to v1.3.0-rc.1

- kubectl-plugin/pkg/cmd/get/get_cluster_test.go
- kubectl-plugin/pkg/cmd/version/version_test.go
> [refactor][kubectl-plugin] remove unnecessary lines

- kubectl-plugin/pkg/cmd/session/session.go
when there's no implicit current context set.
Right now if there's no current context set but an explicit one is with `kubectl ray --context CONTEXT session ...`, the command gets stuck in a retry loop because it cannot find the RayCluster.
This change puts the explicitly specified context into the command `kubectl --context CONTEXT port-forward ...` so that the command can find the RayCluster.
We also add a `-v/--verbose` flag that shows the `kubectl port-forward` command for debugging.
```console
$ kubectl config unset current-context
Property "current-context" unset.
$ kubectl ray --context CONTEXT -n NAMESPACE session CLUSTER_NAME
Forwarding ports to service CLUSTER_NAME-head-svc
Ray Dashboard: http://localhost:8265
Ray Interactive Client: http://localhost:10001
failed to …
```
> [fix][kubectl-plugin] use explicit context for session cmd

- kubectl-plugin/pkg/cmd/create/create_cluster_test.go
- kubectl-plugin/pkg/cmd/delete/delete_test.go
- kubectl-plugin/pkg/cmd/get/get_cluster_test.go
- kubectl-plugin/pkg/cmd/job/job_submit_test.go
- kubectl-plugin/pkg/cmd/log/log_test.go
- kubectl-plugin/pkg/cmd/version/version_test.go
We weren't setting the right missing context for some tests. We also weren't checking the expected error was returned. We were only checking that some error was returned.
> [fix][kubectl-plugin] fix some test errors

- .github/workflows/kubectl-plugin-release.yaml
Fix `krew-release-bot` CI error.
N/A
> [Fix][CI] kubectl plugin krew index CI error

- .github/workflows/consistency-check.yaml
- .github/workflows/helm-lint.yaml
- .github/workflows/test-job.yaml
> [CI] enable CI checks for release-1.3 branch

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
update KubeRay version to v1.3.0
> update KubeRay version to v1.3.0

- ray-operator/config/samples/ray-job.interactive-mode.yaml
Add yaml files used by kubectl plugin doc.
> [Chore] Add RayJob InteractiveMode sample yaml

- .buildkite/test-sample-yamls.yml
- kubectl-plugin/README.md
> chore: update version string in examples and docs

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- ci/markdownlint.yaml
- clients/python-client/README.md
- clients/python-client/python_client_test/README.md
- docs/best-practice/worker-head-reconnection.md
- docs/deploy/installation.md
- docs/design/protobuf-grpc-service.md
- docs/development/release.md
- docs/guidance/aws-eks-iam.md
- docs/guidance/kuberay-with-MCAD.md
- docs/guidance/observability.md
- docs/guidance/rayStartParams.md
- docs/guidance/rayclient-nginx-ingress.md
- docs/guidance/rayservice-high-availability.md
- docs/release/helm-chart.md
- helm-chart/ray-cluster/README.md
* MD012 - No multiple consecutive blank lines
* MD022 - Headers should be surrounded by blank lines
> [chore][docs] enable Markdown lint rules MD012 and MD022

- kubectl-plugin/pkg/cmd/version/version_test.go
- kubectl-plugin/pkg/util/client/fake/fake_client.go
> [Refactor][kubectl-plugin] Move fakeClient in version_test.go to client/fake

- .markdownlint.yaml
- .pre-commit-config.yaml
- docs/components/operator.md
- docs/deploy/installation.md
- docs/guidance/FAQ.md
- docs/guidance/autoscaler.md
- docs/guidance/aws-eks-gpu-cluster.md
- docs/guidance/gcp-gke-gpu-cluster.md
- docs/guidance/gcs-ft.md
- docs/guidance/ingress.md
- docs/guidance/kubeflow-integration.md
- docs/guidance/mobilenet-rayservice.md
- docs/guidance/pod-command.md
- docs/guidance/pod-security.md
- docs/guidance/profiling.md
- docs/guidance/prometheus-grafana.md
- docs/guidance/rayStartParams.md
- docs/guidance/rayjob.md
- docs/guidance/rayserve-dev-doc.md
- docs/guidance/rayservice-troubleshooting.md
- docs/guidance/rayservice.md
- docs/guidance/stable-diffusion-rayservice.md
- docs/guidance/text-summarizer-rayservice.md
- docs/guidance/tls.md
- docs/guidance/volcano-integration.md
* MD041: First line in file should be a top level header
https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
> [chore][docs] enable Markdown lint rule MD041

- kubectl-plugin/pkg/cmd/create/create_cluster.go
- kubectl-plugin/pkg/cmd/create/create_cluster_test.go
- kubectl-plugin/pkg/util/generation/generation.go
- kubectl-plugin/pkg/util/generation/generation_test.go
in `kubectl ray create cluster` with `--head-ephemeral-storage` and `--worker-ephemeral-storage` flags.
Closes #3149
> [feat][kubectl-plugin] support setting K8s ephemeral storage resource

- mkdocs.yml
Got a 404 when trying to access https://ray-project.github.io/kuberay/deploy/docker.md.
> [doc] update file name for container images page

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
> update KubeRay version to v1.3.1

- ray-operator/controllers/ray/rayservice_controller_test.go
Make sure the annotation in RayService has been populated to the derived RayCluster according to https://github.com/ray-project/kuberay/pull/3093#discussion_r1966926918
> [RayService][Test] make sure annotation populated to RayCluster

- ray-operator/config/samples/ray-cluster.sample.yaml
> [operator] remove incorrect comment

- ray-operator/DEVELOPMENT.md
This PR add more details to the development docs in `ray-operator/` for user to follow.
> [Docs] update development md

- kubectl-plugin/pkg/cmd/create/create_cluster.go
- kubectl-plugin/pkg/cmd/create/create_workergroup.go
- kubectl-plugin/pkg/cmd/create/create_workergroup_test.go
- Add options for create workergroup
--worker-node-selectors
- Fix minor comment issue in https://github.com/ray-project/kuberay/pull/3228
https://github.com/ray-project/kuberay/pull/3228 follow-up
N/A
> add node selector option for kubectl plugin create worker group

- ray-operator/controllers/ray/utils/validation_test.go
Refactor TestValidateRayJobSpec into subtests according to https://github.com/ray-project/kuberay/pull/3153#discussion_r1982734201
> [RayJob][Test] refactor TestValidateRayJobSpec with table test

- .github/workflows/image-release.yaml
Address https://github.com/ray-project/kuberay/pull/3117#discussion_r2019642335
N/A
> [CI] Remove create tag step from release

- ray-operator/DEVELOPMENT.md
guide `ray-operator/DEVELOPMENT.md` for readability.
> docs: minor formatting changes to ray-operator dev

- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
Bump version to KubeRay v1.3.2
> [release-1.3] bump version to v1.3.2

- ray-operator/DEVELOPMENT.md
> [docs][operator] fix incorrect example output

- kubectl-plugin/pkg/util/generation/generation_test.go
to be more comprehensive and readable. Compare `RayJobApplyConfiguration` and `RayClusterApplyConfiguration` structs directly instead of field by field.
> [refactor][plugin] update generation_test.go

- kubectl-plugin/pkg/cmd/session/session.go
when the underlying command fails by sending its stdout and stderr to the `kubectl ray session`'s stdout and stderr, respectively.
Running the command successfully in one shell session shows this.
```
$ kubectl ray session dxia-test
Forwarding ports to service dxia-test-head-svc
Ray Dashboard: http://localhost:8265
Ray Interactive Client: http://localhost:10001
Forwarding from 127.0.0.1:8265 -> 8265
Forwarding from [::1]:8265 -> 8265
Forwarding from 127.0.0.1:10001 -> 10001
Forwarding from [::1]:10001 -> 10001
Handling connection for 8265
Handling connection for 8265
```
Running the command in another shell session shows this.
```shell
$ kubectl ray session dxia-test
Forwarding ports to service dxia-test-head-svc
Ray Dashboard: http://localhost:8265
Ray Interactive Client: …
```
> chore: improve `kubectl ray session` error message

- .github/workflows/helm-lint.yaml
> Add Helm chart unittests to CI

- .pre-commit-config.yaml
- kubectl-plugin/pkg/cmd/log/log.go
- ray-operator/controllers/ray/common/job_test.go
- ray-operator/controllers/ray/common/pod_test.go
- ray-operator/controllers/ray/raycluster_controller_test.go
- ray-operator/controllers/ray/rayjob_controller_suspended_test.go
- ray-operator/controllers/ray/rayjob_controller_test.go
- ray-operator/controllers/ray/rayservice_controller_test.go
- ray-operator/controllers/ray/suite_helpers_test.go
- ray-operator/test/e2erayservice/rayservice_ha_test.go
As suggested at https://github.com/ray-project/kuberay/pull/3303#pullrequestreview-2761211609, this PR tries to bump up golangci-lint version and apply necessary linting fixes.
**All** code changes are made by linter.
> Upgrade golang linter for precommit hook

- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/utils/constant.go
- ray-operator/controllers/ray/utils/util.go
- ray-operator/main.go
https://github.com/ray-project/kuberay/pull/3299 follow-ups. Move isOpenShift to options.
Consolidate options management.
N/A
> [refactor] move isOpenShift to options

- ray-operator/controllers/ray/metrics/metrics.go
- ray-operator/controllers/ray/metrics/ray_cluster_metrics.go
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/main.go
Replace package-level metrics with with a `RayClusterMetricCollector` struct that implements `prometheus.Collector`.
https://github.com/ray-project/kuberay/pull/3204#discussion_r2033657264
> [Refactor] Encapsulate RayCluster metrics in a custom Prometheus collector

- apiserver/test/e2e/job_server_e2e_test.go
Fix merge conflict between https://github.com/ray-project/kuberay/pull/3328 and https://github.com/ray-project/kuberay/pull/3285
> [apiserver] [high-priority] Fix API server merge conflict

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
- helm-chart/ray-cluster/tests/raycluster_test.yaml
- helm-chart/ray-cluster/values.yaml
- Add Helm chart unit tests to ray-cluster
- Fix the issue that `head.topologySpreadConstraints` and `worker.topologySpreadConstraints` does not work.
Close #3373 .
Part of #3277 .
> Add Helm chart unit tests to ray-cluster

- proto/config.proto
- proto/serve.proto
> [apiserver] Fix typos in apiserver proto

- ray-operator/DEVELOPMENT.md
Closes: ray-project/kuberay#3400
> [Docs][ray-operator] Add types of tests and debug tips to development doc

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
Use `with` instead of `if` to simplify Helm templates of ray-cluster.
Close #3377 .
Part of #3277 .
> [Refactor][Helm] Use with to simplify ray-cluster templates

- helm-chart/ray-cluster/templates/raycluster-cluster.yaml
- Adjust the indention of ray-cluster template files.
- ~Rename file `raycluster-cluster.yaml` to `raycluster.yaml`~.
> [Refactor][Helm] Adjust the indention of ray-cluster template files

- kubectl-plugin/go.mod
- kubectl-plugin/go.sum
- ray-operator/go.mod
- ray-operator/go.sum
Auto upgrade PR fails CI, which requires human intervene to fix: https://github.com/ray-project/kuberay/pull/3398
Closes #3441 
> [Feature] Fix auto upgrade prometheus

- apiserver/test/e2e/service_server_e2e_test.go
This PR is part of https://github.com/ray-project/kuberay/issues/3313, checking the test coverage for `pkg/http`
Upon inspection, `UpdateRayService` is not tested in e2e test yet. So I add a `TestUpdateRayService` function to test it. Here's the test results:
```
$ go test ./test/e2e -v -run TestUpdateRayService
=== RUN   TestUpdateRayService
--- PASS: TestUpdateRayService (1.63s)
PASS
ok  	github.com/ray-project/kuberay/apiserver/test/e2e	1.762s
```
Closes #3313
> [Feature] Add e2e test for UpdateRayService function

- proto/go.mod
- proto/go.sum
Fixes https://github.com/ray-project/kuberay/pull/3396
Closes #3438
> bump protobuf version

- apiserver/Makefile
* Make `make cluster` **idempotent**
* Display help messages of `start-local-apiserver` and `clear-local-apiserver` in `make help` manual
* Fix `clear-local-apiserver` `.PHONY` target name
The current API server `Makefile` contains several issues that hinder the developer experience. This PR introduces targeted refactors to improve usability and maintainability.
https://github.com/ray-project/kuberay/issues/3384
> [Refactor] Improve API server developer experience

- CONTRIBUTING.md
- apiserver/README.md
As title.
1. Code of Coduct -> Code of Conduct
2. familar -> familiar
3. remove duplicate by 
> [docs] Correct typos in CONTRIBUTING.md and api-server README.md

- apiserver/test/e2e/types.go
- apiserver/test/e2e/utils.go
Observation was conducted in #3455.
Closes #3426 
> [Apiserver] Set the right amount of resource in e2e test

- helm-chart/kuberay-operator/templates/_helpers.tpl
- helm-chart/kuberay-operator/templates/deployment.yaml
- helm-chart/kuberay-operator/values.yaml
Backports https://github.com/ray-project/kuberay/pull/3198
cc @andrewsykim
> [1.3 BACKPORT] Allow app.kubernetes.io/component to be overriden (#3198)

- apiserversdk/proxy.go
This is a small improvement that makes sure we don't repeatedly call `config.Middleware` to create multiple handlers. 
> [apiserversdk] use config.Middleware at most once

- apiserversdk/proxy.go
- apiserversdk/proxy_test.go
> [apiserversdk] Add query filter to proxy

- .github/workflows/image-release.yaml
This reverts commit 0d813b4d83361e47d2660d95f4f16e68fb78b115.
> Revert "[Bug][CI] Multi-platform build fails with docker driver in GitHub Actions (#3570)"

- .github/workflows/test-job.yaml
I tested this PR by https://github.com/kevin85421/kuberay/pull/33.
* GH action: https://github.com/kevin85421/kuberay/actions/runs/14936522653/job/41965118518?pr=33
* Quay: https://quay.io/repository/kevin85421/kuberay?tab=tags
> [CI] Fix MultiArch image push

- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/common/pod_test.go
Automatically detect MIG GPUs and pass them into Ray’s logical resources
Closes #3506
> [Feature] Auto detect MIG GPUs and pass them into Ray’s logical resources

- apiserversdk/proxy.go
1. make `withFieldSelector` private.
2. change `Kuberay` to `KubeRay`.
> [apiserversdk] make withFieldSelector private and consistent 'KubeRay'

- apiserver/pkg/server/validations_test.go
See discussion https://github.com/ray-project/kuberay/pull/3546#discussion_r2078913718
By creating a valid template and modifying/unsetting specific fields, can clearly see what each test case is testing.
> [refactor] Use mutate funcs to clearly show per-test field changes

- ray-operator/controllers/ray/raycluster_controller.go
See https://github.com/ray-project/kuberay/issues/3597#issuecomment-2878151773 for more details.
This is the unconditional requeue I mention. I think it is not necessary to have unconditional requeue, but it needs more investigation.
https://github.com/ray-project/kuberay/blob/a9c48c150b3cb99aec4b29e434d7a1861c96d36a/ray-operator/controllers/ray/raycluster_controller.go#L350 
Closes #3597
> [chore] Remove misleading log

- dashboard/src/app/layout.tsx
- docs/best-practice/worker-head-reconnection.md
- docs/design/protobuf-grpc-service.md
- docs/guidance/aws-eks-iam.md
- docs/guidance/kuberay-with-MCAD.md
- docs/guidance/rayclient-nginx-ingress.md
- docs/reference/api.md
- docs/release/helm-chart.md
- proto/go_client/cluster.pb.go
- ray-operator/DEVELOPMENT.md
- ray-operator/apis/ray/v1/raycluster_types.go
- ray-operator/apis/ray/v1alpha1/raycluster_types.go
- ray-operator/controllers/ray/utils/util.go
> [docs] Fix typos

- .buildkite/test-e2e.yml
#3662
https://github.com/ray-project/kuberay/pull/3649#discussion_r2103107818
Closes #3662
> [Hotfix] Extend Autoscaler e2e tests timeout

- ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
[Test][Autoscaler] Add an E2E test for adding a new worker group
About this test:
1. Start a Ray cluster with Head group and one worker group
2. Apply the change of adding another worker group to the existing Ray cluster
3. Create a detacted actor with a specified resource
4. Verify if a new has been created and is in the newly added worker group
Closes #3618 
> [Test][Autoscaler] Add an E2E test for adding a new worker group

- .github/ISSUE_TEMPLATE/bug-report.yml
> [Chore] Add kubectl plugin and dashboard to components in issue template

- ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
- ray-operator/test/support/ray.go
> [Autoscaler] Improve `TestRayClusterAutoscalerAddNewWorkerGroup`

- helm-chart/kuberay-apiserver/templates/deployment.yaml
- helm-chart/kuberay-apiserver/templates/rbac/cluster_role.yaml
- helm-chart/kuberay-apiserver/templates/rbac/cluster_role_binding.yaml
- helm-chart/kuberay-apiserver/tests/rbac/cluster_role_binding_test.yaml
- helm-chart/kuberay-apiserver/tests/rbac/cluster_role_test.yaml
- helm-chart/kuberay-apiserver/values.yaml
This PR adds v2 related helm chart and values
Closes #3648
> [API Server] Add v2 related helm

- apiserver/Autoscaling.md
- apiserver/HttpRequestSpec.md
- apiserver/pkg/model/converter_test.go
- apiserver/test/cluster/cluster/cluster
- apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go
- apiserver/test/e2e/cluster_server_e2e_test.go
- apiserver/test/e2e/job_submission_e2e_test.go
- apiserver/test/job/job
- apiserver/test/job/query
- clients/python-apiserver-client/test/api_params_test.py
- clients/python-apiserver-client/test/kuberay_api_test.py
> [chore] Update user to `kuberay` instead of a contributor's name

- .github/workflows/image-release.yaml
Closes: ray-project/kuberay#3568
> [Fix][CI] Fix ray operator image build error by setting up docker buildx

- config/grafana/KubeRay-Operator.json
This PR improves the grafana dashboard for kuberay operator, including
1. use irate for reconciliation rate to ensure correct result.
2. remove some redundant information
3. refine some titles and description.
None
> Improve Grafana Dashboard

- go.mod
- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/README.md
- helm-chart/kuberay-operator/README.md.gotmpl
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default-with-webhooks/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
As title. Part of the release process.
> [Release] Update KubeRay version references for 1.4.0-rc.0

- ray-operator/config/samples/ray-service.llm-serve.yaml
Added Example Config For Ray-Serve LLM
> Added Ray-Serve Config For LLMs

- docs/index.md
> [doc] Update GitHub pages's home page

- ray-operator/controllers/ray/common/job.go
> [cherry-pick] Cherry-pick #3771 into release-1.4

- ray-operator/config/samples/ray-cluster.persistent-redis.yaml
> [cherry-pick] Cherry-pick #3780 into release-1.4 branch

- go.mod
- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/README.md
- helm-chart/kuberay-operator/README.md.gotmpl
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default-with-webhooks/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
> [Release] Update KubeRay version references for 1.4.0-rc.2

- ray-operator/config/samples/ray-job.interactive-mode.yaml
- ray-operator/test/sampleyaml/rayjob_test.go
> [cherry-pick] Cherry-pick #3779 into release-1.4 branch

- ray-operator/config/samples/ray-job.kueue-toy-sample.yaml
> [cherry-pick] Cherry-pick #3782 into release-1.4 branch

- ray-operator/config/samples/pytorch-text-classifier/ray-job.pytorch-distributed-training.yaml
> [cherry-pick] Cherry-pick #3796 into release-1.4 branch

- .buildkite/build-start-operator.sh
Using the correct env var for ray nightly testing integration.
> Fix ray nightly image env var setup

- .buildkite/build-start-operator.sh
> [cherry-pick] Cherry-pick #3826 into release-1.4 branch

- .pre-commit-config.yaml
- apiserver/Dockerfile
- experimental/Dockerfile
- go.mod
- proto/Dockerfile
- ray-operator/DEVELOPMENT.md
- ray-operator/Dockerfile
- ray-operator/go.mod
As I described in the related issue, this patch version will be delivered to child and grand child projets.
I would like to avoid such situations.
Closes https://github.com/ray-project/kuberay/issues/3834
> Use Go 1.24.0 in go module

- .pre-commit-config.yaml
- apiserver/Dockerfile
- experimental/Dockerfile
- go.mod
- proto/Dockerfile
- ray-operator/DEVELOPMENT.md
- ray-operator/Dockerfile
- ray-operator/go.mod
This is a cherry-pick PR from https://github.com/ray-project/kuberay/pull/3835 to release-1.4 branch.
> Cherry-pick: Use Go 1.24.0 in go module (#3835)

- ray-operator/controllers/ray/batchscheduler/interface/interface.go
- ray-operator/controllers/ray/batchscheduler/scheduler-plugins/scheduler_plugins.go
- ray-operator/controllers/ray/batchscheduler/schedulermanager.go
- ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go
- ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler.go
- ray-operator/controllers/ray/raycluster_controller.go
> pass client when call batchscheduler.New()

- kubectl-plugin/test/e2e/kubectl_ray_log_test.go
- kubectl-plugin/test/e2e/kubectl_ray_session_test.go
- ray-operator/controllers/ray/common/pod.go
- ray-operator/controllers/ray/raycluster_controller.go
- ray-operator/controllers/ray/utils/util_test.go
This is a cherry-pick PR from https://github.com/ray-project/kuberay/pull/3872 to the release-1.4 branch.
> Cherry-pick: [RayCluster] Make headpod name back to non-deterministic (#3872)

- .krew.yaml
> [Fix][Release] Fix Krew release indentation error (#3823)

- go.mod
- helm-chart/kuberay-apiserver/Chart.yaml
- helm-chart/kuberay-apiserver/values.yaml
- helm-chart/kuberay-operator/Chart.yaml
- helm-chart/kuberay-operator/README.md
- helm-chart/kuberay-operator/README.md.gotmpl
- helm-chart/kuberay-operator/values.yaml
- helm-chart/ray-cluster/Chart.yaml
- ray-operator/config/default-with-webhooks/kustomization.yaml
- ray-operator/config/default/kustomization.yaml
- ray-operator/controllers/ray/utils/constant.go
> [Release] Update KubeRay version references for 1.4.2

- apiserversdk/proxy_test.go
> [apiserversdk] add RayJob envtests

- .pre-commit-config.yaml
- helm-chart/Makefile
- helm-chart/ray-cluster/Chart.yaml
- helm-chart/ray-cluster/README.md
- helm-chart/ray-cluster/README.md.gotmpl
- helm-chart/ray-cluster/values.yaml
Similar to https://github.com/ray-project/kuberay/pull/3331.
Use [helm-docs](https://github.com/norwoodj/helm-docs) to keep the chart README up-to-date.
Since we may have many new fields in the future, having a README to check whether the fields in the RayCluster chart and the RayCluster CRD remain consistent would be very helpful.
Closes #3882
> [Helm] Use helm-docs to generate README for chart ray-cluster automatically

- helm-chart/kuberay-operator/values.yaml
Add the following environment variables to the operator chart:
- ENABLE_LOGIN_SHELL
- ENABLE_RANDOM_POD_DELETE
- RAYJOB_DEPLOYMENT_STATUS_TRANSITION_GRACE_PERIOD_SECONDS
> [Helm] Add missing environment variables to operator chart

- apiserversdk/proxy_test.go
> [apiserversdk] add RayService envtests

- .pre-commit-config.yaml
- helm-chart/Makefile
- helm-chart/kuberay-apiserver/README.md
- helm-chart/kuberay-apiserver/README.md.gotmpl
- helm-chart/kuberay-apiserver/values.yaml
Similar to https://github.com/ray-project/kuberay/pull/3331.
Use [helm-docs](https://github.com/norwoodj/helm-docs) to keep the chart README up-to-date.
Closes #3914
> [Helm] Use helm-docs to generate README for chart api-server automatically

- apiserver/pkg/server/ray_job_submission_service_server.go
- ray-operator/controllers/ray/utils/dashboard_httpclient.go
- ray-operator/controllers/ray/utils/fake_serve_httpclient.go
Remove the ctrl package in `dashboard-httpclient.go`, and remove the name argument in SubmitJobReq since it is no longer being logged.
> [refactor][4/N] Remove ctrl in dashboard http client in `dashboard-httpclient.go`

- ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go
the Volcano logger does not add context (such as CR name, namespace, or reconcile ID) to log messages. Use ctrl logger to instead.
before:
```
$ kubectl logs  deployment/kuberay-operator -f | grep "Pod group CREATE error"
{"level":"error","ts":"2025-08-31T09:55:52.471Z","logger":"volcano","msg":"Pod group CREATE error!","PodGroup.Error":"create not allowed while custom resource definition is terminating","error":"create not allowed while custom resource definition is terminating","stacktrace":"github.com/ray-project/kuberay/ray-operator/controllers/ray/batchscheduler/volcano.(*VolcanoBatchScheduler).syncPodGroup\n\t/home/runner/work/kuberay/kuberay/ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:82\ngithub.com/ray-project/kuberay/ray-operator/controllers/ray/batchs …
```
> Use ctrl logger in Volcano scheduler to include context

- ray-operator/config/samples/ray-cluster.autoscaler-v2.yaml
- ray-operator/config/samples/ray-cluster.autoscaler.yaml
- To document a clear, supported way to adjust autoscaler/Ray log verbosity and align docs with existing env var guidance.
Closes #4095
> [Autoscaler][Sample] Add comment for RAY_LOGGER_LEVEL
