ray-project/kuberay

apiserver/pkg/model/converter_test.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/utils/constant.go
The labels `ray.io/group=headgroup` are scattered around the kuberay source.
This PR makes the `headgroup` constant in the `utils/constant.go` which lowers the possibility of using a wrong value in the future.
=> [Refactor][RayCluster] Make ray.io/group=headgroup be constant

helm-chart/ray-cluster/values.yaml
When auto-scaling is enabled with the default worker group, the max replica count defaults to `2147483647`. 
```
> kubectl -n kuberay describe RayCluster kuberay | grep "Max Replicas" -A 1
Max Replicas:        2147483647
Min Replicas:        0
```
Upon job submission, the head node launches too many worker nodes. On a few occasions, some of the worker nodes were in `Pending` state due to lack of resources.
This PR exposes min/max replica counts for the default worker group as in additional worker groups, providing more control over resource allocation.
I have manually tested the patch to ensure the changes are effective.
=> Exposing min/max replica counts for default worker group

helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml
The current print coloumns for RayService are not being rendered, this is because they were added to the wrong type. 
This PR fixes the kubebuilder annotation and adds another coloumn for "NUM SERVE ENDPOINTS"
```
$ kubectl get rayservice
NAME                SERVICE STATUS   NUM SERVE ENDPOINTS
rayservice-sample   Running          2
```
=> [RayService] fix kubebuilder printcolumn annotations for RayService

ray-operator/config/samples/ray-job.kueue-toy-sample.yaml
https://github.com/ray-project/kuberay/pull/1956#discussion_r1511337275
This PR removes ConfigMap from the YAML. In [this doc](https://docs.ray.io/en/master/cluster/kubernetes/k8s-ecosystem/kueue.html#kuberay-kueue), we need to run `kubectl create -f ray-job.kueue-toy-sample.yaml` multiple times. If the YAML includes a ConfigMap, users may see a warning message indicating that the ConfigMap already exists. Removing the ConfigMap improves the UX.
=> chore: remove ConfigMap from ray-job.kueue-toy-sample.yaml

tests/test_sample_rayservice_yamls.py
Recently,  RayService zero downtime rollout test becomes flaky:
- https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3418#018dfb4f-8302-4e53-b41f-75d82dd3eb0d/243-2083
- https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3416#018dfb25-22b7-4b2c-8978-f2a56721b47c/6-759
- https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3372#018ded1d-5412-486a-ad0a-0224040c2c36/243-1998
https://github.com/ray-project/kuberay/pull/1837 describes the root cause and introduces a hotfix.
My previous pr https://github.com/ray-project/kuberay/pull/1928 attempts to address the issue and remove the hotfix but as shown avoce, it actually fails to resolve them.
This PR introduces logic to ensure that, for zero-downtime rollout tests, during the period when the …
=> [RayService] Address Recent Flakiness in RayService Zero Downtime Rollout Test

ray-operator/Dockerfile
Standard golang images are already publicly available. The images that we are using are just built on top of the existing one. I am not sure if they are really adding any value.
I moved the base image to a distroless image which should decrease the size of the container. Using distroless images is desirable from a security point of view as it does not have a shell and this reduces the attack surface. 
=> Use standard golang image as build image and distroless image as base image for kuberay operator.

ray-operator/main.go
We are currently using the default controller-runtime user-agent which is `manager/v0.0.0`. This PR updates Kuberay's user-agent to `kuberay-operator`. 
Note that it does not include the version of kuberay yet, but we should add that in a follow-up PR. Here's example HTTP log from apiserver that shows the new user-agent being used:
```
I0311 02:35:26.041556       1 httplog.go:131] "HTTP" verb="PUT" URI="/apis/ray.io/v1/namespaces/default/rayservices/rayservice-sample/status" latency="10.397049ms" userAgent="kuberay-operator" audit-ID="8b543d30-4d26-4e0f-96ff-7b2596d0ecb8" srcIP="10.244.0.3:54042" apf_pl="workload-low" apf_fs="service-accounts" apf_iseats=1 apf_fseats=0 apf_execution_time="8.0205ms" resp=200
```
=> Use a default user agent 'kuberay-operator' instead of the default user-agent from controller-runtime

ray-operator/config/samples/ray-cluster.tpu-v4-multihost.yaml, ray-operator/config/samples/ray-cluster.tpu-v4-singlehost.yaml
Adding the `app.kubernetes.io/name: kuberay` label on RayClusters which is required by the TPU webhook to inject env variables.
=> Add missing labels on RayCluster TPU manifests

ray-operator/Makefile
[elastic/crd-ref-docs](https://github.com/elastic/crd-ref-docs) released v0.0.11 yesterday, which caused the KubeRay CI to fail ([example](https://github.com/ray-project/kuberay/actions/runs/8259776939/job/22594249665)). This PR pins the version of crd-ref-docs to v0.0.10.
* The test `operator-consistency-check / ray-operator-verify-api-docs (pull_request) ` passes.
=> [CI] Pin crd-ref-docs to v0.0.10

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go
#1785 checks `numDeletedHeads` to determine whether to create the Redis cleanup Kubernetes Job or not. However, `numDeletedHeads` does not always indicate the number of head Pods that have been deleted but rather those that are in the process of being deleted. Hence, since GCS is still running, the Redis key will not be fully deleted.
* Create a RayCluster with [ray-cluster.external-redis-uri.yaml](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis-uri.yaml).
* Delete the RayCluster: `kubectl delete rayclusters.ray.io raycluster-external-redis-uri`
* Check the Redis after all Ray Pods are deleted.
```sh
kubectl exec -it $YOUR_REDIS_POD -- redis-cli -a "5241590000000000"
KEYS * # expected behavior: no key (without …
```
=> [Bug][GCS FT] Clean up the Redis key before the head Pod is deleted

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/constant.go
The previous PR 1742 changed RayService to use DashboardPort instead of DashboardAgentPort. 
This PR fixes the log and comments to reflect that change.
=> Fix Log to indicate we are Using DashboardPort in RayService

helm-chart/ray-cluster/values.yaml
After spending a while not understanding why my monitoring annotations wouldn't be set on the head service of my clusters I noticed the chart uses `.Values.head.headService` instead of `.Values.service.headService` like specified in the default `values.yaml`
This PR would do the trick but I think using `.Values.head.serviceType` instead of `.Values.service.type` in the templates would be an even better solution for consistency :)
=> [Fix][Helm chart] Move service.headService -> head.headService in values.yaml

ray-operator/Dockerfile
=> [Cherry-pick] Use standard golang image as build image and distroless image as base image for kuberay operator. (#1967)

cli/go.mod, cli/go.sum
Bumps google.golang.org/protobuf from 1.32.0 to 1.33.0.
---
updated-dependencies:
- dependency-name: google.golang.org/protobuf dependency-type: indirect ...
=> [Cherry-pick] Bump google.golang.org/protobuf from 1.32.0 to 1.33.0 in /cli (#1993)

ray-operator/controllers/ray/raycluster_controller_fake_test.go
Parameterizing `Test_ShouldDeletePod` following the review comment here: https://github.com/ray-project/kuberay/pull/1386#pullrequestreview-1611687999
Also I'm assuming https://github.com/ray-project/kuberay/issues/1392 talks about `Test_ShouldDeletePod` and not `Test_RunningPods_RayContainerTerminated`? Lmk!
Fixes https://github.com/ray-project/kuberay/issues/1392 
=> ray-operator: parameterize Test_ShouldDeletePod

helm-chart/kuberay-operator/values.yaml
=> Add seccompProfile.type=RuntimeDefault to kuberay-operator.

docs/development/release.md, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/utils/constant.go, ray-operator/controllers/ray/utils/util.go, ray-operator/main.go
=> [Telemetry] KubeRay version and CRD

helm-chart/ray-cluster/templates/_helpers.tpl, ray-operator/controllers/ray/raycluster_controller.go
This PR fixes a reconciler error when changing the value of `nameOverride` in the values.yaml of a Helm installation for a Ray cluster.  For example, if you update it to `raycluster-custom-name` and install, you will get the following error in the Operator:
`{"level":"info","ts":"2024-03-06T04:34:09.108Z","logger":"controllers.RayCluster","msg":"Got error when calculating new status","RayCluster":{"name":"raycluster-custom-name","namespace":"default"},"reconcileID":"01e6413b-5175-40a1-ad3b-e822cee72e9a","cluster name":"raycluster-custom-name","error":"unable to find head service. cluster name raycluster-custom-name, filter labels map[app.kubernetes.io/created-by:kuberay-operator app.kubernetes.io/name:kuberay ray.io/cluster:raycluster-custom-name …
=> [Bug] Reconciler error when changing the value of nameOverride in values.yaml of helm installation for Ray Cluster

tests/compatibility-test.py, tests/framework/prototype.py, tests/framework/utils.py
As discussed with @kevin85421 offline, we think that we should test the redis cleanup job in the `tests/compatibility-test.py`.
This PR appends the `cleanup_redis` procedure to every test in the `RayFTTestCase` to test the cleanup job by deleting the RayCluster CR and watching the Redis' `DBSIZE` to zero. If it doesn't go zero before timeout, then the test will fail.
Fixes https://github.com/ray-project/kuberay/issues/1997
=> [Test][RayCluster] Test redis cleanup job in the e2e compatibility test

docs/development/development.md, helm-chart/ray-cluster/README.md
These examples are a little misleading, clean them up to clarify behavior.
n/a
=> Remove extranous arguments from examples

helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml
In our online environment, we run over 200 rayjobs daily, and sometimes certain rayjobs encounter issues. Typically, users provide us with two types of information:
They inform us that a specific job named `xgboost-rayjob-batch-xxx` is failing. In such cases, we can use `kubectl describe rayjob xgboost-rayjob-batch-xxx` to identify the headnode of this rayjob. By logging into the head pod, we can examine relevant logs and resolve the problem.
Occasionally, users report problems with a particular ray cluster. In these cases, I would like to quickly locate the rayjob running on that ray cluster. Currently, I can only filter operator logs to identify the issue.
I believe it would be helpful if we could print the cluster information associated with a rayjob when users execute `kubectl get …
=> [RayJob] Add Cluster Name For Rayjob.

apiserver/Makefile
Closes #2054
```sh
make docker-image cluster load-image deploy
```
=> [Bug] Change image repository for `make deploy`

ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/suite_helpers_test.go
This PR aims to follow up [issue#2045](https://github.com/ray-project/kuberay/issues/2045).  The purpose of this initiative is to maintain consistency in association methods and avoid scattering MatchingLabels usage throughout the entire codebase.
In this PR, I focus on updating the `suite_helpers_test.go` file to reflect this change.
#2045 
=> [Refactor] Use RayClusterHeadPodsAssociationOptions to replace MatchingLabels

.github/workflows/consistency-check.yaml, .github/workflows/image-release.yaml, .github/workflows/test-job.yaml, ray-operator/Makefile
Kustomize releases v5.4.0 today, and it requires Go 1.21 instead of Go 1.20 ([ref](https://github.com/kubernetes-sigs/kustomize/blob/116b307b88c0e6bafa9f11e01df5783beafd91f5/kustomize/go.mod#L3)). This PR pins Kustomize to v5.3.0 to fix the CI failure ([example](https://github.com/ray-project/kuberay/actions/runs/8559646066/job/23460583399?pr=2064)).
=> [CI] Pin kustomize to v5.3.0

helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml
```
(ray) ubuntu@jjyao-dev:~/Workspace/kuberay/ray-operator/config/samples (jjyao/first)$ sudo kubectl get rayjob
NAME            JOB STATUS   DEPLOYMENT STATUS   RAY CLUSTER NAME                 START TIME             END TIME               AGE
rayjob-sample   SUCCEEDED    Complete            rayjob-sample-raycluster-znv6g   2024-04-04T21:11:16Z   2024-04-04T21:13:01Z   2m25s
```
=> Show cluster name in kubectl get rayjob

ray-operator/config/samples/ray-service.gke-http-gateway-ingress.yaml, ray-operator/config/samples/ray-service.gke-model-configmap.yaml
This PR contains an example of using Kubernetes Gateway API to expose RayServe Service on GKE with Gateway and HTTP Route Deployment.
Gateway API is the successor of Ingress and the newest way of Exposing services running in the same or multiple namespaces. Gateway API offers multiple benefits and is both powerful and flexible at the same time.
This Kubernetes page provides a list of reasons why one should switch to [GatewayAPI](https://gateway-api.sigs.k8s.io/guides/migrating-from-ingress/#reasons-to-switch-to-gateway-api)
As far as I know, there is currently no logged issue for this.
=> Ray serve gke gateway ingress

ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/utils/util.go
Avoid dereferencing nil pointers when resources.requests are not set.
Closes #2076 
* Install a RayCluster with [this gist](https://gist.github.com/kevin85421/06f0e2da52f21644173d3ad371ef3ade).
* Without this PR, KubeRay will crash because of nil pointer dereference as stated in #2076.
=> [Bug] Ray operator crashes when specifying RayCluster with resources.limits but no resources.requests

ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/suite_helpers_test.go
This PR adds tests for the atomic suspend operation. See #1799 and #1798 for more details.
Besides the new test, this PR also refactors the normal suspending test in `rayjob_controller_suspended_test.go` to make it more compact and compatible with the latest RayJob.
Closes #1799
=> [RayJob] Add Tests for Atomic Suspend Operation

apiserver/go.mod, apiserver/go.sum, cli/go.mod, cli/go.sum, experimental/go.mod, experimental/go.sum, proto/go.mod, proto/go.sum, ray-operator/go.mod, ray-operator/go.sum
There's currently a High CVE detected by Snyk. Upgrading `golang.org/x/net` to v0.23.0 will fix it.
CVE: https://www.cve.org/CVERecord?id=CVE-2023-45288 
=> CVE fix - Upgrade golang.org/x/net

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/fake_httpproxy_httpclient.go, ray-operator/controllers/ray/utils/httpproxy_httpclient.go
I observed that `NumServeEndpoints` changes frequently especially after we start to watch `Endpoints` in #2080. The error message is: 
```
Get \"http://10.244.0.6:8000/-/healthz\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
The [timeout](https://github.com/ray-project/kuberay/blob/3738f78fa8e89a2b61d2d28e3f2710c5036f3a33/ray-operator/controllers/ray/utils/httpproxy_httpclient.go#L27) of the HTTP client is 20 ms. Hence, I increase the timeout to 2 seconds which is the same as the [dashboard HTTP client](https://github.com/ray-project/kuberay/blob/3738f78fa8e89a2b61d2d28e3f2710c5036f3a33/ray-operator/controllers/ray/utils/dashboard_httpclient.go#L106).
* Test
* With this PR, `CheckProxyActorHealth` does not fail during my 30-minute experiment. See [this …
=> [Hotfix] Increase the timeout of the ProxyActor health check

.buildkite/test-sample-yamls.yml, helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml, helm-chart/kuberay-operator/templates/role.yaml, ray-operator/config/rbac/role.yaml, ray-operator/controllers/ray/rayservice_controller.go, tests/framework/prototype.py, tests/test_sample_rayservice_yamls.py
The `Get` operation in controller-runtime also requires `watch` permission. See https://github.com/kubernetes-sigs/controller-runtime/issues/1156 for more details. This PR (1) adds the `watch` permission for the endpoints, and (2) improves the observability of the requests sent by `curl` commands so that users can log in to the `curl` Pod and check the response.
I observed that many requests fail due to timeout, so I think there may be resource contention if we launch 20 curl processes simultaneously. Hence, this PR also adds `time.sleep(1)` between each curl request. 
* TODO: Why does adding `watch` cause the RayService sample YAML tests to fail frequently if we don't add `time.sleep(1)`?
Closes #2073
=> [Bug] KubeRay operator failed to watch endpoint

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go
Some users only upgrade the KubeRay image without upgrading the CRD. For example, when a user upgrades the KubeRay operator from v1.0.0 to v1.1.0 without upgrading the CRD, the KubeRay operator will use the zero value of `NumOfHosts` in the CRD. Hence, all worker Pods will be deleted. This PR ensures that `NumOfHosts` will always be larger than or equal to 1.
Closes #2084 
* Step 1: Install a KubeRay operator via KubeRay v1.0.0 Helm chart.
* Step 2: Install a RayCluster via KubeRay v1.0.0 Helm chart.
* Step 3: Build a KubeRay operator image (`controller:latest`)
* Step 4: Upgrade KubeRay operator via `helm upgrade` (note that the CRD will not be updated)
```sh
helm upgrade --install kuberay-operator kuberay/kuberay-operator --version 1.1.0 --set …
```
=> [Bug] All worker Pods are deleted if using KubeRay v1.0.0 CRD with KubeRay operator v1.1.0 image  

apiserver/pkg/server/ray_job_submission_service_server.go, helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml, helm-chart/kuberay-operator/templates/role.yaml, ray-operator/apis/config/v1alpha1/configuration_types.go, ray-operator/config/rbac/role.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/suite_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go, ray-operator/controllers/ray/utils/fake_httpproxy_httpclient.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go, ray-operator/controllers/ray/utils/httpproxy_httpclient.go, ray-operator/main.go
There are some cases where Kuberay may not be able to directly connect to a Ray head node. For example, there might be a NetworkPolicy disallowing ingress from all Pods or KubeRay is running on a network with no connectivity to Pods. This PR allows Kuberay to use the `services/proxy` subresource to proxy HTTP requests to the Ray head node. This allows Kuberay to make requests to the head node without every connecting to it directly.
Here are some sample HTTP requests in apiserver from my testing using the proxy subresource:
```
I0310 14:30:19.596708       1 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/default/services/rayjob-sample-raycluster-phsj9-head-svc:dashboard/proxy/api/jobs/rayjob-sample-th44t" latency="7.239221ms" userAgent="manager/v0.0.0 (linux/amd64) …
```
=> support using proxy subresources when connecting to Ray head node

apiserver/pkg/model/converter.go, apiserver/test/e2e/config_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go
=> ray-operator coding style change

ray-operator/controllers/ray/common/association.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go
This PR aims to follow up https://github.com/ray-project/kuberay/issues/2045. The purpose of this initiative is to maintain consistency in association methods and avoid scattering MatchingLabels usage throughout the entire codebase.
In this PR, I update the files related with RayService, and add a new AssociationOptions `GetRayClusterWithRayServiceAssociationOptions`.
#2045 
=> [Refactor][RayService] Add GetRayClusterWithRayServiceAssociationOptions

ray-operator/DEVELOPMENT.md, ray-operator/test/support/test.go
Running the operator outside the cluster allows developers to set breakpoints in their IDEs for debugging purposes.
N/A
1. Create a Kubernetes cluster by `kind create cluster --image=kindest/node:v1.24.0` or `k3d cluster create` or `minikube start`
3. `make -C ray-operator install`
4. `make -C ray-operator build`
5. `./ray-operator/bin/manager -leader-election-namespace default -use-kubernetes-proxy`
6. `make -C ray-operator test-e2e`
=> [Chore] Run operator outside the cluster

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
`cleanupInvalidVolumeMounts` verifies and modifies the Pod spec directly which may introduce some unknown unknowns for users. KubeRay should only verify the RayCluster, RayJob, and RayCluster specs. For other resource specs, such as Kubernetes Pods, Jobs, and Services, we should not verify them; instead, we should only propagate the errors.
* Step 1: Create a RayCluster with https://gist.github.com/kevin85421/22c0f1792fe475bb80c3ec7a3180915a. The Ray container in the head Pod mounts a non-existent volume.
```yaml
volumeMounts:
- mountPath: /home/ray/samples
name: ray-example-configmap
- mountPath: /home/ray/
name: not-exist
```
* Step 2: We can find the error by running `kubectl describe raycluster xxxx`.
=> [Refactor] Remove `cleanupInvalidVolumeMounts`

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/suite_helpers_test.go, ray-operator/pkg/client/applyconfiguration/ray/v1/rayclusterstatus.go
My ML platform team runs the kuberay ray-operator. We want to measure the time
it takes for RayCluster's to transition from their initial "unhealthy" state to
some other state. This metric is important for us because our users want their
RayClusters to start in a timely manner. It seems like neither the ray-operator
nor RayClusters provide this info currently.
Add a new `.status.stateTransitionTimes` field to the `RayCluster` custom
resource. This field is a `map[ClusterState]*metav1.Time` that indicates the
time of the last state transition for each state. This field is updated
whenever the `.status.state` changes.
* [original discussion doc](https://docs.google.com/document/d/14yPSZ9iLk7a0qEg14rNWr60Btz0HEeQ3oWKP-GN9QTM)
* [related Slack …
=> feat: record last state transition times

benchmark/perf-tests/100-raycluster/raycluster.yaml, benchmark/perf-tests/100-rayjob/rayjob.yaml, benchmark/perf-tests/README.md
TODO:
* [Prometheus metrics](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2#prometheus-metrics)
* If RayJob custom resources cannot complete indefinitely due to the lack of gang scheduling, it appears that the `clusterloader` process does not time out even after 20 minutes.
#2102 
I modified the script a bit to create 10 RayJob CRs on my local Kind cluster.
=> [Perf] Improve perf-test YAMLs and README

ray-operator/controllers/ray/raycluster_controller_test.go
In PR #2053, the envtest was added to the "Suspend RayCluster", which is specific to Kueue. This PR moves the envtest to the main workflow of RayCluster.
#2053 
=> [Test] Move StateTransitionTimes envtest to a better place

config/grafana/data_grafana_dashboard.json, config/grafana/default_grafana_dashboard.json, config/grafana/serve_deployment_grafana_dashboard.json, config/grafana/serve_grafana_dashboard.json
1. Upgrade the Ray Grafana dashboard from 2.5.0 to 2.9.0.
2. Add the Grafana dashboards for Ray Data / Ray Serve.
=> [Grafana] Update Grafana dashboard

ray-operator/config/samples/ray-cluster.sample.yaml
There are `ray-job.sample.yaml` and `ray-service.sample.yaml` but no `ray-cluster.sample.yaml`. Also it seems that `ray-cluster.mini.yaml` is not useful because it does not specify `workerGroupSpecs`. Therefore, this PR:
1. Rename `ray-cluster.mini.yaml` to `ray-cluster.sample.yaml`.
2. Add `workerGroupSpecs` section in that file.
=> [Chore][Samples] Rename ray-cluster.mini.yaml and add workerGroupSpecs

ray-operator/config/samples/pytorch-mnist/ray-job.pytorch-mnist.yaml, ray-operator/config/samples/pytorch-mnist/ray_train_pytorch_mnist.py
Our scalability test requires some CPU-based workloads. This PR uses CPU to train a MNIST model. I also can run the RayJob successfully on my devbox.
=> [Perf] Add a CPU-based training workload

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go
=> [Cherry-pick][Bug] All worker Pods are deleted if using KubeRay v1.0.0 CRD with KubeRay operator v1.1.0 image (#2087)

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/pkg/client/applyconfiguration/ray/v1/rayclusterstatus.go
A worker Pod is ready if it has a PodCondition with `type == Ready` and `status ==
True`. See https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions
=> feat: add `RayCluster.status.readyWorkerReplicas`

ray-operator/apis/config/v1alpha1/configuration_types.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/suite_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/main.go
- Based on @kevin85421's suggestion at https://github.com/ray-project/kuberay/pull/1980#discussion_r1550243563
- Instead of passing function(s) to `NewRayServiceReconciler` and `NewRayJobReconciler`, initialing them by the `v1alpha1.Configuration` configuration
- https://github.com/ray-project/kuberay/pull/1980
- [] Unit tests
=> Init dashboardClientFunc and httpProxyClientFunc by the config arg

ray-operator/config/samples/pytorch-mnist/ray-job.pytorch-mnist.yaml, ray-operator/config/samples/pytorch-mnist/ray_train_pytorch_mnist.py
Hi @kevin85421, @andrewsykim,
I have made `num_workers` and the CPU part of `resources_per_worker` configurable with envs.
https://github.com/ray-project/kuberay/pull/2116#discussion_r1589696298
=> [Perf] Add NUM_WORKERS and CPUS_PER_WORKER env to the mnist workload

.pre-commit-config.yaml, ray-operator/DEVELOPMENT.md
Add pre-commit hooks supports so that developers can know format errors without running the CI.
Reference: https://github.com/nginxinc/nginx-gateway-fabric/blob/0b0f7111364cd6f06883e414f7ef118207ee7677/.pre-commit-config.yaml
N/A
=> [1/N][Chore] Add pre-commit hooks

.github/workflows/test-job.yaml
pre-commit hooks will be the single source of truth for formatting rules. Therefore this PR replaces all linting CI with pre-commit.
Depends on https://github.com/ray-project/kuberay/pull/2127
N/A
=> [3/N][CI] Replace lint CI with pre-commit

.pre-commit-config.yaml
Because https://github.com/ray-project/kuberay/pull/2129 replaces the CI with pre-commit and https://github.com/ray-project/kuberay/pull/2128 adds new golangci-lint rules, the CI will fail. Therefore this PR temporarily turns off golangci-lint rules except `ray-operator`.
N/A
=> [4/N][Chore] Turn off golangci-lint rules except ray-operator

.pre-commit-config.yaml
Because we use pre-commit in CI, the `no-commit-to-branch` rule must be turned off.
N/A
=> [Chore] Turn off no-commit-to-branch rule

.golangci.yml
Add golangci-lint rules.
Reference:
1. https://github.com/nginxinc/nginx-gateway-fabric/blob/0b0f7111364cd6f06883e414f7ef118207ee7677/.golangci.yml
2. https://github.com/ray-project/kuberay/blob/f77ee03117d2a48b31e041da58e49e16649fd487/.github/workflows/test-job.yaml
Related PR: https://github.com/ray-project/kuberay/pull/2127
N/A
=> [N/N][Chore] Add golangci-lint rules

.golangci.yml, ray-operator/controllers/ray/utils/httpproxy_httpclient.go
Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `noctx`
N/A
=> [Style] Fix golangci-lint rule: noctx

.golangci.yml, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/suite_helpers_test.go, ray-operator/controllers/ray/utils/util.go
Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `unconvert`
N/A
=> [Style] Fix golangci-lint rule: unconvert

ray-operator/DEVELOPMENT.md
Delete the linting docs because `golangci-lint` already includes the `gofumpt` rule.
See https://github.com/ray-project/kuberay/pull/2128 for the rules.
N/A
=> [Docs][Development] Delete linting docs

.pre-commit-config.yaml, ray-operator/.golangci.yml
Some CI fails because other modules (e.g. `experimental`) also use `golangci-lint` and the new rules in the repository root cause them to fail.
- https://github.com/ray-project/kuberay/actions/runs/9068220792/job/24915020733?pr=2141
- https://github.com/ray-project/kuberay/actions/runs/9093023649/job/24991053965?pr=2144
Therefore, this PR moves the `.golangci.yml` into the `ray-operator` folder.
N/A
=> [Chore] Use new golangci-lint rules only for ray-operator

ray-operator/.golangci.yml, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/test/support/events.go
Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `errorlint`
N/A
=> [Style] Fix golangci-lint rule: errorlint

benchmark/perf-tests/100-raycluster/config.yaml, benchmark/perf-tests/100-raycluster/raycluster.yaml, benchmark/perf-tests/100-raycluster/results/junit.xml, benchmark/perf-tests/100-raycluster/wait-for-rayclusters.sh, benchmark/perf-tests/100-rayjob/config.yaml, benchmark/perf-tests/100-rayjob/pytorch-mnist-rayjob.yaml, benchmark/perf-tests/100-rayjob/ray-data-image-resize.yaml, benchmark/perf-tests/100-rayjob/results/junit.xml, benchmark/perf-tests/100-rayjob/wait-for-rayjobs.sh, benchmark/perf-tests/images/ray-pytorch/Dockerfile
Updates the 100 RayJob perf test to use pytorch trainer and Ray Data example workloads
[](https://github.com/ray-project/kuberay/issues/2069)
=> [perf-test] update 100 RayJob perf tests to use PyTorch trainer and Ray Data examples

cli/README.md, cli/pkg/cmd/cluster/create.go, clients/python-client/python_client/utils/kuberay_cluster_builder.py, helm-chart/kuberay-operator/values.yaml, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
The current normal k8s service for Ray Head works very well, except for a rare [hairpin issue](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1679595093811179?thread_ts=1678309468.145329&cid=C02GFQ82JPM) and a special need of [reducing IP usages](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1712780988188599?thread_ts=1712333199.632539&cid=C02GFQ82JPM). However, given that the purpose of the normal k8s service is hiding multiple endpoints behind a shared virtual address, it does not make much sense in the context of Ray. A Ray cluster can only have one head node at any given time and all its worker nodes can not change their Head either. So a headless service, enabling direct access without a virtual IP, makes much sense to Ray.
This PR changes the default service for a …
=> [Feat][RayCluster] Make the Head service headless

ray-operator/config/samples/ray-data-image-resize/ray-job.image-resize.yaml, ray-operator/config/samples/ray-data-image-resize/ray_data_image_resize.py
This PR makes the bucket and bucket prefix configurable in the rat-data-image-resize sample job.
I also refactored ray_data_image_resize.py since I ran into a bunch of issues with `ray.data.read_images` 
https://github.com/ray-project/kuberay/issues/2069
Logs from my test using a larger dataset:
```
$ kubectl logs -f image-resize-10-nodes-4wmng                                                                                                                                                                                                                                                             
2024-05-17 10:57:45,258 INFO cli.py:36 -- Job submission server address: http://image-resize-10-nodes-raycluster-t2sm7-head-svc.default.svc.cluster.local:8265 …
```
=> [perf-tests] make the bucket name and prefix configurable for ray data image resize job

helm-chart/kuberay-operator/values.yaml, helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
Currently you can only set the securityContext at the container level with the RayCluster Helm chart.
https://github.com/ray-project/kuberay/issues/2136
=> Added Pod securityContext value to Helm charts

ray-operator/controllers/ray/common/association.go, ray-operator/test/e2e/create_detached_actor.py, ray-operator/test/e2e/raycluster_autoscaler_test.go, ray-operator/test/e2e/terminate_detached_actor.py, ray-operator/test/support/core.go, ray-operator/test/support/ray.go
See https://github.com/ray-project/kuberay/issues/2173 for more details.
=> [Test][Autoscaler][1/n] Add Ray Autoscaler e2e tests

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
Currently, when updating RayService config, changing MinReplicas or MaxReplicas in the autoscaling config triggers an entirely new RayCluster to be instantiated.  In order to facilitate orchestrating canary deployments, we'd like to have the ability to scale those parameters on an existing cluster as we move traffic over.
Currently no issue linked, but I can create one if needed.
=> RayService: Omits Min and Max replicas from hash calculation

ray-operator/.golangci.yml, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/suite_helpers_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go
Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `ginkgolinter`
N/A
=> [Style] Fix golangci-lint rule: ginkgolinter

ray-operator/config/samples/pytorch-resnet-image-classifier/ray-job.pytorch-image-classifier.yaml
add CPU limit to worker group.
Otherwise using this RayJob YAML might result in the error of Pod using more CPU requests than the default limit.
=> fix: update ray-job.pytorch-image-classifier.yaml

ray-operator/.golangci.yml, ray-operator/apis/ray/v1/raycluster_webhook.go, ray-operator/controllers/ray/batchscheduler/interface/interface.go, ray-operator/controllers/ray/batchscheduler/schedulermanager.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/suite_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go, ray-operator/controllers/ray/utils/fake_httpproxy_httpclient.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go, ray-operator/test/e2e/rayjob_lightweight_test.go, ray-operator/test/e2e/rayjob_suspend_test.go, ray-operator/test/e2e/rayjob_test.go, ray-operator/test/support/ray.go
Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `revive`
N/A
=> [Style] Fix golangci-lint rule: revive

ray-operator/test/e2e/create_detached_actor.py, ray-operator/test/e2e/raycluster_autoscaler_test.go, ray-operator/test/support/ray.go
Continue the work on https://github.com/ray-project/kuberay/issues/2173 for GPU e2e tests.
https://github.com/ray-project/kuberay/issues/2173 for more details.
=> [Test][Autoscaler][2/n] Add Ray Autoscaler e2e tests for GPU workers

ray-operator/.golangci.yml, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/suite_helpers_test.go
Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `unparam`
N/A
=> [Style] Fix golangci-lint rule: unparam

ray-operator/.golangci.yml, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/test/support/meta.go, ray-operator/test/support/test.go
Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `nolintlint`
N/A
=> [Style] Fix golangci-lint rule: nolintlint

ray-operator/.golangci.yml, ray-operator/apis/ray/v1/webhook_suite_test.go, ray-operator/controllers/ray/utils/util.go
Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `gosec`
This PR does the following:
- Adds a comment to explain why we can use `Sha1` hash.
- Adds a comment to explain `InsecureSkipVerify` is used.
N/A
=> [Chore] Fix golangci-lint rule: gosec

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
For a correct configuration of the v2 autoscaler, it is necessary to override the restartPolicy. See: https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/configuring-autoscaling.html#autoscaler-v2-with-kuberay
No issue
=> Allow configuration of restartPolicy

.buildkite/test-sample-yamls.yml
=> [Fix] Use go 1.22 on Buildkite autoscaler e2e tests

ray-operator/controllers/ray/utils/dashboard_httpclient.go
When logging the `FetchHeadServiceURL` function, the port field was included as a string `defaultPortName`. This caused issues in Logz.io, where the port field was expected to be a long integer. The port field from the log entry is removed to ensure only `headServiceURL` is logged.
=> Fix logging issue for FetchHeadServiceURL

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/test/e2e/rayjob_retry_test.go, ray-operator/test/support/ray.go
Unified the code path of `checkBackoffLimitAndUpdateStatusIfNeeded` to avoid forgetting to call the function when we have a new case to fail the RayJob in the future.
I manually tested the case that RayJob exceeded `ActiveDeadlineSeconds`.
* Create a RayJob with [this YAML](https://gist.github.com/kevin85421/37ef825a826129dd94797f5dcf86b4f2). The RayJob sets `activeDeadlineSeconds` to 1 second and the `backoffLimit` to 2. The expected behavior is that the RayJob should not retry although the `backoffLimit` is not 0 because it fails due to timeout.
```
{"level":"info","ts":"2024-07-02T17:02:22.504Z","logger":"controllers.RayJob","msg":"RayJob is not eligible for retry due to failure with DeadlineExceeded","RayJob":{"name":"rayjob-sample","namespace":"default"},"reconcileI …
```
=> [RayJob] Unified checkBackoffLimitAndUpdateStatusIfNeeded codepath and add an e2e test for retry

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/suite_test.go, ray-operator/main.go
The `--reconcile-conccurency` flag only applies for the RayCluster controller, it should also apply for the RayJob and RayService controllers.
=> reconcile concurrency flag should apply for RayJob and RayService controllers

scripts/rbac-check.py
The default PyYAML loaders are not safe for all inputs. This change switches the helm RBAC verification script from CLoader to CSafeLoader.
While I doubt this is being abused currently, there's no reason not to switch to a loader that disallows arbitrary Python object construction. 
From the PyYAML [documentation](https://pyyaml.org/wiki/PyYAMLDocumentation):
> Loader supports all predefined tags and may construct an arbitrary Python object. Therefore it is not safe to use Loader to load a document received from an untrusted source.
See also the unsafe loader [deprecation notice](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).
N/A
=> [Chore] Use safe YAML for helm-chart-verify-rbac

helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml
The multi-namespace role was missing a deletecollection verb for pod resources. [This verb is present for the single namespace role](https://github.com/ray-project/kuberay-helm/blob/bbde24accbfc842201d7c4c7e6d2e7ebb01bb69f/helm-chart/kuberay-operator/templates/role.yaml#L52-L62).
https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1719259919331299
- Used chart version 1.1.0 locally
- Applied this patch locally and pods were deleted
=> fix: Add deletecollection for multi-namespace role to helm charts

ray-operator/test/e2e/rayjob_retry_test.go
Add the "The RayJob in HTTPMode fails and retries" test.
https://github.com/ray-project/kuberay/blob/ea314d7ee780e840382f3de852918f69d7867f25/ray-operator/test/e2e/rayjob_retry_test.go#L89-L93
Testing was conducted on my Apply M2 Mac, with the RayImage changed to `rayproject/ray:2.9.0-aarch64` in the `ray-operator/test/support/defaults.go` file.
Below are the commands I used for the test and the resulting test logs. 
```
$ cd ray-operator
$ kind create cluster --image=kindest/node:v1.24.0
$ IMG=kuberay/operator:nightly make docker-build
$ kind load docker-image kuberay/operator:nightly
$ helm install kuberay-operator --set image.repository=kuberay/operator --set image.tag=nightly ../helm-chart/kuberay-operator
$ go test -timeout 30m -v ./test/e2e/rayjob_retry_test.go …
```
=> [RayJob] add Failing RayJob in HTTPMode e2e test for rayjob with retry

ray-operator/Dockerfile, ray-operator/main.go, ray-operator/pkg/features/features.go
Add feature gating to KubeRay. This uses standard feature gate implementation used by Kubernetes components. 
None
=> add feature gate mechanism to ray-operator

ray-operator/test/e2e/rayjob_retry_test.go
Add test for rayjob_retry_test.go.
https://github.com/ray-project/kuberay/blob/ea314d7ee780e840382f3de852918f69d7867f25/ray-operator/test/e2e/rayjob_retry_test.go#L83-L87
Make sure RayJob status reaches to JobDeploymentStatusFailed after ActiveDeadlineSeconds regardless of retry times.
```
$ kind delete cluster
$ sudo rm -rf bin
$ cd ray-operator
$ kind create cluster --image=kindest/node:v1.24.0
$ IMG=kuberay/operator:nightly make docker-build
$ kind load docker-image kuberay/operator:nightly
$ helm install kuberay-operator --set image.repository=kuberay/operator --set image.tag=nightly ../helm-chart/kuberay-operator
$ go test -timeout 30m -v ./test/e2e/rayjob_retry_test.go ./test/e2e/support.go 2>&1 | tee e2e-rayjob-test.log
```
```
--- PASS: TestRayJobRetry (175.48s) …
```
=> [RayJob] add RayJob pass Deadline e2e-test with retry

.github/workflows/e2e-tests.yaml, docs/components/cli.md
CLI is being deprecated and this removes the file that was causing the deploy ci step to fail. Also removed residual `cli/` mentions in the repo.
=> Fix for deploy error with deprecated cli

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
Implementation details of this PR:
- `updateClusterState` and `updateClusterReason` functions are integrated into a single function `updateRayClusterStatus`.
- The `inconsistentRayClusterStatus` checking is moved into `updateRayClusterStatus`, so that the status will only be updated if it is inconsistent.
- `calculateStatus` function takes one more argument called `reconcileErr`. If it is a non-nil value, then the `Status.State` will be set to `Failed` and `Status.Reason` will be set to the string representation of the error.
- Reconcile functions for each resource:
- Before: Calling each reconcile function and if there is an error, update the status and then return immediately.
- Now: Stored reconcile functions into a slice and …
=> [Refactor][RayCluster] Unify status update to single place

ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
We should always stop writing `rayv1.Failed` to the `Status.State` field.  The detailed reason is described here:https://docs.google.com/document/d/1bRL0cZa87eCX6SI7gqthN68CgmHaB6l3-vJuIse-BrY/edit . The new way to indicate failure is described here: https://github.com/ray-project/kuberay/pull/2245/files
Closes #2234 
=> Don’t assign the rayv1.Failed to the State field

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go, ray-operator/controllers/ray/utils/util_test.go
This is a revised draft of https://github.com/ray-project/kuberay/pull/2245 based on the review.
In this version, a `RayClusterReplicaFailure` condition will be set whenever the `reconcilePods()` returns a `reconcileErr`. This is done by the `calculateStatus()` based on the `reconcileErr` solely. It assumes the `reconcilePods()` is the last reconciliation function.
We also consolidate the fine-grained condition reasons in the previous draft into one `FailedReconcilePods` for simplicity.
Tests are conducted in three parts:
1. Assert the `reconcilePods()` will return a `reconcileErr`.
2. Assert the `calculateStatus()` will set the condition only when the feature gate is enabled.
3. Assert the `inconsistentRayClusterStatus()` will report `true` when conditions are changed.
=> [Feat][RayCluster] Use a new RayClusterReplicaFailure condition to reflect the result of reconcilePods

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/common/association.go, ray-operator/controllers/ray/common/association_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/pkg/client/applyconfiguration/ray/v1/headinfo.go
Closes https://github.com/ray-project/kuberay/issues/2236
This PR adds the new `PodName` to the `HeadInfo` status. And make RayService use the field to fetch the Head Pod.
=> [Feature] REP 54: Add PodName to the HeadInfo

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/utils/constant.go
Have updated Probes Timeout Seconds for Ray Clusters to 2 seconds, as the value used in the probes command for wget timeout is 2 seconds. Also added the wget timeout to be picked from readiness default timeout seconds.
Initially Default Timeout Seconds for both the probes were 1 second, which used to result in the failure of probes, even before the wget command gets finished.
#2264  
=> Updated default timeout seconds for probes

ray-operator/Dockerfile, ray-operator/Dockerfile.buildx
#2205 changes the base image of `Dockerfile.buildx` from `registry.access.redhat.com/ubi9/ubi-minimal:9.3` to `gcr.io/distroless/base-debian11:nonroot` which uses GLIBC_2.31. However, KubeRay operator requires GLIBC_2.32 and GLIBC_2.34. KubeRay operator Pod will fail with the following logs:
```
/manager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /manager)
/manager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /manager)
```
This issue is similar to https://github.com/GoogleContainerTools/distroless/issues/1342, so this PR upgrades the base image from `debian11` to `debian12`.
I can reproduce the issue by pulling images that are built by GitHub Actions. However, when I build the image following the same steps as GitHub …
=> [Bug] Issue with glibc version GLIBC_2.34 and GLIBC_2.32 not found in earlier operator tags

ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
This PR adds RayClusterReady condition type. See here for the reason: https://docs.google.com/document/d/1bRL0cZa87eCX6SI7gqthN68CgmHaB6l3-vJuIse-BrY/edit.
RayClusterReady indicates whether all Ray Pods are ready when the RayCluster is first created.
```yaml
Conditions:
Last Transition Time:   2024-07-30T05:58:56Z
Message:                
Reason:                 HeadPodRunningAndReady
Status:                 True
Type:                   HeadPodReady
Last Transition Time:   2024-07-30T05:58:56Z
Message:                All Ray Pods are ready. Future checks focus on the head
Reason:                 AllPodRunningAndReady
Status:                 True
Type:                   RayClusterReady
```
After RayClusterReady is set to true for the first time, it only indicates whether the RayCluster's …
=> Add RayClusterReady Condition Type 

ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go, ray-operator/controllers/ray/utils/util_test.go
@MortalHappiness found the previous implementation of `RayClusterReplicaFailureReason` failed to capture condition reasons correctly. It made a wrong positional assumption on the error tree passed in so it failed in integration. 
This PR removes the wrong assumption by using the `errors.As` function which traverses the whole tree and finds the first target by the specified pointer type (i.e. the *errRayClusterReplicaFailure). The `RayClusterReplicaFailureReason` can now return the correct condition reason no matter how the error is wrapped.
FailedCreateHeadPod Example:
=> [Fix][RayCluster] Make the RayClusterReplicaFailureReason to capture the correct reason

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
kuberay autoscaler pod should use same command and args as ray head container
this is how we found this issue:
1. we have build image, which has .bashrc in /root, in .bashrc, we export PATH=/opt/miniconda/bin:PATH
2. for ray-head, it works well, since it use /bin/bash -lc to load .bashrc script, but for autoscaler container, it will fail with error: 'failed to create containerd task: failed to create shim task: Could
not run process: container_linux.go:370: starting container process caused:
exec: "ray": executable file not found in $PATH: unknown'
3. usually we build ray image to make sure  ray head works well, so we may missing the situation in autoscaler. so auotscaler container should be better to use same command and args as ray head container
=> kuberay autoscaler pod use same command and args as ray head container

helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/values.yaml
Currently, we don't have support to disable leader election via kuberay values.yaml
to disable leader election and prevent leader election lost errors:
```
leaderElectionEnabled: false
```
true is the default, so there is no need to check if enabled
https://github.com/ray-project/kuberay/issues/2252
https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1717181822513479
https://github.com/ray-project/kuberay/issues/2252
=> Support disable leader election for manager go binary via Values.yaml to mitigate kuberay restarts

helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/values.yaml
This is a follow up for https://github.com/ray-project/kuberay/pull/2262#pullrequestreview-2217437641.
* Case 1: `leaderElectionEnabled: true` -> `helm template .`
* Case 2: `leaderElectionEnabled: false` -> `helm template .`
* Case 3: `leaderElectionEnabled` is not set -> `helm template .`
=> [Helm] Enable leader election when leaderElectionEnabled is not set

kuberay.code-workspace
The cli directry was removed in favor of kubectl-plugin
=> add kubectl-plugin directory to kuberay.code-workspace

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
This PR attempts to fix issues https://github.com/ray-project/kuberay/issues/2125
if head pod has been evicted, we will delete it and let it restart or recreate
https://github.com/ray-project/kuberay/issues/2125
=> [RayCluster][Fix] evicted head-pod can be recreated or restarted

ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
See https://github.com/ray-project/kuberay/issues/2297 for the reason.
`RayClusterProvisioned` represents the first time all Ray pods are ready. So after `RayClusterProvisioned` is set to true for the first time, It will not change any more:
```yaml
Last Transition Time:   2024-08-10T23:00:02Z
Message:                All Ray Pods are ready for the first time
Reason:                 AllPodRunningAndReadyFirstTime
Status:                 True
Type:                   RayClusterProvisioned
```
Closes #2297
=> Add RayClusterProvisioned Condition Type

ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
Follow-up to https://github.com/ray-project/kuberay/pull/2301, we should also set set the RayClusterProvisioned status with condition `False` while the cluster is being provisioned for the first time.
The new condition when cluster is provisioning:
```
status:
conditions:
- lastTransitionTime: "2024-08-13T02:50:44Z"
message: 'containers with unready status: [ray-head]'
reason: ContainersNotReady
status: "False"
type: HeadPodReady
- lastTransitionTime: "2024-08-13T02:50:44Z"
message: RayCluster Pods are provisioning
reason: RayClusterPodsProvisioning
status: "False"
type: RayClusterProvisioned
```
Related to https://github.com/ray-project/kuberay/issues/2297
=> RayClusterProvisioned status should be set while cluster is being provisioned for the first time

ray-operator/config/samples/ray-service.high-availability.yaml
* `DAGDriver` has been completely removed from Ray Serve since Ray 2.9. Therefore, this PR removes `DAGDriver` from the YAML.
* https://github.com/ray-project/kuberay/pull/1649#issuecomment-1813282187
* OOM issue: This PR increases the memory request / limit from 1GB to 2GB.
* KubeRay operator fails to receive the response from the `GET` ("context deadline exceeded") request. 
```json
{"level":"error","ts":"2024-08-19T23:53:21.930Z","logger":"controllers.RayService","msg":"Fail to reconcileServe.","RayService":{"name":"rayservice-ha","namespace":"default"},"reconcileID":"7edec0fb-a933-4f1b-8498-f2596888869c","error":"Failed to get Serve application statuses from the dashboard. If you observe this error consistently, please check https://github.com/ray-project/kuberay/blob/master/docs/guida …
```
=> [release blocker][v1.2.0] Fix HA OOM issue

helm-chart/kuberay-operator/templates/_helpers.tpl, helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/values.yaml, ray-operator/config/rbac/role.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go
When using RayJob with HTTPMode, kuberay sends a POST request through the services/proxy subresource to submit a Ray job. POST http requests correlate to the `create` verb when using services/proxy resource which is missing. This PR adds the `create` verb for the `services/proxy` subresource in the kuberay-operator ClusterRole. 
=> [RayJob] allow create verb for services/proxy, which is required for HTTPMode

apiserver/go.mod, ray-operator/go.mod
Vulnerability scanning shows `Critical` and `Medium` severity vulnerabilities in ray-operator v1.2.0-rc.0 image due to go version 1.22.3. This PR bumps the go toolchain to 1.22.4 to fix these errors.
ray-operator image showing vulnerabilities: `gcr.io/gke-release-staging/ray-operator@sha256:56f36fe9a805a271b218f16df009f06a1d785d53ff4b27a5bb2e5c33f52e7d97`
=> Bump go to 1.22.4 to fix ray-operator vulnerabilities

ray-operator/config/samples/pytorch-mnist/ray-job.pytorch-mnist.yaml
There is a breaking change from `ray:2.9` to `ray:2.34.0`, the reserved resources for CPUs increased from 2 to 3. So the CPU resource for the head pod needs to be increased to reflect this change.
See https://github.com/ray-project/ray/issues/47316 for details.
Closes: ray-project/kuberay#2329
=> [Fix][Sample-Yaml] Increase ray head CPU resource for pytorch minst

ray-operator/controllers/ray/rayservice_controller.go
The comment at https://github.com/ray-project/kuberay/issues/2088#issuecomment-2319156015 mentioned that when upgrading from KubeRay v1.1.1 to KubeRay v1.2.0, updating the RayService CR will trigger the zero downtime upgrade as expected. The old RayCluster will eventually be torn down. However, the K8s service for serving will not point to the new RayCluster.
The reason is that the head service defaults to be headless from KubeRay v1.2.0. However, `ClusterIP` is immutable, so K8s API server will report error. Hence, the reconciliation will exit at L209 because of the head service error, so the serve K8s service's reconcile function L215 will not be executed.
https://github.com/ray-project/kuberay/blob/a69252e6cc90995a3b3085f14af5bcc6869a2d93/ray-operator/controllers/ray/rayservice_controll …
=> [RayService] Use original ClusterIP for new head service

kubectl-plugin/pkg/cmd/cluster/cluster_get.go, kubectl-plugin/pkg/cmd/cluster/cluster_get_test.go
This PR renames filenames and variables using the [top command in the kubectl repo](https://github.com/kubernetes/kubectl/tree/master/pkg/cmd/top) as a reference.
I find some variable naming will cause problem when implementing sub-commands of the `kubectl ray cluster` command. For example, because here
https://github.com/ray-project/kuberay/blob/6c1c16e03370bcc98c08d5e91479f2ddff69a55d/kubectl-plugin/pkg/cmd/cluster/get.go#L19-L24
the options struct is named `ClusterOptions`, if a new command `kubectl ray cluster session` needs to be implemented, it cannot use the name `ClusterOptions` because they both belong to the same package `cluster`. By renaming this to `ClusterGetOptions`, the `session` command can name its options as `ClusterSessionOptions`, which prevents the naming conflict …
=> [Refactor][kubectl-plugin] Rename filenames and variables based on kubectl repo

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
Generate events for when the raycluster_controller fails to create:
- Head pods
- Worker pods
The event generated has EventTypeWarning as the event type. This commit also introduces the following event reasons as constants for ease of use and testing:
- FailedToCreateResource ("Failed")
- CreatedResource ("Created")
- DeletedResource ("Deleted")
This commit additionally adds in tests to verify this behaviour.
Towards https://github.com/ray-project/kuberay/issues/2250 
cc @rueian @kevin85421
=> raycluster_controller: generate events for failed pod creation

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
* Move event types to `constant.go`.
* Refactor some logs to make them consistent.
* Remove `fmt.Sprintf` from some `logger.Info(fmt.Sprintf(...))`.
* `logger.Info("Created $resource", "name", $name)`
* `pod` -> `Pod` 
* Use `CreatedWorkerPod` in the function `createWorkerPod` instead of `CreatedHeadPod`.
=> [Refactor] Fix CreatedWorkerPod for worker Pod deletion event and refactor logs

ray-operator/controllers/ray/rayservice_controller.go
The log message has defined a redundant time unit - the `ServiceDefaultRequeueDuration` variable is of type `time.Duration`, so it's unnecessary to include the time unit in the log message.
=> Don't print redundant time unit in the log message

ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/suite_helpers_test.go, ray-operator/test/support/ray.go
In the progress of https://github.com/ray-project/enhancements/pull/54, we have added the new `.Status.Conditions` field to replace the single `.Status.State` and we are planning not to make further changes to the `.Status.State` anymore. So mark it deprecated to prevent future changes on the field.
=> [Feature][RayCluster]: Deprecate the RayCluster .Status.State field

ray-operator/apis/config/v1alpha1/config_utils_test.go
golangci-lint is failing with this error:
```
apis/config/v1alpha1/config_utils_test.go:78:11: printf: non-constant format string in call to (*testing.common).Logf (govet)
t.Logf(tt.name)
^
```
This log line is not needed anyways since the test is wrapped with `t.Run(tt.name, func(t *testing.T)`. 
=> Remove redundant log line that is failing golangci-lint

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/utils/constant.go
This is a follow-up to https://github.com/ray-project/kuberay/issues/2264 and https://github.com/ray-project/kuberay/pull/2265 
For the Head pod, the exec probe timeout should be higher than 2 as exec probes run 2 "wget" commands:
```
wget -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success
&& wget -T 2 -q -O- http://localhost:8265/api/gcs_healthz | grep success
```
This PR updates the probe timeout for Head pods to 5 seconds. See https://github.com/ray-project/kuberay/pull/2265#discussion_r1742846215 for more details. 
https://github.com/ray-project/kuberay/issues/2264
=> Use longer exec probe timeouts for Head pods

kubectl-plugin/go.mod, kubectl-plugin/go.sum, kubectl-plugin/pkg/cmd/ray.go, kubectl-plugin/pkg/cmd/session/session.go, kubectl-plugin/pkg/cmd/session/session_test.go
This PR implements the Ray session part in this [REP](https://github.com/ray-project/enhancements/blob/main/reps/2024-05-21-ray-kubectl-plugin.md#ray-session---interactive-client--dashboard).
N/A
=> [Feature][kubectl-plugin] Implement kubectl ray session

kubectl-plugin/README.md, kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/log/log_test.go, kubectl-plugin/pkg/cmd/ray.go
This PR adds the `kubectl ray cluster logs` command to retrieve the head node logs for a ray cluster.
=> Add kubectl ray cluster log command

ray-operator/config/samples/vllm/ray-service.vllm.yaml, ray-operator/config/samples/vllm/serve.py
Allow pipeline-parallel-size to be configurable in the vLLM example
Related to https://github.com/ray-project/kuberay/issues/2354
=> add support for pipeline-parallel-size in vLLM example

.github/workflows/actions/compatibility/action.yaml, .github/workflows/e2e-tests-reusable-workflow.yaml, .github/workflows/test-job.yaml
Closes: ray-project/kuberay#2372
=> [CI][GitHub-Actions] Upgrade actions/upload-artifact to v4

helm-chart/kuberay-operator/values.yaml, ray-operator/apis/config/v1alpha1/config_utils.go, ray-operator/apis/config/v1alpha1/config_utils_test.go, ray-operator/controllers/ray/batchscheduler/schedulermanager.go, ray-operator/controllers/ray/batchscheduler/schedulermanager_test.go, ray-operator/main.go
Per review comment here: https://github.com/ray-project/kuberay/pull/2300#issuecomment-2337070070. Remove the redundant "default" option for the batch scheduler name.
How this was tested?
- UT (this PR added UT coverage for various cases)
- Local tests
```
// normal start up
./ray-operator/bin/manager -leader-election-namespace default -use-kubernetes-proxy
// batchscheduler.enabled=true
// this enables volcano integration
./ray-operator/bin/manager -enable-batch-scheduler -leader-election-namespace default -use-kubernetes-proxy
// batchscheduler.name=volcao
// this enables volcano integration
./ray-operator/bin/manager -batch-scheduler volcano -leader-election-namespace default -use-kubernetes-proxy
{"level":"info","ts":"2024-09-10T16:18:31.104-0700","logger":"setup","msg":"Feature flag …
```
=> Remove default option for batch scheduler name

kubectl-plugin/.gitignore
Add `.gitignore` to `kubectl-plugin` folder to ignore the `kubectl-ray` binary.
N/A
=> [Chore][Minor] Add .gitignore to kubectl-plugin

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
Following the [KubeRay CRD Observability Improvement Workstream](https://docs.google.com/document/d/1NCX3fCTiE817AV4chvR46bkNHR7q0zy4QXQfDu-dqF4/edit?usp=sharing), we add the two missing events for Redis Cleanup Job Creation:
* CreatedRedisCleanupJob
* FailedToCreateRedisCleanupJob
=> [Feature][RayCluster]: Generate GCS FT Redis Cleanup Job creation events

.github/workflows/test-job.yaml, .pre-commit-config.yaml, helm-chart/ray-cluster/templates/raycluster-cluster.yaml, ray-operator/DEVELOPMENT.md, scripts/openapi2jsonschema.py, scripts/validate-helm.sh
To resolve issue #2254, the absence of a Kubernetes manifest validation process caused the errors listed in the issue when deploying the Helm Chart. During validation, I also discovered that running `helm template ./` in `helm-chart/ray-cluster` resulted in `.template.spec.containers.ports` being set to `null` (which should either be omitted or set to an empty list `[]`). I have fixed this issue as well.
Closes #2254 
#2174 
#2239 
I reproduced the error from Issue #2174. Running `helm template ./` within the `helm-chart/ray-cluster` directory generates the following output:
```
ray-cluster $ helm template ./
---
metadata:
labels:
helm.sh/chart: ray-cluster-1.1.0
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
name: …
```
=> [Feature] Add Kubernetes manifest validation in pre-commit.

kubectl-plugin/README.md, kubectl-plugin/pkg/cmd/ray.go
This PR updates README.md to add instruction for static shell completion for kubectl ray plugin. Static means that we haven't implemented [Dynamic completion of nouns](https://github.com/spf13/cobra/blob/main/site/content/completions/_index.md#dynamic-completion-of-nouns) yet.
Also the default `completion` command in `cobra` is disabled because the shell completion for `kubectl` plugin works differently from normal commands. Therefore this command is useless. I removed it to avoid confusion. See https://github.com/kubernetes/kubernetes/issues/74178 and https://github.com/kubernetes/kubernetes/pull/105867 for details.
Screenshot (my shell is fish shell):
N/A
=> [Feat][kubectl-plugin] Add instructions for static shell completion

kubectl-plugin/go.mod, kubectl-plugin/pkg/cmd/session/session.go, kubectl-plugin/pkg/cmd/session/session_test.go, kubectl-plugin/pkg/util/client/client.go, kubectl-plugin/pkg/util/client/client_test.go, kubectl-plugin/pkg/util/types.go
https://github.com/ray-project/kuberay/pull/2298 only implemented `kubectl ray session` for `RayCluster`. This PR implements `kubectl session` for `RayJob` and `RayService`.
N/A
=> [Feat][Kubectl-Plugin] Implement kubectl session for RayJob and RayService

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
When a Kubernetes Job cannot be successfully created, it logs the error and generates an event for the failed job creation.
Refer to https://github.com/ray-project/kuberay/issues/2210
=> [RayJob] Add Failure Feedback (log and event) for Failed k8s Creation Task

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
This PR first continues @tinaxfwu's work on https://github.com/ray-project/kuberay/pull/2306 with new event naming and centralization of events to the `constant.go` file.
And following [the RayCluster status improvement workstream](https://docs.google.com/document/d/1NCX3fCTiE817AV4chvR46bkNHR7q0zy4QXQfDu-dqF4/edit), we also add events for RayCluster creation and deletion. Resulting in these 8 new events for RayJob controller:
```go
CreatedRayJobSubmitter        K8sEventType = "CreatedRayJobSubmitter"
DeletedRayJobSubmitter        K8sEventType = "DeletedRayJobSubmitter"
FailedToCreateRayJobSubmitter K8sEventType = "FailedToCreateRayJobSubmitter"
FailedToDeleteRayJobSubmitter K8sEventType = "FailedToDeleteRayJobSubmitter"
CreatedRayCluster             K8sEventType = "CreatedRayCluster" …
```
=> [Feature][RayJob]: Generate submitter and RayCluster creation/deletion events

kubectl-plugin/pkg/cmd/session/session.go, kubectl-plugin/pkg/util/completion/completion.go, kubectl-plugin/pkg/util/completion/completion_test.go
Implement dynamic shell completion for `kubectl ray session` command.
Note: I haven't found a proper way to mock the cmd Factory to get custom resources for testing.
Screencast:
https://github.com/user-attachments/assets/b1df97c1-2be2-4985-a2f0-ec82b51db98a
N/A
=> [Feat][kubectl-plugin] Add dynamic shell completion for kubectl ray session

ray-operator/config/samples/ray-data-image-resize/ray-data-image-resize-gcsfusecsi-job.yaml, ray-operator/config/samples/ray-data-image-resize/ray_data_image_resize_gcsfuse.py
This is a variant of the ray data processing job (`ray_data_image_resize.py`) which leverages GKE GCSFuse CSI driver
to process the images from [Landsat public dataset](https://cloud.google.com/storage/docs/public-datasets/landsat)
In the template code, the bucket name has been replaced with a sample name `ray-images` and the prefix for the data sample has been replaced by `prefix` 
This ray job demonstrates how to mount a GCS bucket using the [GKE GCSFuse CSI driver](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver) and access th contents of a bucket  in a ray job
logs from a successful run on a n2-standard-32 machine type GKE nodes
```
2024-09-26 14:43:39,774	INFO cli.py:36 -- Job submission server address: …
```
=> Add a variant of the ray data processing job with GCSFuse CSI driver

apiserver/pkg/client/cluster.go, apiserver/pkg/client/job.go, apiserver/pkg/client/kubernetes.go, apiserver/pkg/client/service.go, apiserver/pkg/manager/client_manager.go
=> cleanup: remove unused initConnectionTimeout for RayClient in apiserver

kubectl-plugin/.goreleaser.yaml, kubectl-plugin/pkg/cmd/ray.go, kubectl-plugin/pkg/cmd/version/version.go
Closes: ray-project/kuberay#2423
=> [Feat][kubectl-plugin] Add kubectl ray version command

ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/suite_helpers_test.go, ray-operator/controllers/ray/utils/util.go
Resolves https://github.com/ray-project/kuberay/issues/2277
~~This PR introduces a new status condition: `RayClusterSuspend` with two variations, `RayClusterSuspending` and `RayClusterSuspended`.~~
This PR introduces two new status conditions: `RayClusterSuspending` and `RayClusterSuspended`.
The new conditions will populated by default with `metav1.ConditionFalse` if the `features.Enabled(features.RayClusterStatusConditions)` is enabled.
When the gate is enabled, we rely on the new `RayClusterSuspending` to suspend a RayCluster atomically. When a user turns on the `.Spec.Suspend` of a RayCluster, we will enable the `RayClusterSuspending` and persist it before actually stopping all Pods. We will stop all Pods in the next reconciliation and do not consider the `.Spec.Suspend` again before …
=> [Feature][RayCluster]: introduce RayClusterSuspending and RayClusterSuspended conditions

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/test/e2e/rayjob_lightweight_test.go, ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
- This PR is a followup to the https://github.com/ray-project/kuberay/pull/2409 to support adding to resources passed as part of rayStartParams
- https://github.com/ray-project/kuberay/pull/2409#discussion_r1785425100
https://github.com/ray-project/ray/issues/44361
=> [Refactor] Support adding custom accelerator to resources in rayStartParams

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/constant.go
This PR adds `InvalidRayJobSpec`, `InvalidRayJobStatus`, `InvalidRayServiceSpec`, and `InvalidRayClusterStatus` events.
These are existing validations that only have logs, but no event has been produced. Thus we add events for them for better CR observability. For example:
Closes https://github.com/ray-project/kuberay/issues/2437
=> feat: add InvalidRayJobSpec, InvalidRayJobStatus, InvalidRayServiceSpec and InvalidRayClusterStatus events

ray-operator/config/samples/ray-job.tpu-v6e-multihost.yaml, ray-operator/config/samples/ray-job.tpu-v6e-singlehost.yaml, ray-operator/config/samples/tpu/tpu_list_devices.py
Follow up to https://github.com/ray-project/kuberay/pull/2445, this PR modifies `tpu_list_devices.py` to get the number of TPU devices from `ray.available_resources` rather than a runtime environment variable. Additionally, this PR renames the RayJob CRs to include the accelerator and chip size (in case we add more single or multi-host examples).
=> Fix v6e TPU Scripts and RayJob CRs

docs/reference/api.md, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/cmd/job/job_submit_test.go, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/suite_helpers_test.go, ray-operator/controllers/ray/utils/constant.go
Update the experimental `UserMode` submission mode to `InteractiveMode`, which I think better expresses the intend of the API. 
Also updates the new interactive mode to check the existing field `rayjob.spec.jobId` for the submission ID instead of checking for a new annotation.  
=> [RayJob] UserMode -> InteractiveMode and check rayjob.spec.jobId instead of annotation

kubectl-plugin/README.md
Closes: ray-project/kuberay#2449
=> [Docs][kubectl-plugin] Add instructions for downloading from GitHub release

.pre-commit-config.yaml, kubectl-plugin/pkg/cmd/ray.go, kubectl-plugin/pkg/cmd/version/version.go, kubectl-plugin/pkg/util/client/client.go, kubectl-plugin/pkg/util/client/client_test.go
Added the `kubectl ray version` feature to dynamically query the deployment version of the KubeRay operator. The `LabelSelector` used is `app.kubernetes.io/name in (kuberay-operator,kuberay)`, with the Helm Chart corresponding to the `kuberay-operator` and the Kustomize corresponding to `kuberay`.
However, there is a small issue: when users install using the Helm chart and modify `Values.nameOverride`, the CLI is unable to retrieve the version.
```
$ ./kubectl-ray version
kubectl ray plugin version: development
Warning: KubeRay operator installation cannot be found - did you install it with the name "kuberay-operator"?
$ helm install kuberay-operator kuberay/kuberay-operator
$ ./kubectl-ray version
kubectl ray plugin version: development
KubeRay operator version: v1.2.2
```
```
$ helm …
```
=> [Feature][kubectl-plugin] add KubeRay operator version query

apiserver/pkg/util/cluster.go, apiserver/pkg/util/cluster_test.go
=> fix(apiserver): env MEMORY_* use memory ResourceField

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
- Consistent parsing of custom accelerator resources and adding them to ray start params, by sorting the resource limits.
- This makes sure that the first custom accelerator resource gets picked up from the resource limits
- Also fixes a flaky test case.
Address comment: https://github.com/ray-project/kuberay/pull/2425#issuecomment-2417035317
=> [Fix] Consistent parsing of custom accelerator resources

kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/log/log_test.go
This PR adds the node type "worker" and "all" to `kubectl ray log` 
Worker logs:
All RayCluster logs:
Part of #2419 
=> [Feature][kubectl-plugin] Add `all` and `worker` node type to kubectl ray log

ray-operator/test/e2e/rayjob_cluster_selector_test.go, ray-operator/test/e2e/rayjob_lightweight_test.go, ray-operator/test/e2e/rayjob_retry_test.go, ray-operator/test/e2e/rayjob_suspend_test.go, ray-operator/test/e2e/rayjob_test.go, ray-operator/test/e2e/rayservice_ha_test.go, ray-operator/test/e2e/support.go, ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go, ray-operator/test/e2eautoscaler/support.go, ray-operator/test/sampleyaml/raycluster_test.go, ray-operator/test/sampleyaml/support.go, ray-operator/test/support/batch.go, ray-operator/test/support/core.go, ray-operator/test/support/events.go, ray-operator/test/support/namespace.go, ray-operator/test/support/ray.go, ray-operator/test/support/support.go, ray-operator/test/support/test.go, ray-operator/test/support/utils.go
Implementation details for this PR:
- Remove `gomega.Gomega` from `type Test`. For each test that needs to use gomega, use `g := NewWithT(t)` directly in that test.
- Replaced all `test.Expect` with `g.Expect`, `test.Eventually` with `g.Eventually`, and `test.Consistently` with `g.Consistently`
- Now `ginkgolinter` can succesfully detect if we accidentally passed values instead of functions to `Eventually`, fix them.
- Refactored `ray-operator/test/support/ray.go` in the following way:
- `GetXXX` functions: return the objects as well as the error, if any.
- `XXX` functions (`GetXXX` functions without the `Get` prefix): directly call `GetXXX` functions, but returned a closure that can be used in `Eventually`.
- Finally removed …
=> [Refactor][Test] Don't compose Gomega in Test struct

helm-chart/kuberay-operator/values.yaml, ray-operator/apis/config/v1alpha1/config_utils.go, ray-operator/apis/config/v1alpha1/config_utils_test.go, ray-operator/controllers/ray/batchscheduler/schedulermanager.go, ray-operator/controllers/ray/raycluster_controller.go
`--enable-batch-scheduler` is deprecated. If both `--enable-batch-scheduler` and `--batch-scheduler` are set at the same time, the behavior is undefined. For example, users can set `--enable-batch-scheduler=true` and `--batch-scheduler=yunikorn`. However, Volcano will be used in this case.
This PR throws an error if both configs are set.
* Update `values.yaml`
```yaml
batchScheduler:
enabled: true
name: "volcano"
```
* Install the KubeRay operator
* Check the KubeRay operator's log
=> [scheduler] Setting both EnableBatchScheduler and BatchScheduler at the same time is not allowed

ray-operator/go.mod, ray-operator/go.sum, ray-operator/test/support/client.go, ray-operator/test/support/core.go
It's better to use the [remotecommand](https://pkg.go.dev/k8s.io/client-go/tools/remotecommand) package from client-go because this can remove dependencies for external command.
Closes #2462 
=> [REFACTOR]: refactor execute pod cmd with client-go function

kubectl-plugin/pkg/cmd/log/log.go
Currently, if there is no nodes found when using `kubectl ray log`, the command ends silently. If no `out-dir` was specified and directory is generated, it just leaves an empty dir. This PR adds a check and return error if no ray node was found as well as clean up the empty directory if directory was generated. 
Before change:
After change:
=> [Feature][kubectl-plugin]'ray log command' Add check and cleanup directory when no ray node exist

helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/templates/leader_election_role.yaml, helm-chart/kuberay-operator/values.yaml, ray-operator/config/rbac/leader_election_role.yaml
* Configmaps have no status (see eg https://github.com/kubernetes/kubernetes/blob/v1.31.2/pkg/apis/core/types.go#L1722-L1743) ; omiting this to avoid operator having to be explicitly granted that non existing subresource to apply the chart
* Supporting overriding the operator's binary path can be useful for custom rebuilds, or using a wrapper.
```
$ kubectl get configmap --subresource status myconfigmap        # k8s v1.28
Error from server (NotFound): the server could not find the requested resource
```
That's chart only change:
- [x ] Manual tests
=> Drop unused permission + configurable binary path

ray-operator/config/samples/ray-service.high-availability.yaml, ray-operator/test/sampleyaml/rayservice_test.go, ray-operator/test/sampleyaml/support.go, ray-operator/test/support/ray.go
- add `rayservice_test.go` to check RayService can successfully create RayCluster 
The skipped tests are as follows:
- ray-service-alb-ingress.yaml
- ray-service.autoscaler.yaml
- ray-service.gke-http-gateway-ingress.yaml
- ray-service.gke-model-configmap.yaml
- ray-service.high-availability-locust.yaml
- ray-service.mobilenet.yaml
- ray-service.stable-diffusion.yaml
- ray-service.text-summarizer.yaml
- ray-service.tpu-single-host.yaml
- ray-service.text-ml.yaml
Closes #2453
=> [Test] Check RayService can successfully create RayCluster

ray-operator/test/sampleyaml/rayservice_test.go
- Check if `RayService.status.numServeEndpoints` is greater than zero
Closes #2483
=> [Test] Check `.status.numServeEndpoints` is greater than zero

ray-operator/controllers/ray/common/association.go, ray-operator/test/sampleyaml/rayjob_test.go, ray-operator/test/sampleyaml/support.go, ray-operator/test/support/ray.go
- add `rayjob_test.go` to check RayJob can successfully create RayCluster
- the following yamls are not included:
- ray-job.batch-inference.yaml
- ray-job.tpu-v6e-16-multihost.yaml
- ray-job.tpu-v6e-256-multihost.yaml
- ray-job.tpu-v6e-singlehost.yaml
Closes https://github.com/ray-project/kuberay/issues/2452
=> test: add sample yaml rayjob test cases

ray-operator/test/sampleyaml/raycluster_test.go, ray-operator/test/sampleyaml/rayjob_test.go, ray-operator/test/sampleyaml/rayservice_test.go, ray-operator/test/sampleyaml/support.go, ray-operator/test/support/yaml.go
Closes: ray-project/kuberay#2497
=> [Refactor] Extract KubectlApplyYaml and yaml deserialization to support package

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
This PR adds TPUs to the list of known custom accelerators in pod.go, allowing Ray to add the TPU custom resource to the generated `rayStartCommand` when `google.com/tpu` resources are specified in the K8s container.
Manually tested by creating a RayCluster with a TPU worker group and describing the created TPU worker Pod:
```
kubectl describe <tpu-pod-name>
...
ray-worker:
Container ID:  containerd://70ace65d27a18aebbc0ae5d198e9cf8b5a95a216453adea0cbbb10104b0a82fe
Image:         rayproject/ray:2.37.0-py310
Image ID:      docker.io/rayproject/ray@sha256:0e96acf8740eb31f165c7851fa724c225d7938afbf65a73f50020c32faa3b474
Ports:         8081/TCP, 8080/TCP
Host Ports:    0/TCP, 0/TCP
Command:
/bin/bash
-lc
--
Args:
ulimit -n 65536; ray start …
```
=> Add TPU to Known Custom Accelerators for generated rayStartCommand

ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/main.go
Currently, dynamic values are formatted into a single message string in some of the logs. By having them as key-value pairs instead, the logging system can have easier log filtering, as they are stored in a key-value JSON format. In this PR, the existing logs are reformatted to achieve this purpose.
Reference: https://github.com/nginxinc/nginx-gateway-fabric/blob/main/docs/developer/logging-guidelines.md#message-guidelines
Closes #2491 
=> [Logging] Avoid using fmt.Sprintf inside logging functions

ray-operator/config/samples/ray-cluster.tpu-v6e-16-multihost.yaml, ray-operator/config/samples/ray-cluster.tpu-v6e-256-multihost.yaml, ray-operator/config/samples/ray-cluster.tpu-v6e-singlehost.yaml, ray-operator/config/samples/ray-job.tpu-v6e-256-multihost.yaml, ray-operator/config/samples/tpu/tpu_list_devices.py
This PR adds recommended fields to the v6e-256 RayCluster and RayJob sample manifests. For the larger slice size, adding `privileged: true`  resolves a `UNKNOWN: TPU initialization failed: open(/dev/vfio/vfio): No such file or directory: No such file or directory; Couldn't open vfio container /dev/vfio/vfio` error while adding `resources: '"{\"TPU\": 4}"'` to the rayStartParams resolves a race condition that sometimes occurs in RayServices and RayJobs  where Python script execution begins before TPU device detection by the Raylets, causing `ray.available_resources()["TPU"]` to return 0.
This PR was manually tested as follows:
1. Create the RayJob CR
```
kubectl apply -f https://raw.githubusercontent.com/ray-project/kuberay/master/ray-operator/config/samples/ray-job.tpu-v6e-256-multihost.ya …
```
=> Update v6e-256 KubeRay Sample

tests/framework/utils.py
The RayService tests stuck forever. I found that it is image pull error for the `curl` Pod.
=> [CI] Fix RayService CI

config/prometheus/podMonitor.yaml
Both metrics from ServiceMonitor and PodMonitor have the label `ray_io_cluster` after this PR. Before this PR, only metrics from ServiceMonitor have the label.
Part of #2502
=> [metrics] Add ray_io_cluster to all Ray metrics

ray-operator/Dockerfile
When building the image, the following warning keeps appearing. This PR changes the `as` in the Dockerfile from lowercase to uppercase to resolve this warning.
https://docs.docker.com/reference/build-checks/from-as-casing/
```
$ IMG=kuberay/operator:nightly make docker-build
go fmt ./...
go vet ./...
go build                                    \
-ldflags                                    \
"                                           \
-X 'main._buildTime_=2024-11-09 20:21:48'         \
-X 'main._commitId_=95c3830b84997c87577f00c2ed0ebcb4472b443c'         \
"                                           \
-o bin/manager main.go
"docker" build -t kuberay/operator:nightly .
[+] Building 21.8s (19/19) FINISHED …
```
=> [BUG] Fix Dockerfile WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match

ray-operator/Dockerfile
This reverts commit 9c55794fc01aedfe6cb0138936b836baaff1e1b8.
This PR makes the CI pipeline `buildkite/ray-ecosystem-ci-kuberay-ci/test-sample-yamls-latest-release` stuck forever. I haven't investigated it. Revert the commit.
https://github.com/ray-project/kuberay/pull/2530
=> Revert "[BUG] Fix Dockerfile Error: WARN: FromAsCasing: 'as' and 'FROM' Keywords' Casing Do Not match (#2527)"

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go
This PR addresses redundant context information in KubeRay logs and improves log message formatting.
Key changes:
1. Removed duplicate context information:
- Each CR's logger already includes name and namespace in its context.
- Eliminated redundant output of this information in some log messages.
- For example, removed the duplicate 'rayClusterName' field in RayCluster CR logs.
2. Improved error log message format:
- Modified error log messages to start with lowercase letters for consistency.
Closes #2514
=> [Logging] Remove duplicate info in CR logs

helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/values.yaml
When a Pod requests an emptyDir, by default it does not have a size limit which may allow it to consume excess or all of the space in the medium backing the volume. This can quickly overrun a Node and may result in a denial of service for other workloads. This PR adds a sizeLimit field to KubeRay-Operator mounting emptyDir volumes
```
helm install kuberay-operator --version 1.2.2 --set logging.sizeLimit="1Gi" --set logging.baseDir="/tmp/kuberay-operator" --set logging.fileName="kuberay-operator.log"  ../helm-chart/kuberay-operator
```
```
helm install kuberay-operator --version 1.2.2 --set logging.baseDir="/tmp/kuberay-operator" --set logging.fileName="kuberay-operator.log"  ../helm-chart/kuberay-operator
```
=> [Helm] add sizeLimit for emptyDir

.pre-commit-config.yaml
- The current pre-commit configuration uses `grep -oP`, which is a feature specific to GNU grep. This option is not supported on BSD systems (such as macOS), causing potential compatibility issues.
- To address this, we need to replace these grep commands with a more universal alternative like awk, ensuring the hooks work consistently across different Unix-like operating systems.
=> [Chore][precommit] Replace grep with awk in pre-commit hooks for BSD compatibility

ray-operator/controllers/ray/rayservice_controller.go
We only file events for the following two cases:
1. Interactions with the Kubernetes API server: For example, successfully creating Pods or creation failures.
2. Spec/Status validation failures.
However, before this PR, each reconciliation of a RayService CR would create at least one event in most cases. Although `EventCorrelator` has a rate limit and aggregates events to prevent scalability issues, it can introduce a significant delay in filing events to the Kubernetes API server if KubeRay manages multiple RayService CRs.
=> [RayService][Refactor] Avoid flooding Kubernetes events

ray-operator/controllers/ray/rayservice_controller.go
I am reading the RayService controller source code and found that `ctrlResult` is not necessary.
=> [RayService][Refactor] Remove ctrlResult

ray-operator/test/e2e/rayservice_ha_test.go, ray-operator/test/e2e/testdata/locust-cluster.const-rate.yaml
Closes: ray-project/kuberay#2517
=> [Test][HA] Test high-availability during zero-downtime upgrade

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller_test.go
Currently it is possible to specify the `ray.io/cluster` label in the Head or Worker pod template. If the label value contains an incorrect cluster name, it will result in KubeRay doing an infinite loop of creating Pods since the `ray.io/cluster` label is used as a label selector. 
Similar to other labels like `ray.io/group` and `ray.io/node-type`, this PR ensures that overriding the `ray.io/cluster` is not possible.
N/A
=> [RayCluster] don't allow overriding ray.io/cluster label

docs/reference/api.md, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/pkg/client/applyconfiguration/ray/v1/rayservicespec.go
To allow disabling zero downtime upgrade for a specific ray service
Part of https://github.com/ray-project/kuberay/issues/2397
=> [Feature] Disable zero downtime upgrade for a RayService using RayServiceSpec

ray-operator/go.mod, ray-operator/main.go
Some logs from client-go are not in JSON format.
According to https://github.com/kubernetes/client-go/issues/18#issuecomment-624162529, 
Calling `klog.SetLogger()` applies logs with JSON format from client-go.
Closes https://github.com/ray-project/kuberay/issues/2512
=> some logs are not json format

ray-operator/controllers/ray/common/rbac.go
Currently the autoscaler only need to patch rayCluster for scaling up and down. 
So it is better to remove the permission of patch pods, which is a useless permission.
We created a rayCluster with autoscaler, and after testing we found removing the permission will not affect the behavior of the autoscaler.
#2551
=> remove autoscaler's permission of patch pods

kubectl-plugin/pkg/cmd/job/job_submit.go
Check for `ray job submit` entrypoint input from user. 
Currently if there is no "--", it will cause error with `panic: runtime error: slice bounds out of range [-1:]`. 
Or if there is no `entrypoint` input after "--", the command will run through the whole cluster setup process and job submission step and then fail. Adding a check will ensure that it won't need to go through the whole setup/submission process.
=> [Feature][kubectl-plugin] return usage error when no entrypoint input

ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
Currently we're importing several external packages into the current package, which is not a good practice since it's mixing a bunch of symbols together into one "namespace" (similar to `using namespace` in C++).
=> [no-op] Avoid implicit package import

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
Closes: ray-project/kuberay#2550
=> [RayService][Refactor] Change the ServeConfigs to nested map

README.md, docs/components/pythonapiclient.md, docs/components/pythonclient.md, docs/development/development.md, docs/index.md, mkdocs.yml
- These changes fix broken links from deprecated CLI references and provide updated information on the KubeRay Python client.
- #2520
=> [Doc] Remove KubeRay CLI references and add Python client details

ray-operator/config/samples/ray-cluster-fluentbit-sidecar.yaml
Adds an example RayCluster with Fluent-Bit sidecar mode to persist Ray logs. and reference the YAML in this [PR](https://github.com/ray-project/ray/pull/49038).
Using [downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) to get kubernetes metadata.
```yaml
- name: fluentbit
image: fluent/fluent-bit:3.2.2
env:
- name: POD_LABELS
valueFrom:
fieldRef:
fieldPath: metadata.labels['ray.io/cluster']
```
https://github.com/ray-project/ray/pull/49038
=> [Docs] add sample RayCluster with FluentBit sidecar to persist Ray logs

ray-operator/config/samples/ray-cluster.auth.yaml
Forgot to include --config-file in kube-rbac-proxy and fix apiGroup and apiVersion in kube-rbac-proxy config file
N/A
=> [Doc] Fix RayCluster auth sample to include --config-file in kube-rbac-proxy

kubectl-plugin/test/e2e/kubectl_ray_cluster_get_test.go, kubectl-plugin/test/e2e/kubectl_ray_e2e_suite_test.go, kubectl-plugin/test/e2e/kubectl_ray_log_test.go
This adds e2e test for `kubectl ray log`.
=> [Feature][kubectl-plugin] e2e test for 'kubectl ray log'

ray-operator/test/e2eautoscaler/create_concurrent_tasks.py, ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go, ray-operator/test/e2eautoscaler/support.go
Closes https://github.com/ray-project/kuberay/issues/2575
This PR adds a integration for autoscaling, basically spins up a bunch of tasks and check whether max pod replica count has reached during the process.
=> Add test for autoscaler and its desired state

.github/workflows/e2e-tests-reusable-workflow.yaml, ray-operator/test/e2e/rayservice_in_place_update_test.go
1. Increase the timeout from 30m to 60m because the time for a normal run needs around 27 ~ 30m. We should divide these tests into different runners in the future.
2. Add `Eventually` to check the request's response. The reason is that Ray Serve initially launches with its [default values](https://github.com/ray-project/test_dag/blob/4d2c9a59d9eabfd4c8a9e04a7aae44fc8f5b416f/conditional_dag.py#L36-L48), which are then overwritten by [serveConfigV2](https://github.com/ray-project/kuberay/blob/master/ray-operator/test/e2e/support.go#L237).
Closes #2617 
I ran `TestRayServiceInPlaceUpdate` three times for https://github.com/ray-project/kuberay/pull/2611. It failed the first two times. Additionally, the test failed three times in https://github.com/ray-project/kuberay/pull/2588. Hence, the …
=> [Bug] TestRayServiceInPlaceUpdate is flaky

.github/workflows/e2e-tests-reusable-workflow.yaml, .github/workflows/e2e-tests.yaml, kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go, kubectl-plugin/test/e2e/testdata/ray-job.interactive-mode-no-runtime-env.yaml, kubectl-plugin/test/e2e/testdata/ray-job.interactive-mode.yaml, kubectl-plugin/test/e2e/testdata/rayjob-submit-working-dir/entrypoint-python-sample.py, kubectl-plugin/test/e2e/testdata/rayjob-submit-working-dir/runtime-env-sample.yaml
This PR adds test for the `ray job submit` command.
Part of https://github.com/ray-project/kuberay/issues/2608
=> [kubectl-plugin] Add e2e test for kubectl ray job submit

ray-operator/pkg/utils/string_conversion.go, ray-operator/test/utils/string_conversion_test.go
Reading through the code, I found we have several places converting between byte array and string type.
For example:
- https://github.com/ray-project/kuberay/blob/ece1d34448ee7763eea47ee5dc5f284d23f3f55a/ray-operator/controllers/ray/common/job.go#L29
- https://github.com/ray-project/kuberay/blob/ece1d34448ee7763eea47ee5dc5f284d23f3f55a/ray-operator/controllers/ray/common/job.go#L62
Add a util function to apply zero-copy strategy to these conversions.
=> Add a util function to convert string and bytes array

ray-operator/test/e2e/rayservice_in_place_update_test.go, ray-operator/test/support/defaults.go
This PR upgrades ray version to `2.40.0`. However, `TestRayServiceInPlaceUpdate` fails for ray `2.40.0`, so currently pin it to `2.9.0` as a workaround.
N/A
=> [Chore][CI] Upgrade ray version to 2.40 except for TestRayServiceInPlaceUpdate

apiserver/pkg/model/converter.go, ray-operator/Dockerfile, ray-operator/controllers/ray/common/job.go
Followup on https://github.com/ray-project/kuberay/pull/2621, to update a few places with string/byte-slice conversion, which could involve heavy-lifted memory copy.
=> Convert byte slice and string without copy

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
We accidentally set the `.State` of RayCluster CR to `rayv1.Ready` even if there was a reconcile error in PR #2258 where we removed `rayv1.Failed`. This made users unable to deal with `false ready` RayClusters with no pod actually created, see #2357.
But since #2258 has been released and the `rayv1.Failed` has gone, I think we can't bring back `rayv1.Failed` either now. This PR fixes the issue by leaving the `.State` field untouched when there is a reconcile error but setting the error message in the `.Reason` field. That means the initial `.State` for case #2357 will be `blank` and the pod creation error will be in the `.Reason` field. The new unit test case in this PR also tests this behavior.
Example result:
```sh
▶ kubectl describe raycluster raycluster-mini
Name: …
```
=> [RayCluster][Fix] leave .Status.State untouched when there is a reconcile error

ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go, ray-operator/test/e2eautoscaler/support.go
Add e2e tests for Autoscaler V2
Closes #2574
=> [Feature] Add e2e tests for Autoscaler V2

docs/reference/api.md, helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/pkg/client/applyconfiguration/ray/v1/rayclusterspec.go, ray-operator/test/e2e/raycluster_test.go, ray-operator/test/e2e/rayjob_cluster_selector_test.go, ray-operator/test/e2e/rayjob_test.go, ray-operator/test/support/ray.go, ray-operator/test/support/utils.go
As stated in https://github.com/ray-project/kuberay/issues/2544.
It allows for integration with [MultiKueue](https://kueue.sigs.k8s.io/docs/tasks/manage/setup_multikueue/) (multi-cluster Kueue), in specific it provides:
* simpler installation, otherwise only installation of RayCluster CRDs is required
* support for mixed setup in one cluster - some RayCluster instances could be run by MultiKueue and some by the default operator
Relates to #2544 
=> [Feature] Add ManagedBy field to RayCluster

ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go, ray-operator/test/support/ray.go
See #2576 
Closes #2576 
This test follows these sequential steps:
* Create a RayCluster with the Autoscaler enabled, containing a worker group with replicas: 1 and minReplicas: 0.
```
{"msg": "reconcilePods", "desired workerReplicas": 1, "maxReplicas": 5, "minReplicas": 0, "replicas": 1}
```
* Update minReplicas from 0 to 2.
* KubeRay should create an additional Pod.
```
{"msg": "reconcilePods", "desired workerReplicas": 2, "maxReplicas": 5, "minReplicas": 2, "replicas": 1}
{"msg": "Number workers to add": 1, "Worker group": "test-group"}
{"msg": "Created worker Pod for RayCluster"}
```
* Submit some Ray detached actors to trigger autoscaling to 5 Pods.
```
"Executing command: [python /home/ray/test_scripts/create_detached_actor.py actor0]"
"Executing command: [python …
```
=> [Feature] Add an e2e test for Autoscaler to scale up by manually updating `minReplicas` 

ray-operator/test/e2e/raycluster_test.go, ray-operator/test/e2e/rayjob_cluster_selector_test.go, ray-operator/test/e2e/rayjob_lightweight_test.go, ray-operator/test/e2e/rayjob_retry_test.go, ray-operator/test/e2e/rayjob_suspend_test.go, ray-operator/test/e2e/rayjob_test.go, ray-operator/test/e2e/rayservice_ha_test.go, ray-operator/test/e2e/rayservice_in_place_update_test.go, ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go, ray-operator/test/sampleyaml/raycluster_test.go, ray-operator/test/sampleyaml/rayjob_test.go, ray-operator/test/sampleyaml/rayservice_test.go, ray-operator/test/support/test.go
Remove `StreamKubeRayOperatorLogs` to reduce messy logs in CI. We can use the `kuberay-operator.log` in artifacts instead to debug.
N/A
=> [Chore][CI] Remove StreamKubeRayOperatorLogs

ray-operator/controllers/ray/common/pod.go
When determining the size of `/dev/shm` volume mount, we check requests and limits. However, limits should take priority since limits is used for the `--memory` flag in `ray start` and it's always larger than requests. 
See https://github.com/ray-project/kuberay/issues/2640
=> prioritize memory limits over requests for /dev/shm size

ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/common/job_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
Use `ray job submit --no-wait + ray job logs --follow` to be tolerant of duplicated job submissions.
In summary, we can use this shell script to submit to workaround duplicated submissions issue:
```sh
ray job submit --address http://test-url --submission-id test-job-id --no-wait -- echo hello world 2>&1 | grep -zv 'Please use a different submission_id';
ray job logs --address http://test-url --follow test-job-id
```
=> [RayJob][Refactor] use `ray job status` and `ray jog lobs` to be tolerant of duplicated job submissions

helm-chart/kuberay-operator/values.yaml
This feature gate is graduating to Beta (and on by default) in v1.3, the helm-chart default values should reflect that.
=> default RayClusterStatusConditions=true in helm-chart

ray-operator/test/e2e/rayservice_ha_test.go
=> [RayService] Use `waitGroup` to ensure a goroutine's completion before the RayService HA test ends

kubectl-plugin/go.mod, kubectl-plugin/go.sum, kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
Allows user to not need a pre-written rayjob yaml to submit a rayjob. 
Part of https://github.com/ray-project/kuberay/issues/2608 
=> [kubectl-plugin] Add rayjob yaml generation to ray job submit command

ray-operator/test/e2e/testdata/ray-service.ft.yaml, ray-operator/test/support/yaml.go
#2590 adds an e2e test for RayService HA with GCS FT. However, it is quite flaky. On my devbox, it has about a 50% chance of failing. 
The reason is that when the GCS process on the head Pod is killed, the readiness/liveness probes on the worker Pod will fail for a while, causing some requests to be dropped. I no longer observe the issue after upgrading from Ray 2.9.0 to Ray 2.40.0.
Closes #2659
I ran the test 10 times with this PR. All passed.
=> [CI] Deflaky TestRayServiceGCSFaultTolerance

ray-operator/config/manager/manager.yaml, ray-operator/test/sampleyaml/raycluster_test.go, ray-operator/test/support/ray.go, ray-operator/test/support/yaml.go
Continue https://github.com/ray-project/kuberay/issues/2645.
This PR adds e2e tests for the `HeadPodReady`, `RayClusterProvisioned`, and `ReplicaFailure` status conditions.
=> [RayCluster][CI] add e2e tests for RayClusterStatusCondition

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
Adds Kubernetes Event to inform users of upgrade strategy. Ex:
Part of https://github.com/ray-project/kuberay/issues/2554
=> [Feature][RayService]Add kubernetes event to inform user of upgrade strategy

.buildkite/test-e2e.yml
As we add more and more end-to-end tests, 30 minutes is no longer sufficient. This PR increases the timeout from 30 minutes to 1 hour.
There is an example timeout failure: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/5725#_
This is just a hotfix. For long-term, we should separate the e2e tests into different Buildkite runners.
=> [CI][Hotfix] Increase the timeout of `Test E2E` from 30m to 1h

kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
Fix a bug where worker group resources are not passed in correctly
https://github.com/ray-project/kuberay/issues/2608
=> [kubectl-plugin] fix worker resources in 'kubectl ray create cluster' command

.buildkite/test-e2e.yml
See #2652 
Closes #2652 
I set the timeout to 1 second locally using the following command to make the test fail, and observed the logs to see if there was any output : 
```
go test -timeout 1s -v ./test/e2e || (kubectl logs --tail -1 -l app.kubernetes.io/name=kuberay && exit 1) >> ~/data/kuberay-operator.log
```
kuberay-operator.log : 
```
{"level":"info","ts":"2024-12-27T06:14:03.982Z","logger":"setup","msg":"Loaded feature gates","featureGates":{"RayClusterStatusConditions":true}}
{"level":"info","ts":"2024-12-27T06:14:03.983Z","logger":"setup","msg":"Flag watchNamespace is not set. Watch custom resources in all namespaces."}
{"level":"info","ts":"2024-12-27T06:14:03.983Z","logger":"setup","msg":"Setup manager"}
{"level":"info","ts":"2024-12-27T06:14:04.185Z","logger":"setup","msg":"sta …
```
=> [Feature] Print KubeRay logs in Buildkite runner when tests fail

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
Closes: ray-project/kuberay#2549
=> [Fix][RayService] Use LRU cache for ServeConfigs

ray-operator/test/e2e/long_running_counter.py, ray-operator/test/e2e/rayjob_recovery_test.go
Add an test for https://github.com/ray-project/kuberay/pull/2579.
1. Create a RayJob
2. Wait for the Pod created by the K8s Job submitter to be ready
3. Let the Pod to run for a while (e.g. 15s)
4. Delete the Pod
5. The K8s Job should create another Pod
6. The RayJob should eventually succeed.
7. The RayJobDeployment eventually complete. 
(Add this according to the issue https://github.com/ray-project/kuberay/issues/2154)
Close #2655
=> [Feature] Add an e2e test for K8s Job submitter failures

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/constant.go
Currently, we are reusing the `FailedToDeleteWorkerPod` event type for scenarios where both `Delete` (requiring the `delete` verb in `Role` or `ClusterRole`) and `DeleteAllOf` (requiring the `deletecollection` verb) are involved. However, this reuse may lead to confusion because these operations rely on different verbs and permissions.
To improve clarity and maintainability, we should consider introducing a new event type specific to the `DeleteAllOf` operation.
Closes #2672 
=> [Feature]: Add a new event type FailedToDeleteWorkerPodCollection

ray-operator/controllers/ray/raycluster_controller.go
According to [Effetive Go inteface check](https://go.dev/doc/effective_go#blank_implements)
`
The appearance of the blank identifier in this construct indicates that the declaration exists only for the type checking, not to create a variable. Don't do this for every type that satisfies an interface, though. By convention, such declarations are only used when there are no static conversions already present in the code, which is a rare event.
`
The `complete()` function call has ensured that.
https://github.com/ray-project/kuberay/blob/f2d7c1f2b019034d0d194be7f9edc5d7a61fee94/ray-operator/controllers/ray/raycluster_controller.go#L1253
=> [chore] remove redundant interface check

ray-operator/test/support/environment.go
I found developers may need to have arm chip support for better development experience.
Change the GetRayImage handler will support most unit tests and e2e tests to use arm image.
Test Log Format
Success logs for all related references.
- Unit Test
```
test -s /Users/simo/Codes/kuberay/ray-operator/bin/controller-gen || GOBIN=/Users/simo/Codes/kuberay/ray-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.15.0
/Users/simo/Codes/kuberay/ray-operator/bin/controller-gen "crd:maxDescLen=0,generateEmbeddedObjectMeta=true,allowDangerousTypes=true" rbac:roleName=kuberay-operator webhook paths="./..." output:crd:artifacts:config=config/crd/bases
go fmt ./...
go vet ./...
test -s /Users/simo/Codes/kuberay/ray-operator/bin/setup-envtest || …
```
=> [Feature] Support ARM image for test

ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/controllers/ray/rayservice_controller.go
It's not a good pattern to update the CR status from multiple places during a single reconciliation. This PR removes `updateState`, which is called in multiple locations and updates the status only for observability purposes. Additionally, these states are not fully mutually exclusive, making it impossible for users to determine the current state based on the status.
=> [RayService][refactor] Remove `updateState`

ray-operator/controllers/ray/rayservice_controller.go
Refer to issue #2707 
"Closes #2707"
```
k get pods
NAME                                                          READY   STATUS    RESTARTS   AGE
kuberay-operator-696bc84cc4-vtrqs                             1/1     Running   0          3m14s
rayservice-sample-raycluster-bcb7b-head-5ppzt                 1/1     Running   0          2m51s
rayservice-sample-raycluster-bcb7b-small-group-worker-mzvck   1/1     Running   0          2m51s
```
Only RayCluster controllers logs are left.
=> [Refactor] Remove ingress in service controller

experimental/pkg/httpproxy/support.go
Refactored the code to use HTTP constants instead of hard-coded numeric values, improving readability and maintainability.
=> [Refactor] Replace Hard-Coded HTTP Values with Constants

kubectl-plugin/cmd/kubectl-ray.go, kubectl-plugin/go.mod, kubectl-plugin/go.sum, kubectl-plugin/pkg/cmd/get/get_cluster.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/cmd/job/job_submit_test.go, kubectl-plugin/pkg/util/client/client.go, kubectl-plugin/pkg/util/client/client_test.go, kubectl-plugin/pkg/util/types.go
This PR replaces all `Unstructured` and `DynamicClient` objects in kubectl-plugin with native KubeRay types.
Closes: ray-project/kuberay#2386
=> [Refactor][Kubectl-plugin] Replace dynamic client with Ray client

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/constant.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/test/e2e/raycluster_test.go
This PR addresses the following selected part:
Resolves https://github.com/ray-project/kuberay/issues/2720
=> [RayCluster][Feature] setup GCS FT annotations and the RAY_REDIS_ADDRESS env by the GcsFaultToleranceOptions

ray-operator/controllers/ray/common/service.go
The slice only appends at most one time because the following loop breaks once condition matched. It would be better to specify the capacity in advance.
https://github.com/ray-project/kuberay/blob/7bb5877a032c68fe02bf42d39b8883d8d28352c3/ray-operator/controllers/ray/common/service.go#L214-L221
https://github.com/ray-project/kuberay/blob/7bb5877a032c68fe02bf42d39b8883d8d28352c3/ray-operator/controllers/ray/common/service.go#L248-L255
=> [Chore] specify the capacity on calling make

ray-operator/config/samples/ray-cluster.autoscaler-v2.yaml, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.embed-grafana.yaml, ray-operator/config/samples/ray-cluster.tls.yaml, ray-operator/config/samples/ray-job.custom-head-svc.yaml, ray-operator/config/samples/ray-job.resources.yaml, ray-operator/config/samples/ray-job.sample.yaml, ray-operator/config/samples/ray-job.shutdown.yaml, ray-operator/config/samples/ray-service.autoscaler.yaml, ray-operator/config/samples/ray-service.custom-serve-service.yaml, ray-operator/config/samples/ray-service.different-port.yaml, ray-operator/config/samples/ray-service.gke-model-configmap.yaml, ray-operator/config/samples/ray-service.high-availability-locust.yaml, ray-operator/config/samples/ray-service.high-availability.yaml, ray-operator/config/samples/ray-service.mobilenet.yaml, ray-operator/config/samples/ray-service.sample.yaml, ray-operator/config/samples/ray-service.text-ml.yaml
This PR removes unnecessary `preStop` hooks from sample yamls in the KubeRay repo. The `preStop` hooks that call `ray stop` are not needed and can cause issues when deleting the k8s Pod.
For example, if a Ray Pod sidecar container fails and exits before the main container, the pre-stop hook is unable to exec into the Ray container to issue the stop command, causing the Pods to hang rather than gracefully terminate. Tasks/Actors are already gracefully terminated when a Ray Pod is marked for deletion, and the additional `ray stop` command is not needed.
Closes #2606
=> Remove preStop hooks from Ray CR Samples

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
`RayClusterReconciler` doesn't need to be the member function of RayClusterReconciler
Relate to https://github.com/ray-project/kuberay/pull/2726#discussion_r1912559951
Closes #2694 
=> [Refactor] move validateRayClusterStatus out of RayClusterReconciler

ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
While working on https://github.com/ray-project/kuberay/issues/2666, I found that the `DesiredWorkerReplicas` in the RayCluster status remains incorrect when some worker groups have been suspended. Suspended worker groups should not be counted in the `DesiredWorkerReplicas`, or it will confuse users. The `MinWorkerReplicas` and `MaxWorkerReplicas` statuses are in the same situation.
=> [RayCluster][Fix] DesiredReplicas, MinReplicas and MaxReplicas should respect workerGroupSpec.Suspend

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
1. **Ensure PodSpec has at least one container**: OpenAPI only validates whether `containers` exists in the PodSpec or not. However, it doesn't validate whether the PodSpec has at least one container or not. In K8s, it is validated in the server side: https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/apis/core/validation/validation.go?L3635. In KubeRay, we assume that the Ray container is the first container in the Pod. To avoid segfault in KubeRay, this PR checks whether all PodSpec have at least one container or not.
2. `GcsFaultToleranceOptions` and the annotation should not be set at the same time.
3. `RAY_REDIS_ADDRESS` should not be set if KubeRay doesn't aware of GCS FT is enabled.
4. Update error messages to encourage users to use new API …
=> [RayCluster] Validate RayClusterSpec for empty containers and GCS FT

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
Currently, `GetHeadPort` always returns GCS server port for all Ray versions that KubeRay supports. Rename it and do some minor refactors.
=> [chore] Refactor GetHeadPort

.github/workflows/kubectl-plugin-e2e-tests.yaml, kubectl-plugin/test/e2e/kubectl_ray_cluster_get_test.go, kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go, kubectl-plugin/test/e2e/kubectl_ray_log_test.go, kubectl-plugin/test/e2e/kubectl_ray_session_test.go, kubectl-plugin/test/e2e/support.go
I found that the kubectl plugin e2e tests failed because they interfered with each other.
This PR attempts to fix the kubectl plugin e2e errors by creating separate test namespaces for each test.
Skipped one test because it still fails.
Follow-up:
- https://github.com/ray-project/kuberay/issues/2752
- https://github.com/ray-project/kuberay/issues/2753
Closes: ray-project/kuberay#2729
=> [Fix][kubectl-plugin] Create separate namespaces for each kubectl plugin e2e test

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
Add the option to specify worker GPU count. For now we default to nvidia.com/gpu but we can support other GPU types in the future.
#2608 
=> [kubectl-plugin] add --worker-gpu flag for cluster creation

kubectl-plugin/pkg/cmd/create/create.go, kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/client/client.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
Add a command to add new worker groups to existing RayClusters
https://github.com/ray-project/kuberay/issues/2608
=> [kubectl-plugin] add create workergroup command

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
=> [Refactor] Move functions that don’t rely on the controller to non-controller member functions

ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
=> [RayJob] Follow up of RayJob deletion policy PR

docs/reference/api.md, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller_test.go
This is a follow-up RP for https://github.com/ray-project/kuberay/pull/2748.
We limit that the `suspend` field on a worker group is only available under the RayJobDeletionPolicy feature gate:
1. Add a comment saying that the field is not user-facing.
2. Add a validation on RayCluster to reject the suspend field if the feature gate is not enabled.
=> skip suspending worker groups if the RayJobDeletionPolicy feature flag is not enabled

ray-operator/controllers/ray/common/association.go, ray-operator/controllers/ray/common/association_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
=> Move matching labels to association.go

ray-operator/controllers/ray/common/pod.go, ray-operator/test/e2e/raycluster_gcsft_test.go, ray-operator/test/e2e/support.go
Old GCS FT API uses annotations to configure GCS FT behavior. This PR adds e2e tests for it.
=> [GCS FT] Add e2e tests for configuring GCS FT with annotations

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
Follow-ups for https://github.com/ray-project/kuberay/issues/2696#issuecomment-2599448835.
Complete `TODO`s for GCS FT validations.
=> [GCS FT] More validations for configuring GCS FT with envs and annotations

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
This is a follow-up RP for https://github.com/ray-project/kuberay/pull/2748, adding the following validation on RayJob:
1. DeletionPolicy can only be used when the RayJobDeletionPolicy feature gate is enabled.
2. DeletionPolicy=DeleteCluster can't be used with ClusterSelector.
3. DeletionPolicy=DeleteWorkers can't be used with ClusterSelector.
4.  DeletionPolicy=DeleteWorkers currently can't be used with Autoscaler.
=> [RayJob] RayJob deletion policy validation

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/test/e2e/raycluster_gcsft_test.go, ray-operator/test/e2e/support.go
Follow-ups for https://github.com/ray-project/kuberay/issues/2696#issuecomment-2599448835 and resolves https://github.com/ray-project/kuberay/issues/2764.
* Add e2e tests to check if Redis is empty at the end of each GCS FT test.
* Fix Redis cleanup job to accept empty passwords.
=> [GCS FT] Redis e2e cleanup check

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
=> [RayService] Avoid sending health check requests to the head Pod when `excludeHeadPodFromServeSvc` is true

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
Separate PR #2774 into small PRs, We started by moving `IsGCSFaultToleranceEnabled` to `ray-operator/controllers/ray/utils/util.go`
Refer to this https://github.com/ray-project/kuberay/pull/2774#issuecomment-2601501738
Closes #2740 
=> [Refactor]: Move `IsGCSFaultToleranceEnabled` to `utils.go`

ray-operator/controllers/ray/rayservice_controller.go
Originally, if both active and pending clusters exist, only the head Pod of the pending cluster will have its status checked. That is, if the active cluster's head Pod's serve status fails during the upgrade process, it will not be detected in time.
This PR checks the readiness of head Pods for both pending / active clusters if exist.
=> [RayService] Always check the readiness of head Pods for both pending / active clusters if cluster exists

ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
New cluster will only be created when there is no active cluster or RayCluster spec is updated and the upgrade is triggered. New cluster will not be created when current cluster is unhealthy.
It's weird that when a new RayService is created and marked "Restarting". Rename it to `PreparingNewCluster` is a workaround. The long term solution is to delete `Restarting` and use the conditions proposed by @MortalHappiness.
=> [RayService] Rename Restarting to PreparingNewCluster

kubectl-plugin/pkg/cmd/create/create_workergroup.go
When running `kubectl ray create workergroup`, there's a warning that occurs due to creationTimestamp being included in the type but not included in the CRD generation.
```
$ kubectl ray create workergroup gpu-group --ray-cluster sample-cluster --worker-gpu=1
W0121 19:24:22.913198 1950811 warnings.go:70] unknown field "spec.headGroupSpec.template.metadata.creationTimestamp"
W0121 19:24:22.913288 1950811 warnings.go:70] unknown field "spec.workerGroupSpecs[0].template.metadata.creationTimestamp"
W0121 19:24:22.913293 1950811 warnings.go:70] unknown field "spec.workerGroupSpecs[1].template.metadata.creationTimestamp"
W0121 19:24:22.913297 1950811 warnings.go:70] unknown field "spec.workerGroupSpecs[2].template.metadata.creationTimestamp"
```
As a temporary workaround,  we can hide the …
=> [kubectl-plugin] silence warnings when creating worker groups

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go
Addressing the comment https://github.com/ray-project/kuberay/pull/2760#discussion_r1921867783
=> [RayCluster][Feature] reject redis username to head pod out side of GcsFaultToleranceOptions

docs/reference/api.md, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/rayjob_types.go
Automatically generated comments `INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
// Important: Run "make" to regenerate code after modifying this file` need to be cleaned up (these comments and the fields below them are unrelated), otherwise they will appear in `api.md`.
The comment of `Entrypoint` comes from [submit job's entrypoint](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/api.html#/paths/~1api~1jobs/post), I noticed that `Entrypoint` is directly submitted as RayJobRequest.Entrypoint in the code. 
=> [Chore] update comment for headGroupSpec and entrypoint

ray-operator/controllers/ray/common/ingress.go
To make code more concise, remove redundant var declaration, which is assigned with a value at:
https://github.com/ray-project/kuberay/blob/7e726277e8c7313bb79189b6b9004b89dba6cb13/ray-operator/controllers/ray/common/ingress.go#L55
And there is no other usage between the line of assignment and the line of declaration.
=> [Chore] remove redundant var declaration

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
Separate PR https://github.com/ray-project/kuberay/pull/2774 into small PRs
- Move the `ValidateRayJobStatus` function to `validation.go
- Move unit test `TestValidateRayJobStatus` to  `validation_test.go`
Refer to this https://github.com/ray-project/kuberay/pull/2774#issuecomment-2601501738
Closes #2740 
=> [Refactor] Move `ValidateRayJobStatus` to `validation.go` and create its unit test

ray-operator/test/support/defaults.go
This PR bumps the default Ray image used for e2e autoscaler tests to 2.41.0. The newer Ray images contains several fixes for autoscaler issues that currently cause these tests to fail.
Closes #2759
=> [autoscaler] Bump Ray e2e test image

ray-operator/controllers/ray/common/ingress.go
Put the value from the map as a local variable because it is used in the scope.
The else block is in the same scope. Here is the example in go playground: https://go.dev/play/p/UJETQkRla48
=> [Chore] make ingressClassName as a local variable

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
Separate PR https://github.com/ray-project/kuberay/pull/2774 into small PRs
- Move the function `ValidateRayJobSpec` to `validation.go
- Move unit test `TestValidateRayJobSpec` to  `validation_test.go`
Refer to this https://github.com/ray-project/kuberay/pull/2774#issuecomment-2601501738
Closes #2740 
=> [Refactor] Move function `ValidateRayJobSpec` to `validation.go` and its unit test

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/util.go
Try to calculate CR status only based on K8s resources which is the source of the truth. This PR passes K8s services into `calculateStatus` to determine whether update active / pending cluster status or not.
This is a follow up for #2805.
=> [RayService] Calculate status based on K8s resources

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
Separate PR https://github.com/ray-project/kuberay/pull/2774 into small PRs
- Move the function `validateRayServiceSpec` to `validation.go`
- Move unit test `TestvalidateRayServiceSpec` to  `validation_test.go`
Refer to this https://github.com/ray-project/kuberay/pull/2774#issuecomment-2601501738
Closes #2740 
=> [Refactor] Move `validateRayServiceSpec` to `validation.go` and its unit test to `validation_test.go`

ray-operator/test/e2erayservice/rayservice_in_place_update_test.go, ray-operator/test/e2erayservice/rayservice_upgrade_test.go
Resolves https://github.com/ray-project/kuberay/issues/2787
=> [RayService] e2e for check the readiness of head Pods for both pending / active clusters

.pre-commit-config.yaml
Some people will get `v1.60.3` instead of  `1.60.3` in golangci-lint --version and will cause pre-commit failed.
So modified the validation part to allow it.
=> [Chore] Modify pre-commit yaml to allow golangci-lint version with prefix "v"

apiserver/Dockerfile, experimental/Dockerfile, proto/Dockerfile, ray-operator/Dockerfile
When running `make docker-build` with a newer version of Docker, the following warning appears:
```
...
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
```
According to the Docker documentation (https://docs.docker.com/reference/build-checks/from-as-casing/), the `FROM` and `AS` keywords must use consistent casing, either both uppercase or both lowercase.
=> Fix FromAsCasing warning.

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/test/e2erayservice/rayservice_upgrade_test.go
1. `reconcileServe` returns serve application status.
2. Pass serve applications to `calculateStatus`
3. Remove `Status().Update(...)` inside `reconcileServe`.
=> [RayService] Passing serve applications to `calculateStatus` and avoid calling `Status().Update(...)` inside `reconcileServe`

ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
=> [RayService] Remove WaitForServeDeploymentReady

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/test/e2erayservice/rayservice_redeploy_test.go, ray-operator/test/e2erayservice/support.go
1. Deploy a RayService. Wait until all Ray Serve applications are running. The RayCluster should become the active cluster.
2. Send a request to the RayCluster
3. Delete the head Pod.
4. After the head Pod restarts, KubeRay should still submit a request to create the serve applications again.
5. Send a request to the RayCluster
Resolves https://github.com/ray-project/kuberay/issues/2829
=> [RayService] e2e for redeploying RayServe application after recreating a new Head Pod

ray-operator/test/e2erayservice/rayservice_redeploy_test.go, ray-operator/test/support/ray.go
=> [RayService] Use `Ready` condition in e2e tests

ray-operator/config/samples/ray-cluster.external-redis-uri.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml
These yamls are used in the gcsft document: https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/kuberay-gcs-ft.html#kuberay-gcs-ft
We need to update these yamls first so that we can update the gcsft document later.
#2696
#2697
=> [RayCluster] Update sample yamls to use the new gcsFaultToleranceOptions option

ray-operator/test/e2e/raycluster_gcsft_test.go
A follow-up for https://github.com/ray-project/kuberay/issues/2696.
We are using Ray 2.41.0 now, which supports Redis usernames. Therefore, we need to add an e2e test for the case.
=> [RayCluster] e2e test for GCS FT with Redis Username

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
=> [RayService] Remove the dependencies between `constructRayClusterForRayService` and the reconciler to make it more unit testable

ray-operator/Makefile, ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
This PR adds a test case for custom `idleTimeoutSeconds` per worker group supported by the V2 Autoscaler starting in ray 2.40.0. The test case verifies that `idleTimeoutSeconds` for a worker group override the default `idleTimeoutSeconds` set in the `autoscalerOptions` by scaling up replicas of each type and then checking that they are terminated within the expected period.
This PR was tested by running `go test -timeout 30m -v ./test/e2eautoscaler` with the nightly version of the KubeRay operator installed, since the [change adding this field to the WorkerGroupSpec api](https://github.com/ray-project/kuberay/pull/2558) is not yet part of a release.
#2561
=> Add KubeRay e2e Test for custom idleTimeoutSeconds with v2 Autoscaler

ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
This PR reconfigures the `TestRayClusterAutoscalerV2IdleTimeout` test based on the comments in https://github.com/ray-project/kuberay/pull/2725#pullrequestreview-2580154224. Additionally, this PR fixes the test flakiness by adding a `timeoutBuffer` of 20 seconds when checking for replica scale down.
Viewing the test logs confirms that the autoscaler is correctly using the custom `idleTimeoutSeconds` and marking the nodes as idle, but for whatever reason `RayClusterDesiredWorkerReplicas` takes an additional ~10-15 seconds to update and scale down the replica.
Autoscaler container logs:
```
2025-01-29 14:21:03,820 INFO event_logger.py:76 -- Removing 1 nodes of type short-idle-timeout-group (idle).
2025-01-29 14:21:03,821 - INFO - Update instance RAY_RUNNING->RAY_STOP_REQUESTED …
```
=> [Autoscaler][Test] Fix flaky idleTimeoutSeconds test

config/grafana/data_grafana_dashboard.json, config/grafana/default_grafana_dashboard.json, config/grafana/serve_deployment_grafana_dashboard.json, config/grafana/serve_grafana_dashboard.json
The current Grafana Dashboard aggregates metrics from all Ray clusters and summarizes them. Add a `Cluster` variable to Grafana dashboard to enable viewing metrics for individual RayClusters.
Ref: https://github.com/ray-project/kuberay/issues/2502#issuecomment-2465546820
TODO
- Modify the [Using Prometheus and Grafana](https://docs.ray.io/en/latest/cluster/kubernetes/k8s-ecosystem/prometheus-grafana.html) documentation to guide users on how to filters different RayClusters in Grafana.
- Ray core dashboard:
- Ray data dashboard:
- Ray core dashboard:
- Ray data dashboard:
Closes #2502
=> [Grafana] Add a `Cluster` variable to the Grafana Dashboard to enable filtering of different RayClusters

ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/test/support/ray.go
For KubeRay v1.3.0, we define `ServiceStatus` to be equivalent to the ready condition. Mark `ServiceStatus` as deprecated to encourage users to use `Conditions`.
=> [RayService] Mark `ServiceStatus` as deprecated

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
Merge initConditions into calculateConditions so that we have only one place to update the CR status.
=> [RayService] Merge `initConditions` into `calculateConditions`

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/test/e2e/raycluster_gcsft_test.go
When the RayCluster name is too long, the Redis cleanup job name and associated labels exceed Kubernetes' 63-character limit. This causes the cleanup job to fail during creation with the following error:
```
Warning  FailedToCreateRedisCleanupJob  raycluster/text-translation-model-rayservice-raycluster-g9gps        Failed to create Redis cleanup Job text-translation-model/text-translation-model-rayservice-raycluster-g9gps-redis-cleanup, Job.batch "text-translation-model-rayservice-raycluster-g9gps-redis-cleanup" is invalid: spec.template.labels: Invalid value: "text-translation-model-rayservice-raycluster-g9gps-redis-cleanup": must be no more than 63 characters
```
Closes #2845
Update: Tested ✅ , great development doc! 🥇
=> [RayService] Trim Redis Cleanup job less than 63 chars

ray-operator/controllers/ray/rayservice_controller.go
I am trying to unify status updates in calculateStatus.
=> [RayService] Setting observedGeneration inside calculateStatus 

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
To improve RayService observability, we use the following k8s events to log RayService reconciliation actions:
* `CreatedRayCluster`/`FailedToCreateRayCluster`
* `UpdatedRayCluster`/`FailedToUpdateRayCluster`
* `DeletedRayCluster`/`FailedToDeleteRayCluster`
* `CreatedService`/`FailedToCreateService`
The above events are existing events in the code base. Below are newly added:
* `UpdatedService`/`FailedToUpdateService` (new)
* `UpdatedHeadPodServeLabel`/`FailedToUpdateHeadPodServeLabel` (new)
* `UpdatedServeApplications`/`FailedToUpdateServeApplications` (new)
While the last pair of events, `UpdatedServeApplications`/`FailedToUpdateServeApplications`, are actually not related to k8s, I think users may still need them to check if their apps have been updated.
=> [RayService] Create k8s events after creating/updating k8s resources

ray-operator/controllers/ray/rayservice_controller_test.go
=> [RayService] Add zero-downtime triggered test after rayVersion is updated

kubectl-plugin/go.mod, kubectl-plugin/go.sum, kubectl-plugin/pkg/util/client/client.go, kubectl-plugin/pkg/util/client/client_test.go
Right now `kubectl ray version` returns only the image digest if the KubeRay operator uses an image reference that contains both tag and digest. This change returns both and also handles the case where only the digest is present.
We depend on the https://github.com/novln/docker-parser library to simplify image reference parsing logic except in the case where both tag and digest are used which the library doesn't seem to handle. See [this issue][1].
[1]: https://github.com/novln/docker-parser/issues/3
=> [Fix][kubectl-plugin]: make `version` handle digests

ray-operator/controllers/ray/rayservice_controller_test.go
This PR addresses Tests 1, 3, 4, and 5 in https://github.com/ray-project/kuberay/issues/2878.
To reduce the boilerplate of setting the base(happy) path scenario, these tests are structured according to the normal ginkgo habit of using `BeforeEach` for repeated setup.
The `BeforeEach+OncePerOrdered` hook sets up the base(happy) path scenario. It will be automatically executed for each following `Ordered` block.
=> [RayService] More envtests that follow the most common scenario in the RayService code path

ray-operator/DEVELOPMENT.md
Project uses Golang 1.22 not 1.20.
=> [docs][ray-operator] fix typo in Golang version

kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go, kubectl-plugin/pkg/cmd/job/job_submit_test.go, kubectl-plugin/pkg/cmd/log/log_test.go
Replace `assert.Equal(t, tc.expectError, err.Error())` with `assert.Error(t, err, tc.expectError)` because if `err` is `nil`, then `err.Error()` will cause SIGSEGV.
N/A
=> [Fix][kubectl-plugin] Fix no context nil error SIGSEGV in tests

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
when creating a RayCluster with `kubectl ray create cluster NAME --head-gpu N`. Similar to the `--worker-gpu` switch.
=> [kubectl-plugin][feat] support specifying number of head GPUs

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/delete/delete.go, kubectl-plugin/pkg/cmd/delete/delete_test.go, kubectl-plugin/pkg/cmd/get/get_cluster.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/cmd/job/job_submit_test.go, kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/log/log_test.go, kubectl-plugin/pkg/cmd/session/session.go, kubectl-plugin/pkg/util/kubeconfig.go
to tell user they can use `--context` to set the K8s context.
=> [kubectl-plugin] update context error messages

kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go, kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/log/log_test.go
file that's not at the default path. Right now tests fail if there's a K8s
current context set with a command like `kubectl config use-context
my-context`.
This change allows tests to pass regardless of current context.
=> [Fix][kubectl-plugin] make tests use a temporary kube config

.golangci.yml, ray-operator/controllers/ray/common/pod_test.go
=> [CI] Enable `testifylint` `formatter` rule

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/delete/delete.go, kubectl-plugin/pkg/cmd/delete/delete_test.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/log/log_test.go, kubectl-plugin/pkg/cmd/session/session_test.go
in comments and console messages.
* capitalize "Ray" when used as a proper noun
* capitalize Ray K8s CRDs like "RayJob" and "RayCluster"
* capitalize acronyms like "YAML"
* fix some minor typos
No functional changes.
=> [chore][kubectl-plugin] use consistent capitalization

kubectl-plugin/pkg/cmd/version/version.go, kubectl-plugin/pkg/cmd/version/version_test.go
in the `kubectl ray version` sub-command. Right now `kubectl ray version` doesn't allow `--context my-context`. It should like the other `kubectl ray` sub-commands.
Add tests
[Slack thread](https://ray.slack.com/archives/C02GFQ82JPM/p1738608216456149)
=> [kubectl-plugin] support general `kubectl` switches like `--context`

docs/development/development.md, ray-operator/DEVELOPMENT.md
from ray-operator dev docs since pre-commit hooks are used in this repo's other components.
=> [docs] move pre-commit instructions to main dev docs

.gitignore, .pre-commit-config.yaml, scripts/generate-crd-schema.sh, scripts/validate-helm.sh
`openapi2jsonschema.py` requires the `PyYAML` dependency, while `scripts/validate-helm.sh` requires the `kubeconform` dependency. Since they are from two different languages, this PR separates schema generation and Helm validation into two separate hooks to properly handle dependencies.
N/A
=> [CI] Generate CRD json schema separately in pre-commit

kubectl-plugin/pkg/cmd/delete/delete_test.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go
Fix two places.
* use `assert.EqualError()` instead of `assert.Error()` to check the error string is what we expect
* use testify assertion instead of string checking for better error output
=> [chore][kubectl-plugin] use better test assertions

.pre-commit-config.yaml, CHANGELOG.md, ci/markdownlint.yaml, clients/python-client/README.md
Ignore most rules we violate for now.
Fix these two violations.
```
pre-commit run markdownlint --all-files --show-diff-on-failure
...
clients/python-client/README.md:106 MD001/heading-increment Heading levels should only increment by one level at a time [Expected: h3; Actual: h4]
CHANGELOG.md:420:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 2]
```
=> [chore] add Markdown linting pre-commit hook

ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/common/job_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
1. Use `bash` instead of `sh`.
2. Don't split entrypoint, otherwise quotes will be omitted.
Before:
`if ray job status --address http://rayjob-sample-6qxdg-raycluster-b4crs-head-svc.default.svc.cluster.local:8265 rayjob-sample-6qxdg-gnc2m >/dev/null 2>&1 ; then ray job logs --address http://rayjob-sample-6qxdg-raycluster-b4crs-head-svc.default.svc.cluster.local:8265 --follow rayjob-sample-6qxdg-gnc2m ; else ray job submit --address http://rayjob-sample-6qxdg-raycluster-b4crs-head-svc.default.svc.cluster.local:8265 --submission-id rayjob-sample-6qxdg-gnc2m -- python -c import time; import ray; ray.init(); [print(f"iter: {i}, ray.cluster_resources(): {ray.cluster_resources()}") or time.sleep(1) for i in range(600)] ; fi`
After:
`if ray job status --address …
=> [Fix][RayJob] Invalid quote for RayJob submitter

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/delete/delete.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/ray.go, kubectl-plugin/pkg/cmd/session/session.go
by making them more concise and accurate.
Other changes include
* capitalize "Ray" when used as a proper noun
* capitalize acronyms like "YAML"
* prefer non-K8s-specific words like "Ray cluster" instead of "RayCluster" in user-facing messages to abstract away K8s when we can
* remove info about default flag values since Cobra automatically adds them in the help messages
* follow https://clig.dev/ style guide where it makes sense
No functional changes
=> [docs][kubectl-plugin] improve help messages

kubectl-plugin/pkg/util/generation/generation.go
This change fixes a panic issue encountered while testing `ray job submit`. The issue occurs when the GPU resources are not set. Previously, an empty string would cause the `MustParse` function to fail, triggering a panic. 
This update adds a check to ensure that the GPU fields are only parsed when they contain valid values, preventing the panic.
```
$ kubectl ray job submit --name rayjob-sample --working-dir ./workdir/ --runtime-env ./workdir/runtimeEnv.yaml -- python sample_code.py
panic: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
goroutine 1 [running]:
k8s.io/apimachinery/pkg/api/resource.MustParse({0x0, 0x0})
/home/blocka/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/api/resource/quantity.go:141 +0x173 …
```
=> [kubectl-plugin] Fix panic when GPU resource is not set

kubectl-plugin/pkg/cmd/create/create_workergroup.go
and add more info to usage message for `kubectl ray create workergroup`.
```console
kubectl ray create worker-group example-group --cluster sample-cluster`
```
should be
```console
kubectl ray create workergroup example-group --ray-cluster sample-cluster
```
Also add a short flag `-c` for `--ray-cluster` for convenience.
=> [docs][kubectl-plugin] fix incorrect example commands

kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/create/create_workergroup_test.go
when creating a new worker group with `kubectl ray create workergroup`. Write a unit test.
I noticed we are setting resource limits equal to resource requests everywhere else but in this command. I have a K8s [LimitRange] that prevented the creation of these worker Pods that had CPU limit defaulting to less than their CPU requests. Describing the RayCluster showed this warning event.
`Failed to create worker Pod hyperkube/, Pod
"dxia-test-other-group-worker-pm2sh" is invalid:
spec.containers[0].resources.requests: Invalid value: "2": must be less than or equal to cpu limit of 250m`
[LimitRange]: https://kubernetes.io/docs/concepts/policy/limit-range/
=> [fix][kubectl-plugin] set worker group CPU limit

ray-operator/controllers/ray/rayservice_controller_test.go
Endpoints are not cleaned up after a test, so if the name of the endpoint is the same in two different tests, the second test will fail when it tries to create the endpoint because it already exists.
* [CI failure example](https://github.com/ray-project/kuberay/actions/runs/13190875193/job/36823475912)
=> [RayService] Deflaky RayService envtest

ray-operator/config/samples/ray-cluster.gke-bucket.yaml, ray-operator/config/samples/ray-job.sample.yaml, ray-operator/config/samples/ray-service.mobilenet.yaml, ray-operator/config/samples/ray-service.text-summarizer.yaml
1. [text summarizer](https://docs.ray.io/en/latest/cluster/kubernetes/examples/text-summarizer-rayservice.html):
2. [mobilenet](https://docs.ray.io/en/latest/cluster/kubernetes/examples/mobilenet-rayservice.html): The input is the image generated by #2960
=> [release][9/N] Update text summarizer RayService to Ray 2.41

ray-operator/config/samples/ray-cluster.volcano-scheduler-queue.yaml, ray-operator/config/samples/ray-cluster.volcano-scheduler.yaml
Update images to Ray 2.41 and then follow https://docs.ray.io/en/latest/cluster/kubernetes/k8s-ecosystem/volcano.html to check whether the doc still works or not.
```
$ kubectl apply -f ray-operator/config/samples/ray-cluster.volcano-scheduler.yaml 
raycluster.ray.io/test-cluster-0 created
$ kubectl get pod -l ray.io/cluster=test-cluster-0
NAME                        READY   STATUS    RESTARTS   AGE
test-cluster-0-head-9wvn7   0/1     Running   0          9s
```
1. Create a queue with a capacity of 4 CPUs and 6Gi of RAM:
```
$ kubectl create -f - <<EOF
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
name: kuberay-test-queue
spec:
weight: 1
capability:
cpu: 4
memory: 6Gi
EOF
```
2. create a RayCluster with a head node (1 CPU + 2Gi of RAM) and two workers (1 CPU + 1Gi of RAM …
=> [release] Update Volcano YAML files to Ray 2.41

ray-operator/config/samples/ray-cluster.deprecate-gcs-ft.yaml, ray-operator/config/samples/ray-cluster.persistent-redis.yaml, ray-operator/config/samples/ray-service.high-availability.yaml, ray-operator/test/e2erayservice/testdata/ray-service.ft.yaml, ray-operator/test/sampleyaml/raycluster_test.go
Let the yaml files in e2e test using `GcsFaultToleranceOptions` but still keep the backward compatibility on `config/samples/ray-cluster.deprecate-gcs-ft.yaml`.
Closes https://github.com/ray-project/kuberay/issues/2957
=> [Test] Use GcsFaultToleranceOptions in test and backward compatibility

ray-operator/config/samples/pytorch-mnist/ray-job.pytorch-mnist.yaml, ray-operator/config/samples/pytorch-resnet-image-classifier/ray-job.pytorch-image-classifier.yaml, ray-operator/config/samples/pytorch-text-classifier/ray-job.pytorch-distributed-training.yaml, ray-operator/config/samples/ray-data-image-resize/ray-data-image-resize-gcsfusecsi-job.yaml, ray-operator/config/samples/ray-data-image-resize/ray-job.image-resize.yaml
=> Update samples to use Ray 2.41.0 images

ray-operator/config/samples/ray-cluster.tpu-v4-multihost.yaml, ray-operator/config/samples/ray-cluster.tpu-v4-singlehost.yaml, ray-operator/config/samples/ray-cluster.tpu-v6e-16-multihost.yaml, ray-operator/config/samples/ray-cluster.tpu-v6e-256-multihost.yaml, ray-operator/config/samples/ray-cluster.tpu-v6e-singlehost.yaml, ray-operator/config/samples/ray-job.tpu-v6e-16-multihost.yaml, ray-operator/config/samples/ray-job.tpu-v6e-256-multihost.yaml, ray-operator/config/samples/ray-job.tpu-v6e-singlehost.yaml, ray-operator/config/samples/ray-service.tpu-single-host.yaml
This PR updates TPU related manifests in `ray-operator/config/samples` to use the Ray 2.41.0 image, since they're currently using much older images. I also cleaned up some of the other fields in these manifests that are not needed/recommended (unnecessary labels, ray-logs volumes, etc.). This PR was tested by applying the manifests, verifying they were created successfully, and (for the Ray Jobs/Services) checking that they run successfully once scheduled.
Closes #2944
=> Update TPU Ray CR manifests to use Ray 2.41.0

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/constant.go, kubectl-plugin/pkg/util/generation/generation_test.go
Currently, many golang files uses hard-coded strings to represent images and Ray versions. To avoid updating images / Ray versions in multiple places, use constant variables to replace hard-coded strings.
Closes: #2939 
=> [Refactor] Use constants for image tag, image repo, and versions in golang to avoid hard-coded strings

.buildkite/format.awk, .buildkite/test-e2e.yml, .buildkite/test-sample-yamls.yml, ray-operator/test/e2e/raycluster_gcsft_test.go
This PR includes changes to ensure the correct display of go test verbose logs in the Buildkite Runner. Previously, the `---` in the go test logs was interpreted as collapsible items, causing a mismatch between the toggle test name and the collapsed log's test. 
An awk script is used to solve this issue by:
1. Parsing the test logs: Assigning `--- RUN` for the main test making it a collapsable item, and `=== RUN` for subtests. 
For example ([TestGcsFaultToleranceOptions in Test E2E (nightly operator) in this run](https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/6782#0194e8eb-6033-4da0-9656-4ea588f75380/597)): 
The main test name, "TestGcsFaultToleranceOptions", follows `--- RUN`, while subtest names follow `=== RUN`.
3. Replacing `---` for `PASS` and `FAIL` (other than …
=> [Feature] [Fix] Ensure Correct Logs Display for Go Test Logs in Buildkite Runner

.golangci.yml, kubectl-plugin/pkg/cmd/log/log_test.go, ray-operator/controllers/ray/common/pod_test.go
As title
Closes: https://github.com/ray-project/kuberay/issues/2905
=> [CI][#2905] Improvement: enable `testifylint` `compares` rule

.buildkite/test-kubectl-plugin-e2e.yml
This PR standardizes the go test verbose logs across all tests in the Buildkite runner. Currently, most tests use an awk script (format.awk) for log formatting, while only the Test E2E (kubectl-plugin) suite uses gotestfmt. Unifying all logs under a consistent formatting approach to ensure clear and standardized log outputs in Buildkite.
By applying format.awk to Test E2E (kubectl-plugin), the logs become consistent with other test logs:
1. `--- START`, `--- END`, and `--- RUN: TestName` are correctly added
2. For non-run lines, for example `PASS` and `FAIL`, `---` is replaced by `###` 
Resolves #3001 
=> [Fix] Standardize Buildkite Display Format Across All Tests

kubectl-plugin/pkg/cmd/job/job_submit.go
This change fixes the issue where `kubectl ray job submit` can execute even when `working_dir` is not set in the runtime environment.
User can choose to use the `working-dir` parameter directly or set `working_dir` in the runtime-env.
```
$ kubectl ray job submit --name rayjob-sample --working-dir ./workdir/ --runtime-env ./workdir/runtimeEnv.yaml -- python sample_code.py
panic: interface conversion: interface {} is nil, not string
goroutine 1 [running]:
github.com/ray-project/kuberay/kubectl-plugin/pkg/cmd/job.runtimeEnvHasWorkingDir({0xc000596828?, 0x0?})
/home/blocka/kuberay/kubectl-plugin/pkg/cmd/job/job_submit.go:576 +0x105
github.com/ray-project/kuberay/kubectl-plugin/pkg/cmd/job.(*SubmitJobOptions).Validate(0xc00022b680)
/home/blocka/kuberay/kubectl-plugin/pkg/cmd/job/job_submit.go: …
```
=> [kubectl-plugin] Fix panic when working_dir is not set

ray-operator/test/e2erayservice/rayservice_ha_test.go
Print the value of `WorkerGroupSpec.Replicas` to provides observability on autoscaler testing. It helps to identify the cause of issue.
Closes https://github.com/ray-project/kuberay/issues/2980
=> [Autoscaler] Print the value of WorkerGroupSpec.Replicas

kubectl-plugin/pkg/cmd/create/create_workergroup.go
command in the Cobra way.
```console
$ kubectl ray --context gke_kubeflow-platform_europe-west4-b_ml-compute-1 create workergroup -n hyperkube other-group
Error: error getting Ray cluster: resource name may not be empty
```
```console
$ kubectl ray create workergroup other-group
Error: required flag(s) "ray-cluster" not set
```
=> [refactor][kubectl-plugin] require cluster in `create workergroup`

kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
As title
```
$ kubectl ray job submit --name ray-job-sample pip --working-dir ~/workdir --head-gpu 1 --worker-gpu 1 --runtime-env ~/workdir/runtimeEnv.yaml -- python sample_code.py
```
For worker pod:
For head pod:
=> [kubectl-plugin] Support specifying number of head GPUs and worker GPUs for Rayjob

.buildkite/test-e2e.yml, .buildkite/test-kubectl-plugin-e2e.yml, .buildkite/test-sample-yamls.yml
https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/6857#0194f71f-8691-49cf-9279-cfc00c5e82fc
e2e tests failed but displayed success.
After this PR:
https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/6859#0194f740-3433-43ad-aaf1-f81de55661b5
N/A
=> [Fix][CI] E2E tests do not reflect error

ray-operator/config/samples/vllm/ray-service.vllm-tpu-v6e-singlehost.yaml, ray-operator/config/samples/vllm/serve_tpu.py
This PR adds an example vLLM RayService TPU manifest for v6e TPUs used in an [example guide](https://github.com/ray-project/ray/pull/47814).
https://github.com/ray-project/ray/pull/47814
=> Add vLLM TPU example RayService manifest

kubectl-plugin/pkg/cmd/get/get_cluster.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go
Right now `kubectl ray get cluster CLUSTER_NAME` exits 0 when no clusters are found.
```console
$ kubectl ray get cluster NON_EXISTENT_CLUSTER
$ echo $?
0
```
This change makes the command exit 1 with these errors.
```console
$ kubectl ray get cluster NON_EXISTENT_CLUSTER
Error: Ray cluster NON_EXISTENT_CLUSTER not found in any namespace
$ echo $?
1
$ kubectl ray get cluster -n hyperkube NON_EXISTENT_CLUSTER
Error: Ray cluster NON_EXISTENT_CLUSTER not found in namespace hyperkube
$ echo $?
1
```
We move table formatting logic from `GetClusterOptions.Run()` into a separate `printClusters()` function for ease of unit testing.
=> [fix][kubectl-plugin] return error when getting a non-existent cluster

kubectl-plugin/pkg/cmd/job/job_submit.go
`err` is not releated to `isRayClusterReady`. Don't print it.
Before:
N/A
=> [Fix][kubectl-plugin] Don't print wrapped error for job submit startup

kubectl-plugin/pkg/cmd/get/get_cluster.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go
We're currently validating the number of positional arguments ourselves.
We can do this with `cobra.Command{Args: cobra.MaximumNArgs(1)}` instead
to simplify logic. There are no functional changes. The error message changes
slightly but still conveys the same information.
```console
$ kubectl ray --context gke_kubeflow-platform_europe-west4-b_ml-compute-1 get cluster foo bar
Error: too many arguments, either one or no arguments are allowed
```
```console
$ kubectl ray get cluster foo bar
Error: accepts at most 1 arg(s), received 2
```
=> [refactor][kubectl-plugin] use cobra's posargs length validator

kubectl-plugin/pkg/cmd/get/get.go, kubectl-plugin/pkg/cmd/get/get_nodes.go, kubectl-plugin/pkg/cmd/get/get_nodes_test.go, kubectl-plugin/pkg/cmd/get/get_test.go, kubectl-plugin/pkg/cmd/get/get_workergroup.go, kubectl-plugin/pkg/cmd/get/get_workergroup_test.go
with
```console
kubectl ray (get|list) node[s] (NODE_NAME) \
[(-c/--ray-cluster) RAYCLUSTER] [(-n/--namespace) NAMESPACE] [(-A/--all-namespaces)]
```
This idea was originally described in [this doc](https://docs.google.com/document/d/18V5_7SGUzS0LGlaJB7xus04omyr3drKkK4vV6Kz14jY/edit?tab=t.0#heading=h.mekdvpaazlfo).
=> [feat][kubectl-plugin] list Ray nodes

kubectl-plugin/pkg/cmd/job/job_submit.go
The following command is wrongly constructed if `RayJob.Spec.RuntimeEnvYAML`, `runtimeEnv`, and `runtimeEnvJson` are all empty string.
```sh
ray job submit --address http://localhost:8265 --runtime-env-json null --working-dir . -- python sample_code.py
```
Correct command should be
```sh
ray job submit --address http://localhost:8265 --working-dir . -- python sample_code.py
```
=> [Fix][kubectl-plugin] ray job submit runtime-env-json null error

kubectl-plugin/test/e2e/kubectl_ray_log_test.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/test/e2e/raycluster_gcs_ft_test.go, ray-operator/test/e2erayservice/rayservice_redeploy_test.go
Closes #3013 
( raycluster-autoscaler is the rayCluster name from a random yaml I used for testing, which is not related to the issue.)
```
❯ kubectl get pods -l=ray.io/is-ray-node=yes
NAME                         READY   STATUS    RESTARTS   AGE
raycluster-autoscaler-head   2/2     Running   0          9m34s
```
=> [RayCluster] Make headpod name deterministic

ray-operator/controllers/ray/raycluster_controller.go
Cherry-pick of https://github.com/ray-project/kuberay/pull/3057
=> [release-1.3][Fix][RayCluster] fix missing pod name in CreatedWorkerPod and FailedToCreateWorkerPod events (#3057)

kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/log/log_test.go, kubectl-plugin/pkg/cmd/session/session.go, kubectl-plugin/pkg/cmd/session/session_test.go
command with a custom Cobra `Command.Args` function instead of writing our own
logic in `Complete()`.
```console
$ kubectl ray session
Error: session (RAYCLUSTER | TYPE/NAME)
See 'ray session -h' for help and examples
$ kubectl ray logs
Error: log (RAYCLUSTER | TYPE/NAME) [--out-dir DIR_PATH] [--node-type all|head|worker]
See 'ray log -h' for help and examples
```
```console
$ kubectl ray session
Error: accepts 1 arg, received 0
session (RAYCLUSTER | TYPE/NAME)
See 'ray session -h' for help and examples
$ kubectl ray logs
Error: accepts 1 arg, received 0
log (RAYCLUSTER | TYPE/NAME) [--out-dir DIR_PATH] [--node-type all|head|worker]
See 'ray log -h' for help and examples
```
=> [refactor][kubectl-plugin] require one posarg in `session`

kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/log/log_test.go
in the `kubectl ray log` command.
This is more complex but has several advantages.
* better help and error messages, e.g. shows the default "all" value in the
help messages
* more type-safe
* can set the default value of "all" more easily
* supports shell completion
References
* https://stackoverflow.com/a/70541824/553994
* https://applejag.eu/blog/go-spf13-cobra-custom-flag-types/
```console
$ kubectl ray logs -h
...
--node-type string               type of Ray node from which to download log, supports 'worker', 'head', or 'all'
...
$ kubectl ray logs dxia-test
No output directory specified, creating dir under current directory using resource name.
Command set to retrieve both head and worker node logs.
Downloading log for Ray Node dxia-test-default-group-worker-dgxsl
Downloading log for …
```
=> [refactor][kubectl-plugin] make `--node-type` an enum flag

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/validation.go, kubectl-plugin/pkg/util/validation_test.go
The [create cluster](https://github.com/ray-project/kuberay/blob/master/kubectl-plugin/pkg/cmd/create/create_cluster.go)  and [job submit](https://github.com/ray-project/kuberay/blob/master/kubectl-plugin/pkg/cmd/job/job_submit.go) command in the kubectl-plugin does not validate CPU, Memory, and GPU values properly. Since these values are passed as strings and directly used in resource definitions, users can input:
```
kubectl ray job submit --name rayjob-sample --head-cpu -1 --worker-cpu -2 --work-gpu xyz  --runtime-env path/to/runtimeEnv.yaml -- python my_script.py
```
- Negative values (-2, -1) should not be allowed.
- Non-numeric or malformed values (e.g., xyz) should trigger an error, instead of causing a panic, to ensure the program handles these gracefully.
After:
```
$ kubectl ray …
```
=> [kubectl-plugin] Validate resource values for negative and non-numeric inputs

ray-operator/test/sampleyaml/rayjob_test.go, ray-operator/test/sampleyaml/support.go
Dump k8s resources including pods, jobs, services, rayjobs when sampleyaml test failed.
Better logs for debugging.
#2979
file size with error logs: 2.3MB
=> [CI] dump failed test k8s resources

ray-operator/test/sampleyaml/support.go, ray-operator/test/support/resource_logger.go
Make resource logger composable.
Ready to apply to other tests.
#3069
This PR depends on the PR https://github.com/ray-project/kuberay/pull/3025 , please review the latest commit [14c452f](https://github.com/ray-project/kuberay/pull/3070/commits/14c452f24d3ea1ab6970825320149ef47d7820a5).
=> [CI] Composable kube resource logger when test failed

.github/pull_request_template.md, CHANGELOG.md, ci/markdownlint.yaml, docs/development/release.md, docs/guidance/rayclient-nginx-ingress.md
=> [chore][docs] enable Markdown lint rules MD005 and MD007

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/delete/delete.go, kubectl-plugin/pkg/cmd/delete/delete_test.go, kubectl-plugin/pkg/cmd/get/get_cluster.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go, kubectl-plugin/pkg/cmd/get/get_nodes.go, kubectl-plugin/pkg/cmd/get/get_nodes_test.go, kubectl-plugin/pkg/cmd/get/get_workergroup.go, kubectl-plugin/pkg/cmd/get/get_workergroup_test.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/cmd/job/job_submit_test.go, kubectl-plugin/pkg/cmd/log/log.go, kubectl-plugin/pkg/cmd/log/log_test.go, kubectl-plugin/pkg/cmd/session/session.go, kubectl-plugin/pkg/cmd/version/version.go, kubectl-plugin/pkg/cmd/version/version_test.go, kubectl-plugin/pkg/util/kubeconfig.go, kubectl-plugin/pkg/util/kubeconfig_test.go
We were duplicating logic in each command's `Validate()` test.
1. Abstract away K8s context detection logic with a new interface `KubeContexter`.
1. Consolidate tests for this logic in a separate test for `DefaultKubeContexter`.
1. Mock `KubeContexter` in `Validate()` tests with `MockKubeContexter` to simplify the `Validate()` tests.
=> [refactor][kubectl-plugin] simplify cobra `Validate()` tests

ray-operator/test/sampleyaml/raycluster_test.go, ray-operator/test/support/resource_logger.go
Print related resources when a cluster test failed.
Easier to debug.
This PR depends on
https://github.com/ray-project/kuberay/pull/3070
Please review based on the last commit [[CI] apply resource logger to ray cluster test](https://github.com/ray-project/kuberay/pull/3075/commits/6260d3764df25ccf300063792b73a1ae43a1b91e).
=> [CI] apply resource logger to ray cluster test

kubectl-plugin/pkg/cmd/get/get_cluster.go, kubectl-plugin/pkg/cmd/get/get_cluster_test.go, kubectl-plugin/pkg/util/conditions.go, kubectl-plugin/pkg/util/conditions_test.go, kubectl-plugin/test/e2e/kubectl_ray_cluster_get_test.go
in `kubectl ray [get|list] cluster` output.
```console
$ kubectl ray get cluster
NAME                            NAMESPACE   DESIRED WORKERS   AVAILABLE WORKERS   CPUS   GPUS   TPUS   MEMORY    AGE
vectors-test                    deep-end    68                68                  2048   0      0      13624Gi   21h
rayjob-b8ghp-raycluster-g2xvh   hulk        2                 2                   24     1      0      92Gi      15m
rayjob-8pnlm-raycluster-768x8   deadbeef    1                 1                   16     1      0      96Gi      8m35s
```
```console
$ kubectl ray get cluster
NAME                            NAMESPACE   DESIRED WORKERS   AVAILABLE WORKERS   CPUS   GPUS   TPUS   MEMORY    CONDITION              STATUS   AGE
vectors-test                    deep-end    68 …
```
=> [feat][kubectl-plugin] show last Condition and State

.buildkite/test-e2e.yml
This PR follows up on this PR https://github.com/ray-project/kuberay/pull/3021 to address a case where e2e tests failed but displayed success. This fix redirects stderr to stdout to ensure output logs are properly captured and processed by the awk formatter. 
Test with failed `TestRayClusterAutoscaler`:
https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/7025#01951c77-5a62-4cfc-9cc5-5601c688faaf
Failed logs are properly printed and displayed.
N/A
=> [Fix][CI] Redirect stderr to stdout in Test Autoscaler E2E (nightly operator)

CHANGELOG.md, CONTRIBUTING.md, benchmark/memory_benchmark/memory_benchmark.md, benchmark/perf-tests/README.md, ci/markdownlint.yaml, docs/design/protobuf-grpc-service.md, docs/development/release.md, docs/guidance/kuberay-with-MCAD.md, docs/guidance/rayclient-nginx-ingress.md, docs/guidance/rayservice-high-availability.md, docs/release/changelog.md, docs/release/helm-chart.md, helm-chart/kuberay-apiserver/README.md, helm-chart/kuberay-operator/README.md, helm-chart/ray-cluster/README.md, ray-operator/DEVELOPMENT.md
* MD025: Multiple top level headers in the same document
* MD026: Trailing punctuation in header
* MD031: Fenced code blocks should be surrounded by blank lines
* MD032: Lists should be surrounded by blank lines
=> [chore][docs] enable more Markdown lint rules

.krew.yaml
There are some whitespace changes in https://github.com/kubernetes-sigs/krew-index/pull/4426, preventing the auto-merge of the version bump for kubectl plugin.
N/A
=> [Fix][kubectl-plugin] Release bot opens PRs to Krew repo with unexpected whitespace changes

ray-operator/test/e2erayservice/rayservice_ha_test.go
The current tests use `pip install locust` to install the latest version of locust, but the latest version is incompatible with our tests. This PR pins the version to `2.32.10`.
=> [CI] fix locust versions

ray-operator/test/sampleyaml/rayservice_test.go, ray-operator/test/support/resource_logger.go
Print related resources when a ray service test failed.
Easier to debug.
#3069
This PR depends on
https://github.com/ray-project/kuberay/pull/3075
because need to print raycluster when rayservice failed.
Please review the last commit.
=> [CI] apply resource logger to ray service test

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go
Right now `kubectl ray create cluster NAME` returns 0 if a cluster with the
same name already exists. We want this command to have the same behavior as
`kubectl create` not `kubectl apply`. `kubectl create` exits with an error if
there's an existing resource with the same name.
Note: this change will break the existing behavior of users who run the command
as a way to update an existing cluster. Perhaps this is a desirable breaking
change.
```console
$ kubectl ray create cluster dxia-test1
Error: the Ray cluster dxia-test1 in namespace hyperkube already exists
$ echo $?
0
```
```console
$ kubectl ray create cluster dxia-test1
Error: the Ray cluster dxia-test1 in namespace hyperkube already exists
$ echo $?
1
```
=> [fix][kubectl-plugin] error when creating cluster that already exists

ray-operator/controllers/ray/utils/util.go
Currently, KubeRay adds different suffixes to make different services for a RayCluster. It will also trim these service names if they are too long to fit the 63-character limitation by k8s. However, the silent cut is not user user-friendly as users can't easily know the resulting service names beforehand. 
As a part of https://github.com/ray-project/kuberay/issues/3076: we are going to add a length validation to RayCluster names in v1.4 to make sure the silent cut does not take place while keeping sufficient room for the names specified by users, this PR shortens the `-raycluster-xxxxx` RayCluster suffix to just `-xxxxx` for RayJob and RayService, saving 11 characters for users to not be hit by the new length validation.
=> [feat] shorten RayClusterSuffix to have more space for RayService and RayJob names

ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/controllers/ray/utils/validation.go
This is the support PR for https://github.com/ray-project/kuberay/pull/3093 to make easier to review according to https://github.com/ray-project/kuberay/pull/3093#pullrequestreview-2638641916.
To make `ValidateRayClusterSpec` adapt for RayJob and RayService, `IsAutoscalingEnabled` is subject to change.
=> [RayCluster] IsAutoscalingEnabled takes RayClusterSpec

kubectl-plugin/test/e2e/kubectl_ray_session_test.go
=> [Bug] Re-enable flaky kubectl plugin e2e test "should reconnect after pod connection is lost"

.pre-commit-config.yaml
When I first run the pre-commit, I got a bunch of errors. I found the error came from it using different version of golang. It would be better to set the golang version so that people won't run into similar issue.
For the golang version, I tried 1.22.0, but it's not compatible with golangci-lint@v1.60.3. If I downgrade golangci-lint there will be other format error. I also tried 1.22.4, but pre-commit failed with code 137 (OOM). I am not sure if it's bug or a platform issue. I think 1.22.9 is fine since this is only for pre-commit. 
=> [Chore] Set default go version in pre commit

kubectl-plugin/pkg/cmd/delete/delete.go, kubectl-plugin/pkg/cmd/delete/delete_test.go
and user can skip interactive confirmation prompt with `-y/--yes`.
```console
$ kubectl ray delete raycluster/dxia-test1 raycluster/dxia-test2 rayjob/rayjob-sample
Error: delete (RAYCLUSTER | TYPE/NAME)
See 'ray delete -h' for help and examples
```
```console
$ kubectl ray delete raycluster/dxia-test1 raycluster/dxia-test2 rayjob/rayjob-sample
Are you sure you want to delete the following resources?
- raycluster/dxia-test1
- raycluster/dxia-test2
- rayjob/rayjob-sample
(y/yes/n/no)y
Deleted raycluster dxia-test1
Deleted raycluster dxia-test2
Deleted rayjob rayjob-sample
```
```console
$ kubectl ray delete raycluster/dxia-test1 raycluster/dxia-test2 rayjob/rayjob-sample --yes
Deleted raycluster dxia-test1
Deleted raycluster dxia-test2
Deleted rayjob rayjob-sample
```
Signed-off-by: David …
=> [feat][kubectl-plugin] `delete` accepts multiple resources

.github/workflows/consistency-check.yaml
It appears that consistency check `ray-operator-verify-crd-rbac` in step `Verify Changed files` has wrong path to base CRDs.
The path `config/bases` does not exist, while `config/crd/bases` does exist, thus an obvious fix.
Closes #3068 
=> [Fix] Adjust crd path to verify changed files

kubectl-plugin/go.mod, kubectl-plugin/go.sum, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/generation/generation.go
The entrypoint is required even for interactive mode jobs (see issue
#3126). This patch provides an empty endpoint to satisfy the
validation, while the true entrypoint is sent later with `ray job submit`.
The read/modify/update after job completion is also switched a patch request here, since the empty entrypoint gets omitted when roundtripped.
The jsonpatch library added is also pulled in by ray-operator, so not a major new dependency.
Workaround for #3126
=> kubectl ray job submit: provide empty entrypoint

ray-operator/controllers/ray/batchscheduler/interface/interface.go, ray-operator/controllers/ray/batchscheduler/schedulermanager.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler.go, ray-operator/controllers/ray/raycluster_controller.go
Currently Volcano scheduler is using context.TODO(). We should avoid that and use the passed context instead.
=> [bug] use passed context instead of TODO context

.buildkite/setup-env.sh, kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go, tests/framework/config/requirements.txt
There are 2 reason make the test fail.
- There are some kubectl process occupied the 8265 port that is required by the kubectl job submit. But for the independence of tests, we should not expect the test cause this problem to kill the process properly every time, so added the pkill kubectl before running kubectl job submit test.
- The ray is not installed on build kite env, so modified the setup-env.sh to install. 
Closes #2801 
=> [Bug] Re-enable flaky kubectl plugin e2e test in kubectl_ray_job_submit_test.go

ray-operator/test/sampleyaml/rayjob_test.go
Closes https://github.com/ray-project/kuberay/issues/3134.
The certificate of `modin-datasets.intel.com` is broken. Therefore, remove the test until https://github.com/modin-project/modin/issues/7451 is resolved.
Screenshot:
Closes https://github.com/ray-project/kuberay/issues/3134.
=> [ci] remove the test for modin because its certificate is broken

ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
If an user sets redis password in both GCSFaultTolerance and rayStartParam, it will prompt CR event in RayCluster.
However, it's not show in RayJob. Thus, the user need to find the CR event in RayCluster to know the cause.
The PR shows CR event on RayJob if it gets this kind of error. 
Here is result of screenshot.
https://github.com/ray-project/kuberay/issues/2986
=> Rayjob event can't set redis password in both GCSFaultTolerance and rayStartParam

kubectl-plugin/test/e2e/kubectl_ray_session_test.go
Fix the flaky test "should reconnect after pod connection is lost"
Run 10 times and no error:
- https://github.com/ray-project/kuberay/pull/3148
- https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/7287#01955d48-b403-4b6f-a9a1-b94c09446169
Closes: ray-project/kuberay#3140
=> [Fix][kubectl-plugin] Fix the flaky test "should reconnect after pod connection is lost"

.markdownlint.yaml, clients/python-client/python_client_test/README.md
* MD036: Emphasis used instead of a header
https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
Slightly clean up `clients/python-client/python_client_test/README.md`.
=> [chore][docs] enable Markdown lint rule MD036

.markdownlint.yaml, CHANGELOG.md
* MD050: Strong style
* MD052: Reference links and images should use a label that is defined
https://github.com/DavidAnson/markdownlint/tree/main/doc
=> [chore][docs] enable Markdown lint rules MD050 MD052

kubectl-plugin/pkg/cmd/get/get_nodes.go, kubectl-plugin/pkg/cmd/get/get_workergroup.go
Add dynamic shell completion for `kubectl ray get node` and `kubectl ray get workergroup`.
This feature is only limited to the `--ray-cluster` flag.
https://github.com/user-attachments/assets/7d27e24f-0896-444a-9463-32cdd86bd351
=> [Feat][kubectl-plugin] Add dynamic shell completion for kubectl ray get node & workergroup

.markdownlint.yaml, CHANGELOG.md, ray-operator/DEVELOPMENT.md
* MD024: Multiple headers with the same content
https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
=> [chore][docs] enable Markdown lint rule MD024

kubectl-plugin/go.mod, kubectl-plugin/go.sum, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/generation/generation.go
This PR reverts https://github.com/ray-project/kuberay/pull/3127. The main reason is that it's better to ask the users to upgrade to v1.2.2 instead of using `Patch`, which makes our codebase more complex. For details, see https://github.com/ray-project/kuberay/pull/3127#issuecomment-2701440287.
N/A
=> Revert PR #3127

helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/utils/validation_test.go
To make `RayClusterSpec` required in RayService.
This is the support PR according to https://github.com/ray-project/kuberay/pull/3153#discussion_r1983802799
Here is the result after applying a RayService with an empty `RayClusterSpec`.
=> [RayService] make RayClusterSpec required

.github/workflows/consistency-check.yaml, .github/workflows/helm-lint.yaml, .github/workflows/test-job.yaml
Enable all CI checks for release-1.3 branch. Especially required for https://github.com/ray-project/kuberay/pull/3163 
=> Enable CI for release-1.3 branch

ray-operator/config/samples/ray-serve/single_deployment_dag.py, ray-operator/config/samples/ray-service.no-ray-serve-replica.yaml, ray-operator/config/samples/ray-service.worker-no-serve.yaml
A worker pod in RayService without a ray serve replica will be set as readiness probe failed.
We add an YAML and example python file here for demonstration.
The document for this example will be a PR send to `ray-project/ray`
Closes #3048 
=> [Doc] Add a YAML to explain why some worker pod are not ready in RayService

kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/generation/generation.go
The entrypoint is required on kuberay versions prior to 1.2.2. To provide backwards compatability, this patch mirrors the entrypoint that will be used with `ray job submit` to the RayJob object.
The behavior when using 1.2.1 without this patch is confusing -- the user sees an "entry point required" message from kube-apiserver that doesn't make sense since they're providing an entry point to the plugin.  But we can work around that easily and make it "just work" with all 1.2.x versions.
See #3126, discussion at #3127
=> kubectl ray job submit: provide entrypoint

ray-operator/config/samples/ray-cluster.volcano-scheduler-queue.yaml, ray-operator/config/samples/ray-cluster.volcano-scheduler-test-queue.yaml, ray-operator/go.mod, ray-operator/go.sum
1. Create a queue with `cpu: 4`&`memory: 6Gi` and deploy a ray cluster of 1 head pod and 2 worker pods. (They should be scheduled with total resources 3CPUs & memory 4Gi as specified in `ray-cluster.volcano-scheduler-queue.yaml`). And the PodGroup Status should be running.
```console
❯ kubectl apply -f config/samples/ray-cluster.volcano-scheduler-test-queue.yaml
queue.scheduling.volcano.sh/kuberay-test-queue created
❯ kubectl apply -f config/samples/ray-cluster.volcano-scheduler-queue.yaml
raycluster.ray.io/test-cluster-0 created
❯ kubectl get podgroup ray-test-cluster-0-pg -o yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
creationTimestamp: "2025-03-09T07:38:21Z"
generation: 4
name: ray-test-cluster-0-pg
spec:
minMember: 3
minResources:
cpu: …
```
=> [RayCluster]Upgrade volcano to 1.11.0

ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
If an user sets redis password in both GCSFaultTolerance and rayStartParam, it will prompt CR event in RayCluster.
However, it's not show in RayService. Thus, the user need to find the CR event in RayCluster to know the cause.
Here is result of screenshot.
https://github.com/ray-project/kuberay/issues/2986
=> RayService event can't set redis password in both GCSFaultTolerance and rayStartParam 

kubectl-plugin/pkg/cmd/version/version.go, kubectl-plugin/pkg/cmd/version/version_test.go
I think it would be helpful for `kubectl ray version` to print the git commit it was built with for dev versions.
Example output:
```
$ kubectl ray version
kubectl ray plugin version: development (0056fbf, built 2025-03-10T05:43:22Z)
...
```
n/a
=> kubectl plugin: version shows commit for dev

ray-operator/controllers/ray/rayjob_controller_test.go
Make sure the annotation in RayJob has been populated to the derived RayCluster according to https://github.com/ray-project/kuberay/pull/3093#discussion_r1966926918
=> [RayJob][Test] Make sure annotation populated to RayCluster

helm-chart/kuberay-operator/templates/_helpers.tpl, helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/values.yaml
We need to be able to override `app.kubernetes.io/component`, in the same way that the helm chart allows us to override `app.kubernetes.io/name`.
=> Allow app.kubernetes.io/component to be overriden in kuberay-operator helm chart

proto/Dockerfile
Right now running `cd proto && make build-image` errors because the required `unzip` package isn't installed. We install it.
```console
$ make build-image
docker build -t kuberay/proto-generator:7a64c574b9c899871c3b0126d1f33e55e30f7dfb -f Dockerfile .
[+] Building 1.4s (7/16)                                                                                                                               docker:default
=> [internal] load build definition from Dockerfile                                                                                                             0.1s
=> => transferring dockerfile: 1.66kB                                                                                                                           0.0s
=> [internal] load metadata for …
```
=> [fix][proto] install missing `unzip` in Dockerfile

ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/common/job_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/test/e2e/rayjob_retry_test.go
As shown in https://github.com/ray-project/kuberay/issues/3211:
>In v1.3, I observe that the new behavior is:
>
>* Attempt 1: submit job -> tail logs -> error when job fails
>* Attempt 2: ray job status -> ray job logs -> completed
>
>In Attempt 2, the pod successfully completes with exit code 0 because "ray job logs" returns exit 0 even if the job fails. >Here's an example from my cluster:
>
>```
>$ kubectl get po
>NAME                                                        READY   STATUS      RESTARTS   AGE
>pytorch-text-classifier-6q6ff-x59k6                         0/1     Error       0          11m          # first attempt
>pytorch-text-classifier-6q6ff-xqhk7                         0/1     Completed   0          10m.  # second attempt
>```
>
>What I expected was the submitter Job to …
=> [RayJob][Fix] Use --no-wait for job submission to avoid carrying the error return code to the log tailing

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
Add options for create cluster
- --head-node-selectors
- --worker-node-selectors
Node selectors are very common to set for RayCluster, especially since most providers use node selectors as a way to specify the GPU type.
Closes #3143
```bash
❯ ./kubectl-ray create cluster test-cluster --head-node-selectors=1=2,3=4 --worker-node-selectors=a=b,c=d --dry-run
metadata:
name: test-cluster
namespace: default
spec:
headGroupSpec:
dashboard-host: 0.0.0.0
template:
spec:
containers:
- image: rayproject/ray:2.41.0
name: ray-head
ports:
- containerPort: 6379
name: gcs-server
- containerPort: 8265
name: dashboard
- containerPort: 10001
name: client
resources:
limits:
cpu: "2"
memory: 4Gi
requests:
cpu: "2"
memory: 4Gi …
```
=> [kubectl-plugin] Add head/worker node selector option

.github/workflows/image-release.yaml
This Merge Request uses #3015 as a reference to make the `release-image-build` github workflow to take only the tag as input since `krew-release-bot` requires it. 
1. The `workflow-dispatch` step is now empty (i.e., no manual inputs)
2. An error checking step enforces the workflow fails if it's not running on a tag. 
3. Extract the tag for other steps to use. 
Resolve #3016 
=> [Chore][CI] Limit the release-image-build github workflow to only take tag as input

.buildkite/build-start-operator.sh, .buildkite/format.awk, .buildkite/ray-ci-integration.md, .buildkite/test-e2e.yml, docs/development/release.md
Cherry-picking in https://github.com/ray-project/kuberay/pull/3215 because rayci will run against kuberay release branch and therefore this branch needs this to support rayci making kuberay ci use a specific ray image.
=> Integrate with rayci (#3215)

kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
From personal experience, CPU limits cause more problems than they solve. I suggest we remove CPU limits in the plugin by default.
=> [kubectl-plugin] remove CPU limits by default

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
so we can use it for [this proposed cluster config schema][1]. We change in a backwards-compatible way to support multiple worker groups and other fields in the schema.
[1]: https://docs.google.com/document/d/18V5_7SGUzS0LGlaJB7xus04omyr3drKkK4vV6Kz14jY/edit?tab=t.0#heading=h.tuqyq1b6b2x7
=> [refactor][plugin] RayClusterSpecObject

kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/create/create_workergroup_test.go
> While following the instruction from [document  ](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/kubectl-plugin.html) with master branch's kubectl-plugin, it raise error
```shell=
$ kubectl ray create cluster raycluster-sample
$ kubectl ray create workergroup example-group --ray-cluster raycluster-sample --worker-memory 5Gi
```
> It will raise error
```
Error: error updating Ray cluster with new worker group: RayCluster.ray.io "raycluster-sample" is invalid: spec.workerGroupSpecs[1].rayStartParams: Required value
```
Closes #3250 
=> [kubectl-plugin] fix rayStartParams error when creating workgroup

.github/workflows/consistency-check.yaml, scripts/rbac_test.py
This PR moves `rbac_test.py` to another directory to avoid the need to remove it when releasing a new helm chart version
Closes #3255
=> [feat] move rbac_test.py to scripts

kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/create/create_workergroup_test.go
> It's weird to put checking in createWorkerGroupSpec, so rayStartParams will be moved to options.Complete()
The `rayStartParams` will be check in `func (options *CreateWorkerGroupOptions) Complete(cmd *cobra.Command, args []string)`
Closes #3259 
=> [Refactor] move `rayStartParams` to options.complete

ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/apis/ray/v1/rayservice_types.go
for v1 RayJob and RayService CRDs.
https://github.com/ray-project/kuberay/pull/3220 only did this for v1 RayCluster.
We do this for these other two CRDs to be consistent.
=> [operator] add `+optional` to CRD fields that are optional

.github/workflows/image-release.yaml, kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/create/create_workergroup_test.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go, ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/common/job_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/test/e2e/rayjob_retry_test.go
Backports the following bug fixes and improvements:
* #3216 
* #3186 
* #3228 
* #3235 
* #3117 
* #3249 
=> [release-1.3] v1.3.2 backports

ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
One of the goals of https://github.com/ray-project/kuberay/pull/3083 is to provide more predictable Kubernetes service names generated by the KubeRay controller for RayCluster, RayService, and RayJob. Therefore, we shortened the allowed length for CR names and validated them at the beginning so that we can now only add fixed suffixes to generate their Kubernetes service names without mutating and trimming the prefixes of their names. Mutating and trimming their prefixes make them less predictable.
A case mentioned in https://github.com/ray-project/kuberay/issues/2169 shows why we want https://github.com/ray-project/kuberay/pull/3083 for not mutating and trimming the prefixes of service names: A user tends to fully copy the CR name with the generated suffix, such as `-head-svc`, and uses …
=> [feat] enforce DNS1035 validations on RayCluster, RayService, and RayJob names

apiserver/Makefile
I would like to remove lint out of test section, there're two reasons:
First, the `golangci-lint` version documented on the [doc](https://github.com/ray-project/kuberay/blob/master/apiserver/DEVELOPMENT.md#optional-development-tools) doesn't work for existing code, which fails test, see [discussion thread](https://ray.slack.com/archives/C01CKH05XBN/p1744155976705229) at slack channel;
Second reason, linter has nothing to do with testing, which should better live in precommit hook and CI.
Error message:
```sh
/home/ubuntu/kuberay/bin/golangci-lint run  --timeout=3m --exclude='SA1019' --no-config
pkg/client/cluster.go:28:3: undefined: klog (typecheck)
klog.Fatalf("Failed to create RayCluster client. Error: %v", err)
^
```
There's a related issue: …
=> [apiserver] No lint at test

ray-operator/config/samples/ray-cluster.autoscaler-v2.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml
- This PR adds a comment explaining how to configure the AUTOSCALER_UPDATE_INTERVAL_S environment variable in autoscalerOptions. 
```
autoscalerOptions:
env:
- name: AUTOSCALER_UPDATE_INTERVAL_S
value: "30"
```
https://github.com/ray-project/ray/issues/49200
=> [Autoscaler][Sample] Add comment for AUTOSCALER_UPDATE_INTERVAL_S

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayjob_controller.go
Make options as a direct field in reconciler.
As the number of options grows, it can be messy if we make all of them a field of the reconciler.
N/A
=> [refactor] Make options as a direct field in reconciler

helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/templates/role.yaml, helm-chart/kuberay-operator/templates/rolebinding.yaml, helm-chart/kuberay-operator/templates/service.yaml, helm-chart/kuberay-operator/templates/serviceaccount.yaml, helm-chart/kuberay-operator/tests/deployment_test.yaml, helm-chart/kuberay-operator/tests/role_test.yaml, helm-chart/kuberay-operator/tests/rolebinding_test.yaml, helm-chart/kuberay-operator/tests/service_test.yaml, helm-chart/kuberay-operator/tests/serviceaccount_test.yaml, helm-chart/kuberay-operator/values.yaml
Make sure kuberay-operator Helm chart can work as expected with various configurations by adding unit tests.
One can run Helm chart unit tests by:
```bash
$ helm plugin install https://github.com/helm-unittest/helm-unittest.git
$ helm unittest helm-chart/kuberay-operator --strict --debug
PASS  Test Deployment  helm-chart/kuberay-operator/tests/deployment_test.yaml
PASS  Test ClusterRole helm-chart/kuberay-operator/tests/role_test.yaml
PASS  Test ClusterRoleBinding  helm-chart/kuberay-operator/tests/rolebinding_test.yaml
PASS  Test Service     helm-chart/kuberay-operator/tests/service_test.yaml
PASS  Test ServiceAccount      helm-chart/kuberay-operator/tests/serviceaccount_test.yaml
Charts:      1 passed, 1 total
Test Suites: 5 passed, 5 total
Tests:       25 passed, 25 total
Snapshot: …
```
=> Add basic Helm chart unittests for kuberay-operator

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/constant.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go, kubectl-plugin/pkg/util/validation.go, kubectl-plugin/pkg/util/validation_test.go
as described in the [Ray Kubectl Plugin 1.4.0 Wishlist][1].
Here are the resulting RayCluster YAMLs after running `kubectl ray create cluster dxia-test --file /path/to/file.yaml --dry-run` on various config files.
<details>
<summary>RayCluster from a minimal config file</summary>
```yaml
worker-groups:
- replicas: 1
gpu: 1
```
```yaml
metadata:
name: dxia-test
namespace: default
spec:
headGroupSpec:
dashboard-host: 0.0.0.0
template:
spec:
containers:
- image: rayproject/ray:2.41.0
name: ray-head
ports:
- containerPort: 6379
name: gcs-server
- containerPort: 8265
name: dashboard
- containerPort: 10001
name: client
resources:
limits:
memory: 4Gi
requests:
cpu: "2"
memory: 4Gi
rayVersion: 2.41.0
workerGroupSpecs:
- groupName: …
```
=> [feat][plugin] support creating RayCluster with config file

apiserver/pkg/http/client.go, apiserver/pkg/model/converter_test.go, apiserver/pkg/server/cluster_server.go, apiserver/pkg/server/compute_template_server.go, apiserver/pkg/server/job_server.go, apiserver/pkg/server/ray_job_submission_service_server.go, apiserver/pkg/server/serve_server.go, apiserver/pkg/server/validations_test.go, apiserver/pkg/util/cluster.go, apiserver/pkg/util/cluster_test.go, apiserver/pkg/util/error.go, apiserver/pkg/util/job_test.go, apiserver/pkg/util/service_test.go, apiserver/test/e2e/config_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/types.go, kubectl-plugin/pkg/cmd/get/get_cluster.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/client/client.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/suite_helpers_test.go, ray-operator/test/support/ray.go, scripts/lint.sh
Based on suggestion https://github.com/ray-project/kuberay/pull/3303#pullrequestreview-2761211609, for easier code review, in this PR, I apply golangci-lint to `apiserver` directory and it only contain auto-fixed changes.
In the followup PR, there'll two things included:
- All left linter issues manually fixed;
- Enable linter in precommit hook for apiserver.
Commands to execute:
```sh
[~/kuberay] (hjiang/golanglint-autofix-apiserver) 
ubuntu@hjiang-devbox-pg$ pre-commit install -t pre-push
pre-commit installed at .git/hooks/pre-push
[~/kuberay] (hjiang/golanglint-autofix-apiserver) 
ubuntu@hjiang-devbox-pg$ pre-commit run golangci-lint --all-files
```
=> [lint] Apply golangci-lint autofix on `apiserver` directory

apiserver/Makefile, apiserver/test/e2e/cluster_server_e2e_test.go
Before official release, we need to understand the test coverage for integration test; especially for apiserver which is hard to unit test and heavily rely on integration test. 
Result:
```sh
[~/kuberay/apiserver] (master) 
ubuntu@hjiang-devbox-pg$ make e2e-test
go test ./test/e2e/...  -timeout 60m  -race -cover -count=1 -parallel 4
ok      github.com/ray-project/kuberay/apiserver/test/e2e       960.111s        coverage: 78.6% of statements
```
Closes https://github.com/ray-project/kuberay/issues/3329
=> [apiserver] Enable test coverage for e2e test

apiserver/cmd/main.go, apiserver/pkg/http/client.go, apiserver/pkg/interceptor/interceptor.go, apiserver/pkg/model/converter.go, apiserver/pkg/model/converter_test.go, apiserver/pkg/server/cluster_server.go, apiserver/pkg/server/compute_template_server.go, apiserver/pkg/server/job_server.go, apiserver/pkg/server/serve_server.go, apiserver/pkg/util/cluster.go, apiserver/pkg/util/cluster_test.go, apiserver/pkg/util/job_test.go, apiserver/pkg/util/service.go, apiserver/pkg/util/service_test.go, apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go, apiserver/test/e2e/cluster_server_e2e_test.go, apiserver/test/e2e/config_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/job_submission_e2e_test.go, apiserver/test/e2e/service_server_e2e_test.go, apiserver/test/e2e/types.go, scripts/lint.sh
Followup for suggestion https://github.com/ray-project/kuberay/pull/3303#pullrequestreview-2761211609, this PR **fixes half of the linter issues** for apiserver; I didn't put all fixes in one PR for easier review.
To reviewers: each commit in the PR is a self-contained fix for one particular linter complaint; hopefully it relieves your review burden. :)
Command I used to do suggested string replacements:
```sh
find . -regextype posix-egrep -type f -name "*.go" | xargs -o sed -i "s/ApiServerInterceptor/APIServerInterceptor/g"
find . -regextype posix-egrep -type f -name "*.go" | xargs -o sed -i "s/actualRpcStatus/actualRPCStatus/g"
find . -regextype posix-egrep -type f -name "*.go" | xargs -o sed -i "s/startRpcServer/startRPCServer/g"
find . -regextype posix-egrep -type f -name "*.go" | …
```
=> [1/N] [apiserver] Fix half of linter issues for apiserver

kubectl-plugin/pkg/cmd/create/create_cluster_test.go
`TestSwitchesIncompatibleWithConfigFilePresent` is flaky because the test reused the same `cmd` object across subtests, causing `SetArgs` in one iteration to affect the next due to shared flag state. This led to flakiness depending on map iteration order.  
This PR ensures a new command is created per subtest to ensure isolation between each subtest.
Closes #3325 
To ensure the test is not flaky with this PR, I've run 100 times of the `TestSwitchesIncompatibleWithConfigFile` with the following script and passed all of them. In comparison, the original test failed roughly every 10 times.
```
#!/bin/bash
for i in {1..100}; do
echo "Run #$i"
go test ./pkg/cmd/create -run ^TestSwitchesIncompatibleWithConfigFilePresent$ -count=1 -v -race || break
done
```
=> [kubectl-plugin] TestSwitchesIncompatibleWithConfigFilePresent is flaky

ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/test/e2e/support.go, ray-operator/test/e2eautoscaler/support.go, ray-operator/test/e2erayservice/support.go
- Convert hard-coded port names and values into constant variables defined in `ray-operator/controllers/ray/utils/constant.go`
https://github.com/ray-project/kuberay/blob/732a6754ff4d1c1e606bd22c14642b33c982e1d4/ray-operator/controllers/ray/utils/constant.go#L66-L77
Follow up on https://github.com/ray-project/kuberay/pull/3262#discussion_r2035836143
Some codes include hard-coded port name and value, which may cause some typo. 
=> [Refactor] use constant variable for port name and value

apiserver/Makefile
As of now we load two ray images into kind cluster for testing:
https://github.com/ray-project/kuberay/blob/732a6754ff4d1c1e606bd22c14642b33c982e1d4/apiserver/Makefile#L153-L158
There're two relates PRs:
- The code was written that way from the beginning (no explanation): https://github.com/ray-project/kuberay/commit/ff459239fde9a6a0998d38f0fd5e3eb5e365610e
- We used to revert PR (which tries to upgrade ray test image): https://github.com/ray-project/kuberay/commit/d8ffec4070e4517d3e144053be27f91fa0fbb0b4
Reading through the above change, my understand is we pin ray image as 2.9.0, and don't think latest image is necessary (otherwise why do we revert the upgrade PR).
I tested with local e2e test, apart from the known flaky test https://github.com/ray-project/kuberay/issues/3293 (which …
=> [apiserver] Remove unnecessary test image

apiserver/pkg/http/client.go, apiserver/pkg/http/client_test.go
This PR does two trivial changes:
- Improve error stringify function to include http status code interpretation, otherwise people need to check themselves;
+ For low-qps system like apiserver, I prefer verbose logging for easier troubleshooting 
+ Add corresponding unit test for stringify function
- Remove unnecessary `createHttpRequest` function
=> [apiserver] [easy] Add http error status test

apiserver/pkg/util/cluster_test.go
This PR is part of #3318, working on unit test for `pkg/util/cluster.go`.  
Code coverage of `pkg/util/cluster.go` is increased from 79.4% to 85.1%.  
Overall code coverage of `pkg/util` is increased from 63.4% to 67.2%.
#3318 
=> [Feature] Add apiserver unit test(pkg/util/cluster.go)

apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go, apiserver/test/e2e/cluster_server_e2e_test.go, apiserver/test/e2e/config_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/job_submission_e2e_test.go, apiserver/test/e2e/service_server_e2e_test.go, apiserver/test/e2e/types.go
#3354 
**TLDR; ~6.28x Speedup!**
```log
=== RUN   TestCreateJobWithDisposableClusters
=== RUN   TestCreateJobWithDisposableClusters/Create_a_running_sample_job
=== RUN   TestCreateJobWithDisposableClusters/Create_a_failing_sample_job
=== RUN   TestCreateJobWithDisposableClusters/Create_a_job_request_without_providing_a_namespace
=== RUN   TestCreateJobWithDisposableClusters/Create_a_job_request_with_nil_job_spec
=== RUN   TestCreateJobWithDisposableClusters/Create_a_job_request_with_no_namespace_in_the_job_spec
=== RUN   TestCreateJobWithDisposableClusters/Create_a_job_request_with_no_name
=== RUN   TestCreateJobWithDisposableClusters/Create_a_job_request_with_no_user_name
=== RUN   TestCreateJobWithDisposableClusters/Create_a_job_request_with_entrypoint
=== RUN …
```
=> Api server refactor/allow multiple job statuses in jobe2e

apiserver/pkg/util/error.go
**Update:**
Suggested by https://github.com/ray-project/kuberay/pull/3352#discussion_r2041273493, I remove unused code in the file.
I didn't do anything to `UserError` because all util functions seem intentionally implemented that way.
This is the linter complaint.
```sh
pkg/util/error.go:103:15: G115: integer overflow conversion int -> uint32 (gosec)
codes.Code(apiError.Code))
^
```
Linter complains because grpc code takes a uint32, while apiError.Code is a signed integer value;
A deeper look into both source code, openapi package is made for HTTP request, and API status code coming from:
https://github.com/go-openapi/runtime/blob/2bd21c899d267cc8aa9d49cefc5ad0e77de56da5/client_response.go#L77-L99
with code value representing http status code.
Here we're using grpc code, **so it's …
=> [apiserver] Remove unused code in apiserver error utils

apiserver/pkg/manager/resource_manager.go
I found resource manager interface is out of sync with its implementation; for example, we recently add pagination to a bunch of list operations, but they're not reflected in interface, nor it breaks CI and local test => the interface is not used anywhere.
Usually these interfaces are used as a way to do dependency injection, but I checked where the resource manager is used, the logic looks simple so I don't think it's really worthwhile.
There're two ways proposed here to fix the inconsistency and prevent later breakage:
- We use `ResourceManagerInterface` everywhere as data member type;
- We delete the interface declaration.
I took the second path in the PR because:
(1) (major) As I mentioned above, I don't think unit test is a must-have here, considering we already have integration test …
=> [apiserver] Delete resource manager interface

apiserver/pkg/http/client.go, apiserver/pkg/http/client_test.go, apiserver/pkg/util/cluster_test.go, apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go, apiserver/test/e2e/cluster_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/service_server_e2e_test.go, apiserver/test/e2e/types.go, scripts/lint.sh
All noticeable linter issues fixed, this PR enables precommit hook for the whole apiserver.
Closes https://github.com/ray-project/kuberay/issues/3302
=> [apiserver] Enable golang linter for apiserver

apiserver/pkg/interceptor/interceptor_test.go
The pkg/interceptor package had 0% test coverage, which could lead to potential reliability issues as it's a critical component handling all gRPC API requests. This PR adds tests to verify its functionality, achieving 100% coverage:
```bash
$ make test
go test ./pkg/...  -race -coverprofile ray-kube-api-server-coverage.out  -parallel 4
ok      github.com/ray-project/kuberay/apiserver/pkg/interceptor        1.036s  coverage: 100.0% of statements
```
Closes #3312
=> [test][apiserver] Add unittests for pkg/interceptor

apiserver/DEVELOPMENT.md, apiserver/pkg/interceptor/interceptor_test.go
Currently, the `DEVELOPMENT.md` does not show clearly that we need to start the apiserver before running the e2e test. Adding it in the documentation.
=> [DOCS] document step to do before running e2e test

apiserver/Makefile, apiserver/README.md, apiserver/cmd/main.go
Part of https://github.com/ray-project/kuberay/issues/3327.
I personally think current readme is not clear as an entrypoint, something I expect:
- An introduction on apiserver, what's the feature set, how does it correlate to other components, etc
- A simple command to launch and play with apiserver
+ There're too many commands apiserver development page
- Hyperlink to other useful resources, for example, HTTP endpoint spec
This PR tries to improve (2).
=> [apiserver] Add make command to start apiserver

.buildkite/test-e2e.yml, apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go, ci/kind-config-buildkite-e2e-apiserver.yml
#3307
Skip the `TestCreateClusterAutoscaler` test because it is a bit flaky.
- https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/7978#019633d0-5933-4742-a2ff-ded32468b963/913-1065
- https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/7981#0196348e-955f-460f-8c90-a362e1a9e2b2/407-559
Local Test:
```
$ go test ./test/e2e/... -timeout 60m -race -count=10 -parallel=4 -run '^TestCreateClusterAutoscaler$'
--- FAIL: TestCreateClusterAutoscaler (107.77s)
cluster_server_autoscaler_e2e_test.go:130: 
Error Trace:    /home/ubuntu/kuberay/apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go:130
Error:          Not equal: 
expected: 1
actual  : 0
Test:           TestCreateClusterAutoscaler
FAIL
FAIL    github.com/ray-project/kuberay/apiserver/test/e2e …
```
=> [CI] Add apiserver e2e test to buildkite

apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go, apiserver/test/e2e/cluster_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/service_server_e2e_test.go, apiserver/test/e2e/types.go
ApiServer is e2e flaky due to the fixed sleep time waiting for worker pod, changed to polling to deal with the flakiness, and it also speedup the test.
```
=== RUN   TestCreateClusterAutoscaler
--- PASS: TestCreateClusterAutoscaler (158.10s)
PASS
coverage: 54.2% of statements
ok      github.com/ray-project/kuberay/apiserver/test/e2e  159.198s coverage: 54.2% of statements
```
```
=== RUN   TestCreateClusterAutoscaler
--- PASS: TestCreateClusterAutoscaler (119.57s)
PASS
coverage: 54.2% of statements
ok      github.com/ray-project/kuberay/apiserver/test/e2e  120.662s coverage: 54.2% of state
```
Closes #3293
=> [Apiserver][Refactor] Use polling in autoscaler e2e test

.buildkite/test-e2e.yml
When I was checking the E2E test status on Buildkite, I noticed that the `go.mod` for `E2E Operator Version Upgrade` requires Go version 1.23.
Before:
After:
=> [CI] Bump Go version to 1.23 to support E2E Operator Version Upgrade tests in Buildkite

apiserver/pkg/http/client.go, apiserver/pkg/server/cluster_server.go, docs/design/protobuf-grpc-service.md, proto/cluster.proto, proto/config.proto, proto/go_client/cluster_grpc.pb.go, proto/go_client/config.pb.go, proto/go_client/config_grpc.pb.go, proto/go_client/serve.pb.go, proto/kuberay_api.swagger.json, proto/swagger/cluster.swagger.json, proto/swagger/config.swagger.json, proto/swagger/serve.swagger.json
See linked issue for details.
We don't plan to support sorting for list operations, so remove it from documentation everywhere.
I also remove the comment on pagination, because pagination is a very common feature for list; open to revert if people think it necessary.
Closes https://github.com/ray-project/kuberay/issues/3408
=> [doc] [apiserver] Remove wording on pagination and sort

apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/service_server_e2e_test.go
For detail please refer to #3354
```log
=== RUN   TestCreateServiceV2
=== RUN   TestCreateServiceV2/Create_a_fruit_stand_ray_service_using_V2_configuration
=== RUN   TestCreateServiceV2/Create_a_service_request_with_no_namespace_value
=== RUN   TestCreateServiceV2/Create_a_service_request_with_mismatching_namespaces
=== RUN   TestCreateServiceV2/Create_a_service_request_with_no_name
=== RUN   TestCreateServiceV2/Create_a_service_request_with_no_user
=== RUN   TestCreateServiceV2/Create_a_service_request_with_no_cluster_spec
--- PASS: TestCreateServiceV2 (43.18s)
--- PASS: TestCreateServiceV2/Create_a_fruit_stand_ray_service_using_V2_configuration (42.81s)
--- PASS: TestCreateServiceV2/Create_a_service_request_with_no_namespace_value (0.00s)
--- PASS: …
```
=> Api server refactor/allow multiple job statuses in servicee2e

helm-chart/kuberay-operator/templates/_helpers.tpl, helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/templates/leader_election_role.yaml, helm-chart/kuberay-operator/templates/leader_election_role_binding.yaml, helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml, helm-chart/kuberay-operator/templates/multiple_namespaces_rolebinding.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_viewer_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_viewer_role.yaml, helm-chart/kuberay-operator/templates/role.yaml, helm-chart/kuberay-operator/templates/rolebinding.yaml, helm-chart/kuberay-operator/templates/service.yaml, helm-chart/kuberay-operator/templates/serviceaccount.yaml
Define name template helpers for all resources. For example, we will define an helper template for the service account:
```gotmpl
{{- /* Create the name of the service account to use. */ -}}
{{- define "kuberay-operator.serviceAccount.name" -}}
{{- if .Values.serviceAccount.create -}}
{{- default (include "kuberay-operator.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end -}}
{{- end -}}
```
Then we will reuse this helper template multiple times in all RoleBinding/ClusterRoleBinding resources to avoid potential name inconsistency.
```gotmpl
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
...
subjects:
- kind: ServiceAccount
name: {{ include "kuberay-operator.serviceAccount.name" . }}
namespace: {{ …
```
=> [Refactor][Helm] Define name templates for kuberay-operator resources

.pre-commit-config.yaml, helm-chart/Makefile, helm-chart/kuberay-operator/Chart.yaml, helm-chart/kuberay-operator/README.md, helm-chart/kuberay-operator/README.md.gotmpl, helm-chart/kuberay-operator/values.yaml
Use [helm-docs](https://github.com/norwoodj/helm-docs) to keep the chart README up-to-date. 
I have added a `Makefile` under the helm-chart directory, and it contains some useful targets, all the dependencies will be installed automatically as needed:
```
$ make          
Usage:
make <target>
General
help                            Display this help.
Helm
helm-unittest                   Run Helm chart unittests.
helm-lint                       Run Helm chart lint test.
helm-docs                       Generates markdown documentation for Helm charts from requirements and values files.
Dependencies
helm                            Download helm locally if necessary.
helm-unittest-plugin            Download helm unittest plugin locally if necessary.
helm-docs-plugin                Download …
```
=> Use helm-docs to generate README for chart kuberay-operator automatically 

apiserver/Makefile
To load the KubeRay operator image into a `kind` cluster, the correct phony target is `load-operator-image` (not `load-image`, which is used for loading the API server image).
N/A
=> [Docs] Correct command to load KubeRay operator image

.golangci.yml, kubectl-plugin/cmd/kubectl-ray.go, kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/cmd/create/create_workergroup.go, kubectl-plugin/pkg/cmd/delete/delete.go, kubectl-plugin/pkg/cmd/delete/delete_test.go, kubectl-plugin/pkg/cmd/get/get.go, kubectl-plugin/pkg/cmd/get/get_cluster.go, kubectl-plugin/pkg/cmd/get/get_nodes.go, kubectl-plugin/pkg/cmd/get/get_nodes_test.go, kubectl-plugin/pkg/cmd/get/get_workergroup.go, kubectl-plugin/pkg/cmd/get/get_workergroup_test.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/cmd/job/job_submit_test.go, kubectl-plugin/pkg/cmd/log/log_test.go, kubectl-plugin/pkg/cmd/ray.go, kubectl-plugin/pkg/cmd/scale/scale_cluster.go, kubectl-plugin/pkg/cmd/scale/scale_cluster_test.go, kubectl-plugin/pkg/cmd/session/session.go, kubectl-plugin/pkg/cmd/session/session_test.go, kubectl-plugin/pkg/cmd/version/version.go, kubectl-plugin/pkg/cmd/version/version_test.go, kubectl-plugin/pkg/util/client/client.go, kubectl-plugin/pkg/util/client/client_test.go, kubectl-plugin/pkg/util/client/fake/fake_client.go, kubectl-plugin/pkg/util/completion/completion.go, kubectl-plugin/pkg/util/generation/generation.go
Typically we group imports by at least three sections.
1. Standard – All Go standard library imports.
2. Default – Third-party libraries (anything not in standard or custom prefix).
3. Prefix – `github.com/ray-project/kuberay` in our case
There are multiple tools help us do this. For example, we can use gci with the following configuration
```
gci:
sections:
- standard
- default
- prefix(github.com/ray-project/kuberay)
skip-generated: true
```
To keep changes minimal, I only modify kubectl-plugin in this PR. Also since we have wrongly configured local prefix as `github.com/ray-project/kuberay/ray-operator` instead of `github.com/ray-project/kuberay`, the linter will separate `github.com/ray-project/kuberay/ray-operator` with other `github.com/ray-project/kuberay` packages. 
See: …
=> [1/N] [Lint] Group imports by sections

apiserver/README.md
As apiserver become officially maintained component in the coming release v1.4, we should remove stale responsibility wording, which doesn't apply any longer.
=> [apiserver] Update entry point readme page

helm-chart/kuberay-operator/README.md, helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/values.yaml
There is a typo in the values of the Helm chart. The correct term is `operatorCommand`, not `operatorComand`.
=> [HELM] Typo correction (`operatorComand` -> `operatorCommand`)

apiserver/Makefile
* Remove redundant spaces and add missing ones
* Correct inconsistent indentations
* Add missing periods in automatic help documentation comments\
* Add missing `.PHONY`
The current `Makefile` contains several formatting inconsistencies that affect readability and maintainability. Cleaning up these issues improves clarity.
https://github.com/ray-project/kuberay/issues/3384
=> [Refactor] Format API server Makefile for consistency

helm-chart/kuberay-operator/templates/deployment.yaml
The current deployment references the serviceAccount name as `.Values.serviceAccount`. However, since a helper function is already defined, we'll use the helper function for consistency.
=> [HELM] Fix serviceAccount name inconsistency in templates

apiserver/go.mod, apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go, apiserver/test/e2e/cluster_server_e2e_test.go, apiserver/test/e2e/config_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/job_submission_e2e_test.go, apiserver/test/e2e/service_server_e2e_test.go, apiserver/test/e2e/types.go, apiserver/test/e2e/utils.go
Refer to #3417 
On top of that, 
- Moved some help function from e2e test file to `utils.go`.
- Set testing polling interval to `500ms` (gomega's `eventually` polling interval default is `10ms`) to minimize to log size.
Closes #3417 
=> [Apiserver] Use Eventually from Gomega instead of wait from apimachinery

.buildkite/test-e2e.yml, .buildkite/test-kubectl-plugin-e2e.yml, .buildkite/test-sample-yamls.yml, .github/workflows/kubectl-plugin-release.yaml, .pre-commit-config.yaml, apiserver/Dockerfile, apiserver/go.mod, apiserver/pkg/util/error.go, experimental/Dockerfile, experimental/go.mod, kubectl-plugin/go.mod, proto/Dockerfile, proto/go.mod, ray-operator/Dockerfile, ray-operator/go.mod
Kuberay is using 1.23, with the latest version 1.24.
We should upgrade as soon as possible (but low priority tasks), in case s too much upgrade work to do when the gap becomes large.
- Updated the Golang version in every yaml file, `go.mod`, `Dockerfile`
- Fix the linter problem from `golangci-lint` in  `apiserver/pkg/util/error.go` 
Closes #3431 
=> [Feature] Upgrade golang version

apiserver/pkg/model/converter.go, apiserver/pkg/model/converter_test.go
1. Fix linting issues
2. Add a test case for `nil` input in `convertAutoscalingOptions`
3. Add a test for the `ImagePullPolicy` field in `PopulateWorkerNodeSpec`
4. Add unit tests for functions that convert slices of K8s-native CRD objects into KubeRay’s internal API representations:
* `FromCrdToAPIClusters`
* `FromKubeToAPIComputeTemplates`
* `FromCrdToAPIJobs`
To ensure high confidence in code quality before releasing the APIServer to the public, we aim to improve unit test coverage. Currently, the `pkg/model` package within the APIServer has low unit test coverage, as shown below:
After adding new tests above, the unit test coverage boosts from 74.7% to 79.3%.
https://github.com/ray-project/kuberay/issues/3316
=> [TEST] Improve unit test coverage for apiserver `pkg/model`

.github/dependabot.yml
Add a grouping for 'google.golang.org/*' to avoid inconsistency of library versions between sub-projects
Close #3445
Link: https://github.com/kenmcheng/kuberay/pull/16
=> Add a grouping for 'google.golang.org/*' to avoid inconsistency between sub-projects

apiserver/Dockerfile
To avoid downloading dependences after changing the source file, move `go mod download` up before copying source files.
In docker build, the cache depends on the previous layer. Which means the upper layer has changed, the following layers are subject to re-build.
Usually, the modification of deps is less frequent than the modification of source code. In the origin Dockerfile,
https://github.com/ray-project/kuberay/blob/37cf2acb58c901ca1a2af2a3348ac009764a177d/apiserver/Dockerfile#L9-L17
`go mod download` is after copying the go source. Once source files has changed. the docker build will re-run `go mod download` without leveraging the cache.
Thus, move `go mod download` before the copying the go source.
=> chore: move go mod download before copy source in Dockerfile

ray-operator/controllers/ray/utils/constant.go
The BaseWgetHealthCommand is used to configure readiness and liveness probes that Kubernetes will execute against the ray-worker container. These checks should return fairly quickly so that _Kubernetes_ can get the result and possibly retry them. By default, wget retries _20 times_. The retrying should be left to Kubernetes, not wget, so that the command doesn't just hang for minutes while Kubernetes waits for the result.
Fixes #3468 
=> Only try once in HTTP health check commands

.github/workflows/helm.yaml
Fix failed Helm lint and test CI due to the non-zero code returned by `grep`.
=> Fix: Helm lint and test CI failed

.buildkite/test-e2e.yml, ray-operator/test/support/test.go
#3109
I made the test fail to see if any artifacts would be generated — looks good!
Result:
https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/8147#01963f30-29e8-4225-be66-66a6efa0f516/1102-1161
Closes #3109
=> [CI] Upload logs as artifacts to BuildKite

kubectl-plugin/DEVELOPMENT.md, ray-operator/DEVELOPMENT.md
This whole repo was upgraded to 1.24 in
https://github.com/ray-project/kuberay/pull/3461
=> docs: update dev docs to use Golang 1.24

kubectl-plugin/pkg/cmd/job/job_submit.go
Remove the `filepath.Clean` for `workingDir` argument for `ray job submit` because it it not neccessary a filepath. It can be a remote URL or GCS address.
Before:
Note that it's `https:/`, not `https://`
After:
N/A
=> [Fix][kubectl-plugin] Remove filepath.Clean for ray job submit workingDir

kubectl-plugin/pkg/cmd/job/job_submit.go
As title. Pass the `--verbose` flag to `ray job submit` command.
N/A
=> [Feat][kubectl-plugin] Support -v flag for kubectl ray job submit

ray-operator/controllers/ray/expectations/scale_expectations.go
Explicitly wait for the pod to become "not found" instead of also relying on the deletion timestamp. This is because in the RayCluster reconciler, when we call `r.List(ctx, &workerPods, ...)`, we still get pods that are in the process of being deleted. However, since we don't check the deletion timestamp in our reconciler, we mistakenly treat these as running pods, which leads to incorrect deletion logic.
* Assume there are 5 running worker pods
* User requested to scale down to 4 pods
Before this PR:
* In the first reconcilation, there are no expectations, so `IsSatisfied` is `true`
https://github.com/ray-project/kuberay/blob/022ff0de8c1af20f8001f7927ea83c01b453d727/ray-operator/controllers/ray/raycluster_controller.go#L706
* We get running pods using `r.List` …
=> [Fix][Operator] Explictly wait for pod not found for satisfying the delete scale exectation

ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/test/sampleyaml/rayjob_test.go
When I set workerGroupSpecs.numOfHosts greater than 1, such as 2, the raycluster fails to transit Status.State to Ready, which would block RayJob from submitting as a side effect.
- In the `GetWorkerGroupDesiredReplicas`, `CalculateMinReplicas`, `CalculateMaxReplicas` function, I modified the way the count is calculated.
- Any other places that use `GetWorkerGroupDesiredReplicas` have also been updated.
- Refactored the `TestGetWorkerGroupDesiredReplicas`, `TestCalculateMinReplicas`, `TestCalculateMaxReplicas` test
Apply the following yaml file
- [Multi-Host ray cluster yaml](https://gist.github.com/CheyuWu/911a4868c10bfadbb86c872175ab00d3)
After applying the configuration, the result is shown below:
- [multi-host.ray-cluster.volcano-scheduler-queue.yaml](https://gist.github.com/CheyuWu/4a …
=> [Fix] RayCluster fails to transit Status.State to Ready when numOfHosts > 1

.github/workflows/image-release.yaml, .github/workflows/test-job.yaml
The current CI workflow is failing during the Docker setup step.
https://github.com/ray-project/kuberay/actions/runs/14908277500/job/41875886165?pr=3535
According to https://github.com/actions/runner-images/issues/11408#issuecomment-2621122468,  switch to using `docker/setup-docker-action@v4` instead of `docker-practice/actions-setup-docker@master`
=> [CI] Fix: /etc/docker/daemon.json: No such file or directory

kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/cmd/job/job_submit_test.go, ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
Currently, when using `InteractiveMode` in a `RayJob` and setting `backoffLimit` to a value greater than 1, the job's deployment status incorrectly transitions to `Running`. According to [this discussion](https://github.com/ray-project/kuberay/issues/3525#issuecomment-2848333674), `InteractiveMode` should not be used with `backoffLimit`.
To enforce this constraint, a validation check is added during job submission.
- Adds validation logic to prevent `backoffLimit` from being used with `InteractiveMode`.
In `func (options *SubmitJobOptions) Validate() error`:
Add the condition
```go
if submissionMode == rayv1.InteractiveMode && options.RayJob.Spec.BackoffLimit != nil {
return fmt.Errorf("BackoffLimit cannot co-exist with InteractiveMode")
}
```
`rayjob.yaml`
```yaml …
```
=> [Bug][kubectl-plugin] Wrong behavior for InteractiveMode RayJob with BackoffLimit set

ray-operator/test/e2e/raycluster_test.go
Add an end to end test to ensure #3520 fix the problem that all worker pods was added with `deletionTimestamps`
Closes #3533 
I've run the test suite for continuous 10 times without failure by running the following script under `kuberay/ray-operator`:
```bash
#!/bin/bash
for i in {1..10}; do
echo "Run #$i"
go test -timeout 30m -count=1 -v ./test/e2e -run 'TestRayClusterScalingDown'
done
```
```
=== RUN   TestRayClusterScalingDown
Modified Ray Image to: rayproject/ray:2.41.0-aarch64 for ARM chips
Modified Ray Image to: rayproject/ray:2.41.0-aarch64 for ARM chips
raycluster_test.go:171: [2025-05-08T00:15:34+08:00] Created RayCluster test-ns-gsrwk/raycluster-scaling-down successfully
raycluster_test.go:173: [2025-05-08T00:15:34+08:00] Waiting for RayCluster …
```
=> [RayCluster][Expectation] Add a test to ensure expectations work well during scaling down

apiserver/pkg/http/client.go, apiserver/pkg/manager/resource_manager.go, apiserver/pkg/server/serve_server.go, apiserver/test/e2e/service_server_e2e_test.go, proto/go_client/serve.pb.go, proto/kuberay_api.swagger.json, proto/serve.proto, proto/swagger/serve.swagger.json
This PR implements pagination for listing all ray services. 
- delete `ListAllServices` in resource_manager
- `ListAllRayServices` in serve_server reuses `ListAllServices ` in resource_manager
- An e2e test `TestGetAllServicesWithPagination` is added to validate the functionality.
- print service content or size for debugging purpose
```
~/Doc/G/kuberay/apiserver feature/pagi..all-services *6 !2 ?8 > go test -v ./test/e2e/...  -timeout 60m  -race 
-coverprofile ray-kube-api-server-e2e-coverage.out -count=1 -parallel 4 -run TestGetAllServicesWithPagination
=== RUN   TestGetAllServicesWithPagination
=== RUN   TestGetAllServicesWithPagination/Test_pagination_return_part_of_the_result_services
=== RUN   TestGetAllServicesWithPagination/Test_pagination_return_all_result_services
--- PASS: …
```
=> [apiserver] ListAllServices with pagination

.github/dependabot.yml
This PR is intended to mitigate the inconsistencies when dependabot submit a PR for version bump.
- kubernetes group: add a pattern of "sigs.k8s.io/*"
- add `github-dependencies` group for modules with "github.com/" prefix
- add `all-dependencies` group for miscellaneous modules
part of fixes of #3445 
=> Add more grouping to dependabot.yml to resolve inconsistencies when bumping versions

apiserver/test/e2e/cluster_server_e2e_test.go, helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/pkg/webhooks/v1/webhook_suite_test.go
in `RayCluster` CRD by marking it with `// +optional`.
Make it not serialized when empty with `omitempty`.
This change is backwards compatible on K8s clusters with existing
RayCluster CRD and RayCluster CRs.
* RayClusters with non-empty RayStartParams will serialize the same as
before this change.
* RayClusters with empty RayStartParams will serialize the same as
before this change: as an empty map, `{}` in YAML.
* New behavior: we can `kubectl create|apply` RayClusters that lack
RayStartParams in both head and worker groups. Previously the K8s API
would return validation errors requiring this field to be present.
When we get these RayClusters back with `kubectl get raycluster -o
yaml`, there's no `rayStartParams` field present.
See [Optional vs. Required][1] in K8s API Conventions doc.
> …
=> [refactor][operator]: make `RayStartParams` optional

apiserver/pkg/server/serve_server.go, apiserver/pkg/server/validations_test.go
=> [Feature] Add unit test for update service request validation

ray-operator/controllers/ray/common/pod_test.go
Testify has nicer semantics and is more concise.
=> refactor tests: use testify instead of Fatal

ray-operator/controllers/ray/utils/util_test.go
Test different cases that actually trigger different code paths under test instead of using different Ray custom resources. The test's call sites always pass `RayClusterSpec` so creating RayService and RayJobs is irrelevant.
Remove unnecessary type args when the type can be inferred.
=> chore operator: improve `TestIsAutoscalingEnabled` test

ray-operator/controllers/ray/utils/util_test.go
This PR combines `TestCalculateMinReplicas` and `TestCalculateMaxReplicas` into a single test `TestCalculateReplicas`, as both tests share similar logic and test cases. 
```
~/Doc/G/kuberay/ray-operator refector/fuse-tests *9 ?9 > go test -v ./controllers/ray/utils -run TestCalculateReplicas
=== RUN   TestCalculateReplicas
=== RUN   TestCalculateReplicas/Single_group_with_one_host
=== RUN   TestCalculateReplicas/Single_group_with_four_hosts
=== RUN   TestCalculateReplicas/Two_worker_groups:_one_with_a_single_host,_one_with_two_hosts
=== RUN   TestCalculateReplicas/Two_groups_with_suspended
--- PASS: TestCalculateReplicas (0.00s)
--- PASS: TestCalculateReplicas/Single_group_with_one_host (0.00s)
--- PASS: TestCalculateReplicas/Single_group_with_four_hosts (0.00s)
--- PASS: …
```
=> [refactor] Combine TestCalculateMinReplicas and TestCalculateMaxReplicas into a single test

clients/python-client/python_client_test/test_utils.py
This small PR removes the duplicated `test_delete_worker_group` in `python_client_test/test_utils.py`
=> test: remove duplicate delete worker group test

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/util/generation/generation.go, kubectl-plugin/pkg/util/generation/generation_test.go
[autoscaler docs]
<details>
<summary>Usage</summary>
```bash
$ kubectl ray create cluster sample-cluster --help | grep autoscaler
...
Flags:
...
--autoscaler enum                          autoscaler to use, supports: "none", "v1", "v2" (default none)
$ kubectl ray create cluster sample-cluster --autoscaler foo --dry-run
Error: invalid argument "foo" for "--autoscaler" flag: must be one of "none", "v1", or "v2"
$ kubectl ray create cluster sample-cluster --autoscaler none --dry-run
metadata:
name: sample-cluster
namespace: default
spec:
headGroupSpec:
dashboard-host: 0.0.0.0
template:
spec:
containers:
- image: rayproject/ray:2.41.0
name: ray-head
ports:
- containerPort: 6379
name: gcs-server
- containerPort: 8265
name: dashboard
- …
```
=> feat plugin: support enabling autoscaler both v1 and v2

clients/python-client/python_client/kuberay_cluster_api.py
Remove duplicateed `get_ray_cluster_status()` in `clients/python-client/python_client/kuberay_cluster_api.py`.
=> [Refactor] Remove duplicate definition of `get_ray_cluster_status`

ray-operator/controllers/ray/metrics/ray_job_metrics.go, ray-operator/controllers/ray/metrics/ray_job_metrics_test.go, ray-operator/main.go
This PR implement metric kuberay_job_info [proposed in 1.4.0](https://docs.google.com/document/d/1zNiE7lVZYjhrxlTbh1UXOVpR6hh1GIeSfCfE9Lt5v6Y/edit?tab=t.0).
```shell
$ curl -s localhost:8080/metrics | rg "kuberay_job_info"
kuberay_job_info{name="rayjob-fail-sample",namespace="test"} 1
kuberay_job_info{name="rayjob-sample",namespace="test"} 1
```
=> [SLI Metrics] Add metric kuberay_job_info

.github/workflows/consistency-check.yaml, .github/workflows/image-release.yaml, .github/workflows/test-job.yaml
to be consistent with `go.mod`s.
=> chore CI: use Go 1.24 everywhere

apiserver/hack/kind-cluster-config.yaml, ci/kind-config-buildkite.yml, ray-operator/DEVELOPMENT.md
1. Current instructions in `ray-operator/DEVELOPMENT.md` used `kindest/node:v1.24.0`, which cause some e2e test to fail due to the K8s version. 
This PR update the documented version to a minimal required one.
See #2970 for more info.
3. Current CI using latest K8s version, which doesn't align with the documented version. 
This PR explicitly sets K8s version in CI pipeline.
See discussion in https://github.com/ray-project/kuberay/issues/2970#issuecomment-2887133524 for more info.
Closes #2970
=> [Doc][CI] Align K8s version in Doc and CI with minimal required version

ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
See #3615 
Closes #3615 
command : 
```bash
go test -timeout 30m -v ./test/e2eautoscaler -run TestRayClusterAutoscalerGPUNodesForCPUTasks
```
result : 
=> [Test][Autoscaler] Add an E2E test for CPU tasks on GPU nodes.

apiserver/pkg/server/ray_job_submission_service_server_test.go, kubectl-plugin/pkg/cmd/create/create_cluster_test.go, kubectl-plugin/pkg/util/completion/completion_test.go, ray-operator/controllers/ray/common/association_test.go, ray-operator/controllers/ray/common/ingress_test.go, ray-operator/controllers/ray/common/rbac_test.go, ray-operator/controllers/ray/common/route_test.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/test/e2e/raycluster_gcs_ft_test.go
=> refactor tests: use testify instead of Fatal everywhere

.github/workflows/image-release.yaml
We need to push a git tag named `ray-operator/vX.Y.Z` to publish Go modules to https://pkg.go.dev/github.com/ray-project/kuberay/ray-operator?tab=versions
This reverts #3249.
=> [CI] fix missing Go module release step

ray-operator/controllers/ray/metrics/ray_cluster_metrics.go, ray-operator/controllers/ray/metrics/ray_cluster_metrics_test.go
Implement metric kuberay_cluster_provisioned_ready [proposed in 1.4.0](https://docs.google.com/document/d/1zNiE7lVZYjhrxlTbh1UXOVpR6hh1GIeSfCfE9Lt5v6Y/edit?tab=t.0).
```
❯ k apply -f config/samples/ray-cluster.sample.yaml
raycluster.ray.io/raycluster-kuberay-bug created
❯ k apply -f config/samples/ray-service.sample.yaml
rayservice.ray.io/rayservice-sample created
❯ k apply -f config/samples/ray-job.sample.yaml
rayjob.ray.io/rayjob-sample created
configmap/ray-job-code-sample created
kuberay_cluster_condition_provisioned{condition="false",name="raycluster-kuberay-bug",namespace="default"} 1
kuberay_cluster_condition_provisioned{condition="true",name="rayjob-sample-vdr5x",namespace="default"} 1
kuberay_cluster_condition_provisioned{condition="true",name="rayservice-sample-n28cg",namespace=" …
```
=> [SLI Metrics] Add metric kuberay_cluster_condition_provisioned

install/prometheus/install.sh, install/prometheus/overrides.yaml
Currently, we are making our Grafana dashboards, it makes me (and might be the same for end users) feel annoyed that we'll have to import Grafana dashboard json when trying to use them (There are six of them!). 
This PR allow users to auto load the json to grafana without further step, all can be done just by `install.sh`, improving user experience.
#3650
=> [Grafana] Allow auto-load dashboard jsons

ray-operator/test/e2erayservice/support.go
By changing the requests values, e2e upgrade tests can be successfully executed in Github Actions on a regular runner (otherwise the test fails due to insufficient CPU resources)
=> test: reduce requests in sample ray service yaml config

ray-operator/test/e2eautoscaler/check_placement_group_ready.py, ray-operator/test/e2eautoscaler/create_detached_placement_group.py, ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
This PR adds autoscaler e2e tests for basic placement group scenarios:
1. Test that the autoscaler can launch nodes for placement groups (STRICT_PACK, PACK, STRICT_SPREAD, SPREAD).
2. Test that the autoscaler can recover nodes for placement groups if nodes are dead.
Closes https://github.com/ray-project/kuberay/issues/3619
=> [Test][Autoscaler] Add an E2E test for placement groups

.buildkite/test-e2e.yml, ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go
- [TestRayClusterAutoscalerMinReplicasUpdate](https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/9295#0196fa36-b342-4938-a610-5b0c2a17d4a8)
```
raycluster_autoscaler_test.go:354:
Timed out after 300.000s.
Expected
<int32>: 4
to equal
<int32>: 5
```
- [TestRayClusterAutoscalerMaxReplicasUpdate/Create_a_RayCluster_with_autoscaling_enabled(Scale_up_maxReplicas_from_3_to_5)](https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/9298#0196faa6-dc79-4916-b021-75395686cfe7)
```
raycluster_autoscaler_test.go:443: 
Timed out after 600.000s.
Expected
<int32>: 4
to equal
<int32>: 5
```
- Given the recent failures in TestRayClusterAutoscalerMinReplicasUpdate and TestRayClusterAutoscalerMaxReplicasUpdate, it’s clear that tests involving scaling up to 5 worker pods are …
=> [CI] Fix autoscaler e2e test flakiness caused by timeout

install/prometheus/install.sh
Some users might using different version of Ray do so we should let user decide if they want to load dashboard automatically or not. So the flag is added.
Usage: `./install/prometheus/install.sh [--auto-load-dashboard true|false]`
https://github.com/ray-project/ray/pull/53256#issuecomment-2908057759
#3650 
=> [Grafana] Add flag for enabling auto load dashboards

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go, ray-operator/controllers/ray/utils/util.go, ray-operator/pkg/features/features.go
Provide a feature flag to enable the login bash command `-l` if needed. If feature flag is not enabled, it would not apply login bash. This provide the option for the end user to choose one. For example, the `uv` rely on `PATH` if enabling the login bash might overwrite `PATH` potentially.
Part of https://github.com/ray-project/kuberay/issues/3247
=> [Ray-operator] Feature flag login bash

ray-operator/config/samples/ray-cluster.overwrite-command.yaml, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
=> [refactor] Refactor enable login shell

ray-operator/controllers/ray/common/job.go
Closes #3561
My rayjob full yaml is 
```
kind: RayJob
metadata:
name: rayjob-sample
spec:
entrypoint: echo aaa ; python /home/ray/samples/sample_code.py
runtimeEnvYAML: |
pip:
- requests==2.26.0
- pendulum==2.1.2
env_vars:
counter_name: "test_counter"
rayClusterSpec:
rayVersion: '2.41.0' # should match the Ray version in the image of the containers
headGroupSpec:
rayStartParams: {}
template:
spec:
containers:
- name: ray-head
image: harbor.weizhipin.com/arsenal-oceanus/ray:2.41.0
ports:
- containerPort: 6379
name: gcs-server
- containerPort: 8265 # Ray dashboard
name: dashboard
- containerPort: 10001
name: client
resources:
limits:
cpu: "1"
requests:
cpu: "200m"
volumeMounts:
- mountPath: /home/ray/samples
name: code-sample
volumes:
- name: code-sample
configMap: …
```
=> Fix issue where unescaped semicolons caused task execution failures.

ray-operator/config/samples/ray-cluster.uv.yaml
In order to help users getting involved uv easier, provides this `ray-cluster.uv.yaml` as an example. It enables the runtime env hook so that `uv run ...` could work with runtime environment in the RayCluster, reference [uv + Ray: Pain-Free Python Dependencies in Clusters](https://www.anyscale.com/blog/uv-ray-pain-free-python-dependencies-in-clusters) for more information about this runtime env hook.
```
RAY_RUNTIME_ENV_HOOK=ray._private.runtime_env.uv_runtime_env_hook.hook
```
By the way, the `working_dir` is under `/home/ray` as default, which contains files. It might cause some errors during preparing runtime env because some limitations. Changing to folder `/home/ray/samples` could avoid this issue.
```
kubectl exec -it $HEAD_POD -- /bin/bash -c "cd samples && uv run --with emoji …
```
=> [Doc] add ray cluster uv sample yaml

ray-operator/test/e2eautoscaler/raycluster_autoscaler_part2_test.go, ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go, ray-operator/test/e2eautoscaler/support.go
This PR does the following:
1. Raise resource requests used in autoscaler e2e tests to avoid actors being killed.
2. Clean the previous cluster before going to the next sub-test.
Closes https://github.com/ray-project/kuberay/issues/3701
=> [Test][Autoscaler] deflaky unexpected dead actors in tests by higher resource requests

ray-operator/test/e2eautoscaler/raycluster_autoscaler_part2_test.go
Give [the test case](https://github.com/ray-project/kuberay/issues/3701#issuecomment-2926750602) more time to scale down.
The original flaky rate of this test is about 10% on my mac. Now it can pass 100 times without flaky.
```sh
▶ while go test -count=1 ./... -run=TestRayClusterAutoscalerV2IdleTimeout; do :; done
ok  	github.com/ray-project/kuberay/ray-operator/test/e2eautoscaler	96.222s
ok  	github.com/ray-project/kuberay/ray-operator/test/e2eautoscaler	94.784s
ok  	github.com/ray-project/kuberay/ray-operator/test/e2eautoscaler	94.683s
ok  	github.com/ray-project/kuberay/ray-operator/test/e2eautoscaler	94.702s
ok  	github.com/ray-project/kuberay/ray-operator/test/e2eautoscaler	93.944s
ok  	github.com/ray-project/kuberay/ray-operator/test/e2eautoscaler	94.898s
ok …
```
=> [Test][Autoscaler] deflaky autoscaler idle timeout e2e tests by a longer timeout

ray-operator/controllers/ray/rayjob_controller.go
If users run the latest ray-operator code from master branch without updating their RayJob CRD, the operator panics from a nil pointer dereference error in `rayjob_controller.go`. `rayJob.Status.RayJobStatusInfo.EndTime` is nil when a RayJob's Job fails with RayJob CRD from v1.3.2.
We check if `EndTime` is nil and return false from `checkTransitionGracePeriodAndUpdateStatusIfNeeded()` if so.
<details>
<summary>operator logs before shows panic</summary>
```
{"level":"info","ts":"2025-06-04T20:45:21.874Z","logger":"controllers.RayJob","msg":"RayJob","RayJob":{"name":"v6e-16-job","namespace":"hyperkube"},"reconcileID":"c00b3547-8723-4655-b41a-bd08125760db","JobStatus":"FAILED","JobDeploymentStatus":"Running","SubmissionMode":"K8sJobMode"} …
```
=> [fix][operator] RayJob.Status.RayJobStatusInfo.EndTime nil deref error

go.mod
I created an repo to do some experiments and found that we don't need to replace the `v0.0.0` string in release branch to make packages downloadable.
https://github.com/MortalHappiness/testgomodule
=> [Release] Reset ray-operator version in root go.mod to v0.0.0

ray-operator/config/samples/ray-cluster.persistent-redis.yaml
The indention is incorrect. The storageClass should be at the direct level under the spec.
Resolve 1.4.0 document release blocker
=> [Doc][Fix] correct the indention of storageClass in ray-cluster.persistent-redis.yaml

ray-operator/config/samples/ray-job.interactive-mode.yaml, ray-operator/test/sampleyaml/rayjob_test.go
There is no testing for [ray-job.interactive-mode.yaml](https://github.com/ray-project/kuberay/blob/v1.4.0-rc.1/ray-operator/config/samples/ray-job.interactive-mode.yaml)
```bash
$ helm repo update
$ helm install kuberay-operator kuberay/kuberay-operator --version v1.4.0-rc.1
$ kubectl apply -f ray-operator/config/samples/ray-job.interactive-mode.yaml
```
Closes #3778 
=> [Feat] Add e2e test for applying `ray-job.interactive-mode.yaml`

ray-operator/config/samples/pytorch-text-classifier/ray-job.pytorch-distributed-training.yaml
Fix errors for `ray-job.pytorch-distributed-training.yaml` by upgrading `pytorch-lightning` to 1.8.5.
Before:
After:
=> [Chore][Sample-yaml] Upgrade pytorch-lightning to 1.8.5 for `ray-job.pytorch-distributed-training.yaml`

helm-chart/kuberay-operator/README.md, helm-chart/kuberay-operator/values.yaml
We always set honorLabel = true when using serviceMonitor, so we modify value.yaml to set true as default.
=> [Helm Chart] Set honorLabel of serviceMonitor to `true`

.krew.yaml
As title.
The `sha256` should be indented, otherwise there will be yaml format error.
=> [Fix][Release] Fix Krew release indenetation error

scripts/changelog-generator.py
As title.
The original script failed to handle this case because 3553 is an issue, not PR
```
22852028 [ray-operator][Bug] Rayjob is Failed or Succeed, but Raycluster status(jobDeploymentStatus) is still Running(#3553) (#3642)
```
Because the commit message always look like `... (#XXX)`, we can simply extract the PR number by splitting by `#` without using regex.
Follow-up:
See if we can resolve those cherry-picked commits automatically.
=> [Fix] changelog-generator.py failed to parse some commit messages

ray-operator/controllers/ray/utils/httpproxy_httpclient.go
After getting response from ProxyActorHealth, the body is not used if the status is 200. It causes an unnecessary allocation.
Here are the simulation of code from benchmark. 
before:
after:
=> chore: reduce memory allocation on handling http response

kubectl-plugin/pkg/cmd/create/create_cluster.go, kubectl-plugin/pkg/cmd/job/job_submit.go, kubectl-plugin/pkg/util/validation.go, kubectl-plugin/pkg/util/validation_test.go
Follow the Kubernetes API  when user set the resources option without providing a value.
Before:
After:
=> [kubectl-plugin] Validate empty resouce quantity strings

ray-operator/test/e2eupgrade/rayservice_operator_upgrade_test.go
Enable upgrade to image built from source. if `KUBERAY_OPERATOR_UPGRADE_IMAGE` is not provided, empty default will be returned and the e2e upgrade will progress without any changes. In case of providing `KUBERAY_OPERATOR_UPGRADE_IMAGE` with tag `nightly`, operator will be upgraded to the nightly image built from source.
Note that in order for the test to work, image needs to be built and loaded into a kind cluster (by GH actions or equivalent workflow). 
=> test: enable upgrade to image built from source

ray-operator/test/e2erayservice/rayservice_ha_test.go, ray-operator/test/e2erayservice/rayservice_in_place_update_test.go, ray-operator/test/e2erayservice/rayservice_redeploy_test.go, ray-operator/test/e2erayservice/rayservice_upgrade_test.go, ray-operator/test/e2eupgrade/rayservice_operator_upgrade_test.go, ray-operator/test/sampleyaml/support.go, ray-operator/test/support/core.go, ray-operator/test/support/support.go
`CreateCurlPod` need to wait for pod is ready and running. put the waiting logic inside the function for easier to use.
Close https://github.com/ray-project/kuberay/issues/3613
=> [RayService][Test] create curl pod waiting until running

kubectl-plugin/test/e2e/kubectl_ray_log_test.go, kubectl-plugin/test/e2e/kubectl_ray_session_test.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
KubeRay 1.4.0 uses a deterministic name for the head pod. This, unfortunately, breaks the Autoscaler v2 for Ray < 2.48 after a head node restart under GCS FT configuration.
Based on https://github.com/ray-project/kuberay/issues/3868#issuecomment-3076305911, we shouldn't change the behavior in the operator based on the Ray version. Therefor, we decided to change the head pod back to non-deterministic.
- Change back to use non-deterministic head pod name
- Update tests for using non-deterministic head pod name
Closes #3868
=> [RayCluster] Make headpod name back to non-deterministic

kubectl-plugin/pkg/cmd/create/create_cluster.go
Should be `--head-node-selectors` instead of `--head-node-selector` and `--worker-node-selectors` instead of `--worker-node-selector`.
We also remove the first equals `=` delimiter for readability.
=> [kubectl-plugin] fix incorrect flag name in help message

ray-operator/config/samples/ray-service.deepseek.yaml
- Unpinned nightly build is not suitable for a long-term user-facing example
- Ray 2.48 isn't viable since it bundles vLLM version, 0.9.2, which includes https://github.com/vllm-project/vllm/issues/20647.
- The [fix](https://github.com/vllm-project/vllm/pull/20665) will land in the next vLLM release.
Resolve https://github.com/ray-project/kuberay/issues/3845.
=> Pin DeepSeek example to stable Ray release

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/tests/raycluster_test.yaml, helm-chart/ray-cluster/values.yaml
As title.
Enable `gcsFaultTolerance` and set `redisPassword` and `redisAddress` in RayCluster chart.
```yaml
gcsFaultTolerance:
enabled: true
redisAddress: "redis:6379"
redisPassword:
valueFrom: 
secretKeyRef:
name: redis-password-secret
key: password
```
```
helm install ray-cluster ./helm-chart/ray-cluster
```
Closes #3776
=> [Helm] Add gcsFaultToleranceOptions in RayCluster chart

ray-operator/config/webhook/manifests.yaml, ray-operator/pkg/webhooks/v1/raycluster_webhook.go, ray-operator/pkg/webhooks/v1/raycluster_webhook_test.go, ray-operator/pkg/webhooks/v1/rayjob_webhook.go, ray-operator/pkg/webhooks/v1/rayjob_webhook_test.go, ray-operator/pkg/webhooks/v1/rayservice_webhook.go, ray-operator/pkg/webhooks/v1/rayservice_webhook_test.go, ray-operator/pkg/webhooks/v1/suite_test.go
when the Ray resource is created or updated. For users who opt into installing the webhooks, this validation makes the K8s API fail the resource creation or update request immediately in a synchronous way that's more obvious.
We refactor the RayCluster webhook to use the same validation functions that the RayCluster controller uses. We also add tests for RayJob and RayService webhooks.
follow up to https://github.com/ray-project/kuberay/pull/3083#issuecomment-2694462235
=> [feat][operator] validate Ray resource metadata in webhook

ray-operator/test/e2e/raycluster_gcs_ft_test.go, ray-operator/test/e2e/support.go, ray-operator/test/e2eautoscaler/raycluster_autoscaler_part2_test.go, ray-operator/test/support/redis.go
This PR adds e2e tests for autoscaler v1 and v2 with GCS FT enabled.
Also, moves Redis-related functions to an upper level for sharing. 
Closes https://github.com/ray-project/kuberay/issues/3878
=> [Test] add e2e tests for autoscaler v1 and v2 with GCS FT

helm-chart/ray-cluster/README.md, ray-operator/test/e2eautoscaler/raycluster_autoscaler_part2_test.go, ray-operator/test/support/support.go
=> Add a test util function for killing the head Pod and wait

ray-operator/test/e2e/raycluster_gcs_ft_test.go
=> Use DeletePodAndWait in e2e test

apiserversdk/config.go, apiserversdk/proxy.go, apiserversdk/proxy_test.go
Add retry logic and timeout to apiserver v2:
1. Timeout is set to long timeout (30 seconds) to prevent unbounded request
2. The retry logic determines if a http status code is retryable
Wrap errors with more informations
Closes #3606 
=> [apiserver] Add retry and timeout to apiserver V2

config/grafana/KubeRay-Operator.json
Change the title of RayServices section in Grafana Dashboard json to improve readability.
The reason is to accurately reflect its query, `count(kuberay_service_info) by (namespace)`, which counts existing RayService instances.
None
=> Update RayServices section title in Grafana Dashboard json

ray-operator/test/e2erayservice/support.go, ray-operator/test/e2eupgrade/rayservice_operator_upgrade_test.go, ray-operator/test/e2eupgrade/support.go
test: add worker pod to upgrade tests for stability
This change would allow to unblock flaky/ unsuccessful upgrade test runs on github runner. While the tests in current form work fine locally/ on a ubuntu ec2 instance, they fail consistently, when executed on github runner
=> test: add worker pod to upgrade tests for stability

ray-operator/test/e2erayservice/rayservice_ha_test.go, ray-operator/test/e2erayservice/support.go, ray-operator/test/e2erayservice/testdata/rayservice.deletiondelay.yaml
- Add e2e test for validating if the `deletionDelaySeconds` set in rayService work
We enabled setting RayClusterDeletionDelaySeconds in RayService CRD in PR https://github.com/ray-project/kuberay/pull/3864. While this is a public API and user-facing behavior change, we should add an e2e test for it
=> [Feature] Add e2e test for setting RayCluster deletion delay in RayService

apiserversdk/docs/migration.md
- To prepare users for v1 to v2 transition early, clarify key differences, and align with community plans for stage-2 development.
- https://docs.google.com/document/d/1DprqE46H_IiljeY_w4M5pZVCVPANg8ZfrL1Fy77sSH0/edit?usp=sharing
Closes #3607
=> [apiserver] Add migration doc from v1 to v2

ray-operator/Makefile
Environment:
•	macOS: `15.3.1`
•	Architecture: `arm64`
When running the following commands:
```
cd ray-operator
make kustomize
./bin/kustomize
```
The `kustomize` process is immediately killed with no error message.
Install the latest kustomize version.
https://github.com/kubernetes-sigs/kustomize
=> fix: kustomize download fails for Apple Silicon (arm64) architecture

apiserver/test/e2e/apiserversdk/types.go, apiserver/test/e2e/apiserversdk/utils.go, apiserver/test/e2e/types.go
We discovered the flakiness for APIServer e2e test, which occurs in following two places:
1. ` TestGetRayClusterProxy` timeout [here](https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/10242/steps/canvas?jid=019865a8-79fb-4305-ace3-bb4e70a44c50)
2. Duplicate namespace are generated and used between different test cases, causing RayCluster creation error in `TestListClusters` [here](https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/10301/steps/canvas?jid=0198968c-640d-48bc-8546-0eb51eaf43c4)
We made following changes:
1. Increase timeout from 1 minute to 3 minutes in `waitForClusterConditions`, which is used in `TestGetRayClusterProxy`
2. Add `time.Unix` after the namespace name to ensure uniqueness 
=> [Test] Fix Apiserver flaky test

ray-operator/controllers/ray/rayjob_controller.go
We shouldn’t print “`Both RayCluster and the submitter K8s Job are created`” when using HTTP mode, since currently we don’t create a K8s job in HTTP mode.
=> fix: add missing logging for RayJob HTTP mode status transition

ray-operator/config/manager/manager.yaml
This PR adds a `seccompProfile` set to `RuntimeDefault` in the KubeRay operator Deployment manifest at both the pod and container levels.
This change resolves Pod Security Standards (PSS) warnings observed in Kubeflow deployments by ensuring the operator runs with the recommended seccomp configuration. This aligns with Kubernetes security best practices and improves compliance in restricted environments.
- part of https://github.com/kubeflow/manifests/pull/3200
=> Add seccompProfile to KubeRay operator deployment for PSS compliance

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/suite_test.go, ray-operator/main.go
- It makes more sense for `BatchSchedulerManager`  to be part of the reconciler options, since it is clearly an optional configuration.
- In order to integrate batchScheduler with RayJob (and also Ray Service in the future), RayJob reconciler need to know the info of `BatchSchedulerManager`.
For these reasons, I suggest moving ‎`BatchSchedulerManager` into the reconciler options, creating it in main.go, and passing it to any controller that requires it.
=> Move `BatchSchedulerManager` into reconciler option

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_unit_test.go, ray-operator/controllers/ray/utils/resources.go, ray-operator/controllers/ray/utils/resources_test.go
`desiredGPU` count is incorrect when using MIGs like `nvidia.com/mig-2g.20gb`
Closes #3925
=> Correct `sumGPUs` to include MIGs in count

ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go
Some http method already uses constant, some doesn't. This PR replace the http method string to http method constant for consistency.
=> [Dashboard-client] replace http method from string to constant

ray-operator/controllers/ray/utils/dashboard_httpclient.go
Some `io.ReadAll` in dashboard client is missing error checking, so this PR add error handling for them.
=> [Dashboard-client] Add proper error checking in dashboard client

experimental/Makefile
The current `experimental/Makefile` uses `-s $(CMD)` to check whether
tool binaries (e.g., `golangci-lint`, `go-bindata`) exist.
However, `-s` is not a valid shell command, and running the Makefile produces:
`bash: s: command not found`
This breaks the development tool installation workflow.
This PR replaces `-s $(CMD)` with the correct check:
```make 
test -s $(CMD) || <install command>
```
This ensures the Makefile properly verifies whether the binary exists
and installs it if missing. The fix also makes the Makefile consistent
with the style used in other parts of the KubeRay repo.
- Ran `make dev-tools` locally after the change.
- Verified that:
- `golangci-lint` and `go-bindata` are correctly installed into `bin/` if missing.
- No `bash: s: command not found` errors appear.
- …
=> [Experimental] Fix Makefile tool check: replace `-s` with `test -s`

ray-operator/controllers/ray/rayjob_controller.go
Remove unnecessary logger.Info statements in RayJobReconciler.Reconcile that duplicate status transitions already reflected in rayJobInstance.Status.JobDeploymentStatus.
=> [RayJob] remove redundant RayJob status-transition logs in reconciler

ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
This PR adds validation to prevent configuration inconsistency when using Ray autoscaler v2.
- Add validation to prevent setting RAY_enable_autoscaler_v2 to '1' or 'true' when enableInTreeAutoscaling is false
- This prevents Ray head failure due to configuration mismatch
- Add corresponding test cases for the new validation logic
Previously, users could manually set RAY_enable_autoscaler_v2 environment variable without enabling enableInTreeAutoscaling, which would cause Ray head to fail.
Add validation in KubeRay to forbid setting RAY_enable_autoscaler_v2 to '1' or 'true' without enableInTreeAutoscaling: true.
- Added test cases for the new validation logic
- All existing tests pass
- Manual testing with invalid configurations shows proper error messages
=> Add validation for RAY_enable_autoscaler_v2 environment variable

ray-operator/controllers/ray/batchscheduler/kai-scheduler/kai_scheduler.go
Thanks @win5923 for pointing out https://github.com/ray-project/kuberay/pull/3948#discussion_r2298432267 that we should include reconcile ID when using logger, so instead of storing logger in kai-scheduler we should create new one with context so the the reconcile ID will be include.
Before:
After:
As image shown, the latter had reconcileID":"5ec43f18-2a15-4df8-84b0-d1505e0608df and more hierarchical logger name `controllers.RayCluster.kai-scheduler`
=> Use ctrl logger and create logger in function in kai-scheduler

ray-operator/controllers/ray/batchscheduler/kai-scheduler/kai_scheduler.go
Quick follow up for #3995 , remove the app.name (rayCluster) in logger since logger already include rayCluster.
=> Remove unecessary raycluster log in kai-scheduler logger

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/utils/util.go
This is a follow up for #3992.
=> Follow up 3992: Remove logs and add comments

ray-operator/main_test.go
1. Add test  for case `set QPS and Burst`
2. Add test for case `set Burst using float`
https://github.com/ray-project/kuberay/issues/2367
=> [Follow Up][Test] Support to set QPS and burst by configuration

helm-chart/kuberay-operator/templates/_helpers.tpl, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go
Remove checking CRD in Volcano scheduler initialization so that the operator doesn’t need permission to view CRDs. See https://github.com/ray-project/kuberay/pull/3785#discussion_r2193331350 for more context
Also Remove the duplicate import `"volcano.sh/apis/pkg/apis/scheduling/v1beta1"`
Install Volcano and kuberay-operator
```
$ kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
$ helm install kuberay-operator --set image.repository=kuberay/operator --set image.tag=nightly --set batchScheduler.name=volcano  ../helm-chart/kuberay-operator
```
1. Create a queue with a capacity of 4 CPUs and 6Gi of RAM
```yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
name: kuberay-test-queue
spec:
weight: 1
capability:
cpu: …
```
=> [Feature] Remove checking CRD in Volcano scheduler initialization

ray-operator/apis/config/v1alpha1/configuration_types.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/suite_test.go, ray-operator/controllers/ray/utils/fake_httpproxy_httpclient.go, ray-operator/controllers/ray/utils/httpproxy_httpclient.go, ray-operator/controllers/ray/utils/util.go
Similiar to #3992 , removed the ctrl pkg from `httpproxy_httpclient.go`
=> [refactor][5/N]  Refactor `httpproxy_httpclient.go`

helm-chart/kuberay-operator/templates/_helpers.tpl, ray-operator/config/rbac/role.yaml, ray-operator/controllers/ray/common/rbac.go, ray-operator/controllers/ray/raycluster_controller.go
This PR adds `pods patch` and `pods/resize patch` rbac permissions to KubeRay operator and the generated service account for RayClusters. This will allow the Ray autoscaler to perform IPPR.
=> [RayCluster] grant pods and pods/resize patch permissions for IPPR

docs/reference/api.md, ray-operator/Makefile
Reverts ray-project/kuberay#4029, since we have to support go 1.24.6 first, then we can bump crd-ref-docs to v0.2.0
https://github.com/ray-project/kuberay/blob/3858146ac12efee0ee383443b3aeb387646034c0/ray-operator/go.mod#L3
=> Revert "Bump crd-ref-docs to v0.2.0 for Go 1.24+ compatibility"

.buildkite/test-e2e.yml, .buildkite/test-kubectl-plugin-e2e.yml, .buildkite/test-sample-yamls.yml
=> [CI] Use golang:1.24-bookworm (Debian 12) in CI for Python-3.11 support (#3949)

clients/python-client/python_client/kuberay_cluster_api.py
For the `RayClusterApi` in the python-client, if you're running it within a pod in a K8s cluster, it cannot find the kube_config and so none of the API methods work. This checks for the kube_config and if not fount, tries to load the in-cluster config. 
N/A
=> feat[python-client]: add support for loading kubeconfig from within pod

clients/python-client/python_client/kuberay_job_api.py, clients/python-client/python_client_test/helpers.py, clients/python-client/python_client_test/test_cluster_api.py, clients/python-client/python_client_test/test_job_api.py, clients/python-client/python_client_test/test_utils.py
The RayJob API for the python client had no functionality to suspend, resubmit, or delete a RayJob CR. Also, the status reporting would report the status as unknown when a descriptive status could be retrieved from the `jobDeploymentStatus`.
N/A
Prerequisite:
* Kind cluster running
* Kuberay Operator installed
From your terminal build a new whl file
```bash
cd clients/python-client/
poetry build
```
In a jupyter notebook with the whl file in your current dir
```
%pip install ./python_client-0.0.0.dev0-py3-none-any.whl --force-reinstall
```
Define the RayJob body
```python
from python_client import kuberay_job_api, constants
job_body = {
"apiVersion": constants.GROUP + "/" + constants.JOB_VERSION,
"kind": constants.JOB_KIND,
"metadata": {
"name": "test-job",
"namespace": "default", …
```
=> [feat][python-client]: Add suspend, resubmit, & delete logic, and improve status reporting in python client

ray-operator/controllers/ray/utils/validation.go, ray-operator/controllers/ray/utils/validation_test.go
ClusterSelector with SidecarMode requires injecting a sidecar container into an already running Pod. However, Kubernetes does not natively support adding new containers to Pods that are already running.
Before:
The sidecar mode's RayJob CR will keep running but didn't actually submit the job.
```yaml
kind: RayJob
metadata:
name: rayjob-use-existing-raycluster
spec:
submissionMode: "SidecarMode"
entrypoint: python -c "import ray; ray.init(); print(ray.cluster_resources())"
clusterSelector:
ray.io/cluster: rayjob-sidecar-mode-czhkm
```
After:
failed the job. (After Nary's PR: https://github.com/ray-project/kuberay/pull/3981
https://github.com/ray-project/kuberay/issues/3928
=> [RayJob] ClusterSelector shouldn't support SidecarMode

ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler_test.go, ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_task_groups.go
The yunikorn batchscheduler didn't respect gang scheduling. This PR make it take `numOfHosts` into account so that the yunikorn could schedule the entire RayCluster as a whole.
Closes https://github.com/ray-project/kuberay/issues/4073
=> [RayCluster] yunikorn batchscheduler respect gang scheduling

ray-operator/config/samples/ray-cluster-agc-gatewayapi.yaml
This PR adds an example on how to leverage [Application Gateway for Containers (AGC)](https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview) as an ingress for ray clusters
Example yaml file added to enable AGC as in ingress to Ray Clusters. This is an example for PR: https://github.com/ray-project/ray/pull/56574
=> AGC gateway api example

ray-operator/config/samples/ray-service.sample.yaml
The head node of [the rayservice sample](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-service.sample.yaml) typically uses around 3.5GB of memory, as shown in the image below. With the current settings (2GB), this can lead to **OOM**. We should increase the memory limit to prevent this issue.
=> [Doc] Increase head node memory limit for RayService sample to avoid OOM

dashboard/src/components/ClustersTable/ClustersTable.tsx, dashboard/src/components/JobsTable/JobsTable.tsx
[Spec](https://docs.google.com/document/d/1rSDVEsCXPKYNupmfaZw8ywW8XcSrlo5SrgU0gV9pxDs/edit?tab=t.0)
In the KubeRay Dashboard, the Grafana icon in the cluster table currently has no functionality if the Grafana link is not configured. This may confuse users since the icon appears clickable but leads nowhere.
- If the Grafana link is not provided, the Grafana icon should be hidden from the dashboard table.
- If the Grafana link is configured, the icon should remain visible and functional.
Launch api server and frontend server
```bash
$ go run cmd/main.go -httpPortFlag :31888 -cors-allow-origin=*
$ yarn dev
```
Upload the rayjob sample
```bash
$ kubectl apply -f ray-operator/config/samples/ray-job.sample.yaml
```
Check the rayjob dashboard
Check the raycluster dashboard
The Grafana …
=> [Feature] [KubeRay Dashboard] hidden the grafana dashboard if link is not provided

dashboard/src/components/ClearableSelect.tsx, dashboard/src/components/FrontendTable/FrontendTableToolbar.tsx
Currently, when selecting a filter status from the dropdown, the filtering works correctly but the selected status is not displayed as the current filter.
Launch the frontend and api server
```console
$ go run cmd/main.go -httpPortFlag :31888 -cors-allow-origin=*
$ yarn dev
```
Closes #4107 
=> [Fix] [KubeRay Dashboard] The current filter status is not shown in the status filter 
