ray-project/kuberay

msft-operator/ray-operator/.gitignore, msft-operator/ray-operator/Makefile, msft-operator/ray-operator/config/manager/manager.yaml, msft-operator/ray-operator/config/quota/priority.yaml, msft-operator/ray-operator/config/quota/quota.yaml, msft-operator/ray-operator/config/rbac/role_binding.yaml, msft-operator/ray-operator/config/samples/ray-cluster.complete.yaml, msft-operator/ray-operator/config/samples/ray-cluster.mini.yaml, msft-operator/ray-operator/controllers/common/pod.go, msft-operator/ray-operator/controllers/common/service.go, msft-operator/ray-operator/controllers/raycluster_controller.go, msft-operator/ray-operator/controllers/raycluster_controller_test.go, msft-operator/ray-operator/controllers/utils/util.go, msft-operator/ray-operator/controllers/utils/util_test.go, msft-operator/ray-operator/go.sum
The deletion of workers has only been allowed through a scaleStrategy where the specific names of the pods to be removed has to be defined.
This PR keeps that logic, but adds the ability to remove random workers if the scaleStrategy does not define any specific pods.
E.g. if current running worker pods in a group is `5`
and you modify the `replicas = 3` with only 1 pod in the scaleStrategy, e.g.
```
scaleStrategy:
workersToDelete:
- raycluster-complete-worker-small-group-bdtwh
```
Then the second to be removed will be randomly selected by the ray operator
=> allow deletion of workers

bytedance/CONTRIBUTING.md, bytedance/Makefile, bytedance/README.md, bytedance/cmd/main.go, bytedance/config/crd/bases/ray.io_rayclusters.yaml, bytedance/config/manager/controller_manager_config.yaml
1.  Fix leader election failure that controller can not start with `--leader-elect`
2. Fix CRD too long issue. This is a known issue. See https://github.com/kubernetes-sigs/kubebuilder/issues/1140 for more details
3. Add README.md and CONTRIBUTING.md
=> Fix leader election failure and crd too long issue

msft-operator/ray-operator/Dockerfile
Building `msft-operator` with current `Dockerfile` gives the error:
```
go: error loading module requirements
```
Upgrading from go 1.12 to 1.15 resolves the issue.
=> Upgrade to go 1.15

ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray-cluster.mini.yaml
1. update `ray-cluster.mini.yaml`
- There was an issue when using current `ray-cluster.mini.yaml`. So, I've changed to specify name for each port and add 10001 port to use external python client
- https://github.com/ray-project/kuberay/issues/42#issuecomment-931015809
2. update `ray-cluster.heterogeneous.yaml`
- The original `ray-cluster.heterogeneous.yaml` doesn't work in raw. So I changed some fields to make it work.
- I'll specify each line with some screenshots.
Please take a look and give some feedback :)
=> Fix issues in heterogeneous sample

ray-operator/Makefile, ray-operator/config/crd/bases/ray.io_rayclusters.yaml
The objectmeta in template is always nill. It is related to `controller-tools`.
https://github.com/kubernetes-sigs/controller-tools/issues/448
=> fix missing template objectmeta

ray-operator/config/samples/config-map-ray-code.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.getting-started.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray-cluster.mini.yaml
1. Update configmap
1. Rename the script to avoid a "`ray has no attribute init`" issue [1]
2. Fix `services.get_node_ip_address`
3. Change `ray_nodes` dir to avoid a `Permission error`
2. Update yaml
1. Bump rayVersion to `1.8.0`
2. Bump ray image version to `1.8.0`
3. Change command: `sleep infinity`
4. Add a comment on `init-myservice`'s command
[1]:
```
trying to connect to Ray!
Traceback (most recent call last):
File "/opt/code.py", line 1, in <module>
import ray
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/__init__.py", line 91, in <module>
import ray._raylet  # noqa: E402
File "python/ray/_raylet.pyx", line 118, in init ray._raylet
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/runtime_env/validation.py", line 11, in <module>
from …
```
=> Update samples yaml

docs/design/protobuf-grpc-service.md
Per Ali's request in https://github.com/ray-project/kuberay/pull/93, It's better to write a one page summary about the proposed change and get it approved before any implementation.
#53 #54 
/cc @akanso @chenk008 @caitengwei @chaomengyuan 
=> Add core API and backend service design doc

proto/cluster.proto, proto/config.proto, proto/error.proto
Part of #53 #82 
This is just api definition and we will test changes later with business logic together
=> [proto] Add core api definitions as protobuf message

.github/workflows/test-job.yaml
fix #115. with the change, we can fix the CI issue.
#115 
=> Pass --timeout option to golangci-lint

.github/workflows/test-job.yaml, apiserver/cmd/main.go, apiserver/pkg/interceptor/interceptor.go, apiserver/pkg/manager/client_manager.go, apiserver/pkg/server/cluster_server.go, ray-operator/Makefile
=> enable goimport and add new makefile target to only build image without test

apiserver/cmd/main.go, apiserver/pkg/manager/resource_manager.go, apiserver/pkg/model/converter.go, apiserver/pkg/server/cluster_server.go, apiserver/pkg/server/compute_template_server.go, apiserver/pkg/util/cluster.go, apiserver/pkg/util/config.go
Implement the gPRC service and provide the interface for cluster CRUD operations.
#87 
- [] Unit tests
=> Implement resource manager and gRPC services

README.md, apiserver/deploy/base/apiserver.yaml, manifests/README.md, manifests/base/kustomization.yaml, manifests/cluster-scope-resources/kustomization.yaml, manifests/cluster-scope-resources/namespace.yaml, manifests/cluster-scope-resources/params.yaml, ray-operator/config/default/kustomization.yaml, ray-operator/config/default/namespace.yaml, ray-operator/config/manager/manager.yaml
Address #114. With this change, it's much easier for user to bring up the KubeRay in their environments. 
#114 
=> Add quick start deployment manifests

docs/troubleshooting.md
A troubleshooting guide for mismatch python version.
#148 
=> Add troubleshooting guide for ray version mismatch

.github/workflows/test-job.yaml, apiserver/cmd/main.go, apiserver/pkg/client/cluster.go, apiserver/pkg/interceptor/interceptor.go, apiserver/pkg/manager/resource_manager.go, apiserver/pkg/util/error.go, cli/cmd/root.go, cli/go.mod, cli/go.sum, cli/pkg/cmd/cluster/create.go, cli/pkg/cmd/template/compute/create.go, cli/pkg/cmdutil/client.go, ray-operator/api/raycluster/v1alpha1/raycluster_types_test.go, ray-operator/controllers/common/ingress.go, ray-operator/controllers/common/ingress_test.go, ray-operator/controllers/common/pod_test.go, ray-operator/controllers/common/service_test.go, ray-operator/controllers/raycluster_controller_test.go
1. Introduce gofmt github action
2. Move goimports from build job to lint job
3. Run gofmt -s -w to simplify test codes
last piece of https://github.com/ray-project/kuberay/issues/76
https://github.com/ray-project/kuberay/issues/76
=> Enable gofmt and move goimports to linter job

ray-operator/main.go
The flag `watch-namespace` specify a namespace which will be wathced. By default it is empty, all namespaces will be watched.
=> [Feature] Add flag `watch-namespace`

ray-operator/Makefile, ray-operator/main.go
Add subcommand to print version, commit id, build time. It can help user to troubleshoot.
Closes https://github.com/ray-project/kuberay/issues/137
=> [Feature]Add subcommand `--version`

ray-operator/config/rbac/role.yaml, ray-operator/controllers/raycluster_controller.go
Leader election need lease permissions, otherwise it will failed
```
cannot get resource "leases" in API group "coordination.k8s.io"
```
=> [Bug]Leader election need lease permission

cli/cmd/root.go
We need to ignore `ConfigFileAlreadyExistsError` when write to config, otherwise it will panic.
Closes #https://github.com/ray-project/kuberay/issues/171
=> [CLI] check viper error

.gitignore, ray-operator/config/rbac/role.yaml, ray-operator/config/samples/ray-cluster.autoscaler.debug.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/controllers/common/constant.go, ray-operator/controllers/common/pod.go, ray-operator/controllers/common/pod_test.go, ray-operator/controllers/common/rbac.go, ray-operator/controllers/raycluster_controller.go, ray-operator/controllers/utils/util.go
With this change, user doesn't have to manually configure service account/role/role binding etc and user can also save effort to configure autoscaler container. What user just need to do is configure `enableInTreeAutoscaling: true` in their cluster spec.
Address
- https://github.com/ray-project/kuberay/issues/28
Related 
- https://github.com/ray-project/ray/pull/21086
- https://github.com/ray-project/ray/pull/22348
=> Support in-tree autoscaler

proto/Dockerfile, proto/Makefile, proto/README.md, proto/hack/generate.sh
1. Add instructions in README.md
2. Add proto-generator image and hack scripts
With this change, user doesn't need to pollute their environment for proto generation. Everything is done inside the container and it's every clean, easy and consistent.
Address https://github.com/ray-project/kuberay/issues/84
=> Use container to generate proto files

helm-chart/kuberay-operator/templates/role.yaml
Updates RBAC rules in the Helm template to match those generated by the Operator Framework based on the application code.
The update was initially needed because after deploying the `kuberay-operator` nightly build, its service account was unable to access `leases` in the `coordination.k8s.io` API group. Further investigation revealed that the Helm manifest was even further outdated, which is fixed by this PR.
Fixes #174 
=> Helm: ensure RBAC rules are up to date with the latest autogenerated manifest

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
Currently, `tolerations` and `nodeSelector` specified in the `values.yaml` are not being passed to the Helm deployment. This PR fixes that.
=> Support scheduling constraints in Helm-deployed clusters

ray-operator/config/rbac/role.yaml
There's a type in cluster role and I didn't notice this because I used docker for desktop. After I change to kind, the problem surfaces
=> Fix serviceaccount typo in operator role

docs/best-practice/worker-head-reconnection.md
To correct tiny mistake in the documents
=> docs: Fix typo in best practice

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
Currently the Helm chart offers no way of pulling images from a private registry. This PR adds such functionality.
=> Helm: support imagePullSecrets for ray clusters

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
It is often useful to populate the container environment with values specified as Kubernetes secrets or configmaps, using the `envFrom` key of the pod spec. For example, we use this technique to provide database credentials to our pods.
This PR implements such functionality for Ray clusters deployed with Helm.
=> Support envFrom in rayclusters deployed with Helm

README.md, apiserver/README.md, apiserver/deploy/base/apiserver.yaml, cli/README.md, helm-chart/kuberay-operator/README.md, helm-chart/kuberay-operator/templates/leader-role.yaml, helm-chart/kuberay-operator/templates/leader-rolebinding.yaml, helm-chart/kuberay-operator/values.yaml, ray-operator/DEVELOPMENT.md, ray-operator/config/manager/manager.yaml, ray-operator/config/rbac/leader_election_role.yaml, ray-operator/config/rbac/leader_election_role_binding.yaml, ray-operator/config/rbac/role.yaml, ray-operator/config/rbac/role_binding.yaml, ray-operator/config/rbac/service_account.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.getting-started.yaml, ray-operator/config/samples/ray-cluster.mini.yaml
1. Unify the names in manifests
2. Fix not working examples
3. Update README.md
=> Manifests and docs improvement  for prerelease 

cli/Makefile
It's hard to manage cli version without build scripts. This Makefile help to generate cli with correct version information.
=> Add Makefile for cli project

cli/Makefile, manifests/base/kustomization.yaml
Pin manifests to v0.2.0 and I will cut tag later. 
[](https://github.com/ray-project/kuberay/issues/193)
=> Pin release tag to v0.2.0

ray-operator/main.go
Now the ray-operator print log like:
```
1.647951526734085e+09   INFO    setup   the operator    {"version:": ""}
```
it is a bit poor readable.
This change tries to make log time readable like:
```
2022-03-22T20:17:16.707+0800    INFO    setup   the operator    {"version:": ""}
```
=> [ray-operator]Make log timestamp readable

apiserver/pkg/client/cluster.go, apiserver/pkg/client/kubernetes.go
Currently when we create kubernetes client, it will check if it is running in K8s' pod. And this logic is implemented in `sigs.k8s.io/controller-runtime/pkg/client/config`. Additional the `controller-runtime` support enviroment KUBECONFIG .
The official tool can help to simplify the code.
=> Simplify k8s client creation

.github/workflows/release.yaml, helm-chart/kuberay-operator/README.md, helm-chart/ray-cluster/README.md
Allows running helm (e.g. in Terraform) without having to clone this repo
Ported from https://github.com/ray-project/ray/pull/22799
=> Add CD for helm charts

.github/workflows/actions/compatibility/action.yaml, .github/workflows/test-job.yaml
Run compatibility tests in parallel to save time
#159
=> run compatibility in parallel using multiple workflows

ray-operator/controllers/common/service.go
We need to use the utils.CheckLabel() function when creating a K8s service
#220 
=> adding label check

.github/workflows/site.yaml, docs/components/apiserver.md, docs/components/cli.md, docs/components/operator.md, docs/deploy/helm-cluster.md, docs/deploy/helm.md, docs/deploy/installation.md, docs/guidance/ingress.md, docs/index.md, mkdocs.yml, ray-operator/README.md
1. Use Material for MkDocs to generate a site
2. Add ci job for site rendering
3. Create soft links for operator,apiserver and cli components
4. Add some new pages to enrich content of the new site
Some README.md are soft links
```
ln -s  ../../ray-operator/README.md operator.md
ln -s ../../apiserver/README.md apiserver.md
ln -s ../../cli/README.md cli.md
```
This PR help create a Github site that organize all the existing docs together. This help user to easily onboard KubeRay project. 
https://github.com/ray-project/kuberay/issues/212
=> Build KubeRay Github site

ray-operator/controllers/common/service.go, ray-operator/controllers/raycluster_controller.go
A not found error in the context of a delete or update operation is possible if the user for example deletes the RayCluster while the operator is trying to update it.
This PR suppresses those errors and only logs them 
=> suppress not found errors into regular logs

helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/values.yaml
Add values for custom op's probe seconds
=> Helm: supports custom probe seconds

apiserver/cmd/main.go, apiserver/pkg/util/cluster.go, apiserver/pkg/util/time.go, ray-operator/api/raycluster/v1alpha1/raycluster_types.go, ray-operator/api/raycluster/v1alpha1/raycluster_types_test.go, ray-operator/controllers/common/pod.go, ray-operator/controllers/common/pod_test.go, ray-operator/controllers/raycluster_controller.go, ray-operator/controllers/raycluster_controller_test.go, ray-operator/controllers/suite_test.go, ray-operator/controllers/utils/util.go, ray-operator/controllers/utils/util_test.go
Run gofumpt once a while to correct some of the file formats.
N/A
=> Update format by running gofumpt

apiserver/cmd/main.go, apiserver/deploy/base/apiserver.yaml, apiserver/deploy/base/monitor.yaml, apiserver/go.mod, apiserver/go.sum, config/grafana/KubeRay-ApiServer-1650105351221.json, config/grafana/KubeRay-Controller-Runtime-Controllers-1650108080992.json, ray-operator/config/manager/kustomization.yaml, ray-operator/config/manager/service.yaml, ray-operator/controllers/common/metrics.go, ray-operator/controllers/raycluster_controller.go
1. Add kubernetes service for operators and backend service for scratching
2. Update ServiceMonitor to match service definiton
3. Add Grafana Dashboards for backend service and operators
This is used to expose kuberay core component's metrics and it will help user to better monitor healthiness of the components.
1. Backend
2. Operator
=> Emit prometheus metrics from kuberay control plane

ray-operator/config/manager/manager.yaml, ray-operator/controllers/common/pod.go
This patch fixed tow bugs:
1. add missing port declaration in manager.yaml file
2. avoid adding the same port again if it already exists in existing pod template.
#249
=> fix duplicated port config and manager.yaml missing config

ray-operator/config/prometheus/monitor.yaml
When applying the Ray Operator's prometheus config, the prometheus's ServiceMonitor spec.selector is missing the "matchLabels" spec. Therefore, we need to update the prometheus config with the proper selector spec.
Closes #252 
=> Fix Ray Operator prometheus config

install/prometheus/install.sh
Right now the `/install/prometheus/install.sh` script is assuming the directory path is `/install/prometheus/`. However, the main README instruction is asking users to run this script from the top directory which will result the following errors:
```
+ monitor_dir=../../config/prometheus
+ pushd ../../config/prometheus
./install/prometheus/install.sh: line 14: pushd: ../../config/prometheus: No such file or directory
```
Therefore, we need to make sure `monitor_dir` is set to the right directory without depending on the user's current directory path.
None
=> Install: Fix directory path for prometheus install.sh

ray-operator/DEVELOPMENT.md
1.18 doesn't work yet. See #257.
=> docs fix: specify only Go 1.16 or 1.17 works right now

tests/compatibility-test.py
enable ci test to check ctrl plane health state
Enable ci test code to fail when cluster cannot be correctly set up.
#251 
=> [CI]enable ci test to check ctrl plane health state

README.md, manifests/overlays/single-namespace-resources/kustomization.yaml, manifests/overlays/single-namespace/kustomization.yaml, manifests/overlays/single-namespace/patch-cluster-role-binding.json, manifests/overlays/single-namespace/patch-cluster-role.json, manifests/overlays/single-namespace/patch-deployment.json, manifests/overlays/single-namespace/patch-others.json
Run kuberay in a single namespace.
Instead of  setup kuberay using 
```bash
kubectl apply -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources"
kubectl apply -k "github.com/ray-project/kuberay/manifests/base"
```
now we use
```bash
kubectl apply -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources"
kubectl apply -k "github.com/ray-project/kuberay/manifests/singe-namespace"
```
#227
=> [Feature]Run kuberay in a single namespace

helm-chart/kuberay-operator/crds/crd.yaml, ray-operator/Makefile
=> Sync crds to Helm chart

ray-operator/config/rbac/role.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayservice_controller.go
Fixes a typo in the operator's role that prevents it from managing service accounts, which in turn blocks setup of autoscaling Ray clusters.
TODO: How to test??
=> [hotfix] Fix Service account typo

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Currently the patch in #259 isn't working because a later line overwrites with
the original bad value. This change sets the head pod's service account
to the one configured in the RayCluster.
=> fix operator: correctly set head pod service account

ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
This PR exposes the autoscaler container pull policy in the Ray CRD for testing purposes. This PR is [needed for Ray CI testing purposes](https://github.com/ray-project/ray/pull/25386#issuecomment-1150325385).
The CI environment needs to have the pull policy set to IfNotPresent, while for local testing the default policy of Always is more convenient.
A quick review is appreciated.
=> Set autoscaler imagePullPolicy to IfNotPresent. Provide override.

.github/workflows/test-job.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/main.go
This is a patch to bug #155. I added reconcile logic so that in case of following fields updated, we will rebuild the cluster.
1. head template container amount
2. head template container image
3. head template container resources
4. worker template container amount
5. worker template container image
6. worker template container resources
#155
=> enable force cluster upgrade

README.md, docs/deploy/installation.md, ray-operator/apis/ray/v1alpha1/raycluster_types.go
This PR adds a warning about a known issue (#271) to the KubeRay docs.
=> Warn explicitly against using kubectl apply to create RayCluster CRD.

ray-operator/controllers/ray/raycluster_controller_test.go, tests/compatibility-test.py, tests/config/ray-cluster.mini.yaml.template
add more tests for kuberay
#298
=> add cluster nodes info test

ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Closes https://github.com/ray-project/kuberay/issues/321
Fixes the logic that appends --num-gpus tp rayStartParams based on container resources.
The issue is that current logic looks for a resource named "gpu". However device plugins require extended resource names like "nvidia.com/gpu". 
This PR tweaks the logic so that we search for a resource key ending with ~~"/gpu"~~ "gpu".
=> Fix GPU-autofill for rayStartParams

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/utils/util_test.go
and change import names accordingly. My IDE was complaining about
these redundant imports.
=> refactor: remove redundant imports

ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go
It's one word so don't need to be camel-cased.
=> minor refactor: fix camel-casing of unHealthy -> unhealthy

apiserver/README.md, apiserver/pkg/manager/resource_manager.go, apiserver/pkg/model/converter.go, apiserver/pkg/server/cluster_server.go, apiserver/pkg/util/cluster.go, cli/pkg/cmd/cluster/create.go, cli/pkg/cmd/cluster/list.go, docs/design/protobuf-grpc-service.md, proto/cluster.proto, proto/go_client/cluster.pb.go, proto/swagger/cluster.swagger.json
=> fix: typo worker_group_sepc -> worker_group_spec

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
We are comparing memory to K8s Pod storage request
instead of memory request.
Add tests.
Expand error message with more information.
This error message is used in K8s events.
More information here might be helpful.
Update comments and log messages for clarity and smoother English usage.
Make repeated strings constants.
=> fix: bug in object store memory validation

tests/compatibility-test.py
The current compatibility test does not use the correct build of kuberay. This patch fixed this issue
#323
=> fix wrong kuberay image used by compatibility test

apiserver/deploy/base/apiserver.yaml, apiserver/deploy/base/kustomization.yaml, ray-operator/config/manager/kustomization.yaml, ray-operator/config/manager/manager.yaml, ray-operator/config/manager/service.yaml, ray-operator/config/rbac/kustomization.yaml, ray-operator/config/rbac/role.yaml, ray-operator/config/rbac/service_account.yaml
We follow the best practice of https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ and add following labels to better help filter and managed resources in Kubernetes
- app.kubernetes.io/name
- app.kubernetes.io/component
These labels are needed to better manage resource in kubernetes especially the namespace is used for multiple types of workloads. Without the change, it's not that easy to filter and list the target components.
#338 
=> Support KubeRay management labels

apiserver/pkg/manager/resource_manager.go, apiserver/pkg/util/cluster.go, apiserver/pkg/util/config.go, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/rbac.go, ray-operator/controllers/ray/common/service.go
=> add standard label for the filtering of cluster

docs/components/config/samples/config-map-ray-code.yaml, docs/components/config/samples/ray-cluster.complete.yaml, docs/components/config/samples/ray-cluster.heterogeneous.yaml, docs/components/config/samples/ray-cluster.mini.yaml, docs/components/media/create-ray-cluster.gif, docs/components/media/logs-ray-cluster.gif, docs/components/media/overview.png, docs/components/media/update-ray-cluster.gif, mkdocs.yml, ray-operator/README.md
These changes help fix broken links (examples and screenshot) in the documentation.
It help remove warning message in building the static website
https://github.com/ray-project/kuberay/issues/291
https://github.com/ray-project/kuberay/issues/331
=> Fix broken links by creating referenced soft links

cli/pkg/cmd/cluster/list.go, cli/pkg/cmd/template/compute/list.go
CLi doesn't make corresponding changes when we add `ListAll` 
https://github.com/ray-project/kuberay/blob/cb75cd029cd7a7ad23785ef53560f96e76d4215b/proto/cluster.proto#L48-L53
We want to make namespace field optional so 
1. without namespace -> it will fetch all clusters across multiple namespaces
2. with namespace -> fetch cluster under given namespace
```
./main template compute list
+------------------------+------------+-----+--------+-----+-----------------+
|          NAME          | NAMESPACE  | CPU | MEMORY | GPU | GPU-ACCELERATOR |
+------------------------+------------+-----+--------+-----+-----------------+
| compute-template-test2 | default    |   1 |      1 |   0 |                 |
| compute-mid            | ray-system |   2 |      2 |   0 |                 |
| …
```
=> Cli: make namespace optional to adapt to ListAll operation

apiserver/pkg/server/cluster_server.go, apiserver/pkg/server/compute_template_server.go
Added a validation for cluster request to make sure the namespace in the request is same as the one defined in the Ray cluster.
=> Validate namespace consistency in the request when creating the cluster and the compute template 

ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/raycluster_controller_test.go
A Ray cluster only supports one head pod.
Accordingly, the KubeRay operator ignores headGroupSpec.Replicas and creates exactly one head pod.
To match this operator behavior and simplify configuration, this PR makes headGroupSpec.Replicas optional and labels the field as deprecated.
We might have anticipated HA or FT features might be implemented via multiple heads, but that's not the route we're going down.
=> Make replicas optional for the head spec.

apiserver/cmd/main.go, apiserver/pkg/manager/resource_manager.go, apiserver/pkg/util/error.go, proto/Dockerfile, proto/Makefile, proto/go.mod, proto/go.sum, proto/go_client/cluster.pb.gw.go, proto/go_client/config.pb.gw.go
1. Upgrade grpc-gateway version
2. Make sure grpc status code can be convert to HTTP code correctly
https://github.com/ray-project/kuberay/issues/364
=> Enable DefaultHTTPErrorHandler and Upgrade grpc-gateway to v2

ray-operator/controllers/ray/raycluster_controller_test.go
this PR fixed the flaky test issue. The root cause is that the RayCluster object gets updated in the middle of the test so we have to get the latest RayCluster object and try it again.
#133
=> fix flaky test issue

docs/guidance/autoscaler.md, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Update the autoscaler images reflect the latest changes, mitigate user issues.
After the upcoming release, we will no longer need to make these updates -- autoscaler images will be matched to Ray images.
=> Update autoscaler image

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
The updateStatus method in reconcile was using wrong labels for the pods scraping.
=> [Bug] Fix raycluster updatestatus list wrong label

ray-operator/controllers/ray/rayservice_controller.go
The PR unified the two logger used in the rayservice controller, and adds user facing events, looking like the following
```
Events:
Type    Reason                    Age                    From                   Message
----    ------                    ----                   ----                   -------
Normal  WaitForDashboard          2m33s (x2 over 2m33s)  rayservice-controller  Service "rayservice-sample-raycluster-97tzg-dashboard-svc" not found
Normal  FailedServeDeploy         2m29s                  rayservice-controller  Put "http://rayservice-sample-raycluster-97tzg-dashboard-svc.default.svc.cluster.local:52365/api/serve/deployments/": dial tcp 10.72.1.85:52365: i/o timeout (Client.Timeout exceeded while awaiting headers)
Normal  FailedServeDeploy         2m21s (x4 over 2m31s) …
```
=> [Serve] Unify logger and add user facing events

.github/workflows/test-job.yaml, docs/guidance/gcs-ha.md, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/utils/util.go, tests/compatibility-test.py, tests/config/ray-cluster.ray-ha.yaml.template
Initial support for GCS HA in kuberay. 
Design document is at: https://github.com/wilsonwang371/kuberay/blob/wilson/ray2.0_gcs_ha/docs/guidance/gcs-ha.md
1. added yaml for Ray GCS HA + External Redis Deployment
2. a document describing Ray GCS HA details.
3. introduced new annotation in RayCluster to enable Ray GCS HA
4. Added Event reconcile function so that in case of Readiness Probe failure, we can try to recover head or worker node if possible.
5. Added Liveness and Readiness Probes based on new features introduced in https://github.com/ray-project/ray/pull/26408
6. Added Ray detached actor and Ray serve basic tests in Compatibility Test.
7. Updated github workflow to reduce its running time
To enable GCS HA, in RayCluster yaml file, a new annotation is required.
```yaml
apiVersion: …
```
=> Initial support for external Redis and GCS HA

ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Should resolve https://github.com/ray-project/ray/issues/26064, where users report the autoscaler crash-looping due to a missing log directory.
Gives the shared log mount configured by the KubeRay operator for Ray logs a more specific path.
(This log mount was introduced in https://github.com/ray-project/kuberay/pull/274)
Previously the path was `/tmp/ray`. Instead, we should use `/tmp/ray/session_latest/logs`, which is where Ray and the autoscaler would like to write logs.
By using the more specific path, we ensure that the path will exist on container startup, preventing the file-not-found issues described in https://github.com/ray-project/ray/issues/26064.
Ray attempts to create this directory with `os.makedirs(path, …
=> [autoscaler] Make log file mount path more specific.

.github/workflows/test-job.yaml, apiserver/pkg/manager/resource_manager.go, apiserver/pkg/util/error.go, cli/pkg/cmd/cluster/list.go, cli/pkg/cmd/config/get.go, cli/pkg/cmd/config/set.go, cli/pkg/cmd/template/compute/list.go, ray-operator/Makefile, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go, ray-operator/controllers/ray/utils/httpproxy_httpclient.go
Use a more strict format check with gofumpt
We discussed this a long time before. Due to some conflicts with our internal branch, we postponed this until now. Since our downstream branch and upstream branch is in sync now, it is a good time for us to apply a more strict code formatting on kuberay.
N/A
=> use more strict formatting

ray-operator/Makefile, ray-operator/controllers/ray/common/constant.go, tests/compatibility-test.py, tests/config/ray-cluster.ray-ha.yaml.template
1. improve compatibility test stability by increasing the initial wait time in liveness/readiness probe.
2. remove unnecessary gofumpt run in Makefile.
N/A
=> improve test stability

ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.yaml
These ports should be exposed by the Ray head service by default.
For now, this PR adds the container ports to the `raycluster.complete` and `raycluster.autoscaler` example files, so that the service configured for these examples exposes the relevant ports.
My main motivation right now is documenting Ray Cluster interaction methods in the Ray docs.
=> [minor] Add client and dashboard ports to ports in example configs.

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go
if NodePort is "0" for updating RayCluster's `status.endpoints`.
follow up to #341
=> fix controller: use Service's TargetPort

apiserver/pkg/manager/resource_manager.go, docs/design/protobuf-grpc-service.md, proto/config.proto, proto/go_client/config_grpc.pb.go, proto/swagger/config.swagger.json
Fix the comment of ListAllComputeTemplates on swagger-ui.
=> Fix `ListAllComputeTemplates` proto comments

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/raycluster_controller.go, tests/compatibility-test.py, tests/config/ray-cluster.ray-ha.yaml.template
Timeout values in Github workflow Kind environment is not long enough for ray serve tests.
#406
=> tune readiness probe timeouts

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayservice_controller.go
For Ray Serve, if we set the death info time as 0, it will increase SLA. This pr sets the env for RayService create Ray containers.
```
spec:
containers:
- args:
- 'ulimit -n 65536; ray start --head  --num-cpus=2  --metrics-export-port=8080  --dashboard-agent-listen-port=52365  --memory=2147483648  --block  --dashboard-host=0.0.0.0  --node-ip-address=$MY_POD_IP  --object-store-memory=100000000  --port=6379 '
command:
- /bin/bash
- -c
- --
env:
- name: MY_POD_IP
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: status.podIP
- name: RAY_IP
value: 127.0.0.1
- name: RAY_PORT
value: "6379"
- name: RAY_timeout_ms_task_wait_for_death_info
value: "0"
- name: RAY_ADDRESS
value: 127.0.0.1:6379
```
=> RayCluster created by RayService set death info env for ray container

.github/workflows/test-job.yaml, tests/compatibility-test.py
Sometimes the base compatibility test can fail. This might be related to exceptions not being handled correctly. 
#294
=> improve compatibility test stability

apiserver/pkg/interceptor/interceptor.go, apiserver/pkg/util/error.go
Current response doesn't give any detail clues on the failure
Detail logs are swallowed due to previous `GetStatus` change. I add them back now. 
=> Expose swallowed detail error messages

tests/compatibility-test.py, tests/config/cluster-config.yaml, tests/config/ray-service-cluster-update.yaml.template, tests/config/ray-service-serve-update.yaml.template, tests/config/ray-service.yaml.template, tests/config/raycluster-service.yaml
add 8000 port forwarding in kind and avoid using `kubectl port-forward`
N/A
=> add new 8000 port forwarding in kind

docs/components/config/samples/ray-cluster.autoscaler.large.yaml, docs/components/config/samples/ray-cluster.autoscaler.yaml, docs/components/config/samples/ray-cluster.complete.large.yaml, ray-operator/README.md, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/samples/ray-cluster.getting-started.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray-cluster.ingress.yaml, ray-operator/config/samples/ray-cluster.mini.yaml, ray-operator/config/samples/ray-cluster.without-block.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml
This PR
- Adds two sample configs for clusters with large Ray pods meant to take up entire 16CPU K8s nodes.
- Adds warnings that resources should be increased for production use-cases 
Closes https://github.com/ray-project/kuberay/issues/417
=> [docs] Add sample configs with larger Ray pods

ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
This PR updates the logic that selects a default autoscaler image.
For Ray versions at least 2.0.0, use the same image for the autoscaler as for the Ray container.
This eliminates the possibility of autoscaler/Ray incompatibility and reduces docker pull time.
For earlier Ray versions, use `rayproject/ray:2.0.0` to guarantee up-to-date autoscaler functionality.
As of the Ray 2.0.0 branch cut earlier today, an image tagged `rayproject/ray:2.0.0` exists on Dockerhub.
Until the official Ray release in two weeks, this image is unofficial and its actual contents are a moving target -- but I think we can live with the inconsistency in the short term. (I'm open to other opinions on this choice.) 
Closes https://github.com/ray-project/kuberay/issues/360
=> [Autoscaler] Match autoscaler image to Ray head image for Ray >= 2.0.0

ray-operator/controllers/ray/rayjob_controller.go
Nil pointer dereference if the value of `TTLSecondsAfterSetting` is None
=> Fix nil pointer dereference

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/utils/util.go
`include-dashboard` is not a flag parameter, so we should convert it to `--include-dashboard=true` instead of `--include-dashboard`
```bash
(base) ➜  ray-operator git:(ping-7) ray start --help                           
Usage: ray start [OPTIONS]
Start Ray processes manually on the local machine. PublicAPI: This API is
stable across Ray releases.
Options:
--node-ip-address TEXT          the IP address of this node
--address TEXT                  the address to use for Ray
--port INTEGER                  the port of the head ray process. If not
provided, defaults to 6379; if port is set
to 0, we will allocate an available port.
--object-manager-port INTEGER   the port to use for starting the object
manager
--node-manager-port INTEGER     the …
```
=> Fix wrong ray start command

ray-operator/controllers/ray/common/pod.go
The ray cluster will not load the .bashrc before the container start. The reason is the ray process starting command is like this:
```yaml
Command:
/bin/bash
-c
--
Args:
ulimit -n 65536; ray start --head  --system-config='{"gcs_rpc_server_reconnect_timeout_s": 20}'  --block  --num-cpus=4  --memory=8000000000  --dashboard-host=0.0.0.0  --node-ip-address=$MY_POD_IP  --port=6379  --metrics-export-port=8080
```
/bin/bash -c means non-Interactive mode to run bash. 
reference to https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
non-Interactive mode would not load /etc/profile, .bashrc, ...
we can use login mode to get similar effect with the interactive mode
https://github.com/ray-project/kuberay/issues/409
- [*] I've made sure the tests are passing. 
- …
=> [operator] enable bashrc before container start

ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/httpproxy_httpclient.go
This pr adds the resp code error handling for RayService.
=> Add http resp code check for kuberay

ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml
This PR cleans up the "complete" and "autoscaler" sample yamls a bit.
Unnecessary pod spec fields are removed without sacrificing the completeness of the examples. 
The idea is to make the configuration look less intimidating.
=> Clean up example samples

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go
Based on @iycheng Ray side requirement, we need 2 more env for RayService nodes.
=> Add more env for RayService head or worker pods

ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go
If Ray job name is too long, the worker node will try to connect to the wrong head node service.
```bash
(base) ➜  ~ k get svc -n flytesnacks-development
NAME                                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                         AGE
l94lnxh5ktptbgzsfnj-n0-0-raycluster-xg6hj-head-svc   NodePort    10.96.123.235   <none>        6379:32288/TCP,10001:31845/TCP,8265:32389/TCP   33s
(base) ➜  ~ k describe pods -n flytesnacks-development ptbgzsfnj-n0-0-raycluster-xg6hj-worker-test-group-5kbn5 | grep address 
ulimit -n 65536; ray start  --node-ip-address=$MY_POD_IP  --address=al94lnxh5ktptbgzsfnj-n0-0-raycluster-xg6hj-head-svc:6379  --metrics-export-port=8080  --num-cpus=2 …
```
=> fix: worker node can't connect to head node service

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
Also allow setting rayVersion
Signed-off-by: Christos Kotsis <28815556+ulfox@users.noreply.github.com>
Include options to configure enableInTreeAutoscaling & rayVersion for rayCluster
Configuring headNode autoscaling is not possible with the current helm chart without modification
=> helm-chart/ray-cluster: allow head autoscaling

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go
The async serve handler needs to be disabled for ray service cluster for now until it's fixed.
=> Disable async serve handler in Ray Service cluster.

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go
This is needed to speedup serve controller recovery time due to raylet died. Otherwise, serve has to wait until GCS announce the node failure before start the controller.
=> Disable pin on head for serve controller by default in service operator

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go
=> Disable pin on head for serve controller by default in service operator (#457)

.github/workflows/test-job.yaml
0.3 post submit test doesn't upgrade the image actually.  I determine to make this change instead of manually build the image. 
=> Enable docker image push against release-0.3 branch

helm-chart/kuberay-apiserver/Chart.yaml, helm-chart/kuberay-operator/Chart.yaml, helm-chart/ray-cluster/Chart.yaml
Address https://github.com/ray-project/kuberay/issues/452
Make helm chart version to match release version.
https://github.com/ray-project/kuberay/issues/452
=> Update helm chart version to 0.3.0

docs/guidance/rayservice.md, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, tests/config/ray-service-cluster-update.yaml.template, tests/config/ray-service-serve-update.yaml.template, tests/config/ray-service.yaml.template
Renames the config fields to match more directly:
- `serveDeploymentGraphConfig` -> `serveConfig`
- `serveConfigs` -> `deployments`
We should also make the fields support `snake_case` so that they can be copy-pasted directly from `serve build`, but that would be a larger change.
=> [rayservice] Fix config names to match serve config format directly

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
We can not set additional workers with the current helm chart.
There are some PRs that aim to fix this but they appear to be stale
https://github.com/ray-project/kuberay/pull/266
We wanted to keep untouched the default worker that is already
included in the helm chart but allow the addition of new workers.
The changes are adding the following logic:
- Allow to disable the default worker group, if needed, via worker.disabled = true
- Allow to set additional workers by using the extraWorkers map
The extraWorkers map has a different structure compared to the default worker because we
wanted to add additional flexibility. Due to that, some variables in the extraWorkers
have different naming (which matches the name of the related CRD attributed)
Note: PR was done to support additional workers …
=> helm-charts/ray-cluster: Allow extra workers

.github/workflows/test-job.yaml
https://github.com/ray-project/kuberay/issues/453
With this change, release branch can update image to dockerhub.
https://github.com/ray-project/kuberay/issues/453
=> Enable docker image push for release-0.3 branch

helm-chart/kuberay-apiserver/templates/role.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_viewer_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_viewer_role.yaml, helm-chart/kuberay-operator/templates/role.yaml
The operator deployed by the helm chart need permission for the rayjobs resource, the role is already update in the `ray-operator/config/rbac`, we need sync up in the helm chart.
#440 
=> sync up helm chart's role

README.md
Error massage
```
(base) ➜  kuberay git:(master) ✗ export KUBERAY_VERSION=master
kubectl create -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources?ref=${KUBERAY_VERSION}"
kubectl apply -k "github.com/ray-project/kuberay/manifests/base?ref=${KUBERAY_VERSION}"
error: hit 27s timeout running '/usr/local/bin/git fetch --depth=1 origin master'
error: hit 27s timeout running '/usr/local/bin/git fetch --depth=1 origin master'
```
Increasing timeout can fix the issue.
=> Add timeout to the query parameters

docs/guidance/rayservice.md, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, tests/config/ray-service-cluster-update.yaml.template, tests/config/ray-service-serve-update.yaml.template, tests/config/ray-service.yaml.template
This is a PR to pick https://github.com/ray-project/kuberay/pull/464 into the KubeRay 0.3.0 branch. 
This changed the names of some config fields to match Ray Serve's API.
=> [0.3.0 pick][rayservice] Fix config names to match serve config format directly

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Removing elements while iterating over VolumeMounts slice causes panics.
```
WARN[0000] ingress class annotation is not set for cluster default/raycluster-sample 
--- FAIL: TestCleanupInvalidVolumeMounts (0.00s)
panic: runtime error: index out of range [2] with length 2 [recovered]
panic: runtime error: index out of range [2] with length 2
goroutine 103 [running]:
testing.tRunner.func1.2({0x10543be80, 0x14000042468})
/usr/local/go/src/testing/testing.go:1389 +0x1c8
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1392 +0x384
panic({0x10543be80, 0x14000042468})
/usr/local/go/src/runtime/panic.go:838 +0x204
github.com/ray-project/kuberay/ray-operator/controllers/ray/common.cleanupInvalidVolumeMounts(...)
/Users/wanxing/work/code/kuberay-github/ray-operator/controllers/ray/common/ …
```
=> Fix panic in cleanupInvalidVolumeMounts 

docs/guidance/observability.md, helm-chart/kuberay-apiserver/Chart.yaml, helm-chart/kuberay-apiserver/templates/role.yaml, helm-chart/kuberay-operator/Chart.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_viewer_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_viewer_role.yaml, helm-chart/kuberay-operator/templates/role.yaml, helm-chart/ray-cluster/Chart.yaml, helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
Cherry-pick following changes to release-0.3 branch
for stable release
=> Cherry pick master fixes to release-0.3

docs/best-practice/worker-head-reconnection.md, docs/guidance/gcs-ft.md, mkdocs.yml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller.go, tests/compatibility-test.py, tests/config/ray-cluster.ray-ft.yaml.template
=> correct gcs ha to gcs ft

README.md, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/util.go
Failed to convert Unix time to meta time.
```
2022-08-16T10:29:43.043Z	DEBUG	controllers.RayJob	RayJob information	{"RayJob": "rayjob-sample", "jobInfo": {"status":"SUCCEEDED","entrypoint":"python /home/ray/samples/sample_code.py","message":"Job finished successfully.","start_time":1660645691607,"end_time":1660645710418}, "rayJobInstance": "PENDING"}
2022-08-16T10:29:43.043Z	INFO	controllers.RayJob	Update status from PENDING to SUCCEEDED	{"rayjob": "rayjob-sample-z7j5q"}
2022-08-16T10:29:43.043Z	INFO	controllers.RayJob	UpdateState	{"oldJobStatus": "PENDING", "newJobStatus": "SUCCEEDED", "oldJobDeploymentStatus": "Running", "newJobDeploymentStatus": "Running"}
2022-08-16T10:29:43.057Z	ERROR	controller.rayjob	Reconciler error	{"reconciler group": "ray.io", "reconciler kind": "RayJob", …
```
=> Properly convert unix time into meta time

docs/guidance/autoscaler.md, docs/guidance/observability.md, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml
This PR
- Updates some configs to refer to Ray 2.0.0
- Updates autoscaler docs to reflect beta status for autoscaler integration
- Makes a couple of grammar edits
It would be good to pick this into the 0.3 branch, since some of the Ray docs refer to the configs in the release branch.
One viable strategy to manage docs for the release branch is just to check the master branch docs straight into the 0.3 branch. 
=> [doc] Config and doc updates ahead of KubeRay 0.3.0/Ray 2.0.0

ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml
PR against 0.3 branch, isolates config changes from https://github.com/ray-project/kuberay/pull/486/
Updates Ray versions in a few config examples to Ray 2.0.0.
Useful since we refer to the KubeRay configs in the 0.3 release branch in new Ray docs.
We can work out cleaner versioning later.
=> [0.3 pick] Update Ray versions in a few sample configs.

config/prometheus/podMonitor.yaml, config/prometheus/rules/prometheusRules.yaml, config/prometheus/serviceMonitor.yaml, docs/guidance/observability.md
Sample configuration for exporting metrics from ray cluster workers. This works with autoscaling and should cover new workers and remove destroyed worker pods as well
The podMonitor CRD resource works in a similar way that serviceMonitor works but instead of targeting services, it targets pods.
Prometheus example after applying this manifest
```
ray_raylet_mem{..., container="ray-head", ...} | ...
...
ray_raylet_mem{..., container="ray-worker", ..., pod="ray-cluster-main-worker-generic-group-h2nhg",...} | ...
...
```
=> config/prometheus: add metrics exporter for workers

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
This is a follow up fix to #328.
Code in that PR breaks out of a loop that checks for
GPU resources on the first iteration.
It should only break out of the loop if it finds GPUs.
=> fix: correctly set GPUs in rayStartParams

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
In this commit we extend the capability of ray-cluster helm chart to allow adding pod lifecycle in the head & worker nodes 
The changes are not needed, but can extend the customization of the head & worker pods.
We can use postStart and preStop lifecycles to run custom commands. For example, send a webhook after a headnode starts.
Example:
```
lifecycle:
preStop:
exec:
command: ["/bin/sh","-c","ray stop"]
```
=> helm-chart/ray-cluster: Allow setting pod lifecycle

helm-chart/kuberay-operator/README.md
Fixes another `apply crd.yaml` to read `create crd.yaml`.
See #271.
=> Helm instructions: kubectl apply -> kubectl create

ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml
across Container restarts
Ray logs are written to `/tmp/ray` by default. Right now
various RayCluster example YAMLs use `volumeMounts` for `/var/log`
which doesn't have anything written to it.
So right now `/tmp/ray` logs are deleted after Container restarts.
This change sets `volumeMounts.mountPath` to `/tmp/ray` so that
logs in this dir are persisted across Container restarts for the life
of the Pod.
This change also adds volumes for head Pods which was missing before.
=> fix examples: bad K8s log config causing logs to be lost

ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.yaml
I tried to follow the [document](https://docs.ray.io/en/latest/cluster/kubernetes/getting-started.html) to build a simple ray cluster (1 head node + 1 worker node) and run a simple job on the cluster. However, when I submitted a job to my head node, the job failed due to OOM as shown in the following picture.
I ran this experiment on GKE with autopilot. Some nodes in GKE may have just the same amount of memory as the resource request of head node. As shown in the figure, the node only have 0.5G memory (same as resource request) rather than 1G (resource limit). Hence, we need to increase the value of resource request of the head node.
#528 
```bash
! kubectl create -k "github.com/ray-project/kuberay/ray-operator/config/default?ref=v0.3.0&timeout=90s"
! kubectl apply -f …
```
=> Ray GettingStarted tutorial causes head node OOM

helm-chart/kuberay-operator/README.md, helm-chart/ray-cluster/README.md, helm-chart/ray-cluster/values.yaml
There are 3 problems in current helm chart default configurations.
* [Q1] There is a mismatch between labels in ray-head pod and selector in ray-head ClusterIP service. See https://github.com/ray-project/kuberay/issues/495 for more details.
* [Solution]: I updated the value of `nameOverride` from `ray` to `kuberay` as mentioned by @jeethridge.
* [Q2] When I solved Q1, I found dashboard could not be launched successfully. The root cause is that `dashboard_agent` would round down the CPU request config (200m) to 0.
* [Solution]: Increase CPU request from 200m to 1.
* [Q3] After I solved Q2, the dashboard still could not be rendered on my browser. The root cause is that the image `rayproject/ray:latest` points to a very old version. Thank @hckuo for pointing this out!
* [Solution]: Updated …
=> Fix Helm chart default configuration

helm-chart/ray-cluster/README.md
This PR removes the reference to KubeRay 0.4.0 in the Helm documentation.
There's a comment indicating that the command to download an install the charts won't work until KubeRay 0.4.0.
However, some users may miss the comment and attempt to run the command.
We can re-introduce the command to the documentation when we release KubeRay 0.4.0.
This PR also updates the description of Ray to match the current description in the Ray repo.
=> Update Helm doc.

helm-chart/ray-cluster/values.yaml
This allows comparison between boolean types, i.e. see ray-cluster/templates/raycluster-cluster.yaml:107, where we assert:
{{- if ne .Values.worker.disabled true }}
The default setting for the default workergroup is now an explicit `disabled: false`.
Closes #537.
=> helm: Uncomment the disabled key for the default workergroup

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
As mentioned by @tbabej in #537, an error will be reported if the `disabled` key on the default worker group is undefined. In old Helm versions, when `disabled` key is undefined, it will be set to `nil`. Hence, when we run the following command, it will report the error "incompatible types for comparison". Obviously, `nil` and boolean cannot be compared for equality. See https://github.com/helm/helm/issues/6376 for more details.
```
$ helm lint    
==> Linting .
[ERROR] templates/: template: ray-cluster/templates/raycluster-cluster.yaml:105:9: executing "ray-cluster/templates/raycluster-cluster.yaml" at <ne .Values.worker.disabled true>: error calling ne: incompatible types for comparison
Error: 1 chart(s) linted, 1 chart(s) failed
```
In this PR, I give the `disabled` key a default value …
=> [Helm][minor] Make "disabled" flag for worker groups optional

.github/workflows/site.yaml
Github Action failed in this [PR](https://github.com/ray-project/kuberay/actions/runs/3040044978/jobs/4895656877) because the charts have already existed. We need to skip publishing new charts if the charts are existing. Although we added the `skip existing` flag, `chart-releaser-action` would still update `index.yaml` in the branch gh-pages. Hence, we can prevent `index.yaml` from overwriting by MkDocs. See #545 for more context.
[TODO]
Because charts in v0.3.0 have some bugs, we use #545 and this PR to host "xxxx-chart-latest" releases. It is not good to update release charts every commit merge. Hence, when we are ready for v0.4.0, we should:
(1) [release.yaml](https://github.com/ray-project/kuberay/blob/master/.github/workflows/release.yaml): Use `chart-releaser-action` (#545) to …
=> [Bug] Skip publishing new charts if they are existing

helm-chart/kuberay-operator/README.md
Get the download URL from the release tagged with v0.3.0 instead of the latest release, which just returns the ray-cluster Helm chart
Signed-off-by: Sigmund Vestergaard <sigmundv@gmail.com>
The instructions given in `helm-chart/kuberay-operator/README.md` don't work, because the command that gets the download URL is wrong. This PR fixes the command such that it gets the correct download URL.
NOTE: The proposed fix gets the chart from release v0.3.0, but you might want to get it from the latest release, which is a different tag.
Fixes #569
=> Fixed download URL for Helm chart

ray-operator/DEVELOPMENT.md
See https://github.com/ray-project/kuberay/issues/568.
Closes #568 
=> [Doc] Cannot build kuberay with Go 1.16

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go
In #164, @Jeffwan mentions that RBAC files cannot be updated automatically with the command `make manifests`. The root cause is the lack of a newline after kubebuilder markers. This issue is same as https://github.com/kubernetes-sigs/controller-tools/issues/551.
In addition, the permissions of `config/rbac/role.yaml` is the union of kubebuilder markers in `raycluster_controller.go`, `rayjob_controller.go`, and `rayservice_controller.go`.
closes #164 
* Step1: Add the following marker in one of "xxxxx_controller.go"
* `// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;delete`
* Step2: `make manifests`
* Step3: Check `config/role.yaml`
* There is no kubebuilder marker defining permissions of Deployment, and thus `role.yaml` will be …
=> Add reminders to avoid RBAC synchronization bug

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Deploy a RayCluster with a worker group with replicas >= 2 and supply a name in the pod template. The operator will fail to generate multiple worker replicas and will show an error creating the second pod. See this [commit](https://github.com/kevin85421/kuberay/commit/fe80c7513e7345a968d2f43965e3d29105385033) for more details. The following instructions can reproduce this bug.
```bash
git clone git@github.com:kevin85421/kuberay.git
git checkout replicate-worker-name-control-group
cd helm-chart/kuberay-operator
helm install kuberay-operator .
cd helm-chart/ray-cluster
helm install ray-cluster .
```
[Solution]: Set `ObjectMeta.Name` to an empty string, and use `GenerateName` to prevent name conflicts.
[Note]: Relationship between `Name` and `GenerateName` …
=> [Bug] Pod reconciliation fails if worker pod name is supplied

.github/workflows/actions/compatibility/action.yaml, tests/compatibility-test.py, tests/kuberay_utils/utils.py
This is a patch that separate compatibility test into different files so that later we can only enable the necessary tests and delay other tests to nightly. 
#514 #298
=> update test files before separating them

helm-chart/kuberay-apiserver/values.yaml
The `rbacEnable` value is being checked [here](https://github.com/ray-project/kuberay/blob/390002d1f3c0290d9b2e0f9ca09277713aec838d/helm-chart/kuberay-apiserver/templates/role.yaml#L2) to apply the default role and rolebinding. However, the value was missing from the `values.yaml`. 
None
=> [bugfix][apiserver helm]: Adding missing rbacenable value

.github/workflows/test-job.yaml
With gofumpt version upgraded, there is some issue installing it. We now need to use a fixed version of gofumpt to avoid test issues from external.
#597
=> [CI]use fixed version of gofumpt

docs/deploy/kuberay-with-MCAD.md, docs/guidance/kuberay-with-MCAD.md, mkdocs.yml
This is a documentation PR that provides the capability to queue and gang dispatch kuberay clusters using MCAD project.
=> kuberay int with MCAD

ray-operator/config/samples/ray_v1alpha1_rayjob.yaml
The --object-store-memory flag in the sample RayJob config causes failed RayCluster setup, with this message:
https://github.com/ray-project/kuberay/blob/1694b9e2fba06f4d2378ea70c3fda679ee67b61d/ray-operator/controllers/ray/common/pod.go#L836-L837
This prevents the job from running to completion.
This PR fixes the issue by removing the `--object-store-memory` flag from the configuration.
Ray does a good enough job of figuring out appropriate object store memory itself.
=> [RayJob] Fix example misconfiguration.

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
This PR exposed an interface in KubeRay helm charts to enable users to configure sidecar containers (See the [logging documentation](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/logging.html) and https://github.com/ray-project/kuberay/issues/353 for more details).
<details>
<summary> configMap.yaml </summary>
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: fluentbit-config
data:
fluent-bit.conf: |
[INPUT]
Name tail
Path /tmp/ray/session_latest/logs/*
Tag ray
Path_Key true
Refresh_Interval 5
[OUTPUT]
Name stdout
Match *
```
</details>
<details>
<summary> Updated values.yaml </summary>
* Update `head.volumes` and `head.sidecarContainers`
```yaml
image:
repository: rayproject/ray
tag: 2.0.0
pullPolicy: IfNotPresent
nameOverride: "kuberay"
fullnameOverride: "" …
```
=> [Feature][Helm] Enable sidecar configuration in Helm chart

tests/kuberay_utils/utils.py
Currently, we use `time.sleep()` to wait for the system convergence in E2E tests. However, `time.sleep()` will block the process for fixed units of time. Hence, we need to use new wait functions that block the process only when the system is not ready.
* `kind create cluster --wait ...` ([Link](https://kind.sigs.k8s.io/docs/user/quick-start/))
* `kubectl wait` ([Link](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait))
* Without this PR
* With this PR
Closes #611 
=> [Feature] Optimize the wait functions in E2E tests

docs/guidance/rayservice.md
Copy-edits the guidance outlining RayService for clarity and consistency. 
FYI @DmitriGekhtman :) 
Contributes to #520 
N/A
=> [doc] Copy-Edit RayService

helm-chart/script/chart-test.sh, ray-operator/DEVELOPMENT.md
[chart-testing](https://github.com/helm/chart-testing) (ct) has a lot of prerequisites. In addition, ct also has docker support. Adding the Docker support in [chart-test.sh](https://github.com/ray-project/kuberay/blob/master/helm-chart/script/chart-test.sh) can save the efforts for developers to install dependencies manually.
Update [chart-test.sh](https://github.com/ray-project/kuberay/blob/master/helm-chart/script/chart-test.sh) to support running tests with docker and documentation for chart lint tests in [DEVELOPMENT.md](https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md).
Closes #622 
=> [Feature] Docker support for chart-testing

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
Extra annotations on the RayCluster custom resource are needed to enable functions like GCS FT for a Ray cluster. These annotations should be configurable in the Helm chart without editing the `raycluster-cluster.yaml` template.
I couldn't find any related issue.
=> Allow annotations in ray cluster helm chart

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
Currently service type is not used in helm and ClusterIP is hardcoded
https://github.com/ray-project/kuberay/blob/159d57f565cabee36c97fa55cbc5d401bfeef906/helm-chart/ray-cluster/templates/raycluster-cluster.yaml#L15
=> Helm: add service type configuration to head group for ray-cluster

helm-chart/kuberay-operator/templates/role.yaml, ray-operator/config/rbac/role.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go
These changes address issue #630
When trying to create one of the example `RayCluster` on OpenShift, it will fail with the operator reporting "cannot set blockOwnerDeletion if an ownerReference refers to a resource you can’t set finalizers on:".
As per https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-, we were able to fix the issue by applying the new `role.yaml` that is created running `make manifests` after applying the changes in this PR. 
Closes #630 
As mentioned, this PR was tested by applying the contents of the `role.yaml` file to the kuberay-operator `ClusterRole` 
=> Fix finalizer typo and re-create manifests

ray-operator/DEVELOPMENT.md, scripts/rbac-check.py
Currently, RBAC YAML files in `helm-chart/kuberay-operator/templates` and `ray-operator/config/rbac` should be synchronized manually. We have pointed this out in [DEVELOPMENT.md](https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md#consistency-check), but it is not easy for users to find the messages. Hence, we need to make this information become more explicit in both [DEVELOPMENT.md](https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md#consistency-check) and [rbac-check.py](https://github.com/ray-project/kuberay/blob/master/scripts/rbac-check.py).
Closes #640 
#631 
```bash
python3 ../scripts/rbac-check.py
```
=> [Feature][Doc] Explain that RBAC should be synchronized manually

docs/guidance/ingress.md, ray-operator/config/samples/ray-cluster.ingress.yaml, ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/common/ingress_test.go
This issue is not totally same as #441, and thus I opened a new issue. Users cannot create `ingress` with the instructions in https://ray-project.github.io/kuberay/guidance/ingress/. The operator also reports the error message:
```
2022-10-18T00:34:38.187Z	ERROR	controllers.RayCluster	Ingress create error!	{"Ingress.Error": "Ingress.extensions \"raycluster-ingress-head-ingress\" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: \"nginx\": can not be set when the class field is also set", "error": "Ingress.extensions \"raycluster-ingress-head-ingress\" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: \"nginx\": can not be set when the class field is also set"}
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).reconcileIn …
```
=> [Bug] Fail to create ingress due to the deprecation of the ingress.class annotation

tests/compatibility-test.py, tests/config/requirements.txt, tests/kuberay_utils/utils.py, tests/scripts/test_detached_actor_2.py
In KinD E2E tests, we use `kubectl wait` to block the process only when the system is not ready. However, it is not good to use `kubectl wait --for=condition=Ready` after deleting a resource. See the **Example 1** section in #618 for more details.
[Example]
The test `test_detached_actor` kills GCS on the head pod and uses `kubectl wait` to make sure that the new head pod is ready. However, in my experiment, the head pod will need 60 seconds to crash after the GCS server is killed. The head pod is `READY:1/1, STATUS: Running` before the crash. Hence, `kubectl wait` cannot make sure the new head pod is ready.
https://github.com/ray-project/kuberay/blob/ea6e8d1e5d36690c2a3577361db124fad1389a00/tests/compatibility-test.py#L319-L327
The workaround solution is to replace the `kubectl wait` with …
=> [Bug] Update wait function in test_detached_actor

ray-operator/Makefile, ray-operator/controllers/ray/suite_test.go
Signed-off-by: Shreyas Krishnaswamy <shrekris@anyscale.com>
This change updates some test settings and error behavior to improve compatibility with M1 Macbooks. Thanks @simon-mo for the suggested changes!
Copies over some changes from #366.
- This change updates testing configurations.
=> Update tests for better Mac M1 compatibility

tests/framework/config/ray-cluster.mini.yaml.template, tests/framework/prototype.py
* [Design Doc](https://docs.google.com/document/d/1OyMBgQ9zx5FF0GV3f3WKVdW-Y4OXz_epaywYgTw893w/edit?usp=sharing)
Currently, existing tests for operators only test for the default configuration. However, from the last 6 weeks (the design doc is created on Sep. 26, 2022), 11 out of 34 commits are used to fix bugs caused by configurations. Hence, this project decided to focus on configuration. This PR is a prototype that can reproduce every YAML-related configuration bug (in the 11 reported config bugs) by adding a simple JsonPatch.
```python
if __name__ == '__main__':
template_name = 'config/ray-cluster.mini.yaml.template'
namespace = 'default'
with open(template_name) as base_yaml:
baseCR = yaml.load(base_yaml, Loader=yaml.FullLoader)
patch_list = [
jsonpatch.JsonPatch([{'op': 'replace', …
```
=> Configuration Test Framework Prototype

docs/guidance/gcs-ft.md
This PR adds the instruction about how to use SSL/TLS for redis connection.
=> [doc] Add instructions about how to use SSL/TLS for redis connection.

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/utils/util.go
`RayServices` check the entire `RayCluster` config, and they issue an A/B update if any part of the config has changed. The Ray Kubernetes autoscaler uses the `replicas` and `workersToDelete` fields in the `RayCluster` config to guide the cluster's autoscaling. This means that whenever the autoscaler tries to update the cluster's goal status, the `RayService` restarts the entire cluster (see #649 for more details).
This change updates the `RayService`'s logic to (1) add an annotation to the `RayCluster` which points to a hash of the `RayCluster`'s original configuration, (2) compares the goal-state `RayCluster`'s hash to this cached hash, and (3) only. triggers an A/B update if the goal hash changes.
Addresses #649.
=> [RayService] Compare cached hashed config before triggering update

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go
If maxReplicas < Replicas, treat maxReplicas as the target replica count and log the discrepancy.
Partly addresses https://github.com/ray-project/kuberay/issues/560 in which some entity (possibly the Ray autoscaler) set replicas > maxReplicas.
See https://github.com/ray-project/ray/pull/29770/ for the corresponding safeguard in the autoscaler code.
=> [raycluster controller] Always honor maxReplicas

apiserver/cmd/main.go, apiserver/go.mod, apiserver/pkg/client/cluster.go, apiserver/pkg/client/job.go, apiserver/pkg/client/kubernetes.go, apiserver/pkg/client/service.go, apiserver/pkg/manager/resource_manager.go, apiserver/pkg/model/converter.go, apiserver/pkg/util/error.go, apiserver/pkg/util/time.go, ray-operator/go.mod, ray-operator/go.sum, ray-operator/main.go
support sync log to file in pod.
this feature is controllered by `log_file ` parameter in command line, default only output log to std
https://github.com/ray-project/kuberay/issues/593
use `-logFilePath=output.txt` when executing apiserver
use `-log-file-path=output.txt` when executing ray-operator
you can add these parameter in ENTRYPOINT of Dockerfile
then swap the based image in Dockerfile which can exec into
=> [Feature] Sync logs to local file

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
Signed-off-by: Andrew Li <orcahmlee@gmail.com>
This PR aligns the `minReplicas` and `maxReplicas`.
Since the RayCluster CRD uses `minReplicas` and `maxReplicas`, the `values.yaml` should use it instead of using `miniReplicas` and `maxiReplicas`
- [] I've made sure the tests are passing. 
=> [Feature][Helm] Align the key of minReplicas and maxReplicas

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go
#625 indicates that the `appProtocol` field is required to integrate with [Open Service Mesh](https://release-v0-11.docs.openservicemesh.io/docs/guides/app_onboarding/app_protocol_selection/#application-protocol-selection). We discussed how to expose head service for users in the community sync Oct. 25. We did not reach a conclusion in that meeting. Setting the default `appProtocol` to `tcp` will not change any existing behaviors because the default value of `Protocol` is "TCP" ([Link](https://pkg.go.dev/k8s.io/api/core/v1#ServicePort)). This PR enables users to integrate KubeRay with Open Service Mesh.
* Some documents related to `appProtocol`
* Proposal: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1507-app-protocol
* Motivation: …
=> [Feature] Set default appProtocol for Ray head service to tcp

tests/compatibility-test.py, tests/scripts/test_ray_serve_1.py, tests/scripts/test_ray_serve_2.py
As shown in the following code segment, the existing ray-serve test in [compatibility-test.py](https://github.com/ray-project/kuberay/blob/2a7f0f2acd840f315e46596341c392c8153ae641/tests/compatibility-test.py) has the following pattern:
* Create a container that launches a Python REPL process by Docker API.
* Attach a socket to the container with parameters params={'stdin': 1, 'stream': 1, 'stdout': 1, 'stderr': 1}.
* Use the socket to interact with Python REPL.
* Use a while loop to check the received message of the socket.
https://github.com/ray-project/kuberay/blob/3f7b34c731bd2ee413fb622a05124b52f1588f20/tests/compatibility-test.py#L174-L267
However, this is buggy because the received message of the socket includes STDIN, STDOUT, and STDERR. That is, the received message includes the …
=> [Bug] Misuse of Docker API and misunderstanding of Ray HA cause test_ray_serve flaky

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
The options of the Autoscaler are useful but not exposed to the Helm values.yaml, such as `idleTimeoutSeconds` and `resources`.
Closes #665 
=> [Feature][Helm] Expose the autoscalerOptions

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
Some users hope to pull the busybox images from private repositories. Hence, this PR makes the image field of init container become configurable in the RayCluster helm chart.
Q1: Is it possible for us to have multiple init containers?
Q2: Is it possible to expose other fields for init containers? See [k8s doc](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container) for other container fields.
Closes #673 
* `worker.initContainerImage` and `smallGroup.initContainerImage` (commented out `disabled: true`) are defined.
* `worker.initContainerImage` and `smallGroup.initContainerImage` (commented out `disabled: true`) are undefined.
=> [Feature] Expose initContainer image in RayCluster chart

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go, ray-operator/controllers/ray/utils/utils_suite_test.go
when submitting job in cluster selector mode, job will submit to the existing cluster.
If the job cr deleted, these cluster would not be deleted.
we will stop job in these condition
https://github.com/ray-project/kuberay/issues/595
https://github.com/ray-project/kuberay/pull/470
- [*] Manual tests
1. apply the ray cluster (modify from ray-operator/config/samples/ray-cluster.complete.yaml, just add sample code) 
```yaml
......
volumeMounts:
- mountPath: /tmp/ray
name: ray-logs
- mountPath: /home/ray/samples
name: code-sample
resources:
limits:
cpu: "1"
memory: "2G"
requests:
cpu: "500m"
memory: "1G"
volumes:
- name: ray-logs
emptyDir: {}
- name: code-sample
configMap:
name: ray-job-code-sample
items:
- key: sample_code.py
path: sample_code.py
.....
---
apiVersion: v1 …
```
=> [ray job] support stop job after job cr is deleted in cluster selector mode

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go
like so. Missing IPs will be excluded.
```
status:
head:
podIP: string
serviceIP: string
```
Motivation for this change is so that users can get the head IP from the
RayCluster CRD directly without knowing the underlying implementation
details of kuberay.
In a later commit we update the API server to parse the status
and return the IPs for each cluster.
=> feat: enrich RayCluster status with head IPs

ray-operator/config/manager/manager.yaml
Sets the operator's deployment strategy to Recreate for Kustomize configs.
This is a follow-up to https://github.com/ray-project/kuberay/pull/566/ which set the operator's deployment strategy to Recreate for Helm configs.
=> [operator] Set operator strategy to Recreate in kustomize config

README.md, docs/deploy/installation.md
Remind users to upgrade kubectl.
https://discuss.ray.io/t/installing-kuberay-operator-failing/8204/4
=> [docs] State version requirement for kubectl

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go
https://github.com/ray-project/kuberay/pull/468/ has the RayCluster controller throw an error if head ip can't be determined while updating RayCluster status
That is problematic for two reasons:
1. Head pod ip is not determined while the head pod is pending placement.
2. Status updating logic should be best-effort. If there's a brief inconsistency leading to multiple or no head pods listed, the reconciler should take appropriate action, but the status processing logic doesn't need to fail.
Throwing an error in the first situation might be leading to test failures:
https://github.com/ray-project/kuberay/actions/runs/3424423296/jobs/5706807752
This PR modifies the headIP status logic to be best effort -- if the IP cannot be …
=> [fix][raycluster controller] No error if head ip cannot be determined.

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
some corner cases can be triggered and the error below is returned
```
Invalid value: \"/dev/shm\": must be unique", 
```
#688
=> Fix duplicated volume issue

tests/compatibility-test.py, tests/config/requirements.txt, tests/framework/prototype.py, tests/kuberay_utils/utils.py
#704 causes `kubectl wait` to be flaky, and thus I used `RayClusterAddCREvent` to reduce flakiness.
In #704, `kubectl wait` sometimes waits for 1 head pod and 2 worker pods (goal state is 1 head pod and 1 worker pod) due to the inconsistency between Kubernetes API server and informer cache, and thus the function `create_kuberay_cluster` is flaky. `RayClusterAddCREvent` specifies the goal state (1 head pod and 1 worker pod) directly to reduce flakiness.
https://github.com/ray-project/kuberay/blob/17264a6f409208ee24cbb743c59fa40c9eed856a/tests/framework/prototype.py#L204-L231
https://github.com/ray-project/kuberay/issues/704
=> Replace kubectl wait command with RayClusterAddCREvent

.github/workflows/site.yaml
We decided to host Helm charts in [ray-project/kuberay-helm](https://github.com/ray-project/kuberay-helm). Hence, `helm-chart-releaser` in KubeRay should be removed.
This PR is a part of #553
Closes #722 
=> Remove helm-chart-releaser from KubeRay repository

docs/release/helm-chart.md
We need to formalize the release process. Documents are helpful.
Closes #724
=> Add documentations for the release process of Helm charts

apiserver/go.mod, apiserver/go.sum, ray-operator/go.mod, ray-operator/go.sum
client_golang used by KubeRay (v1.11.0) has a vulnerability (CVE-2022-21698). Hence, upgrade to v1.11.1 by the following command.
* `ray-operator`
```sh
cd ray-operator 
go get -u github.com/prometheus/client_golang@v1.11.1
make build
```
* `apiserver`
```sh
cd apiserver
go get -u github.com/prometheus/client_golang@v1.11.1
go build ./...
``` 
Closes #696 
=> [Bug] client_golang used by KubeRay has a vulnerability

helm-chart/kuberay-operator/values.yaml, ray-operator/README.md, ray-operator/config/manager/manager.yaml
We have some indication from users that the default resource limits for the KubeRay operator may be too small when managing many Ray pods.
See the discussion here: https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1667409518664019
* Increase the default resource limits  
* Document the fact that users need to observe resource usage and adjust as needed.
Closes #685 
=> [Bug][Doc] Increase default operator resource requirements, improve docs

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/rbac.go
I'd like to give the autoscaler
- The name of the pod it's running in, via an env variable
- Permission to patch the head pod
The goal is to enable more efficient "list pods" API calls in the autoscaler. Currently each autoscaler lists without specifying a resource version, which is [taxing on etcd](https://kubernetes.io/docs/reference/using-api/api-concepts/#the-resourceversion-parameter), especially if there are many Ray clusters in the K8s cluster.
We would like to specify a reasonably fresh pods resource version in the API call.
To that end, we will have the autoscaler patch the head pod's annotations.
The resource version carried in the response is the version at which the pod was modified, so it should be fresh enough.
After the autoscaler patches the head pod, it can read the …
=> [Autoscaler] Pass pod name to autoscaler, add pod patch permission

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
This PR cleans up the ray-cluster Helm chart.
- Removes unnecessary and deprecated fields.
- Adds some comments
- Renames initArgs to rayStartParams in a backwards-compatible way.
Closes https://github.com/ray-project/kuberay/issues/739
=> [Helm] Clean up RayCluster Helm chart ahead of KubeRay 0.4.0 release

apiserver/README.md, cli/README.md, docs/development/development.md
There's some user confusion concerning whether the KubeRay API Server and KubeRay CLI are required components.
This PR adds some clarifying notes and adds maintainer contacts (@Jeffwan @scarlet25151).
Let me know if this list of maintainers should be modified.
=> [APIServer][Docs] Identify API server as community-managed and optional

apiserver/pkg/util/cluster.go, apiserver/pkg/util/service.go
The rayservice need indicate the serve port for exposing the ray serve service, in the default raycluster template we are missing the serve port, here we need add it at the service part.
=> [Bug][apiserver] fix apiserver create rayservice missing serve port

helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go
See #629 to get more context. The behavior of this PR is almost the same as #629. The only difference is that this PR promises that operator will try to stop the job at least once. In #629, if the RayJob is deleted when the operator is down, the operator will not try to stop the job.
* Finalizer reference
* https://book-v1.book.kubebuilder.io/beyond_basics/using_finalizers.html
* https://book.kubebuilder.io/reference/using-finalizers.html
* Need to discuss
* I decide to remove the finalizer no matter StopJob() succeeds or not. If the operator does not stop the job successfully, users can still stop them by Dashboard, RESTful API, .. etc. However, it is hard for most users to use the following command to remove RayJob.
* `kubectl patch rayjobs.ray.io/rayjob-sample-2 --type json --patch='[ …
=> [Feature] [RayJobs] Use finalizers to implement stopping a job upon cluster deletion

helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go
The `RayService` operator checks whether a pending `RayCluster`'s [Serve application is `"HEALTHY"`](https://github.com/ray-project/kuberay/blob/850fd486207294b97e143961b752d6c5ce7c0fa2/ray-operator/controllers/ray/rayservice_controller.go#L553) before it sets it as the active cluster. There's a few issues with this approach:
1. `"HEALTHY"` is not a valid [Serve `ApplicationStatus`](https://github.com/ray-project/ray/blob/65d0c0aa48be8f9f7faae857d3ab71444997755a/python/ray/serve/_private/common.py#L31-L35).
2. A Serve application can be healthy but not ready (e.g. if it's `NOT_STARTED` or still `DEPLOYING`). If the cluster switchover happens before the app is ready, incoming traffic is briefly dropped until the Serve app becomes ready.
This change updates `getAndCheckServeStatus` to track …
=> [RayService] Track whether Serve app is ready before switching clusters

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go
Makes RayCluster errors related to Pod creation easier more apparent to user.
```
kubectl get rayclusters dxia-test2 -o yaml
...
status:
state: failed
kubectl describe rayclusters dxia-test2
...
Status:
State:   failed
```
```
kubectl get rayclusters dxia-test2 -o yaml
...
status:
reason: 'pods "dxia-test2-head-lbvdc" is forbidden: exceeded quota: quota, requested:
limits.cpu=15,requests.cpu=15, used: limits.cpu=60,requests.cpu=60, limited: limits.cpu=10,requests.cpu=10'
state: failed
kubectl describe rayclusters dxia-test2
...
Status:
Reason:  pods "dxia-test2-head-9mdm5" is forbidden: exceeded quota: quota, requested: limits.cpu=15,requests.cpu=15, used: limits.cpu=60,requests.cpu=60, limited: limits.cpu=10,requests.cpu=10
State:   failed
```
fixes #603
=> feat: update RayCluster `.status.reason` field with pod creation error

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
Exposes securityContext in Helm charts.
See https://github.com/ray-project/kuberay/pull/750.
TODO: Test with the workflows in https://github.com/ray-project/kuberay/pull/750
=> [Helm] Expose security context in helm chart.

docs/deploy/docker.md, docs/deploy/installation.md, docs/development/development.md, helm-chart/kuberay-operator/README.md, helm-chart/ray-cluster/README.md
=> [Release] Update docs for release v0.4.0

helm-chart/kuberay-operator/templates/deployment.yaml, tests/compatibility-test.py, tests/framework/prototype.py
Add ```app.kubernetes.io/component: kuberay-operator``` label in [helm-chart/kuberay-operator/templates/deployment.yaml](https://github.com/ray-project/kuberay/blob/5177ebfbc885faa4abca8109f1fb692b3c85e880/helm-chart/kuberay-operator/templates/deployment.yaml) to make operator pod can be selected in ```show_cluster_info()```.
The only way I found to check if the test pass in ```teardown()``` is to access the private field ```self._outcome``` in unittest.TestCase object([reference](https://stackoverflow.com/questions/4414234/getting-pythons-unittest-results-in-a-teardown-method)). The fields in ```self._outcome``` changes in Python 3.11. It seems like accessing ```self._outcome``` in unittest.TestCase is not a robust approach.
Because all of the labels app.kubernetes.io/component: for the …
=> [Feature] Improve the observability of integration tests

.github/workflows/consistency-check.yaml
Closes https://github.com/ray-project/kuberay/issues/791, which occurred due to CRD consistency job's automatic choice of an incompatible Go version (1.18.x).
=> [CI] Pin go version in CRD consistency check

helm-chart/ray-cluster/values.yaml
Closes https://github.com/ray-project/kuberay/issues/788
See the issue for further context.
Manually tested as follows:
```
helm install kuberay-operator kuberay-operator/
helm install raycluster ray-cluster/
```
Confirmed that resource requests and limits are as expected.
Confirmed correct Ray internal state using
```
kubectl exec -it <head-pod> -- ray status
```
which produced the output
```
======== Autoscaler status: 2022-12-05 11:34:13.524240 ========
Node status
---------------------------------------------------------------
Healthy:
1 node_310f01ea0047365c5f0d8c09c360de5b030c14debaa3d109795a6cf7
1 node_b9725b30f0d8e9b15eb1f10952e56d76538ceef949cff07a2cc78855
Pending:
(no pending nodes)
Recent failures:
(no failures) …
```
=> [helm] Add memory limits and resource documentation.

helm-chart/kuberay-operator/templates/deployment.yaml, tests/compatibility-test.py
Show debug information in failed test cases.
Make operator label consistent across Kustomize and Helm deployment methods.
Picks #775 into the 0.4 release branch (it helps debug CI failures)
=> [Feature] Improve the observability of integration tests (#775)

helm-chart/ray-cluster/values.yaml
Adds appropriate memory limits to Helm chart, with some documentation.
Picks Helm improvement #789 into the release branch.
Necessary for consistent default Ray Cluster "helm install" experience.
=> [helm] Add memory limits and resource documentation. (#789)

.github/workflows/image-release.yaml
This PR adds a GitHub Actions workflow to manually build and tag Operator and APIServer images.
It is based on the image build steps in https://github.com/ray-project/kuberay/blob/master/.github/workflows/test-job.yaml.
Instructions on how to use will be added to the release docs in a follow-up.
=> [CI] Add workflow to manually trigger release image push

apiserver/DEVELOPMENT.md, apiserver/README.md, apiserver/deploy/base/apiserver.yaml, docs/best-practice/worker-head-reconnection.md, docs/design/protobuf-grpc-service.md, docs/guidance/gcs-ft.md, docs/troubleshooting.md, helm-chart/kuberay-apiserver/templates/role.yaml
There are several legacy docs that out of date for v0.4.0 release, we modify some of them related to apiserver and gcs ft.
=> update docs for release v0.4.0

helm-chart/kuberay-operator/values.yaml
Search ".Values.ingress.enabled" in VS Code. Only one result matches in [helm-chart/kuberay-apiserver/templates/ingress.yaml](https://github.com/ray-project/kuberay/blob/781eed1e6b40093efc6e11c2dfc93777dadd9716/helm-chart/kuberay-apiserver/templates/ingress.yaml).
https://github.com/ray-project/kuberay/blob/781eed1e6b40093efc6e11c2dfc93777dadd9716/helm-chart/kuberay-apiserver/templates/ingress.yaml#L1
All integration tests in KubeRay CI deploy the KubeRay operator via Helm chart.
=> [Bug] Remove an unused field (ingress.enabled) from KubeRay operator chart

helm-chart/kuberay-operator/values.yaml
Removes the unused ingress.Enabled field from the operator Helm chart.
(Take 4)
Picking https://github.com/ray-project/kuberay/pull/812 into the 0.4.0 release branch.
FYI @kevin85421 @sihanwang41
=> Remove ingress.enabled from KubeRay operator chart (#812)

ray-operator/controllers/ray/rayservice_controller.go
Signed-off-by: Sihan Wang <sihanwang41@gmail.com>
Ignore K8s reconcile when there is no config/label/annotation change
[#28652](https://github.com/ray-project/ray/issues/28652)
Local testing, all reconciles are under 2 seconds interval
=> [RayService] Skip update events without change

README.md, docs/deploy/installation.md, docs/guidance/autoscaler.md, docs/guidance/rayjob.md, docs/guidance/rayservice.md, docs/notebook/kuberay-on-kind.ipynb, helm-chart/kuberay-apiserver/Chart.yaml, helm-chart/kuberay-operator/Chart.yaml, helm-chart/kuberay-operator/README.md, helm-chart/ray-cluster/Chart.yaml, ray-operator/README.md
Updates KubeRay versions in master.
To be merged after images and Helm charts are built.
=> [post-0.4.0 KubeRay release] Update KubeRay versions 

README.md
See https://github.com/ray-project/kuberay/issues/288#issuecomment-1344955244 for more details.
* I can reproduce this issue with `kubectl v1.21.0` 
```console
$ kubectl create -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources?ref=${KUBERAY_VERSION}&timeout=90s"
error: git cmd = '/usr/local/bin/git fetch --depth=1 origin v0.3.0&timeout=90s': exit status 128
$ kubectl version --client=true --short=true
Client Version: v1.21.0
```
* Fix this issue by updating `kubectl` to v1.22.0+
```console
$ kubectl create -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources?ref=${KUBERAY_VERSION}&timeout=90s"
namespace/ray-system created
customresourcedefinition.apiextensions.k8s.io/rayclusters.ray.io created
customresourcedefinition.apiextensions.k8s.io/rayjobs.ray.io …
```
=> [Bug] error: git cmd when following docs

CHANGELOG.md
Updates CHANGELOG.md with changes for 0.4.0.
The new section can be used as the release notes for 0.4.0 after it is approved and merged. 
=> [0.4.0 release] Update changelog for KubeRay 0.4.0

docs/deploy/installation.md, helm-chart/kuberay-operator/README.md, helm-chart/kuberay-operator/values.yaml, helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
Some fields in KubeRay operator chart and RayCluster chart are useless.
Closes #549 
* KubeRay operator chart is tested by KubeRay CI (compatibility test, configuration test, helm lint test)
* RayCluster chart is tested by KubeRay CI (helm lint test) and manually.
Run the following command based on the commit d30d76ddca6b01b3c0e698c6388ab2767e2f0801.
```sh
helm template .
```
<details>
<summary>output</summary>
```
---
apiVersion: ray.io/v1alpha1
metadata:
labels:
app.kubernetes.io/name: kuberay
helm.sh/chart: ray-cluster-0.4.0
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
name: release-name-kuberay
spec:
headGroupSpec:
serviceType: ClusterIP
block: "true"
dashboard-host: "0.0.0.0"
template:
spec: …
```
=> Remove unused fields from KubeRay operator and RayCluster charts

tests/framework/prototype.py, tests/framework/utils.py, tests/test_sample_raycluster_yamls.py
Previously, we did not test `ray-cluster.external-redis.yaml` in [test_sample_raycluster_yamls.py](https://github.com/ray-project/kuberay/blob/3a647129e248640f2314bfafd257f6b7a5db232f/tests/framework/test_sample_raycluster_yamls.py) because it installs multiple Kubernetes resources and cannot clean up by `clean_up()`. This PR defines a general-purpose cleanup method to remove related Kubernetes resources.
Closes #772
```sh
RAY_IMAGE=rayproject/ray:2.1.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_raycluster_yamls.py
```
=> [Feature] Define a general-purpose cleanup method for CREvent

docs/guidance/volcano-integration.md, helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, helm-chart/ray-cluster/values.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/samples/ray-cluster.getting-started.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray-cluster.mini.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml, tests/config/ray-cluster.mini.yaml.template, tests/config/ray-cluster.ray-ft.yaml.template, tests/config/ray-service.yaml.template
Minimal configuration for RayCluster CRs should be as simple as possible. This PR makes `serviceType` optional and the default is `ClusterIP`.
(from [Kubernetes official documentation](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types))
> ClusterIP: Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from within the cluster. This is the default that is used if you don't explicitly specify a type for a Service.
Part of #368 
```sh
helm install raycluster .
kubectl get svc
```
* TYPE of `raycluster-kuberay-head-svc` is ClusterIP.
=> [Feature] Make head serviceType optional

.github/workflows/actions/configuration/action.yaml, .github/workflows/test-job.yaml, docs/guidance/volcano-integration.md, helm-chart/ray-cluster/values.yaml, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/samples/ray-cluster.getting-started.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray-cluster.mini.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml, tests/framework/utils.py
Currently, we only run config tests with the nightly KubeRay operator. However, we also need to keep the compatibility of the current sample YAML files with the latest KubeRay operator release. If not, some bugs may happen (e.g. https://github.com/ray-project/kuberay/issues/856).
If we only update the KubeRay operator image to the latest release in the current KubeRay chart, #856 cannot be caught. This is because old CRD defined `serviceType` as a required field and #851 made it optional. Hence, we need to install both CRD and the KubeRay operator with the latest release to catch #856.
We can parallelize them by dividing them into two GitHub Actions jobs. However, I need to work on a lot with GitHub Actions syntax to reach the goal, and we plan to move KubeRay CI from GitHub Actions to …
=> [Feature] Run config tests with the latest release of KubeRay operator

helm-chart/kuberay-apiserver/templates/role.yaml, helm-chart/kuberay-apiserver/templates/rolebinding.yaml, helm-chart/kuberay-apiserver/values.yaml, helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/templates/leader_election_role.yaml, helm-chart/kuberay-operator/templates/leader_election_role_binding.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_viewer_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_viewer_role.yaml, helm-chart/kuberay-operator/templates/role.yaml, helm-chart/kuberay-operator/templates/rolebinding.yaml, helm-chart/kuberay-operator/values.yaml
This change allows Kuberay to be used in multitenanted clusters.
I have tested this by running a series of template commands e.g.
```sh
helm template blah ./helm-chart/kuberay-operator --debug --set batchScheduler.enabled=1 --set watchNamespace=x
```
=> [Feature] Enable namespaced installs via helm chart

ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/controllers/ray/raycluster_controller.go
Signed-off-by: Archit Kulkarni <architkulkarni@users.noreply.github.com>
This PR fixes an issue where RayJobs would never be submitted even if the Ray Cluster was up and running. Debugged this with @brucez-anyscale .
The root cause is the following:
The cluster status is only marked "Ready" if all pods are RUNNING.  The cluster state only gets updated when a reconcile happens.
However, the Cluster reconcile doesn't get requeued if all the pods are in [RUNNING, PENDING] state. 
In particular, when the head pod becomes PENDING, the cluster never gets reconciled again. 
So the cluster is stuck in a state where it's status is not "Ready". Since the RayJob reconciler waits for the cluster status to be "Ready" before submission, the job hangs and is never submitted.
The fix in this PR is to …
=> [RayCluster controller] [Bug] Unconditionally reconcile RayCluster every 60s instead of only upon change

ray-operator/controllers/ray/raycluster_controller.go
instead of longer `Builder.Watches()`.
=> refactor: use equivalent, shorter `Builder.Owns()` method

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml
by adding additional printer columns for number of desired workers, number of available workers, status, age, head Pod IP, and head Service IP.
```
kubectl get rayclusters
NAME         AGE
dxia-test    53m
keshi-test   2d23h
```
```
kubectl get rayclusters
NAME         DESIRED WORKERS   AVAILABLE WORKERS   STATUS   AGE
dxia-test    3                 4                   ready    60m
keshi-test   1                 2                   ready    2d23h
kubectl get rayclusters -o wide
NAME         DESIRED WORKERS   AVAILABLE WORKERS   STATUS   AGE     HEAD POD IP    HEAD SERVICE IP
dxia-test    3                 4                   ready    60m     10.169.4.130   10.160.217.214
keshi-test   1                 2                   ready    2d23h   10.169.6.102   10.160.218.91
```
=> feat: enrich `kubectl get` output

ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/raycluster_controller.go
=> refactor: remove redundant import in `raycluster_controller.go`

helm-chart/kuberay-apiserver/templates/deployment.yaml
To ensure kuberay is usable in K8s clusters where nodeselectors/tolerations are required to schedule workloads.
I tested this by installing with the following values in addition to default, then checking the pod's properties.
```yaml
nodeSelector:
my: node
tolerations:
- key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: topology.kubernetes.io/zone
operator: In
values:
- antarctica-east1
- antarctica-west1
```
=> [Feature] Nodeselector/Affinity/Tolerations value to kuberay-apiserver chart

README.md, helm-chart/ray-cluster/README.md
The nightly docker images for arm64 are available. See https://github.com/ray-project/ray/issues/31537#issuecomment-1405687464 for more details. Hence, users can run Ray in Docker containers on ARM machines (including Mac M1) and on ARM cloud instances (e.g. AWS Graviton).
Closes #523 
```sh
helm repo add kuberay https://ray-project.github.io/kuberay-helm/
helm install kuberay-operator kuberay/kuberay-operator --version 0.4.0
helm install raycluster kuberay/ray-cluster --version 0.4.0 --set image.tag=nightly-aarch64
kubectl port-forward --address 0.0.0.0 svc/raycluster-kuberay-head-svc 8265:8265
kubectl exec -it ${RAYCLUSTER_HEAD_POD} -- bash
python -c "import ray; ray.init(); print(ray.cluster_resources())" # (in Ray head Pod)
```
=> [Bug] KubeRay does not work on M1 macs.

tests/kuberay_utils/utils.py
1. This PR ensures all temp files are removed after the compatibility tests are completed. In the current implementation, some temporary files will not be deleted after the process exits due to:
https://github.com/ray-project/kuberay/blob/683f0fa91928fda056027a6ccd6b564435898c72/tests/kuberay_utils/utils.py#L44
With the option `delete=False`, the temporary files will not be deleted after the process exits, and need to be deleted manually. See [NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html) for more details. Check `/tmp` to see the temporary files after the tests are completed.
In this PR, temporary files will be deleted automatically once we close the files. See how [NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html) works. 
```python
with …
```
=> Ensure all temp files are deleted after the compatibility test

docs/guidance/pod-security.md, tests/framework/utils.py, tests/kuberay_utils/utils.py, tests/test_security.py
This PR is a follow-up for #866. 
1. It enables the test framework to install the operator with custom configurations.
2. It put the operator in the pod security namespace rather than the default namespace in security testing.
3. It moves some logic into setUpClass and split the pod security test into:
```
Test 1: Create RayCluster with securityContext config under restricted mode
Test 2: Create pod without securityContext config under restricted mode
```
Closes #880
Check 1: It put the operator in the pod security namespace rather than the default namespace in security testing:
Check 2: It enables the test framework to install the operator with custom configurations:
Install KubeRay operator with custom config:
Install KubeRay’s latest release with custom config: (see #858 for more …
=> Enable test framework to install operator with custom config and put operator in a namespace with enforced PSS in security testing

ray-operator/controllers/ray/raycluster_controller_test.go
The test "should be able to update all Pods to Running" is flaky. See
https://github.com/ray-project/kuberay/actions/runs/4058693982/jobs/6985922032
https://github.com/ray-project/kuberay/actions/runs/4071855521/jobs/7014050487
https://github.com/ray-project/kuberay/actions/runs/4049283327/jobs/6965472578
https://github.com/ray-project/kuberay/actions/runs/4037511626/jobs/6940851665
For Kubernetes, we use lister to get Kubernetes cluster information from the local cache. However, the local cache may have a jet lag with the Kubernetes API server. Hence, we need to replace `Expect` with `Eventually` to wait for the local cache to become up-to-date.
#882 
I tested this PR with the following bash script. It succeeds 10 times consecutively.
```sh
#!/bin/bash
for i in …
```
=> [Bug] Fix flaky test: should be able to update all Pods to Running

ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
to not count head Pods. closes #885
=> fix: `.status.availableWorkerReplicas`

ray-operator/controllers/ray/suite_test.go
The test "should be able to update all Pods to Running" is flaky. The reason is that we get Kubernetes cluster information from the local cache. However, the local cache may have a jet lag with the Kubernetes API server. 
So, the thought is we should get the true status of the Pods directly from the API server in the operator test.
In [client.New doc](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.3/pkg/client#New),  it says:
> New returns a new Client using the provided config and Options. The returned client reads *and* writes directly from the server (it doesn't use object caches). It understands how to work with normal types (both custom resources and aggregated/built-in resources), as well as unstructured types.
In [kubebuilder's writing-tests …
=> Use k8sClient from client.New in controller test

ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go
In a previous [experiment](https://github.com/ray-project/kuberay/issues/894#issuecomment-1416892144), it was shown that 86 runs succeed, and 14 runs failed with the following errors：
```
[Fail] Inside the default namespace When creating a raycluster [It] should update a raycluster object 
/home/lyc/Desktop/kuberay/ray-operator/controllers/ray/raycluster_controller_test.go:279
[Fail] Inside the default namespace When creating a raycluster [It] should have only 1 running worker 
/home/lyc/Desktop/kuberay/ray-operator/controllers/ray/raycluster_controller_test.go:286
[Fail] Inside the default namespace When creating a rayservice [It] should perform a zero-downtime update after a code change. 
/home/lyc/Desktop/kuberay/ray-operator/controllers/ray/rayservice_controller_test.go:354
```
The …
=> refactor: Fix flaky tests by using RetryOnConflict

helm-chart/kuberay-apiserver/templates/service.yaml
The selector in the kuberay-apiserver service doesn't match the label of the kuberay-apiserver.  So the kuberay-apiserver can not be accessed via the   the kuberay-apiserver service.
Pod labels:
```
app.kubernetes.io/component: kuberay-apiserver
app.kubernetes.io/name: ccccc
pod-template-hash: 69b79f99c5
```
Service selector
```
app.kubernetes.io/name: kuberay-apiserver
```
This PR changes the service selector to match the apiserver pod labels in the helm template. 
=> match selector of service to pod labels

helm-chart/kuberay-apiserver/templates/deployment.yaml
The sidecar container is useful for adding security capabilities to the pod.  This PR adds the capability to inject the sidecar container to the api-server pod by the values.yaml file.
=> add sidecar container option

.github/workflows/test-job.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml, tests/compatibility-test.py, tests/config/ray-cluster.ray-ft.yaml.template, tests/test_sample_raycluster_yamls.py, tests/test_sample_rayservice_yamls.py, tests/test_security.py
Ray 2.3.0 changes `REDIS_DEFAULT_PASSWORD` from `"5241590000000000"` to `""` in [ray-project/ray#31257](https://github.com/ray-project/ray/pull/31257/files).
Closes #927
https://github.com/ray-project/ray/issues/32794
#925 
* Ray FT related tests: 
```sh
RAY_IMAGE=rayproject/ray:2.3.0 python3 tests/compatibility-test.py RayFTTestCase 2>&1 | tee log
```
* RayService sample YAML test:
```sh
RAY_IMAGE=rayproject/ray:2.3.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_rayservice_yamls.py 2>&1 | tee log
```
* RayCluster sample YAML test
```sh
RAY_IMAGE=rayproject/ray:2.3.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_raycluster_yamls.py 2>&1 | tee log
```
* Pod security test
```sh
python3 tests/test_security.py 2>&1 | tee log
```
=> [Ray 2.3.0] Update --redis-password for RayCluster

apiserver/README.md
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
The README for the apiserver has an incorrect location for the helm chart (see below). This PR updates the READ to use the correct helm chart location.
```bash
$ helm -n ray-system install kuberay-apiserver kuberay/helm-chart/kuberay-apiserver
Error: INSTALLATION FAILED: chart "helm-chart/kuberay-apiserver" matching  not found in kuberay index. (try 'helm repo update'): no chart name found
$ helm -n ray-system install kuberay-apiserver kuberay/kuberay-apiserver
NAME: kuberay-apiserver
LAST DEPLOYED: Mon Feb  6 12:02:18 2023
NAMESPACE: ray-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
n/a
Note: this PR updates a readme, so there shouldn't be any impact to the tests.
=> Update apiserver chart location in readme

.buildkite/example.yml
The Buildkite infrastructure for KubeRay CI is ready (Thanks @krfricke!). This PR is used to test the infrastructure after it is merged. 
#695
```bash
docker run -it golang:1.17
git clone https://github.com/ray-project/kuberay.git
cd kuberay/ray-operator
make test
```
=> [CI][Buildkite] An example test for Buildkite

CONTRIBUTING.md, README.md
…discussion forum
As seen in conversations in #926, its not clear for new users/contributors of Kuberay how to reach out to community. Make it easy to find in this contribution doc.
=> Update contribution doc to show users how to reach out via slack

ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go
Sometimes, the Ray Jobs API "GET" `/jobs/` endpoint returns a traceback string instead of valid JSON (which must begin with `'{'`). 
We should look into whether this is a bug on the Ray side and whether we are returning the correct error code.
This PR propagates the underlying traceback string to the user, instead of hiding it behind a "JSON parse error" as before.  
Partially addresses #897 but doesn't fix the root cause (jobs run at the same time seem to conflict with each other)
=> [RayJob] Propagate error traceback string when GetJobInfo doesn't return valid JSON

apiserver/pkg/util/cluster.go, helm-chart/ray-cluster/templates/raycluster-cluster.yaml, ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/util.go, tests/config/ray-cluster.mini.yaml.template, tests/config/ray-cluster.ray-ft.yaml.template, tests/config/ray-service.yaml.template
Some big tech companies do not use `kube-dns` as the DNS server for Kubernetes Pods. They have a lot of Kubernetes services in the cluster, but services in different namespaces may have the same name. Hence, IP address with the information of both Kubernetes service name and Kubernetes namespace is useful in this case. That is, **Fully Qualified Domain Name (FQDN)** is a must.
* Use `kube-dns` as the DNS server: We can use `${HEAD_SERVICE}` to access the head service.
* With FQDN, we need to use `${HEAD_SERVICE}.${NAMESPACE}.svc.cluster.local` to access the head service.
~~Note: It breaks the **backward compatibility** (users need to update `until nslookup $RAY_IP ...` in their YAML files). However, this update is a must. It actually blocks some users to adopt KubeRay.~~
[Update]: We plan …
=> [Feature] Replace service name with Fully Qualified Domain Name 

.github/workflows/test-job.yaml, apiserver/README.md, docs/guidance/pod-command.md, docs/guidance/volcano-integration.md, ray-operator/DEVELOPMENT.md, ray-operator/apis/ray/v1alpha1/rayjob_types_test.go, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.getting-started.yaml, ray-operator/config/samples/ray-cluster.head-command.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray-cluster.ingress.yaml, ray-operator/config/samples/ray-cluster.mini.yaml, ray-operator/config/samples/ray-cluster.separate-ingress.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go
Inspired by https://github.com/ray-project/kuberay/pull/822
I think I got all references to 2.2.0:
```
$ ag '2\.2\.0' | grep -v 'third_party' | grep -v 'go.sum' | grep -v 'go.mod'
CHANGELOG.md:17:* Critical stability improvements to the [Ray Autoscaler integration](https://ray-project.github.io/kuberay/guidance/autoscaler/). (To benefit from these improvements, use KubeRay >=0.4.0 and Ray >=2.2.0.)
```
=> [Post Ray 2.3 Release] Update Ray versions to Ray 2.3.0

ray-operator/config/samples/ray-cluster.external-redis.yaml
https://github.com/ray-project/kuberay/issues/949
Closes #949 
```sh
kubectl apply -f ray-cluster.external-redis.yaml
kubectl exec -it ${HEAD_POD} -- bash
echo $RAY_REDIS_PASSWORD
```
=> [Feature] Read Redis password from Kubernetes Secret

.buildkite/example.yml
```
docker run -it golang:1.17
```
The PATH environment variables of image `golang:1.17` in my devbox and buildkite pipeline are different, so I need to update the PATH in the buildkite script.
#919 
=> [CI][Buildkite] Fix the PATH issue

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
See https://github.com/ray-project/kuberay/issues/928.
Now user can get env var `RAY_CLUSTER_NAME` in head and worker pods.
Closes #928
```shell
rootPath={Your kuberay repo path}
kubectl apply -f $rootPath/ray-operator/config/samples/ray-cluster.complete.yaml
kubectl exec -it $(kubectl get pods -o=name | grep head) -- env | grep RAY_CLUSTER_NAME
kubectl exec -it $(kubectl get pods -o=name | grep worker) -- env | grep RAY_CLUSTER_NAME
kubectl apply -f $rootPath/ray-operator/config/samples/ray-cluster.complete.yaml
kubectl exec -it raycluster-complete-worker-small-group-fw6kk -- env | grep RAY_CLUSTER_NAME
```
=> Inject cluster name as an environment variable into head and worker pods

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
This PR:
1. Inject the `--block` option to the ray start command automatically if the user has not set the `-- block` option. See https://github.com/ray-project/kuberay/pull/675 and https://github.com/ray-project/kuberay/pull/912#issuecomment-1436393712
2.  According to [ray start options document](https://docs.ray.io/en/latest/cluster/cli.html#ray-start), there are many parameters that the user should be able to set in the format `'parameters': 'true'` or `'parameters': 'false'` (e.g `--block`, `--disable-usage-stats`) in `rayStartParams`. However, kuberay can not handle(will fail to run all the pods) if the user set 'parameters': 'false' in rayStartParams. This PR enables the user to set a 'false' value.
**Prove that Without --block, it may take a much longer time to detect the …
=>  Inject the --block option to ray start command automatically

clients/python-client/examples/use-raw-config_map_with-api.py, clients/python-client/examples/use-raw-with-api.py, clients/python-client/python_client/utils/kuberay_cluster_builder.py, clients/python-client/python_client_test/test_api.py, clients/python-client/python_client_test/test_utils.py, helm-chart/ray-cluster/values.yaml, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, tests/config/ray-service.yaml.template
Although we have `autoscalerOptions.imagePullPolicy` to overwrite the default `imagePullPolicy` (Always) in Autoscaler, there are still some reasons to update the default value for `imagePullPolicy`.
1. No Ray image with the tag `latest` is used in KubeRay. In that case, the default image pull policy for Pod should be `IfNotPresent`. See [this doc](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting) for more details.
2. The default image pull policies for head Pod and worker Pods are `IfNotPresent`, but the default image pull policy is `Always`.
3. https://github.com/ray-project/ray/tree/master/python/ray/tests/kuberay => With this PR, we can run the tests locally without updating any line of code. 
Closes #890
```sh …
```
=> [Feature] The default ImagePullPolicy should be IfNotPresent

docs/guidance/prometheus-grafana.md, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Currently, KubeRay always exposes a Prometheus metrics endpoint on port 8080, and users are unable to customize this export port (see issue #864). However, the [Ray documentation](https://docs.ray.io/en/latest/ray-observability/ray-metrics.html#customize-prometheus-export-port) indicates that users are able to set up a custom Prometheus export port.
To better meet the needs of users and maintain consistency with Ray's capabilities, I recommend enabling the customization of the Prometheus export port for KubeRay users.
- Add `metrics-export-port: "{Port Number}"` to `rayStartParams` for head and worker pods.
- Add `containerPort: {Port Number}` to `template.spec.containers[0].ports` for head and worker pods.
**Note, It's user's responsibility to maintain rayStartParam ports and container …
=> Customize the Prometheus export port

ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go
KubeRay is anticipated to provide a Prometheus metrics endpoint on port 8080. 
However, if users specify alternative ports in Spec.HeadGroupSpec.Template.Spec.Containers[ray_index].Ports without setting the metrics port, the head service will exclude the default metrics port. As a result, the service monitor will be unable to scrape metrics. Refer to the following code snippet for the existing logic.
https://github.com/ray-project/kuberay/blob/6490749f4c5044a0ce40fdc653e04b50c052784d/ray-operator/controllers/ray/common/service.go#L158-L163
This can be reproduced by using any [sample yaml files](https://github.com/ray-project/kuberay/tree/master/ray-operator/config/samples), for example, running:
```shell
kind delete cluster
rootPath="/home/ubuntu/kuberay" 
cd $rootPath …
```
=> Fix issue with head pod not monitered by Prometheus under certain condition

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Currently, the init container logic is wrong. It waits for the head service rather than GCS server. The head service will be ready when the image pull finishes. The current retry logic is implemented by Ray internal.
https://github.com/ray-project/kuberay/blob/71e260f2ae906a1a0646f11c9c3e5c332de2c70c/ray-operator/config/samples/ray-cluster.complete.yaml#L124-L129
For example, add `command: ["sleep 180"]` in the headGroupSpec. Then, the head Pod command will be `sleep 180 && ulimit -n 65536; ray start ...`. To clarify, the GCS server requires a minimum of 120 seconds to become ready after the head service is ready. It exceed the timeout of the Ray internal retry mechanism, so the worker will fail.
In this PR, we add a default init container to use `ray health-check` to check the status of …
=> [Feature] Add default init container in workers to wait for GCS to be ready

docs/guidance/aws-eks-iam.md
Users want to access S3 buckets in Ray Pods. See this [slack thread](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1678303095557969) for more context.
#956 
https://github.com/ray-project/ray/issues/33256
=> [Feature][Doc] Access S3 bucket from Pods in EKS

ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
1. In k8s,  [cluster domains](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction) are configuration.  But now kuberay hard coded it to `cluster.local`. So fix this to either read cluster domain from `/etc/resolv.conf` or environmental variable
=> Read cluster domain from resolv.conf or env

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
For computing on cloud, service account is important. For example, we need query data from a private database, but workers dont have permission because missing service account.
Open #967 
- [x ] I've made sure the tests are passing. 
=> [Feature] Add service account section in helm chart

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go
`observedGeneration` is a common pattern in Kubernetes to determine whether the current status is out-of-date or not.
* Good article: [Kubernetes operator best practices: Implementing observedGeneration](https://alenkacz.medium.com/kubernetes-operator-best-practices-implementing-observedgeneration-250728868792)
* [StatefulSet](https://github.com/kubernetes/kubernetes/blob/d2be69ac11346d2a0fab8c3c168c4255db99c56f/pkg/controller/statefulset/stateful_set_utils.go#L575-L586) uses `ObservedGeneration` to determine whether update status or not.
```go
// inconsistentStatus returns true if the ObservedGeneration of status is greater than set's
// Generation or if any of the status's fields do not match those of set's status.
func inconsistentStatus(set *apps.StatefulSet, status …
```
=> [Feature][Hotfix] Add observedGeneration to the status of CRDs

ray-operator/config/samples/ray-cluster.external-redis.yaml
The [Kuberay pull request #950](https://github.com/ray-project/kuberay/pull/950) discusses using Redis password secrets as environment variables, as described in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).
Specifically, a new environment variable `RAY_REDIS_PASSWORD` is created and assigned a value from a secret:
```yaml
- name: RAY_REDIS_PASSWORD
valueFrom:
secretKeyRef:
name: redis-password-secret
key: password
```
Additionally, the rayStartParams configuration includes a reference to this environment variable:
```yaml
redis-password: $REDIS_PASSWORD
```
However, the current Kuberay implementation sets another environment variable, `REDIS_PASSWORD` based on …
=> Improve ray-cluster.external-redis.yaml

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, helm-chart/ray-cluster/values.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml
See https://github.com/ray-project/kuberay/issues/931
Closes #931
=> Add rayVersion in the RayCluster chart

docs/guidance/tls.md, ray-operator/config/samples/ray-cluster.tls.yaml, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go
Ray can be configured to use TLS on it’s gRPC channels ([ref](https://docs.ray.io/en/latest/ray-core/configure.html#tls-authentication)). However, the document requires users to have related knowledge about TLS, HTTPS, and basic cryptography to create correct public-private key pairs, self-signed certificates, and certificate authority.
In KubeRay, users also need to know how does head / workers communicate with each other.
* head uses `POD_IP` to communicate with worker.
* worker uses the fully qualified domain name of the head service (i.e. `FQ_RAY_IP`) to communicate with the head.
Hence, head needs to have `FQ_RAY_IP`'s certificate, and worker requires the certificate of its `POD_IP`.
Configuring TLS in KubeRay can be a challenging task for users. To ease this process, this PR offers …
=> [Feature] TLS authentication

.github/workflows/test-job.yaml, clients/python-client/requirements.txt
Testing python client library in CI.
Though currently, the test does not interact with the k8s cluster, the __init__ function in kuberay_cluster_api will load kube config, which will report errors if there is no k8s server.
=> [Feature] Add python client test to action

ray-operator/controllers/ray/utils/dashboard_httpclient.go
In RayJob, the HTTP client submits a job to the RayCluster only when all Pods are running. However, the readiness of Pods does not necessarily imply that the dashboard is ready. Furthermore, the HTTP client has a timeout of 2 seconds, which is shorter than the time required for the dashboard to initialize. Hence, a weird behavior may happen: 
During job submission in KubeRay operator, HTTP clients may fail due to timeout, even though the RayCluster receives the request and launches the job successfully. The KubeRay operator resubmits the job because it thinks that the submission has failed. However, @architkulkarni discovered that resubmitting a job with the same name as a previously submitted job can cause the first submission to fail. This bug was fixed in Ray 2.4.0. Bug: …
=> [Hotfix][release blocker][RayJob] HTTP client from submitting jobs before dashboard initialization completes

clients/python-client/python_client/utils/kuberay_cluster_utils.py
1. Verify the built clusters in examples of the python client library are functional.
2. Remove init containers in template because there will be default init container in v0.5.0([#973](https://github.com/ray-project/kuberay/pull/973)).
Cover the following examples: [use-builder.py](https://github.com/ray-project/kuberay/blob/master/clients/python-client/examples/use-builder.py), [use-director.py](https://github.com/ray-project/kuberay/blob/master/clients/python-client/examples/use-director.py), [use-raw-config_map_with-api.py](https://github.com/ray-project/kuberay/blob/master/clients/python-client/examples/use-raw-config_map_with-api.py), [use-raw-with-api.py](https://github.com/ray-project/kuberay/blob/master/clients/python-client/examples/use-raw-with-api.py), …
=> Release v0.5.0 python client library validation

.github/workflows/test-job.yaml, clients/python-client/requirements.txt, clients/python-client/setup.cfg
The kuberay python-client library uses Kubernetes Python Client. Hence, it is necessary to make Kubernetes Python Client be the prerequisite when installing kuberay python-client library.
=> Add kubernetes dependency in python client library

README.md, docs/deploy/docker.md, docs/deploy/installation.md, docs/guidance/autoscaler.md, docs/guidance/aws-eks-iam.md, docs/guidance/kubeflow-integration.md, docs/guidance/prometheus-grafana.md, helm-chart/kuberay-operator/Chart.yaml, helm-chart/kuberay-operator/README.md, helm-chart/ray-cluster/Chart.yaml, helm-chart/ray-cluster/README.md, manifests/overlays/single-namespace-resources/kustomization.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml
1. This PR mainly focuses on correctness validation rather than document improvement.
2. Use the nightly KubeRay operator image to test the documents.
```sh
RAY_IMAGE=rayproject/ray:2.3.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_raycluster_yamls.py 2>&1 | tee log
```
<details>
<summary>Screenshot</summary>
</details>
```sh
RAY_IMAGE=rayproject/ray:2.3.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_rayservice_yamls.py 2>&1 | tee log
```
<details>
<summary>Screenshot</summary>
</details>
* Since we have chosen to make the entire Kubernetes Service configurable (https://github.com/ray-project/kuberay/issues/877) to users, this PR removes `headServiceAnnotations` from the YAML.
```sh
helm template kuberay-operator . | kubectl apply -f -
kubectl …
```
=> Release v0.5.0 doc validation

mkdocs.yml
There were some doc files that were missing from the nav so were hard or impossible to access from the front page of the docs.  This PR adds them to the nav and groups them better to avoid having a long list of files.
=> [Doc] Update nav to include missing files and reorganize nav

docs/best-practice/worker-head-reconnection.md, docs/guidance/gcs-ft.md
Update docs for best practice docs.
for kuberay 0.5.0 we mark the GCS FT feature to stable.
=> Kuberay 0.5.0 docs validation update docs for GCS FT

apiserver/pkg/util/cluster.go, clients/python-client/examples/use-raw-with-api.py, clients/python-client/python_client_test/test_api.py, clients/python-client/python_client_test/test_utils.py, helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml, tests/config/ray-cluster.mini.yaml.template, tests/config/ray-cluster.ray-ft.yaml.template, tests/config/ray-service.yaml.template
See https://github.com/ray-project/kuberay/pull/973 for more details.
* KubeRay APIServer
* Python client
* Helm Charts
* Sample YAML files
* RayCluster
* RayJob 
* RayService
* Template YAML files for end-to-end tests => KubeRay CI
```sh
RAY_IMAGE=rayproject/ray:2.3.0 OPERATOR_IMAGE=kuberay/operator:v0.5.0 python3 tests/test_sample_raycluster_yamls.py 2>&1 | tee log
```
```sh
RAY_IMAGE=rayproject/ray:2.3.0 OPERATOR_IMAGE=kuberay/operator:v0.5.0 python3 tests/test_sample_rayservice_yamls.py 2>&1 | tee log
```
```sh
kind create cluster --image=kindest/node:v1.23.0
helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0
helm install raycluster .
```
```sh
OPERATOR_IMAGE=kuberay/operator:v0.5.0 python3 tests/test_security.py
```
```sh …
```
=> [Post v0.5.0] Remove init containers from YAML files

apiserver/DEVELOPMENT.md, docs/development/development.md, mkdocs.yml, proto/README.md
The current dev guide is accurate and concise, but there is room to improve clarity and readability, which is the aim of this PR.  Note: I used GPT for the first copyediting pass and I reviewed it manually to ensure the changes were positive and the underlying meaning did not change.
=> [Doc] Copyedit dev guide

.github/workflows/actions/configuration/action.yaml, clients/python-client/examples/use-raw-with-api.py, clients/python-client/python_client_test/test_api.py, clients/python-client/python_client_test/test_utils.py, docs/guidance/volcano-integration.md, ray-operator/apis/ray/v1alpha1/rayjob_types_test.go, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/samples/ray-cluster.head-command.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray-cluster.mini.yaml, ray-operator/config/samples/ray-cluster.tls.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, tests/framework/utils.py
For KubeRay, the configuration YAML files (e.g. files in ray-operator/config/samples) in the master branch must be compatible with:
* Nightly KubeRay operator
* Latest release of KubeRay operator (i.e. v0.5.0 at this moment)
The field `serviceType` is a required field before v0.5.0, but becomes optional from v0.5.0. Hence, when v0.5.0 becomes the "latest release of KubeRay operator", we can remove it from sample YAML files.
We only keep the optional fields in `ray-cluster.complete.yaml`, `ray-cluster.complete.large.yaml`, and RayCluster chart's `values.yaml`.
Closes #856 
* KubeRay operator tests (i.e. `xxxx.go`)
```sh
make test
```
* Test RayCluster YAML files
```sh
RAY_IMAGE=rayproject/ray:2.3.0 OPERATOR_IMAGE=kuberay/operator:v0.5.0 python3 …
```
=> [Post release v0.5.0] Remove serviceType

docs/guidance/volcano-integration.md, helm-chart/ray-cluster/values.yaml, ray-operator/config/samples/ray-cluster.autoscaler.large.yaml, ray-operator/config/samples/ray-cluster.autoscaler.yaml, ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.complete.yaml, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/config/samples/ray-cluster.head-command.yaml, ray-operator/config/samples/ray-cluster.heterogeneous.yaml, ray-operator/config/samples/ray-cluster.mini.yaml, ray-operator/config/samples/ray-cluster.tls.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml, tests/config/ray-cluster.mini.yaml.template, tests/config/ray-cluster.ray-ft.yaml.template, tests/config/ray-service.yaml.template
From v0.5.0, we inject `--block` in the `rayStartParams` automatically in #932. We remove `block` from YAML files after release v0.5.0 to follow the compatibility philosophy (#940) of KubeRay. 
There are still some instances of `block: "true"` in KubeRay operator tests and the Python client. However, since users will not touch them, it is okay to skip them for now and continue with the release process.
#940 
=> [Post release v0.5.0] Remove block from rayStartParams

ray-operator/controllers/ray/rayservice_controller.go
Current logic will cause the ray-operator keep sending requests when there is no deployment statuses.  When the runtime env preparation time is long, ray-operator will keep redeploying the ray serve cluster.
So after ray-operator sends the config request, it will eventually get the status from ray serve.
Collaborating with customer to fix the runtime env issue, and verify RayService can be started with this change.
Config:
Change `serveConfig` in `ray-operator/config/samples/ray_v1alpha1_rayservice.yaml` to 
```
serveConfig:
importPath: test_grpc:entry
runtimeEnv: |
working_dir: "https://github.com/sihanwang41/test-placeholder/raw/main/grpc_test.zip"
```
=> Fix config frequent update

docs/development/release.md
* Update the release document and improve the release process based on the learnings from v0.5.0.
* Update the format from 1,2,3 to headings because the former will make some issues for mkdocs.
I checked both markdown and mkdocs.
* mkdocs
```sh
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```
=> [Post release v0.5.0] Update release doc

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
```sh
(base) ➜  ray-cluster git:(fix-helm-chart) helm install raycluster .
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(RayCluster.spec.workerGroupSpecs[0]): missing required field "rayStartParams" in io.ray.v1alpha1.RayCluster.spec.workerGroupSpecs
```
Currently, `rayStartParams` is a required field now, so we need to use `rayStartParams: {}` if `rayStartParams` in values.yaml is empty. 
```yaml
dashboard-host: '0.0.0.0'
initArgs:
111: 222
helm template .
rayStartParams: {}
initArgs:
111: 222
helm template .
```
=> [Bug] rayStartParams is required at this moment.

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
Should fix https://github.com/ray-project/kuberay/issues/1038
(https://github.com/ray-project/kuberay/issues/1038)
-  Manual tests
=> [Helm][ray-cluster] Fix parsing envFrom field in additionalWorkerGroups

docs/guidance/tls.md, ray-operator/config/samples/ray-cluster.tls.client.yaml, ray-operator/config/samples/ray-pod.tls.yaml
Provide an example of connect Ray client to a remote Ray cluster with TLS enabled on the ray client port.
Closes #992
Setup the environment
```bash
kubectl cluster-info --context kind-kind
export KUBERAY_VERSION=v0.5.0
kubectl create -k "github.com/ray-project/kuberay/ray-operator/config/default?ref=${KUBERAY_VERSION}&timeout=90s"
git clone https://github.com/tedhtchang/kuberay
cd kuberay
git checkout connect-remote-raycluster-tls
kubectl apply -f ray-operator/config/samples/ray-cluster.tls.yaml
kubectl apply -f ray-operator/config/samples/ray-pod.tls.yaml
kubectl logs ray-client-tls
```
Verify the log contains IP of the head node.
```
Defaulted container "client" out of: client, gen-cert (init)
OpenBLAS WARNING - could not determine the L2 cache size on this system, …
```
=> Example Pod to connect Ray client to remote a Ray cluster with TLS enabled

README.md, docs/guidance/ingress.md, docs/guidance/kubeflow-integration.md, docs/guidance/observability.md, docs/guidance/pod-command.md, docs/guidance/prometheus-grafana.md, docs/guidance/tls.md, docs/index.md
* Fix layout issues of KubeRay website. See https://github.com/ray-project/kuberay/issues/1021 for more details.
* Update the introduction of KubeRay.
#1021 
```sh
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```
=> [Doc][Website] Update KubeRay introduction and fix layout issues

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Flyte will create `ResourceQuota` for each Kubernetes namespace. To support `ResourceQuota`, each container in the namespace requires setting resource limits. However, the injected health-check init container does not specify the resource limits.
**Why am I using the same resource configurations for the init container as those used in the Ray container?**
In Kubernetes Pod, all init containers will be executed in a sequence, one by one, and each init container must complete successfully before the next one starts. On the other hands, when all init containers complete successfully, all application containers will start in parallel, and the startup order is arbitrary.
For example, we have 3 init containers and 3 application containers. The execution order will be:
init1 -> init2 -> init3 -> …
=> [Bug] Enable ResourceQuota by adding Resources for the health-check init container

ray-operator/apis/ray/v1alpha1/raycluster_types_test.go, ray-operator/apis/ray/v1alpha1/rayjob_types_test.go, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/config/samples/ray-cluster.external-redis.yaml, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, tests/compatibility-test.py, tests/config/ray-cluster.ray-ft.yaml.template
When we kill the GCS server process (`pkill gcs_server`) on the head Pod, a Raylet (?) will exit the process if it cannot connect to the GCS server after `RAY_gcs_rpc_server_reconnect_timeout_s` ([code](https://sourcegraph.com/github.com/ray-project/ray@3aa6ede43743a098b5e0eb37ec11505f46100313/-/blob/src/ray/rpc/gcs_server/gcs_rpc_client.h?L527-L546)). By default, the value is 60s.
In #634, the `RAY_gcs_rpc_server_reconnect_timeout_s` values for both head and workers are set to 60 seconds. This means that the head and workers will crash almost simultaneously, 60 seconds after the GCS server process is terminated. Therefore, we need to ensure that the `RAY_gcs_rpc_server_reconnect_timeout_s` for the workers is greater than the time it takes for a new GCS server process to become available …
=> [Bug][GCS FT] Worker pods crash unexpectedly when gcs_server on head pod is killed

tests/compatibility-test.py, tests/config/ray-cluster.ray-ft.yaml.template, tests/config/ray-service.yaml.template, tests/framework/prototype.py
* Use HTTP request to verify serve deployment after the cluster recovers from a failure to fix https://github.com/ray-project/ray/issues/34799.
* For Ray 2.1.0, containers require tens of seconds to become "READY" after the Pod is running. In addition, the serve deployment takes few seconds to be ready to serve requests after all containers are "READY".
* With #1036, the worker Pods will not crash after the GCS server process is killed. Hence, the output of `test_detached_actor_2.py` may be different based on the actor is assigned to the head or a worker. `test_detached_actor_1.py` calls `increment()` twice, and `test_detached_actor_2.py` calls `increment()` once. Hence, if the actor is scheduled on a worker, the output of `test_detached_actor_2.py` should be 3. On the other hand, the …
=> [Bug] compatibility test for the nightly Ray image fails

ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go
`BuildServiceForHeadPod` method creates the `corev1.Service` object without ensuring the order of ports. When the  `rayservice_controller` reconciliation loop updates the Service Spec, K8s detects a change in the  and applies it. This will lead to a performance degradation.
Closes [1044](https://github.com/ray-project/kuberay/issues/1044)
=> Fix in HeadPod Service Generation logic which was causing frequent reconciliation

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
The experiment result in #1062 shows that `r.Status().Update()` occurred 48 times during the RayCluster initialization phase and 239 times after the RayCluster completed the initialization process within 10 minutes. Hence, this PR mainly focuses on relieving the frequent status update caused by `r.Status().Update() Final status update for any CR modification.`.
The root cause is that `r.Status().Update()` is called at the end of the function `Reconcile` no matter whether it should be updated or not. The frequent status update will hurt the performance of the Kubernetes cluster. 
Refer to the source code of [ReplicaSet](https://sourcegraph.com/github.com/kubernetes/kubernetes@9e622d23648f4af4a12835de97484dc0e4859269/-/blob/pkg/controller/replicaset/replica_set_utils.go?L41-L48) and …
=> RayService object's Status is being updated due to frequent reconciliation

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
According to [this discussion](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1683240364495989), users may need to adjust the ImagePullPolicy of the init container, which is currently set to `PullIfNotPresent`.
This PR aligns the init container's ImagePullPolicy with the ImagePullPolicy of the ray container.
None
1. Add the line `imagePullPolicy: Always` to the `workerGroupSpecs[0].template.spec.containers[0]` in the `ray-cluster.complete.yaml` file(can be found [here](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.complete.yaml))
2. 
```shell
kubectl apply -f /home/ubuntu/workspace/kuberay/ray-operator/config/samples/ray-cluster.complete.yaml
```
4. 
```shell
kubectl get pod raycluster-complete-worker-small-group-pfzbm -o yaml
```
Here …
=> Align Init Container's ImagePullPolicy with Ray Container's ImagePullPolicy

helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/config/samples/ray-service.different-port.yaml, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/fake_httpproxy_httpclient.go, ray-operator/controllers/ray/utils/httpproxy_httpclient.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
Without this PR, users can only serve requests via port 8000.
To serve requests via another port (e.g. 9000), user needs to specify `spec.serveConfig.port` and the head Pod's `serve` port to 9000. See [RESTful API](https://docs.ray.io/en/master/serve/api/index.html#put-api-serve-deployments) and [single-application config schema](https://docs.ray.io/en/master/serve/api/doc/ray.serve.schema.ServeApplicationSchema.html#ray.serve.schema.ServeApplicationSchema) for more details.
The HTTPProxy is used to check the health condition ([code](https://sourcegraph.com/github.com/ray-project/ray@d5b470140b4d7dc5724f69d12551c42f4a4957c4/-/blob/python/ray/serve/_private/http_proxy.py?L385-L395)) of Serve deployments. If the Serve deployments are healthy, the HTTPProxy will add the label …
=> [Bug] Service (Serve) changing port from 8000 to 9000 doesn't work

helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go
Native Kubernetes Jobs have a `suspend` [flag](https://kubernetes.io/docs/concepts/workloads/controllers/job/#suspending-a-job) that allows to temporarily suspend a Job execution and resume it later, or start Jobs in a suspended state and have a custom controller, such as [Kueue](https://kueue.sigs.k8s.io/), decide later when to start them.
So adding it to `RayJob` `spec` for consistency. Moreover, some frameworks like Kubeflow are adding it, so it becomes a standard functionality. An example implementation for MPIJob: https://github.com/kubeflow/mpi-operator/pull/511
* If a `RayJob` is created with a `spec.suspend` == `true`, then `RayCluster` instance (with corresponding Kubernetes resources) is not created and the Ray job is not submitted to the cluster. The `JobDeploymentStatus` is …
=> [Feature] Support suspend in RayJob

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go
When submitting a Ray job to Kubernetes with the autoscaler, the following behaviors can be observed:
1. A new worker pod is created as the autoscaler increases the number of replicas.
2. An existing worker is terminated simultaneously.
3. The total number of worker pods remains equal to the original replica count.
The root cause is that both the autoscaler and the RayJob controller are trying to update the replicas, causing worker pods to be repeatedly created and terminated.
So, This PR:
1. Preventing Ray job controllers from updating the RayCluster when the autoscaler is enabled.
2.  Even when the autoscaler is not enabled, Ray job controller only modifies the replica, rather than the entire RayClusterSpec.
The reproduction file can be found here: …
=> [Bug] autoscaler not working properly in rayjob 

ray-operator/config/samples/ray_v1alpha1_rayjob.yaml
https://github.com/ray-project/kuberay/pull/926 adds the `suspend: false` field to `ray_v1alpha1_rayjob.yaml`. However, since this field is new and not present in the CRD of kuberay/operator:v0.5.0, it would compromise backwards compatibility.
We need to ensure that sample files function with both the 0.5.0 and nightly versions, so we shouldn't add `suspend: false `now, but only after the 0.6.0 release.
The failure can  be reproduced:
1. introducing `suspend: false` will cause the Sample YAML Config Test - 2.4.0 to consistently fail :
```
error: error validating "/home/runner/work/kuberay/kuberay/ray-operator/config/samples/ray_v1alpha1_rayjob.yaml": error validating data: ValidationError(RayJob.spec): unknown field "suspend" in io.ray.v1alpha1.RayJob.spec; if you choose to ignore these …
```
=> Fix for Sample YAML Config Test - 2.4.0 Failure due to 'suspend' Field 

ray-operator/controllers/ray/batchscheduler/interface/interface.go, ray-operator/controllers/ray/batchscheduler/schedulermanager.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler_test.go, ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/common/ingress_test.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/rbac.go, ray-operator/controllers/ray/common/rbac_test.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/suite_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
cc @kevin85421  the PR is ready for review. I deployed using the instructions in development.md. I tested with the smallest sample: https://raw.githubusercontent.com/ray-project/kuberay/master/ray-operator/config/samples/ray-cluster.mini.yaml
Closed #1079
=> feat: Rename instances of rayiov1alpha1 to rayv1alpha1

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/config/samples/ray-cluster.autoscaler.tls.yaml, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
This PR adds the ability to mount volumes in AutoscalerOptions to enable TLS in Autoscaler.  At the moment, if you enable TLS and the autoscaler, the autoscaler is unable to connect to the Ray head because the certificates doesn't exist and there was no way to mount volumes where the certs reside like what you can do in the other containers [for example](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.tls.yaml#L56-L60)
This PR adds the ability to mount volumes in the AutoscalerOptions so we can mount the TLS volumes.
No github issue but here's the Slack chat for more context - https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1684511397156609
=> [Bug] Autoscaler doesn't support TLS

ray-operator/DEVELOPMENT.md, ray-operator/Makefile
cc @kevin85421 
This parametrizes the Makefile we are using to build and push Ray Operator images.
Closes #1116 
I did not run manual tests as this is just modifying the makefile for image builds/push.
=> Parametrize ray-operator makefile

.github/workflows/consistency-check.yaml, .github/workflows/test-job.yaml, ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/hack/verify-generated-files.sh
Checks consistency for deepcopy generated files
Closes #1111
=> Add consistency check for deepcopy generated files

ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go
This PR addresses a bug in the `BuildServiceForHeadPod` function where a nil map was not properly handled when building the head service for a Ray cluster. This caused a panic when attempting to add labels and annotations to uninitialized maps.
Changes include:
1. A fix in the `BuildServiceForHeadPod` function to correctly initialize the `Labels` and `Annotations` maps if they are nil. 
2. A unit test that specifically tests the scenario of nil maps in the input `HeadService`. 
With this fix, the function can safely handle nil maps and ensures that the `Labels` and `Annotations` of the head service are always properly initialized, which prevents runtime errors when attempting to modify these maps.
=> [Bug] Fix null map handling in `BuildServiceForHeadPod` function

helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/templates/leader_election_role.yaml, helm-chart/kuberay-operator/templates/leader_election_role_binding.yaml, helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml, helm-chart/kuberay-operator/templates/multiple_namespaces_rolebinding.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayjob_viewer_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_editor_role.yaml, helm-chart/kuberay-operator/templates/ray_rayservice_viewer_role.yaml, helm-chart/kuberay-operator/templates/rolebinding.yaml, helm-chart/kuberay-operator/values.yaml, ray-operator/DEVELOPMENT.md, ray-operator/config/rbac/leader_election_role.yaml, ray-operator/main.go
Currently, KubeRay supports the following options:
* Watching all custom resources in the Kubernetes cluster: This is the default setting, which installs cluster-scoped RBAC resources (i.e., ClusterRole and ClusterRoleBinding).
* Watching only the namespace where the operator is deployed: This is achieved by setting `singleNamespaceInstall` to true, which installs namespaced RBAC resources (i.e., Role and RoleBinding).
However, for users who only have namespaced access, they would need to deploy one KubeRay operator for each namespace. This can increase the maintenance overhead, such as upgrading the version of KubeRay for each deployed instance.
This PR implements a feature that supports users to deploy a KubeRay operator to watch multiple namespaces without installing ClusterRole and …
=> [Feature] Watch CR in multiple namespaces with namespaced RBAC resources

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
cc @kevin85421 
Closes #1089 
I deployed using the instructions in development.md. I tested with the smallest sample: https://raw.githubusercontent.com/ray-project/kuberay/master/ray-operator/config/samples/ray-cluster.mini.yaml
=> ray-operator: Reuse contexts across ray operator reconcilers

helm-chart/ray-cluster/values.yaml, ray-operator/config/samples/ray-service.autoscaler.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go
In #1123, the autoscaler container fails to GET the RayCluster from the Kubernetes API Server and receives error code 401 after a zero-downtime upgrade. If you are interested in the root cause, you can read the "debug process" section.
We have two solutions for this issue:
* Solution 1: Still create a ServiceAccount for users if the specified `ServiceAccountName` does not exist. The only difference is that we do not set the ControllerReference for the ServiceAccount to avoid it being deleted by the Kubernetes garbage collector. (Step 5 in the section **"3. Root cause of this issue"**)
* (+) More backward-compatible
* (-) Users need to delete the ServiceAccount themselves, which may introduce "unknown unknowns" for users.
* Solution 2 (this PR): If users specify ServiceAccountName, they …
=> [Bug][breaking change] Unauthorized 401 error on fetching Ray Custom Resources from K8s API server

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go
The function `updateLocalWorkersToDelete` will update `WorkersToDelete` by filtering out Pods that are not included in `runningPods`. Hence, Pods with the status `PodFailed` are not deleted permanently.
In the autoscaler scale-down process, the autoscaler adds a failed Pod to `WorkersToDelete` and waits for all Pods in `WorkersToDelete` to be deleted before making the next decision. You can find the corresponding code [here](https://sourcegraph.com/github.com/ray-project/ray@ray-2.4.0/-/blob/python/ray/autoscaler/_private/kuberay/node_provider.py?L324-L329). However, the failed Pods will not be deleted by operator because of `updateLocalWorkersToDelete`.
* Note (optional): The definition of `non_terminated_nodes` in Autoscaler ([link](https://sourcegraph.com/github.com/ray-project/ray@cd1b …
=> [Bug][Autoscaler] Operator does not remove workers

apiserver/pkg/util/cluster.go, apiserver/pkg/util/cluster_test.go
Users may wish to add PVC volumes to Ray pods instead of hostPath volumes as its [recommended](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) to avoid hostPath volumes when possible due to security risks. Plus, it was something [already marked](https://github.com/ray-project/kuberay/blob/f6a172f3d7e44d4ee22bd058f2c33a69601c39c2/apiserver/pkg/util/cluster.go#L387) to be implemented.
#1087 
- [ X ] I've made sure the tests are passing. 
- [ X ] Unit tests
=> Add support for pvcs to apiserver

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
We are currently using Ray for computing heavily tasks on GKE. When initializing, it spawns a worker each worker group. Then, it triggers GKE scale up node. It's money cost. 
This happens because ternary function in template file. `{{ 0 | 1 }} = 1`
https://github.com/ray-project/kuberay/blob/87dde227d95457949a22a6cfea41bfbaeca46116/helm-chart/ray-cluster/templates/raycluster-cluster.yaml#L91
https://github.com/ray-project/kuberay/blob/87dde227d95457949a22a6cfea41bfbaeca46116/helm-chart/ray-cluster/templates/raycluster-cluster.yaml#L157
workaround by setting default replica to zero.
Open #965 
=> [Bug] Allow zero replica for workers for Helm

ray-operator/config/security/ray-cluster.pod-security.yaml
The existing sample YAML was pinned to Ray 2.2.0.  Running the test locally failed with 
```
2023-06-12:14:21:56,768 INFO     [utils.py:163] Execute command: kubectl logs -n=pod-security -l ray.io/node-type=head --tail=-1
Error from server (BadRequest): container "ray-head" in pod "raycluster-pod-security-head-hg67c" is waiting to start: ContainerCreating
ERROR
======================================================================
ERROR: test_ray_cluster_with_security_context (__main__.PodSecurityTestCase)
Create a RayCluster with securityContext config under restricted mode.
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests/test_security.py", line 98, in test_ray_cluster_with_security_context …
```
=> [Sample YAML] Bump ray version in pod security YAML to 2.4.0

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Related slack thread: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1686170239143299
* Without this PR, the values in the column `Disk(root)` are `0.0000B/1.0000B`.
* With this PR, everything works fine.
=> [Ray Observability] Disk usage in Dashboard

ray-operator/config/security/ray-cluster.pod-security.yaml
Cherry pick of #1160 to the 0.5.2 release branch.  Context from that PR is copied below for convenience.
----
The existing sample YAML was pinned to Ray 2.2.0. Running the test locally failed with
2023-06-12:14:21:56,768 INFO     [utils.py:163] Execute command: kubectl logs -n=pod-security -l ray.io/node-type=head --tail=-1
Error from server (BadRequest): container "ray-head" in pod "raycluster-pod-security-head-hg67c" is waiting to start: ContainerCreating
ERROR
====================================================================== ERROR: test_ray_cluster_with_security_context (__main__.PodSecurityTestCase) Create a RayCluster with securityContext config under restricted mode. ---------------------------------------------------------------------- Traceback (most recent call last):
File …
=> [Sample YAML] Bump ray version in pod security YAML to 2.4.0 (#1160)

docs/release/changelog.md
I had to run an extra `git fetch` command to get the `git log` command to work.  This PR adds it to the instructions to make them more beginner-friendly.
=> [Doc] Add git fetch --tags command to release instructions

docs/guidance/ingress.md, ray-operator/config/samples/ray_v1alpha1_rayservice-alb-ingress.yaml
three updates comparing with [this](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/alb-ingress.yaml)
- Update the service name to `rayservice-sample-serve-svc`
- Update the port to 8000.
- Health check.
With these two changes, customer will have workable CR out of the box for Ray Service.
Tested with eks.
I will put more details into the ray doc.
=> [RayService] Add RayService alb ingress CR

helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml, helm-chart/kuberay-operator/templates/multiple_namespaces_rolebinding.yaml, helm-chart/kuberay-operator/values.yaml
https://github.com/ray-project/kuberay/pull/1106#issuecomment-1578439022
(1) Users can set `rbacEnable`: false and `serviceAccount.create: false` to prevent the creation of any RBAC resources.
(2) Users can use the `singleNamespaceInstall` option to determine whether to create namespaced RBAC resources (e.g., Role and RoleBinding) or cluster-scoped RBAC resources (e.g., ClusterRole and ClusterRoleBinding).
(3) If `singleNamespaceInstall` is set to true, users can use the `watchNamespace` option to determine in which namespaces the Role and RoleBinding should be installed. If watchNamespace is not set, the Role and RoleBinding will be installed in the same namespace as the KubeRay operator.
(A) Role for leader election
(B) Role for RayCluster preparation (e.g., Pods, Services) 
(C) …
=> [Helm][RBAC] Introduce the option crNamespacedRbacEnable to enable or disable the creation of Role/RoleBinding for RayCluster preparation

ray-operator/DEVELOPMENT.md
In the development workflow, unit tests are automatically run when building the Docker image.  These can take 2+ minutes to complete.
This PR adds an instruction for skipping this step, which allows for faster iteration speed.
=> Add instruction to skip unit tests in DEVELOPMENT.md

ray-operator/config/samples/ray-service.autoscaler.yaml, tests/compatibility-test.py, tests/framework/prototype.py, tests/framework/utils.py, tests/kuberay_utils/utils.py, tests/test_sample_rayservice_yamls.py
4 e2e tests for RayService:
- deploy 2 applications
- deploy then execute in place update
- deploy then execute zero downtime rollout
- autoscaling
The e2e tests should be run with the following command:
```
RAY_IMAGE=rayproject/ray:2.5.0 OPERATOR_IMAGE=controller:latest pytest -vs tests/test_sample_rayservice_yamls.py --log-cli-level=INFO
```
To run a specific test in `test_sample_rayservice_yamls.py`, specify the test name with `-k`, e.g:
```
RAY_IMAGE=rayproject/ray:2.5.0 OPERATOR_IMAGE=controller:latest pytest -vs tests/test_sample_rayservice_yamls.py -k test_service_autoscaling --log-cli-level=INFO
```
=> [RayService] Add e2e tests

ray-operator/config/samples/ray-service.autoscaler.yaml
Change the repo used for the runtime env for the autoscaling e2e test to [ray-project/test_dag](https://github.com/ray-project/test_dag/tree/master).
=> [RayService] Change runtime env for e2e autoscaling test

docs/guidance/mobilenet-rayservice.md, ray-operator/config/samples/ray-service.mobilenet.yaml
=> MobileNet example

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/util.go
```
500 Internal Server Error Traceback (most recent call last):
File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/optional_utils.py", line 279, in decorator
raise e from None
File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/optional_utils.py", line 271, in decorator
ray.init(
File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
return func(*args, **kwargs)
File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 1509, in init
_global_node = ray._private.node.Node(
File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/node.py", line 244, in __init__
node_info = ray._private.services.get_node_to_connect_for_driver(
File …
```
=> [Bug] KubeRay operator fails to get serve deployment status due to 500 Internal Server Error

ray-operator/DEVELOPMENT.md
Previously there were no instructions about the `gofumpt` linter.  External contributors had to figure it out themselves when the Lint step failed in CI for their PR.
This PR adds the linting instructions to the development documentation.  These instructions were originally written by @shrekris-anyscale.
=> [Doc] Add gofumpt lint instructions

docs/guidance/rayservice.md
Make some small changes to the RayService docs so that it matches with the new multi-application sample rayservice yaml file.
=> [RayService] Update docs to use multi-app

helm-chart/kuberay-apiserver/templates/route.yaml, helm-chart/kuberay-apiserver/values.yaml
API server Helm chart allows creating an ingress, but for the OpenShift, the default way to expose services is the usage of Route. This PR adds support for Routes creation
- [x ] Manual tests
=> Add support for openshift routes

.github/workflows/consistency-check.yaml, helm-chart/kuberay-operator/templates/rolebinding.yaml, helm-chart/script/rbac_test.py, scripts/requirements.txt
* RBAC files
* `leader_election_role.yaml` / `leader_election_rolebinding.yaml` => Role / RoleBinding for leader election
* `role.yaml` / `rolebinding.yaml` => ClusterRole / ClusterRoleBinding for KubeRay operator to create Kubernetes resources for custom resources 
* `multiple_namespaces_role.yaml` / `multiple_namespaces_rolebinding.yaml` => Role / RoleBinding in multiple namespaces for KubeRay operator to create Kubernetes resources for custom resources
* Test: Firstly, I wanted to try https://github.com/helm-unittest/helm-unittest, but it turned out to be not as versatile as expected.
Closes #1186 
=> [Bug] KubeRay tries to create ClusterRoleBinding when singleNamespaceInstall and rbacEnable are set to true

docs/guidance/FAQ.md
Adding FAQs to assist Users with Troubleshooting.
Closes #1130
=> Add FAQ page

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/util.go
Without #1173, the Kubernetes service for the dashboard agent uses a round-robin algorithm to evenly distribute traffic among the available Pods, including the head Pod and worker Pods. This may cause stability issues. Hence, #1173 decides to only send the requests to the head service's 52365 (dashboard agent port). The dashboard agent service is no longer used after #1173, so this PR aims to remove the service.
1. Merge `setAgentListPortStartParams` into `setMissingRayStartParams`: The function `setAgentListPortStartParams` will always be called after `setMissingRayStartParams` and both have very similar functionalities. Hence, there is no reason to keep them as two separate functions.
2. Remove `RayClusterDashboardServiceLabelKey: utils.GenerateDashboardAgentLabel(rayClusterName)` from …
=> [Refactor] Remove Dashboard Agent service

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go
This PR is similar to #1065. Without this PR, the RayCluster reconciler will update the CR's status in every reconciliation. Refer to the source code of [ReplicaSet](https://sourcegraph.com/github.com/kubernetes/kubernetes@9e622d23648f4af4a12835de97484dc0e4859269/-/blob/pkg/controller/replicaset/replica_set_utils.go?L41-L48) and [StatefulSet](https://sourcegraph.com/github.com/kubernetes/kubernetes@9e622d2/-/blob/pkg/controller/statefulset/stateful_set_utils.go?L577-L586). They will check the difference between the original status and the new status to determine whether update the status or not. Hence, this PR implements a similar function `inconsistentRayClusterStatus` to determine whether update status or not.
#1182
* I conducted an experiment similar to #1214. In …
=> RayCluster updates status frequently

docs/guidance/prometheus-grafana.md
The [web page](https://ray-project.github.io/kuberay/guidance/prometheus-grafana/) contains some unreachable files due to file path issues.
For example, when we click `install.sh script`, the result is `404 Not found`
None
=> [Doc][Website] Add complete document link

docs/guidance/rayservice-troubleshooting.md
=> [RayService][Doc] RayService troubleshooting handbook

docs/guidance/gcp-gke-gpu-cluster.md, docs/guidance/stable-diffusion-rayservice.md
This document heavily references https://github.com/ray-project/aviary/blob/master/docs/kuberay/deploy-on-gke.md.
1. Follow this document to create a GKE cluster with GPU
2. Deploy the Stable Diffusion example.
=> [Doc] GKE GPU cluster setup

docs/guidance/FAQ.md, docs/guidance/rayservice-troubleshooting.md, docs/index.md, mkdocs.yml
Improve FAQ page and RayService troubleshooting guide.
=> [Doc] Improve FAQ page and RayService troubleshooting guide

docs/guidance/rayjob.md, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml
- Updates the sample YAML to include submitterPodTemplate.  Commented out because it's optional.
- Updates the markdown doc to include submitterPodTemplate.
- Miscellaneous fixes, such as adding missing fields to the doc or sample YAML.
TODO before merge:
Closes #1227 
=> [Doc] [RayJob] Add documentation for submitterPodTemplate

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go
Without this PR, the `rayServiceClusterStatus.DashboardStatus.HealthLastUpdateTime` would be initialized by the `updateAndCheckDashboardStatus` function at a very early stage because the `FetchHeadServiceURL` function ([code](https://github.com/ray-project/kuberay/blob/422098d1f8308e4419f9617eb8c112d255a9fdc8/ray-operator/controllers/ray/rayservice_controller.go#L1027-L1034)) fails to fetch the head service because it has not been created yet.
When using a very large image (e.g., `ray-ml:2.5.0`), the head Pod requires more time than the `DeploymentUnhealthySecondThreshold` (which is typically set to 300 seconds in most examples) to pull the image. Hence, before the head Pod is running and ready, the RayService will be considered unhealthy by calling `markRestart` …
=> [Bug] Long image pull time will trigger blue-green upgrade after the head is ready

docs/guidance/rayservice-troubleshooting.md, docs/guidance/rayservice.md
=> [Doc] Improve RayService doc

ray-operator/config/samples/ray_v1alpha1_rayjob.yaml
The docstring of `runtimeEnv` didn't appear right above the runtimeEnv field.  This PR fixes the issue.
=> [Doc] Fix the order of comments in sample Job YAML file

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go
Without this PR, there are two mechanisms to delete Pods.
1. Autoscaler: When Autoscaler wants to scale down the cluster, it will send a patch to update `replicas` and `workersToDelete` fields in RayCluster CR. Then, KubeRay operator will delete all Pods in `workersToDelete`.
2. Random Pod deletion: If all Pods in `workersToDelete` have been deleted, and additional deletions are still required to reach the target state, the KubeRay operator will proceed to delete worker Pods randomly.
This PR provides a new behavior for Pod deletion:
* Case 1: If Autoscaler is disabled, we will always enable random Pod deletion.
* Case 2: If Autoscaler is enabled, the default behavior is disabling random Pod deletion. We also provide a feature flag `ENABLE_RANDOM_POD_DELETE` for users to go back to the …
=> [release blocker][Feature] Only Autoscaler can make decisions to delete Pods

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go
=> [cherry-pick][0.6.0][Feature] Only Autoscaler can make decisions to delete Pods (#1253)

helm-chart/kuberay-operator/templates/deployment.yaml
Some custom Kubernetes clusters require special labels and annotations for pods, which currently can not be set.
This PR allows setting custom labels on the kuberay operator. 
(https://github.com/ray-project/kuberay/issues/1275)
=> [Feature] Allow custom labels&annotations for kuberay operator (#1275)

docs/guidance/rayservice-troubleshooting.md, ray-operator/controllers/ray/rayservice_controller.go
Note that `NetworkPolicy` will not have any effect if you do not have CNI plugin installed in your Kubernetes cluster. Hence, I developed this PR on AWS EKS and installed the CNI plugin Calico.
* Step 1: Follow this [doc](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) to install Calico in your EKS cluster.
* Step 2: Create a NetworkPolicy to block all incoming traffic to the Ray head Pod.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: block-head-pod
spec:
podSelector:
matchLabels:
ray.io/node-type: head
ingress: []
```
* Step 3: Install KubeRay operator with this PR.
```bash
helm install kuberay-operator kuberay/kuberay-operator --version 0.6.1 --set image.repository=$YOUR_DOCKERHUB_REPO,image.tag=$YOUR_DOCKERHUB_TAG
``` 
* Step 4: Create a …
=> [RayService][Observability] Add more loggings about networking issues

ray-operator/Makefile
* Removes dependency on `go get` to unblock further Golang upgrades
Should close #518
=> [Golang] Remove `go get`

tests/compatibility-test.py, tests/framework/utils.py, tests/kuberay_utils/utils.py
Before Ray 2.6.0, there was a bug in Ray Serve that caused the `test_ray_serve` to be quite unstable (See #1058 for more details). Therefore, we only run `test_ray_serve` for Ray versions 2.6.0 and later. Currently, Ray 2.6.0 is not included in the KubeRay CI pipeline. However, I believe the release manager for Ray 2.6.0 will open a PR to update the version from 2.5.0 to 2.6.0 (or 2.6.2) in the next few days.
Closes #1058 
```sh
RAY_IMAGE=rayproject/ray:2.5.0 python3 tests/compatibility-test.py RayFTTestCase.test_ray_serve 2>&1 | tee log
```
* `test_ray_serve` is executed in [Compatibility Test - Nightly](https://github.com/ray-project/kuberay/actions/runs/5743528549/job/15568228623?pr=1288#step:3:1406).
* `test_ray_serve` is skipped in [Compatibility Test - …
=> [CI] Only run test_ray_serve for Ray 2.6.0 and later

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
=> Allow manually creating init containers in Kuberay helm charts

ray-operator/Dockerfile
We are currently using generic golang and distroless images to build the ray-operator (and other images).
Using “ubi(universal base image)” and “scratch” will improve the security of our images. [UBI](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) images are actively maintained, scanned, and updated by Red Hat productization and security teams. Using these images will improve user confidence in what is being provided by the KubeRay community.
`scratch` is similar to the distroless, but this will make the dockerfile more portable for build systems that are unable to access `gcr.io/distroless/static`
Not directly related, but we should really update the Go version we are using: https://github.com/ray-project/kuberay/issues/518
Go 1.17 seems to have a lot of …
=> Update ray operator Dockerfile

.github/workflows/quay-test.yaml
I will have a sync with the repository admin to setup `QUAY_USERNAME` and `QUAY_ROBOT_TOKEN` tomorrow. I add a GitHub Action workflow that can only be triggered manually as a sanity check. This will be removed from the master branch if the `secrets` are set correctly. I have already tested this PR on my fork (https://github.com/kevin85421/kuberay/actions/runs/5790693022/job/15694229870).
=> [Quay] Sanity check for KubeRay repository setup

.buildkite/kind-in-docker.yml, tests/framework/config/kind-config-buildkite.yml
This PR configures `kind` to allow `kubectl` to connect to it. This is a prerequisite for testing sample YAML files end-to-end in Buildkite. The configuration is copied from @simon-mo's work in https://github.com/ray-project/ray/pull/22035.
=> [CI] Verify kubectl in kind-in-docker step

docs/guidance/rayservice-troubleshooting.md, docs/guidance/rayservice.md, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/config/samples/ray-service.autoscaler.yaml, ray-operator/config/samples/ray-service.custom-serve-service.yaml, ray-operator/config/samples/ray-service.different-port.yaml, ray-operator/config/samples/ray-service.mobilenet.yaml, ray-operator/config/samples/ray-service.stable-diffusion.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, tests/config/ray-service.yaml.template
Before Ray 2.6.0, the status of a Serve deployment would be `UPDATING` if it was attempting to scale up additional replicas. The Serve deployment could remain in the `UPDATING` status for longer than `serviceUnhealthySecondThreshold` seconds if the cluster lacked sufficient resources to accommodate the new replicas. In such cases, KubeRay would mark the RayCluster as unhealthy and proceed to prepare a new RayCluster instead. We should not trigger the new RayCluster preparation if it is in scaling process.
In the RayService, KubeRay can mark a RayCluster as unhealthy in two possible scenarios.
Case 1: The KubeRay operator cannot connect to the dashboard agent on the head Pod for more than the duration defined by the `deploymentUnhealthySecondThreshold` parameter.
* …
=> [RayService] Revisit the conditions under which a RayService is considered unhealthy and the default threshold

.buildkite/kind-in-docker.yml
This PR extends the basic `kind`-in-docker test to install the Kuberay operator.
=> [CI] Install kuberay operator in buildkite test

.github/workflows/image-release.yaml, .github/workflows/quay-test.yaml, .github/workflows/test-job.yaml
```yaml
if: contains(fromJson('["refs/heads/master"]'), github.ref)
```
Because I am not a collaborator of this GitHub repo, I cannot read the `secrets` of this repo. Hence, we will not log in to either DockerHub or Quay for PR. We will only log in to the image registries after the PR is merged into the master branch.
#1133: We can close the issue if the PR works well after merge.
We can only verify this PR after it is merged.
=> [CI] Publish KubeRay operator / apiserver images to Quay

.buildkite/kind-in-docker.yml
Closes #1309.  I don't know why, after but downgrading the `kind` version to `0.11.1`, I never observed the issue again.  Whereas with `0.20.0`, the issue is consistently reproducible.
I haven't investigated which `kind` version between 0.11.1 and 0.20.0 is the first one that caused the issue.  
The reason for choosing 0.11.1 is that this is the version used in Ray CI, and we haven't observed the issue in Ray CI. https://github.com/architkulkarni/ray/blob/5cb837dbaf1e5875f4f365e67cec6b09d90bf710/ci/k8s/prep-k8s-environment.sh#L8
- [] Manual tests
=> [CI] Downgrade `kind` from to `v0.20.0` to `v0.11.1`

ray-operator/controllers/ray/rayservice_controller.go
See #1303 for more context.
I decided on some light future-proofing by checking if *any* labels have changed before updating the pod (though there is only one label being changed right now).
Closes #1303 
I followed `DEVELOPMENT.md` and was able to stand up a `RayService` in a local `kind` cluster using an operator image built from this PR:
```
❯ k get po -n default
NAME                                                      READY   STATUS    RESTARTS   AGE
ervice-sample-raycluster-pn4cd-worker-small-group-qfntp   1/1     Running   0          6m46s
kuberay-operator-5987588ffc-dg2mn                         1/1     Running   0          23m
rayservice-sample-raycluster-pn4cd-head-fnsl6             1/1     Running   0          6m46s
```
```
❯ k get svc -n default
NAME …
```
=> Do not update pod labels if they haven't changed

.buildkite/test-rayjob-sample-yamls.yml, tests/framework/config/kind-config-buildkite.yml, tests/framework/config/kind-config.yaml, tests/framework/utils.py
Sets up the Buildkite CI pipeline to test the RayJob sample YAML files using `kind`.
Closes #1246 
=> [CI] Run sample job YAML tests in buildkite

apiserver/DEVELOPMENT.md, proto/Dockerfile, proto/Makefile
Please see issue#1329 
Update Development.md and Dockerfile for Go 1.19
Closes #1329 
Run the following and make sure no errors from the make commands.
```bash
git clone --single-branch --branch issue-1329 https://github.com/tedhtchang/kuberay.git
cd kuberay/proto
export IMAGE_NAME=<registry>/proto-generator # For example: docker.io/tedhtchang/proto-generator
export IMAGE_TAG=test
export PREBUILT_REMOTE_IMAGE=${IMAGE_NAME}:${IMAGE_TAG}
make make build-image
make generate
```
/cc @kevin85421 @anishasthana
=> Update doc and base image for Go 1.19

ray-operator/config/samples/ray-job.custom-head-svc.yaml, ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/common/ingress_test.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, tests/test_sample_rayjob_yamls.py
As @mmourafiq pointed out in https://github.com/ray-project/kuberay/pull/1326#issuecomment-1678476425, some users prefer a deterministic head service name for RayJob in order to set up a reverse proxy. Although we've made the entire head service configurable, there are some issues that arise when we set the name of the head service:
* Kubernetes Jobs cannot communicate with the Ray head because of an incorrect service name.
* Ray workers fail to connect to the Ray head due to the same naming issue.
Closes #1294 
```sh
helm install kuberay-operator kuberay/kuberay-operator --version 0.6.0 --set image.repository=controller,image.tag=latest
kubectl apply -f ray-job-custom-head-svc-name.yaml
kubectl get rayjobs.ray.io rayjob-sample -o=jsonpath='{.status.jobStatus}'
```
=> [Bug][RayJob] RayJob with custom head service name

apiserver/Makefile, apiserver/pkg/util/cluster.go
The version of `golangci-lint` used in the KubeRay api server hangs when used with higher versions of golang (1.20+). This is related [to this issue](https://github.com/golangci/golangci-lint/issues/3420)
Closes #1334
=> Bump the golangci-lint version in the api server makefile

docs/guidance/aws-eks-gpu-cluster.md, docs/guidance/stable-diffusion-rayservice.md, docs/guidance/text-summarizer-rayservice.md, ray-operator/config/samples/ray-service.text-sumarizer.yaml
This is needed for Kuberay CUJ testing
Manually tested
=> Documentation and example for running simple NLP service on kuberay

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
Prior to this pull request, the RayCluster Helm chart had uniform default images for various worker groups. This PR introduces a new feature that empowers users to designate distinct images for both worker groups and the head Pod. To ensure backward compatibility, the PR verifies if the "image" section is defined for each Pod. If an image isn't specified in values.yaml, the Pod's image defaults to the option provided at the outset of values.yaml.
Closes #1291
(Link to [values.yaml](https://gist.github.com/Darren221/471b253cf0297aa96340a94a306396d6) for test 1) 
```shell
helm install kuberay-operator kuberay/kuberay-operator --version 0.6.0
helm install ray-cluster kuberay/helm-chart/ray-cluster --version 0.6.0 -f kuberay/helm-chart/ray-cluster/values.yaml
kubectl …
```
=> [Feature] Allow RayCluster Helm chart to specify different images for different worker groups

tests/framework/config/kind-config-buildkite.yml, tests/framework/config/kind-config.yaml
Kind's [extraPortMappings configuration](https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings) is for NodePort or Ingress. However, we do not use these Kubernetes functionalities in CI tests. In addition, I cannot use `kubectl port-forward` to check Ray dashboard if the kind cluster is created by this Kind configurations.
=> [CI] Remove extraPortMappings from kind configurations

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, tests/compatibility-test.py, tests/config/ray-cluster.mini.yaml.template, tests/config/ray-cluster.ray-ft.yaml.template, tests/config/ray-service.yaml.template
* Remove unused constant variables: `ray.io/cluster-dashboard`, `ray.io/health-state`, `NAMESPACE`, and `DefaultRedisPassword`.
* Merge `initLivenessProbeHandler` and `initReadinessProbeHandler` into 1 function. Both readiness and liveness probes perform the same checks for most Kubernetes use cases.
* Kubernetes probe supports several handlers, including `exec`, `httpGet`, `GRPC`, and `tcpSocket`. However, the previous implementation assumes that users will always use `exec`.
* The minimum value of `probe.SuccessThreshold` is 1, but the default value (`DefaultReadinessProbeSuccessThreshold` & `DefaultLivenessProbeSuccessThreshold`) in KubeRay is 0. Although Kubernetes will override 0 with 1, it would be better to set it to 1 explicitly to avoid some potential K8s compatibility issues.
* …
=> [GCS FT] Give readiness / liveness probes good default values

docs/guidance/rayjob.md, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.resources.yaml, ray-operator/config/samples/ray_v1alpha1_rayjob.yaml, ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/common/job_test.go, ray-operator/controllers/ray/rayjob_controller.go, tests/test_sample_rayjob_yamls.py
Adds the fields entrypoint_num_cpus, gpus, resources in Kuberay Rayjob spec. Ray Job API supports specification of these resources, but before this code change the Kuberay Job Spec did not expose these fields  
Closes #1266
=> Add field to expose entrypoint num cpus in rayjob

helm-chart/kuberay-operator/templates/role.yaml, helm-chart/kuberay-operator/values.yaml, ray-operator/Makefile, ray-operator/config/rbac/role.yaml, ray-operator/controllers/ray/common/route.go, ray-operator/controllers/ray/common/route_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/go.mod, ray-operator/go.sum, ray-operator/main.go
This replaces PR https://github.com/ray-project/kuberay/pull/1185.
- [ x] Unit tests
=> Operator support for openShift

ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/util.go, tests/framework/prototype.py
Unlike init containers, which start one by one in a sequence, all application containers in the same Pod can start simultaneously. Therefore, it is fine to enforce the Ray container to be the first application container.
**Backward compatibility** (v0.6.0):
**[Case 1]**:
* Add an Nginx sidecar container as the first application container, and the Ray container as the second.
* [Gist](https://gist.github.com/kevin85421/969599a7dcbf28fe4a99e2576b6be599)
The head Pod crashes repeatedly because KubeRay identifies the first app container (i.e., Nginx container) as the Ray container and injects `ray start ...` command into the Nginx container.
**[Case 2]**:
* Add an Nginx sidecar container as the first application container, and the Ray container as the second.
* Add an env with name `ray` and …
=> [Feature] Ray container must be the first application container

ray-operator/Makefile
We first make kustomize as part of make helm (and hence make sync). But this is not required. This was realized while running make sync. This code change simply removes kustomize from make helm.
Closes #1368 
=> Remove unnecessary kustomize in make helm

ray-operator/config/samples/ray-service.autoscaler.yaml, tests/framework/prototype.py, tests/test_sample_rayservice_yamls.py
The `test_service_autoscaling` sometimes cannot scale up successfully due to https://github.com/ray-project/ray/issues/39224, so this PR updates configurations to avoid the issue. See [this buildkite failure](https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/1507#018a4db8-b73b-4753-b07b-f398eaaa551d) for more details.
https://github.com/ray-project/ray/issues/39224
=> [Bug] Fix flakiness of RayService e2e tests

docs/guidance/volcano-integration.md, ray-operator/config/samples/ray-cluster.volcano-scheduler-queue.yaml, ray-operator/config/samples/ray-cluster.volcano-scheduler.yaml
reviewers @tgaddair @kevin85421 
- Update the Volcano integration doc to make it easier for users to follow the installation and example steps
- Move RayCluster yaml examples into /config/samples/
- Clarify that additional labels `ray.io/priority-class-name` and `volcano.sh/queue-name` requires the corresponding resources to be created first before creating a raycluster
=> Update Volcano integration doc

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/raycluster_types_test.go, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/common/ingress_test.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/route_test.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go
Before the introduction of this PR, KubeRay used to determine the Ray Autoscaler sidecar container's image based on the `rayVersion` parameter. 
* Case 1: If this version was older than Ray 2.0.0, KubeRay defaulted to using Ray 2.0.0 for the sidecar container image.
* Case 2: In other cases, it used the same image as the Ray head container. For more information, please refer to `autoscalerSupportIsStable` and `getAutoscalerImage`.
Case 1 is not necessary at this moment because KubeRay does not guarantee the support of a version older than Ray 2.0.0. In addition, there is no compatibility test for the version mismatch between Ray Autoscaler and Ray.
I also removed the description of the `rayVersion` behavior in https://github.com/ray-project/ray/pull/39345.
=> [Feature] Use image of Ray head container as the default Ray Autoscaler container

ray-operator/config/samples/ray-service.text-ml.yaml
=> [services] Add text ml rayservice yaml

helm-chart/kuberay-apiserver/templates/deployment.yaml, helm-chart/kuberay-operator/templates/deployment.yaml
fixes #1391 Some organizations have strict labeling requirements for their K8s objects, mainly deployments and pods. kuberay-operator was allowing to add custom labels via values.yaml to pods but not to deployments and kuberay-apiserver was not allowing to add custom labels to either. Added code to pull labels for deployment if present in values.yaml. Also, added code to pull annotations for apiserver as well as is the case with operator.  
Closes #1391 
=> fix: Issue #1391 - Custom labels not being pulled in

docs/guidance/ingress.md, docs/index.md, ray-operator/config/samples/ray-cluster-alb-ingress.yaml, ray-operator/config/samples/ray-cluster.separate-ingress.yaml
The Ray Dashboard is a Read/Write service into the cluster and thus should not be publicly exposed.
I'll be mirroring these over in the Ray docs in a follow up PR!
=> [Docs] Update Security Guidance on Dashboard Ingress

tests/compatibility-test.py, tests/framework/prototype.py, tests/framework/utils.py, tests/test_sample_rayservice_yamls.py, tests/test_security.py
Currently E2E tests run only with Kind cluster. The goal of this PR is to make these tests more configurable and allow it to run with any Kubernetes cluster. It is now possible to login to arbitrary cluster using kubectl/oc command and run tests with arbitrary cluster. For example:
```
oc login ...
EXTERNAL_CLUSTER=true RAY_IMAGE=rayproject/ray:2.5.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/compatibility-test.py
```
Closes #1284
- [] I've made sure the tests are passing. 
- [] Unit tests
- [] Manual tests
- [*] This PR is not tested :(
=> Allow E2E tests to run with arbitrary k8s cluster

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
The function `checkIfNeedSubmitServeDeployment` is used to determine whether to update or create Ray Serve applications. Without this PR, this function returns true in the following two conditions:
(1) When there is no Serve config cache in the KubeRay operator, indicating that either a new RayCluster has just become ready or the KubeRay operator has crashed.
(2) When the Serve config in the cache differs from the RayService CR's ServeConfigV2, indicating an in-place Serve config update.
However, in the case of a head Pod crash and restart without GCS FT, the KubeRay operator will not send a request to create new Ray Serve applications because the Serve config cache remains the same as the RayService CR's ServeConfigV2.
Furthermore, the RayCluster will not be labeled as unhealthy because …
=> [Bug][RayService] KubeRay does not recreate Serve applications if a head Pod without GCS FT recovers from a failure.

helm-chart/kuberay-operator/values.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go
* Implement Method 5 in https://github.com/ray-project/kuberay/issues/1286#issuecomment-1699968632.
* Add a feature gate.
* Kubernetes Job configurations, e.g. `backoffLimit`, `completions`, ... etc.
* Documentations (including how to delete it if it fails)
* E2E tests
* Improve observability
* Test if the Job fails to connect to Redis.
Closes #1286 
```sh
kubectl apply -f ray-cluster.external-redis.yaml
kubectl exec -it $REDIS_POD -- bash
redis-cli -a "5241590000000000"
KEYS *
HGETALL  "4c31680c-2a27-4788-92d8-6867188ecdd8"
kubectl delete rayclusters.ray.io raycluster-external-redis 
KEYS *
```
=> [Feature][GCS FT] Clean up Redis once a GCS FT-Enabled RayCluster is deleted

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
Use `RayContainerIndex` in `ray-operator/controllers/ray/rayjob_controller.go` to fix #1397
Hi @kevin85421,
I currently leave the `rayjob_controller_unit_test.go` untouched so that we can make sure `RayContainerIndex` is 0. Do you think we should change the usage of `0` to `RayContainerIndex` in `rayjob_controller_unit_test.go` as well?
=> [Feature][RayJob] Use Use RayContainerIndex instead of 0 (#1397)

ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler_test.go
`ClusterName` has been removed in higher K8S version.
In order to be compatible with feature upgrade.
Closes #1445
=> use raycluster app's name as podgroup name key word

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
Some GitOps systems, like Flux, will revert changes that are not initiated by the system itself. The Ray Autoscaler modifies the `Replicas` field to scale the Ray cluster up or down. Consequently, a conflict arises where the Autoscaler makes updates to the field, and Flux continuously reverts them. To address this issue, this PR makes the `Replicas` field optional. If the field is optional, Flux will not have the reverting behavior.
* Similar issue: https://github.com/fluxcd/flux/issues/1686
* Related discussions:
* https://ray-distributed.slack.com/archives/C01CKH05XBN/p1685123816833509
* #1120 
Closes #1154 
Closes #1120 
Closes #265 
=> [Feature] Make replicas optional for WorkerGroupSpec

apiserver/README.md
The API Server examples are out of date. This PR updates the examples.
Please note that the API server examples for this PR where tested on #1419.
Closes #1290
Contributes to #1408
=> Updated API server documentation

ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go, tests/framework/prototype.py
As discussed in the https://github.com/ray-project/kuberay/issues/1381#issuecomment-1720721651, I added a readiness check to the dashboard server as a workaround before the release of KubeRay 1.0.0.
I didn't add new tests for these changes because it was hard to mock the `rayDashboardClient` accordingly to simulate the target behavior. But I did make sure these changes can pass the current tests.
To further add tests for these, I would suggest adding mocking functionalities into the `FakeRayDashboardClient` first. For example:
```go
func (r *FakeRayDashboardClient) GetJobInfo(ctx context.Context, jobId string) (*RayJobInfo, error) {
return r.GetJobInfoMock(ctx, jobId)
}
// setup mock
ts := time.Now()
r.GetJobInfoMock = func(ctx context.Context, jobId string) (*RayJobInfo, error) {
if …
```
=> [Bug][RayJob] Check dashboard readiness before creating job pod (#1381)

tests/test_sample_raycluster_yamls.py
My understanding is that the RayCluster sample YAML test framework only adds RayCluster CRs, but doesn't add the other resources in the sample YAML file (for example the external redis deployment).  In the case of the external redis sample YAML, the sample YAML test started failing after https://github.com/ray-project/kuberay/pull/1412/ and my tentative hypothesis is that the cleanup job added by the PR hangs if there's no external redis.
For now, we should merge this PR to unbreak CI.  Later, we can decide whether to properly support an end-to-end external redis test.
Closes #1459 
=> [CI] Skip redis raycluster sample YAML test

.buildkite/test-sample-yamls.yml
This PR reenables the rayjob sample yaml test that tests against the latest kuberay version. Previously it was skipped due to breaking changes in the API.
=> [CI] Reenable rayjob sample yaml latest test

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
GKE's Autopilot does not support GPU-using init containers, so we explicitly specify the resources for the init container instead of reusing the resources of the Ray container. The resource consumption of the init container should be constant. Hence, it is OK to hard-code the resources.
Closes #1349 
```sh
gcloud container clusters create-auto kuberay-gpu-cluster --region=us-west1
```
=> [Enhancement] GPU RayCluster doesn't work on GKE Autopilot

ray-operator/controllers/ray/common/constant.go
Maintaining code cleanliness is the best policy.
I believe that redundant variables should be deleted to avoid confusion in subsequent development.
#1472 
=> [Enhancement] Remove unused variables in constant.go

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
This PR fixes an issue where the raycluster-cluster template is not correctly referencing the root context's image field as it's intended.  So you get the following error when trying to install:
`
Error: INSTALLATION FAILED: template: ray-cluster/templates/raycluster-cluster.yaml:132:29: executing "ray-cluster/templates/raycluster-cluster.yaml" at <.Values.image.repository>: nil pointer evaluating interface {}.image
`
N/A
=> Helm chart ray-cluster template reference fix

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
Clean and high readability code is easier to maintain and less prone to introducing bugs. This enhances the long-term sustainability of the project.
This change is to cleanup the KubeRay helm chart and remove a typo.
#1472
https://github.com/ray-project/kuberay/pull/1106#issuecomment-1574164061
```shell
$ git diff --cached | cat
diff --git a/helm-chart/ray-cluster/templates/raycluster-cluster.yaml b/helm-chart/ray-cluster/templates/raycluster-cluster.yaml
index 0c13e86..c080720 100644
--- a/helm-chart/ray-cluster/templates/raycluster-cluster.yaml
+++ b/helm-chart/ray-cluster/templates/raycluster-cluster.yaml
@@ -110,8 +110,8 @@ spec:
{{- end }}
{{- end }}
replicas: {{ $values.replicas }}
-    minReplicas: {{ $values.minReplicas | default (default 0 $values.miniReplicas) }}
- …
```
=> Remove miniReplicas in raycluster-cluster.yaml

ray-operator/Dockerfile
There's a number of CVEs that are closed in the latest versions of the go-1.19 toolset.
1. https://bugzilla.redhat.com/show_bug.cgi?id=2234712
2. https://bugzilla.redhat.com/show_bug.cgi?id=2234713
3. https://bugzilla.redhat.com/show_bug.cgi?id=2237782
4. https://bugzilla.redhat.com/show_bug.cgi?id=2237798
5. https://bugzilla.redhat.com/show_bug.cgi?id=2238352
cc @kevin85421 @z103cb @tedhtchang
=> Update Dockerfile to address closed CVEs

ray-operator/Dockerfile, ray-operator/Makefile
E.g. with docker buildx build --platform linux/amd64,linux/arm64/v8
To support different architectures with multi-arch docker images with `docker buildx`, we should remove GOARCH=amd64 in Dockerfile.
None.
=> Remove GOARCH in ray-operator/Dockfile to support multi-arch images

tests/test_sample_raycluster_yamls.py
Reverts ray-project/kuberay#1465
Previously, we skipped the redis raycluster e2e test in https://github.com/ray-project/kuberay/pull/1465 due to the indefinite hanging it caused.
After the https://github.com/ray-project/kuberay/pull/1466 got merged, we can now safely perform the Redis cleanup e2e test without hanging. There is no need to skip the test anymore.
#1465
#1422
#1459
=> Revert "[CI] Skip redis raycluster sample YAML test"

config/prometheus/serviceMonitor.yaml, ray-operator/config/samples/ray-cluster.embed-grafana.yaml
Ray exposes Prometheus metrics through three endpoints: 8080, 44217 (for autoscaler metrics), and 44227 (for dashboard metrics). See [/tmp/ray/prom_metrics_service_discovery.json](https://docs.ray.io/en/latest/cluster/metrics.html?highlight=prom_metrics_service_discovery.json#auto-discovering-metrics-endpoints) on the head Pod for more details. Some Grafana panels embedded in the Ray dashboard require metrics from Autoscaler. Hence, the panel may show "No data".
This PR scrapes metrics from all 8080, 44217, and 44227, so the panel will not show "No data" anymore.
Closes #1487 
=> [Feature][Observability] Scrape Autoscaler and Dashboard metrics

ray-operator/controllers/ray/common/job.go
=> [Cherry-pick][RayJob] Add default CPU and memory for job submitter pod (#1319)

apiserver/Dockerfile, proto/Dockerfile, ray-operator/Dockerfile
This PR upgrades Dockerfiles to the latest version of the go-toolset:1.19 image that closes CVE-2023-44487.
https://bugzilla.redhat.com/show_bug.cgi?id=2242803
cc @kevin85421 @anishasthana @z103cb @tedhtchang @blublinsky
=> Update Dockerfiles to address CVE-2023-44487 (HTTP/2 Rapid Reset)

.buildkite/test-sample-yamls.yml, .github/workflows/image-release.yaml, README.md, apiserver/README.md, docs/deploy/images.md, docs/deploy/installation.md, helm-chart/kuberay-operator/Chart.yaml, helm-chart/kuberay-operator/README.md, helm-chart/ray-cluster/Chart.yaml, helm-chart/ray-cluster/README.md, tests/framework/utils.py
* v1.0.0-rc.0 does not support CRD v1, so the sample YAML tests fail consistently. #1482 comments the tests out, and this PR uncomments them.
* Update some docs.
Closes #1491
=> [Post v1.0.0-rc.1] Reenable sample YAML tests for latest release and update some docs

docs/development/release.md
Some KubeRay users, like [Flyte](https://github.com/flyteorg/flyte), want to use the [generated Golang client](https://github.com/ray-project/kuberay/tree/master/ray-operator/apis/ray) by `go install github.com/ray-project/kuberay/ray-operator@vX.Y.Z`. However, there is no `go.mod` in the root directory of KubeRay repo, so users cannot do that until we provide a specific tag for `ray-operator/` directory.
=> [Release][Doc] Add instructions to release Go modules.

ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/common/job_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
=> [RayJob]: Always use target RayCluster image as default RayJob submitter image

ray-operator/controllers/ray/rayjob_controller_test.go
Resolves https://github.com/ray-project/kuberay/issues/1471
As discussed in the issue, we should not use `++` in a `retry.RetryOnConflict` block because it is not idempotent.
We should use the following, which will guarantee the idempotency with retries, to remove the flaky mentioned in the issue:
```
*myRayCluster.Spec.WorkerGroupSpecs[0].Replicas = *myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas + 1
```
=> [Test][Bug] Update worker replias idempotently in rayjob autoscaler envtest (#1471)

README.md, docs/guidance/kuberay-with-MCAD.md
Closes #1327 Improve the kuberay macad integration doc
#1327 
=> Update kuberay mcad integration doc

ray-operator/config/samples/ray-service.mobilenet.yaml
According to the comment in [issue #1463](https://github.com/ray-project/kuberay/issues/1463#issuecomment-1771746578), only the Ray head and workers with Serve replicas will have an HTTPProxyActor in a stable state. Without this PR, if the replica is scheduled on the head, there will be only one replica in the cluster and the worker will not have an HTTPProxyActor. Hence, the K8s serve service has only one endpoint from the head, and this endpoint will be removed when the head Pod is terminated, and thus there will be no HTTPProxyActor & replica available.
This PR makes sure both the head Pod and worker Pod have 1 replica and 1 HTTPProxyActor. Hence, when the head Pod is deleted, the K8s serve service still has an endpoint from worker to achieve high-availability.
Closes #1463
- Testing …
=> [Bug] RayService with GCS FT HA issue

apiserver/README.md, apiserver/pkg/util/job.go, apiserver/pkg/util/job_test.go
Fixes errors introduced by PR that added job submitter to API server
- [x ] I've made sure the tests are passing. 
=> Fixed processing of job submitter

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/main.go
This PR fixes a number of issues related to the reconciliation of the RayJob status.
It also sets RayJob resources as owners of the Kubernetes Jobs that submit Ray jobs via the CLI.
It also addresses the issue of systematic failure upon retry of the job submission reported in #1480, by disabling submission retry altogether,  until a proper solution is found. 
The simplest solution would be to expose the job override option to the CLI, though this requires more thoughts and can be addressed in a separate PR:
https://github.com/ray-project/ray/blob/56affb7e4b5af8b1da7a322fdc6ecc7e2258d522/dashboard/modules/job/job_manager.py#L919
Fixes #1478.
Fixes #1480.
=> [RayJob] Fix RayJob status reconciliation

ray-operator/config/samples/ray-service.high-availability.yaml
This PR adds a sample YAML for RayService high-availability, and I will add a doc to describe RayService high-availability based on this YAML.
=> [Feature] Add an example for RayService high availability

.github/workflows/image-release.yaml, docs/development/release.md
Automate the creation of the release tags for the `ray-operator` Go module.
Closes #1549
I've tested it locally on my fork.
=> [CI] Create release tag for ray-operator Go module

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
The RayService's health check mechanism is not well-defined. This PR is a hotfix for v1.0.0, and I will revisit the mechanism after the release. Hence, I do not spend much time on writing tests for this PR.
* Change 1: `updateAndCheckDashboardStatus`
* Question: KubeRay will not update the status of the RayService custom resource when the only changes are related to timestamps. Without this PR, deleting the head Pod of a GCS ft-enabled RayCluster could potentially trigger an unnecessary zero-downtime upgrade immediately after the head Pod restarts.
```sh
kubectl apply -f ray-service.high-availability.yaml
kubectl describe rayservices.ray.io rayservice-ha
export HEAD_POD=$(kubectl get pods --selector=ray.io/node-type=head -o custom-columns=POD:metadata.name --no-headers)
kubectl delete pod …
```
=> [Hotfix][Bug] Avoid unnecessary zero-downtime upgrade

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
The job reconciler pings the job status endpoint every 3 seconds. Previously, if this failed at any time during the job execution, the job deployment status would be set to FailedToGetJobStatus, and it would never be updated back to JobDeploymentStatusRunning because due to an oversight, the existing code only updates the JobDeploymentStatus if the JobStatus changed. Thus in the case where the JobStatus doesn't change (e.g. "RUNNING" -> "RUNNING"), but there is an intermittent failure to get the job status, the JobDeploymentStatus is never updated from JobDeploymentStatusFailedToGetJobStatus to JobDeploymentStatusRunning.
This PR fixes this bug by explicitly updating the status back to JobDeploymentStatusRunning if the reconcile loop gets a JobStatus when the previous status is …
=> [Bug][RayJob] Fix FailedToGetJobStatus by allowing transition to Running

tests/compatibility-test.py, tests/framework/prototype.py, tests/framework/utils.py, tests/test_sample_raycluster_yamls.py, tests/test_sample_rayjob_yamls.py, tests/test_sample_rayservice_yamls.py, tests/test_security.py
It allows to install and uninstall Kuberay operator using scripts. It will be useful for environments where it is not possible to use Helm.
=> Allow to install and remove operator via scripts

tests/framework/prototype.py
`test-raycluster-sample-yamls-nightly-operator` becomes very flaky recently. #1556 introduces a new YAML file for a RayCluster with GCS FT. As a result, the sample YAML tests have become flaky. There are two YAMLs, ray-cluster.external-redis.yaml and ray-cluster.external-redis-uri.yaml, for GCS FT-enabled RayCluster custom resources. If the Redis Pod from the first YAML isn't deleted in time, the RayCluster from the second YAML will connect to the terminating Redis. Consequently, the RayCluster crashes when the Redis Pod is eventually deleted.
=> [Bug] Fix flaky sample YAML tests

ray-operator/controllers/ray/raycluster_controller.go
* Mitigate the penalty if the Redis cleanup Job fails.
* Minimize the computing resources for the K8s Job.
* Set the backoffLimit to 0 to avoid 6 dead Pods to overload ResourceQuota's `count/pods`.
* With the default configuration `redis_db_connect_retries = 600` and `redis_db_connect_wait_milliseconds = 100`, it takes 13 mins to fail. This PR configures the environment variables so that the Job takes 3 mins to fail. See https://github.com/ray-project/ray/pull/40860 for more details.
* Add loggings to improve the observability for troubleshooting.
* Note:
* If we delete the Redis deployment, the Redis cleanup Job cannot connect to Redis, so it retries based on the environment variables mentioned above.
* If we delete the key in Redis, the Redis cleanup Job can connect to Redis but fails …
=> [GCS FT] Improve GCS FT cleanup UX

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go
1. Improve observability for troubleshooting.
2. Increase the probability to trigger the flakiness.
#1550 
=> [Feature] Improve observability for flaky RayJob test

ray-operator/main.go
For now, `exitOnError` without keysAndValues, will cause panic: odd number of arguments passed as key-value pairs for logging.  It is noisily.
=> Fix: odd number of arguments

.buildkite/test-sample-yamls.yml, .github/workflows/image-release.yaml, README.md, apiserver/README.md, docs/deploy/images.md, docs/deploy/installation.md, helm-chart/kuberay-operator/README.md, helm-chart/ray-cluster/README.md, tests/framework/utils.py
=> [Cherry-pick][Post v1.0.0-rc.1] Reenable sample YAML tests for latest release and update some docs (#1544)

docs/development/release.md, docs/release/helm-chart.md
=> [Doc] Update release docs

.github/workflows/actions/kind/action.yml, .github/workflows/actions/kind/kind.yaml, .github/workflows/e2e-tests.yaml, ray-operator/DEVELOPMENT.md, ray-operator/Makefile, ray-operator/go.mod, ray-operator/go.sum, ray-operator/test/e2e/counter.py, ray-operator/test/e2e/fail.py, ray-operator/test/e2e/rayjob_cluster_selector_test.go, ray-operator/test/e2e/support.go, ray-operator/test/support/client.go, ray-operator/test/support/core.go, ray-operator/test/support/defaults.go, ray-operator/test/support/environment.go, ray-operator/test/support/events.go, ray-operator/test/support/namespace.go, ray-operator/test/support/ray.go, ray-operator/test/support/support.go, ray-operator/test/support/test.go, ray-operator/test/support/utils.go
This PR adds e2e tests for the operator, following up https://github.com/ray-project/kuberay/pull/1539#issuecomment-1778717122.
This e2e testing enables to assert Kuberay resources, in a way that cannot be achieved with existing tests (envtest).
The e2e tests execution output is post-processed using gotestfmt:
The logs and events are gathered and uploaded are part of the workflow run:
=> [CI]: Kuberay operator e2e tests

ray-operator/Dockerfile
cc @kevin85421  @tedhtchang @jbusche 
Closes #1632
Test image that I built and pushed:  quay.io/anishasthana/kuberay-operator:ubiminimaltest
Output of payload checker:
```
---- Successful run
```
=> Make KubeRay Operator Image FIPS compliant

ray-operator/config/samples/ray-cluster.complete.large.yaml, ray-operator/config/samples/ray-cluster.separate-ingress.yaml, ray-operator/config/samples/ray-cluster.volcano-scheduler-queue.yaml, ray-operator/config/samples/ray-cluster.volcano-scheduler.yaml, ray-operator/config/security/ray-cluster.pod-security.yaml
in example YAMLs
This field has been deprecated since 0.3.0.
[Related comment](https://github.com/ray-project/kuberay/issues/612#issuecomment-1266279244)
#612
=> chore: remove all deprecated `HeadGroupSpec.replicas`

apiserver/pkg/model/converter_test.go, apiserver/pkg/util/cluster.go, helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1/raycluster_types_test.go, ray-operator/apis/ray/v1/rayjob_types_test.go, ray-operator/apis/ray/v1/rayservice_types_test.go, ray-operator/apis/ray/v1/zz_generated.deepcopy.go, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/raycluster_types_test.go, ray-operator/apis/ray/v1alpha1/rayjob_types_test.go, ray-operator/apis/ray/v1alpha1/rayservice_types_test.go, ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler_test.go, ray-operator/controllers/ray/common/ingress_test.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/route_test.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/utils/util.go
It has been deprecated since 0.3.0.
Changes to generated files made by running `cd ray-operator && make sync generate manifests`.
closes #612
=> chore: remove `HeadGroupSpec.Replicas` from `raycluster_types.go`

docs/reference/api.md, mkdocs.yml, ray-operator/DEVELOPMENT.md, ray-operator/Makefile, ray-operator/hack/config.yaml
This pull request supports auto-generation of CRD docs with the help of [elastic/crd-ref-docs]( https://github.com/elastic/crd-ref-docs).
We can build CRD API docs in `ray-operator` with the config file `ray-operator/hack/config.yaml` via:
```shell
make api-docs
```
Then the API reference will be generated at `docs/reference/api.md` as defined.
/cc @kevin85421
Closes #438 
=> [Doc] Support CRD docs generation

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go
RayService features a health check mechanism to monitor the status of the dashboard agent on the Ray head and the status of Ray Serve applications. It will trigger a new RayCluster preparation when the RayService controller thinks that the RayCluster is not healthy.
Almost no users benefit from this mechanism, and many have complained about why KubeRay created a new RayCluster automatically. Most users do not have enough computing resources to run two RayClusters simultaneously. In addition, maintaining the RayService health check mechanism is quite challenging due to the numerous interconnected health checks in KubeRay, including: (1) the RayCluster controller, (2) K8s readiness/liveness probes, (3) Raylet, (4) Ray Autoscaler, and (5) the RayService controller. That's why I decide to …
=> [RayService][Health-Check][1/n] Offload the health check responsibilities to K8s and RayCluster

ray-operator/controllers/ray/rayservice_controller.go
This PR removes the hotfix made by #1581. As stated in the description of PR #1581 shown below, this change is implemented to respect the health check mechanism of RayService. However, we have already decided to offload the health check responsibilities to K8s and RayCluster, and RayService controller will no longer trigger new RayCluster preparation based on the data plane status (Ray Serve status & Ray dashboard agent status). Thus, it is safe to remove the hotfix and offload the responsibilities to the Pod's liveness probes.
> * Question: When we delete the dashboard agent process on the head Pod, the head Pod becomes not ready. Hence, the dashboard agent health check will be skipped. Hence, the zero-downtime upgrade will not be triggered after deploymentUnhealthySecondThreshold …
=> [RayService][Health-Check][2/n] Remove the hotfix to prevent unnecessary HTTP requests

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
After PR #1656, the function `updateAndCheckDashboardStatus` no longer requires a check for its return value. Therefore, we can remove the function's return value. In addition, the value of `HealthLastUpdate` in the RayService CR status is totally for observability after PR #1656. Hence, we can change its definition to be more easy-to-understand. See [here](https://github.com/ray-project/kuberay/pull/1581/files#r1376729892) for more details about the old definition. 
=> [RayService][Health-Check][3/n] Update the definition of HealthLastUpdateTime for DashboardStatus

.github/workflows/consistency-check.yaml, docs/reference/api.md, ray-operator/DEVELOPMENT.md, ray-operator/Makefile, ray-operator/hack/config.yaml, ray-operator/hack/verify-api-docs.sh
This pull request adds support for consistency check of API reference in CI.
Besides, it ignores additional types related to `RayClusterStatus` in `hack/config.yaml`.
/cc @kevin85421
It's a subsequent pull request of #1625.
1. This pull request should [pass](https://github.com/ray-project/kuberay/actions/runs/6905995210/job/18790000256?pr=1655).
2. #1661 I used the commit version at 3754d34ef61734b569d235f5512c27c3f40d82df as the base since `docs/reference/api.md` is outdated with the current config. The workflow is expected to fail. Here is the [result](https://github.com/ray-project/kuberay/actions/runs/6911466506/job/18806035717?pr=1661).
=> [Doc] Support consistency check for API reference in CI

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
#1656 has already prevented the initiation of new RayCluster preparation based on the health status of the Ray dashboard agent and Ray Serve applications. Therefore, the RayService controller now focuses solely on whether the RayCluster is ready to handle incoming traffic. This PR removes the health check for Ray Serve applications. Ray Serve applications should be managed by Ray Core and ServeController instead of KubeRay.
I do not update any test logic in this PR to prove that the definition of readiness is still the same and backward compatible.
=> [RayService][Health-Check][4/n] Remove the health check for Ray Serve applications.

ray-operator/config/samples/ray-service.autoscaler.yaml, ray-operator/config/samples/ray-service.custom-serve-service.yaml, ray-operator/config/samples/ray-service.different-port.yaml, ray-operator/config/samples/ray-service.high-availability.yaml, ray-operator/config/samples/ray-service.mobilenet.yaml, ray-operator/config/samples/ray-service.stable-diffusion.yaml, ray-operator/config/samples/ray-service.text-ml.yaml, ray-operator/config/samples/ray-service.text-summarizer.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/controllers/ray/rayservice_controller.go, tests/config/ray-service.yaml.template
#1659 removes all references to `DeploymentUnhealthySecondThreshold` from KubeRay Core.
=> [RayService][Health-Check][5/n] Remove unused variable deploymentUnhealthySecondThreshold

ray-operator/config/samples/ray-service.autoscaler.yaml, ray-operator/config/samples/ray-service.custom-serve-service.yaml, ray-operator/config/samples/ray-service.different-port.yaml, ray-operator/config/samples/ray-service.high-availability.yaml, ray-operator/config/samples/ray-service.mobilenet.yaml, ray-operator/config/samples/ray-service.stable-diffusion.yaml, ray-operator/config/samples/ray-service.text-ml.yaml, ray-operator/config/samples/ray-service.text-summarizer.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, tests/config/ray-service.yaml.template
KubeRay operator will prepare a new RayCluster if the RayServe applications are unhealthy for more than `ServiceUnhealthySecondThreshold` seconds. However, we have already removed this behavior in #1656, so this PR removes the references of `ServiceUnhealthySecondThreshold` in the KubeRay codebase.
=> [RayService][Health-Check][6/n] Remove ServiceUnhealthySecondThreshold

apiserver/README.md, apiserver/pkg/util/job.go, apiserver/pkg/util/job_test.go
Resources for job submitter were assigned incorrectly, causing and error in e2e test
Resource requests aligned with resource limits
=> Fixed the issue with jobSubmitter resources

apiserver/CreatingServe.md, apiserver/pkg/util/cluster.go, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayservice_controller.go
#1207 removed the K8s service for the dashboard agent, but there are still some variables with "AgentService" in their names. This may cause misleading, so this PR changes `EnableAgentService` to `EnableServeService`. In fact, the K8s service introduced by #1672 is designed for serving purposes. It is used to expose HTTP Proxy actors on each Ray node.
Follow up for https://github.com/ray-project/kuberay/pull/1672#issuecomment-1821898634
=> [Refactor] Rename EnableAgentService to EnableServeService

apiserver/CreatingServe.md, apiserver/pkg/util/service.go, apiserver/test/e2e/config_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/types.go, clients/python-apiserver-client/python_apiserver_client_test/kuberay_api_scaling_test.py
Due to original and newly introduced bugs, API server e2e test was failing
https://github.com/ray-project/kuberay/issues/1591
=> fixed some bugs in e2e-test

tests/compatibility-test.py
As discussed with @kevin85421 offline,
Because `test_detached_actor` is too flaky on the new Ray 2.8.0 and nightly, skipping the test until https://github.com/ray-project/ray/issues/41343 is solved can save us some time from reruning those failed github actions.
=> [CI] Skip the flaky compatibility test `test_detached_actor` until https://github.com/ray-project/ray/issues/41343

docs/deploy/installation.md, ray-operator/DEVELOPMENT.md
* https://github.com/ray-project/kuberay/pull/1584#issuecomment-1828634414
#1584 implements a validation webhook, and best practices require users to install cert-manager concurrently. Currently, KubeRay uses cert-manager 1.13.2 which supports Kubernetes 1.23+. KubeRay currently supports Kubernetes 1.20 and above. However, it would be acceptable to only support versions 1.23 and higher, as the Kubernetes community has not supported version 1.23 since February 2023. (https://endoflife.date/kubernetes). In addition, KubeRay is still compatible with Kubernetes 1.20.7 if users decide to not use the webhook.
=> chore: Update K8s compatibility

.github/workflows/test-job.yaml, helm-chart/kuberay-operator/values.yaml, ray-operator/controllers/ray/common/constant.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, tests/compatibility-test.py, tests/config/ray-cluster.mini.yaml.template
KubeRay only includes readiness/liveness probes when GCS is enabled. Therefore, if GCS is not enabled and the Raylet/dashboard agent processes crash, they will not be detected. Hence, we should inject the probes no matter whether the GCS is enabled or not.
In #1656, we decide to offload the health check responsibilities, including the dashboard agent on Ray head and Ray Serve applications, to K8s and Ray. With this PR, all RayCluster custom resources have probes to check the status of the Raylet which is fate-sharing with the Ray dashboard agent.
The compatibility test `KubeRayHealthCheckTestCase` for Ray 1.13.0 will fail because Ray 1.13.0 does not support the `/api/local_raylet_healthz` health-check endpoint. See here for the [evidence](https://sourcegraph.com/search?q=context%3Aglobal+r …
=> [RayService][Health-Check][8/n] Add readiness / liveness probes

.github/workflows/test-job.yaml
We decided to use Quay as our main image registry, so we should stop to publish new images to DockerHub. That is, we will still publish old images like the operator and API server to DockerHub, but we will not publish new images like security proxy to it.
The [CI failure](https://github.com/ray-project/kuberay/actions/runs/7052685241/job/19198265229) appears to be caused by the absence of a repository named `kuberay/security-proxy` on DockerHub, so I guess this update can fix the issue.
=> [CI] Stop to publish new images to DockerHub

helm-chart/kuberay-operator/crds/ray.io_rayclusters.yaml, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayclusters.yaml, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/crd/bases/ray.io_rayservices.yaml
so they show up with `kubectl get all`.
```
❯ kubectl get all
NAME                                DESIRED WORKERS   AVAILABLE WORKERS   STATUS   AGE
raycluster.ray.io/raycluster-mini                                                  17s
```
[docs](https://book.kubebuilder.io/reference/markers/crd)
=> feat: add all three CRDs to the all category

ray-operator/main.go
When run ray-operator out of K8s cluster, leader-election-namespace is required. Otherwise it will panic `unable to find leader election namespace`
=> Add flag leader-election-namespace

helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml
This PR introduces rules to fix issue #1706, i.e. KubeRay Operator is not able to do operations on Jobs when installed "namespaced".
Closes #1706 
Can confirm on a local installation that this addition fixes the issue.
=> introduce batch.jobs rules for multiple namespace role

ray-operator/config/manager/manager.yaml
Noticed that using `make deploy` command to deploy kuberay operator, it will use the default image tag `:latest` to build the operator.
In [Kubernetes documentation](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting), it said that
> If don't specify a registry hostname, Kubernetes assumes that you mean the Docker public registry.
> If omit the imagePullPolicy field, and the tag for the container image is :latest, imagePullPolicy is automatically set to Always.
To avoid the failure of pulling an image from a remote repository that does not exist, there should specify the imagePullPolicy.
Without this PR, there would be an error when deploying the kuberay operator.
With this PR, the process of deploying the kuberay operator is quick fast because can use the …
=> Set imagePullPolicy in manager.yaml

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go
Follow the https://github.com/ray-project/kuberay/pull/932, we continue to enforce the `--block` option in the ray start command. Previously, we only injected the `--block` option when it was missing in the `rayStartParams`. Now, we override it to be `true` anyway and we don't need to inject `sleep infinity` anymore.
@kevin85421, should we add a warning message in the validation webhook to inform users when their `block` value is overridden?
=> [Feature] Override the `block` option of `rayStartParams` to true

ray-operator/main.go
* Create a Kubernetes cluster, and create a namespace `n1`.
* Deploy the operator with the following changes in `values.yaml`.
```yaml
image:
repository: kuberay/operator
tag: nightly
crNamespacedRbacEnable: true
singleNamespaceInstall: true
watchNamespace:
- n1
```
* We will get the following error message by running `kubectl logs ${KUBERAY_POD}` caused by [this line](https://github.com/ray-project/kuberay/blob/1779fcdd13ab15fda8fc477c496a6e2f7f1e2605/ray-operator/main.go#L157).
* Solution: Initialize the map before the assignment.
* Create a Kubernetes cluster, and create a namespace `n1`.
* Build the image with this PR, and deploy the operator with the following changes in `values.yaml`.
```yaml
image:
repository: controller
tag: latest
crNamespacedRbacEnable: true …
```
=> [Bug] Avoid assigning an entry to a map that is nil

ray-operator/controllers/ray/rayjob_controller.go
```go
if isJobSucceedOrFailed(rayJobInstance.Status.JobStatus) && rayJobInstance.Status.JobDeploymentStatus != rayv1.JobDeploymentStatusComplete {
...
}
```
The check of `JobDeploymentStatusComplete` is not necessary because there is a check to skip the reconciliation if the status is `rayv1.JobDeploymentStatusComplete`. 
* https://github.com/ray-project/kuberay/blob/b16c705c5e6fe194932301312ade7e1a87ec0ae2/ray-operator/controllers/ray/rayjob_controller.go#L124-L128
=> [RayJob][Status][1/n] Redefine the definition of JobDeploymentStatusComplete

apiserver/pkg/manager/resource_manager.go, apiserver/pkg/model/converter.go, apiserver/pkg/model/converter_test.go, apiserver/pkg/model/volumes.go, apiserver/pkg/model/volumes_test.go, apiserver/pkg/server/cluster_server.go, apiserver/pkg/server/serve_server.go, apiserver/pkg/util/cluster.go, apiserver/pkg/util/cluster_test.go, apiserver/pkg/util/job.go, apiserver/test/e2e/types.go, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1/webhook_suite_test.go, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/controllers/ray/batchscheduler/interface/interface.go, ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/rbac.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayjob_controller.go
This PR unifies all `v1 "k8s.io/api/core/v1"` to `corev1 "k8s.io/api/core/v1"` and removes duplicated imports, such as here found by @kevin85421: https://github.com/ray-project/kuberay/blob/b16c705c5e6fe194932301312ade7e1a87ec0ae2/ray-operator/controllers/ray/rayjob_controller.go#L11-L12
The `corev1` alias is a better choice than `v1` given that there are a lot of other packages named `v1` such as ` k8s.io/api/batch/v1` and `k8s.io/apimachinery/pkg/apis/meta/v1`. If we just use the `v1`, we will be easily confused with other `v1`.
=> [Refactor] Standardize all `k8s.io/api/core/v1` imports as `corev1`

.github/workflows/image-release.yaml, .github/workflows/test-job.yaml, ray-operator/DEVELOPMENT.md, ray-operator/Dockerfile.buildx
=> Publish Multi Arch images

ray-operator/controllers/ray/batchscheduler/schedulermanager.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/common/ingress_test.go, ray-operator/controllers/ray/common/job.go, ray-operator/controllers/ray/common/job_test.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/rbac.go, ray-operator/controllers/ray/common/route.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/suite_test.go, ray-operator/controllers/ray/utils/constant.go, ray-operator/main.go, ray-operator/test/e2e/rayjob_cluster_selector_test.go
The following diagram represents the dependency graph for packages in KubeRay. Originally, `constant.go` resided in the common package. However, sometimes the `utils` package needs to use certain constant variables from `constant.go`, but importing common would cause a circular dependency. Hence, we need to hard code some values or define constant variables in the `utils` as the workaround ([example](https://github.com/ray-project/kuberay/blob/be1037386f5c52f10058a6ba6f8a18054e67b8bb/ray-operator/controllers/ray/utils/util.go#L35)). This PR moves `constant.go` from `common` to `utils`.
=> [Refactor] Move constant.go from common to utils to avoid circular dependency

ray-operator/config/certmanager/certificate.yaml, ray-operator/config/default-with-webhooks/webhookcainjection_patch.yaml, ray-operator/config/webhook/service.yaml
instead of `ray-operator`. The former seems to be more widely used in this project.
=> chore webhook: change K8s annotations to use `kuberay-operator`

ray-operator/config/webhook/kustomization.yaml
and ValidatingWebhookConfiguration so they have more specific names of `kuberay-webhook-service` and `kuberay-validating-webhook-configuration` instead of the generic `webhook-service` and
`validating-webhook-configuration`, respectively.
The Service is in the `ray-system` namespace so it's unlikely to conflict with another Service's name in this namespace. But `ValidatingWebhookConfigurations` are cluster-scoped, so it's likely to conflict with another one that's also named `validating-webhook-configuration`.
running `bin/kustomize build config/default-with-webhooks` before and after, the diff is
```
50131c50131
<   name: webhook-service
---
>   name: kuberay-webhook-service
```
```
50252,50253c50252,50253
<   - webhook-service.ray-system.svc
<   - …
```
=> chore: add `kuberay-` name prefix to validating webhook Service

apiserver/pkg/server/ray_job_submission_service_server.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/suite_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/fake_httpproxy_httpclient.go, ray-operator/controllers/ray/utils/httpproxy_httpclient.go, ray-operator/main.go
The global `utils.GetRayDashboardClientFunc` and `utils.GetRayHttpProxyClientFunc` are used for injecting faked implementations while testing.
However, these global variables make tracing their mutations very hard and confusing. Even let developers suspect whether there were unsynchronized concurrent accesses to them or not. (https://github.com/ray-project/kuberay/pull/1724)
To reduce the scope of debugging and confusion, this PR removes these two global variables and introduces the `dashboardClientFunc` and `httpProxyClientFunc` as member fields of the `RayJobReconciler` and `RayServiceReconciler` instead. These two new member fields can only be injected when calling the `NewRayServiceReconciler` and `NewRayJobReconciler` constructors, therefore, they will be much easier to trace. 
- …
=> [Refactor] Remove global utils.GetRayXXXClientFuncs

ray-operator/apis/ray/v1/raycluster_webhook.go, ray-operator/apis/ray/v1/webhook_suite_test.go
This change prevents RayClusters with invalid names from being created
with actionable error messages instead of allowing their creation but
failing later with hidden errors.
```
❯ head /tmp/raycluster.yaml                                                                                                                                                                                                                                                                (base)
---
metadata:
name: sample.foo
...
❯ kubectl apply -f /tmp/raycluster.yaml                                                                                                                                                                                (base)
The RayCluster "sample.foo" is …
```
=> fix: validate RayCluster name with validating webhook

ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/utils/util.go
#1674 introduces default readiness and liveness probes for Ray Pods, regardless of whether GCS fault tolerance is enabled. For the head Pod, the readiness probe verifies the status of GCS and Raylet. The GCS check utilizes the API endpoint from the Ray dashboard at `DASHBOARD_ADDRESS:8265/api/gcs_healthz`.
I checked with @architkulkarni and @shrekris-anyscale. I can imply that the Ray dashboard is ready for “Ray Job Submission” and Ray Serve RESTful API if `DASHBOARD_ADDRESS:8265/api/gcs_healthz` returns “success”. Hence, a "ready" RayCluster implies that all Ray Pods are running and ready, including Ray head.
* Check https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/580-pod-readiness-gates/README.md for the details of `PodReady`.
=> [RayJob][Status][2/n] Redefine `ready` for RayCluster to avoid using HTTP requests to check dashboard status

ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/controllers/ray/rayjob_controller.go
This PR doesn’t change any code logic. Most of the work was done by #1733.
* `initRayJobStatusIfNeed` is the source of truth where `JobDeploymentStatusInitializing` is defined.
* `JobDeploymentStatusInitializing` means that `JobID`, `JobStatus`, and `RayClusterName` are initialized, so double creations of RayCluster CRs and `ray job` will not happen.
* `JobDeploymentStatusInitializing` implies that the RayJob is ready to create or get RayCluster CR.
=> [RayJob][Status][3/n] Define JobDeploymentStatusInitializing

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_test.go
* Reproduce the error
* Step 1: Set `suspend` to true.
* Step 2: The status changes to `suspended` after all Pods are deleted.
* Step 3: Set `suspend` back to false; this will trigger the creation of Pods.
* Step 4: Set `suspend` back to true before all Pods are fully operational. In this case, the state remains `suspended` instead of becoming `ready`.
* Step 5: At this moment, the KubeRay operator will skip the reconciliation because `suspend: true` and the status is `suspended`.
The function `reconcilePods` should only create Pods when `suspend` is false and the status is not `suspended`. However, RayCluster currently does not have a well-defined state machine. To avoid adding complexity to the codebase, I decided not to skip the reconciliation until we have a well-defined state …
=> [Hotfix][Bug] `suspend` is not a stateless operation 

ray-operator/controllers/ray/raycluster_controller.go
Follow-up to https://github.com/ray-project/kuberay/pull/1711 & https://github.com/ray-project/kuberay/pull/1741.
After https://github.com/ray-project/kuberay/pull/1741, we always run the reconcile loop for suspended RayCluster, regardless of it's state. This means that for suspended clusters we will always call DeleteCollection and record an event.
This PR makes a small optimization to check existing pods before calling DeleteCollection. This should not be susceptible to the same bug fixed in https://github.com/ray-project/kuberay/pull/1741 since we are not checking cluster state, but rather checking informer cache for existing pods.
https://github.com/ray-project/kuberay/issues/1667
=> Check existing pods for suspended RayCluster before calling DeleteCollection

ray-operator/controllers/ray/raycluster_controller_test.go
* Delete `"should update a raycluster object deleting a random pod"`.
* In #1253, we decided to make Ray Autoscaler the only decision maker to delete Ray Pods. In the test, random Pod deletion will not happen because `EnableInTreeAutoscaling` is true.
* The test `"simulate Ray Autoscaler scales down"` simulates the Ray Autoscaler's behavior to scale down the RayCluster by updating `WorkersToDelete`. However, we don't clean up the `WorkersToDelete` after the scaling process finishes.
=> [Bug] Clean up WorkersToDelete after the scaling process finishes

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
=> [RayJob][Status][5/n] Refactor getOrCreateK8sJob

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go
Reproduce the error:
* Step 1: Deploy a KubeRay operator without this PR. I recommend using the nightly image [1].
* Step 2: Create a RayJob using [this YAML](https://gist.github.com/kevin85421/d39ddb40a6fa247c0662f03ebaae0169). It is configured to sleep for 1000s, giving you ample time to terminate the head Pod while the job is running.
* Step 3: Delete the head Pod after the job is submitted.
* Step 4: If the submitter Pod reaches the `backoffLimit` before the new head Pod is ready, the KubeRay operator will fail after the head Pod is restored. This failure occurs because if the job is not found, both `jobInfo` and `error` will return as `nil`. Consequently, at L274, `isJobPendingOrRunning(jobInfo.JobStatus)` will attempt to dereference a `nil` pointer.
[1] To easily reproduce the …
=> [Bug][RayJob] Avoid nil pointer dereference

ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/suite_test.go
As @kevin85421 found out, we have set [`RAYCLUSTER_DEFAULT_REQUEUE_SECONDS_ENV`](https://github.com/ray-project/kuberay/blob/bf3fd63a97bc0b61c1858545dee3233679754c11/ray-operator/controllers/ray/suite_test.go#L83) to 10 seconds to speed up the tests. But we still wait for [`utils.RAYCLUSTER_DEFAULT_REQUEUE_SECONDS+5`](https://github.com/ray-project/kuberay/blob/bf3fd63a97bc0b61c1858545dee3233679754c11/ray-operator/controllers/ray/raycluster_controller_test.go#L208), which is 305 seconds and is too long, to fail a test.
I believe this inconsistency exists because there is no convenient converter for the env variable.
In this PR, I replaced all usages of `RAYCLUSTER_DEFAULT_REQUEUE_SECONDS` with `RAYCLUSTER_DEFAULT_REQUEUE_SECONDS_ENV`  in tests with the help of a simple `MustGetEnvInt` …
=> [Refactor] Use RAYCLUSTER_DEFAULT_REQUEUE_SECONDS_ENV as timeout of status check in tests

ray-operator/controllers/ray/batchscheduler/interface/interface.go, ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go, ray-operator/controllers/ray/raycluster_controller.go
Fixes https://github.com/ray-project/kuberay/issues/1752
- [√] I've made sure the tests are passing. 
- [√] Unit tests
- [√] Manual tests
=> Add volcano taskSpec annotations to pod

apiserver/DEVELOPMENT.md, apiserver/Makefile, apiserver/deploy/base/secure/apiserver.yaml, apiserver/deploy/base/secure/kustomization.yaml, apiserver/deploy/local/secure/kustomization.yaml
For testing we do need to be able to build both secure and insecure versions of app server. Added this support to make file
- [x ] I've made sure the tests are passing. 
=> added support for secure API server build

ray-operator/controllers/ray/raycluster_controller_test.go, ray-operator/controllers/ray/rayservice_controller_test.go
To simulates the Ray Autoscaler's behavior, it is better to manually clean up `WorkersToDelete` field after the scaling process in the CI test.
=> Clean up WorkersToDelete field during the CI test 

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go
Starting in Ray 2.8.0, the Ray Serve REST API is exposed at the same port as the Ray Dashboard instead of the dashbaord agent port (though I think the dashboard agent port still works.)
In addition, as a result of that change, the dashboard agent is no longer a concept that is exposed to the user.
This PR
- Updates the RayService controller to use the Dashboard endpoint instead of the DashboardAgent endpoint to make Serve REST API requests
- Removes the `DashboardAgentListenPort` from the `HeadService` and `ServeService` of the RayCluster and RayService, because it is no longer exposed to users.
After this PR, the DashboardAgentListenPort is only used for the RayCluster health probe: https://github.com/ray-project/kuberay/blob/cbd8adbdd911da7f039fc912137a09e7b044478d/ray-operator/controlle …
=> [RayService] Use DashboardPort for RayService instead of DashboardAgentPort

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/utils/util.go
Following the previous proposal https://github.com/ray-project/kuberay/issues/1557#issuecomment-1784162985, this PR introduces a new environment variable `GCS_FT_REDIS_CLEANUP_DEADLINE_SECONDS` to the kuberay-operator.
This variable will be set to the `.spec.activeDeadlineSeconds` option of the redis cleanup job of a fault-tolerant RayCluster, and it will terminate the job after the deadline no matter what.
This PR further makes the kuberay-operator remove the `ray.io/gcs-ft-redis-cleanup-finalizer` finalizer on the RayCluster allowing it to be deleted after the job is terminated.
The default value of `GCS_FT_REDIS_CLEANUP_DEADLINE_SECONDS` is 300. This essentially makes all redis cleanup jobs work in a best-effort manner for 5 minutes by default. …
=> [Feature][GCS FT] Best-effort redis cleanup job

apiserver/pkg/model/converter.go, apiserver/pkg/model/converter_test.go, apiserver/pkg/util/job.go, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/apis/ray/v1/zz_generated.deepcopy.go, ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/apis/ray/v1alpha1/zz_generated.deepcopy.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/test/e2e/rayjob_test.go
* Without this PR, the transition between `Running` and `Complete` is pretty confusing. If `ShutdownAfterJobFinishes` is false, the RayJob's `JobDeploymentStatus` will be `JobDeploymentStatusRunning` although the Ray job is `Succeeded` or `Failed`. Both `Succeeded` and `Failed` are terminal states, so the job can't have any state transition. However, KubeRay still has to process a lot of unnecessary code, including sending a request to the RayCluster to check the status of the Ray job.
* This PR redefines `JobDeploymentStatusComplete`. `JobDeploymentStatusComplete` means that the JobStatus is `Succeeded` or `Failed`, and we only check TTL when the RayJob is `JobDeploymentStatusComplete`.
* Currently, the lifecycles of the submitter K8s Job and its Pod are not well-defined. For example, …
=> [RayJob][Status][6/n] Redefine JobDeploymentStatusComplete and clean up K8s Job after TTL

ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/controllers/ray/rayjob_controller.go
`JobDeploymentStatusNew` indicates that this is a new RayJob CR, similar to [NewState](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/8cb6c8035eabd73c045f4078b27fa35767e2a52c/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L333) in the [spark-on-k8s-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master).
=> [RayJob][Status][7/n] Define JobDeploymentStatusNew explicitly

ray-operator/controllers/ray/rayjob_controller.go
Currently, only a RayJob with the status `JobDeploymentStatusRunning` can transition to `JobDeploymentStatusComplete` in the current state machine. In the future, there might be other conditions under which a RayJob transitions to `JobDeploymentStatusComplete` from other statuses. For example, if a RayJob fails to submit Ray jobs several times, we may consider transitioning its status to `JobDeploymentStatusComplete`. However, only the transition from Running will check `JobStatus`.
=> [RayJob][Status][8/n] Only a RayJob with the status Running can transition to Complete at this moment

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go
Without this PR, RayJob has a complex behavior to pass changes from RayJob's spec to the associated RayCluster.
* If Ray Autoscaling is enabled, do not pass any changes to the associated RayCluster.
* If the change concerns only replicas, update the RayCluster.
* Otherwise, do not update the RayCluster.
This PR decides to remove the behavior because:
* For batch jobs, the required computation resources should be deterministic. Hence, no need to pass changes to RayCluster.
* If users still wish to update `replicas` at runtime, they should use the Ray Autoscaler instead.
* If users still want to update `replicas` manually, they still can update RayCluster directly.
* Allowing users to update `replicas` at runtime will make gang scheduling much more complex.
* The best practice for batch …
=> [RayJob][Status][9/n] RayJob should not pass any changes to RayCluster

ray-operator/controllers/ray/rayjob_controller.go
#735 promises that the KubeRay operator will try to stop the job at least once by adding a finalizer to the RayJob. We should only need to add the finalizer to the RayJob when the CR status is `JobDeploymentStatusNew`.
=> [RayJob][10/n] Add finalizer to the RayJob when the RayJob status is JobDeploymentStatusNew

ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/test/e2e/rayjob_test.go
* Only RayJob with the status `Running` and `Initializing` allows transitioning to `Suspended`. This PR adds a test to ensure there is no state transition from `Complete` to `Suspended`.
* Resume a suspended RayJob by setting `suspend` to false:
* Without this PR, it will fail to get RayCluster because `Status.RayClusterName` is empty.
* This PR explicitly defines that the RayJob will transition from `Suspended` to `New`. Consequently, the RayCluster will be created upon resumption. However, there is still an issue with the submitter Job. If users don't set `shutDownAfterFinishes`, the submitter Job will become Complete after suspension. When we resume the RayJob, a new Kubernetes Job will not be created because one already exists. This is a follow-up issue.
=> [RayJob][Status][11/n] Refactor the suspend operation

ray-operator/controllers/ray/rayjob_controller.go
See https://github.com/ray-project/kuberay/pull/1776#pullrequestreview-1797420259.
Closes #1777
Work as expected:
=> [Feature] Warn Users When Updating the RayClusterSpec in RayJob CR

tests/compatibility-test.py
These global variables `ray_image`, `ray_version`, and `kuberay_operator_image` are heavily used in test case declarations. But currently, their value will be changed in the `if __name__ == '__main__'` block which runs after test case declarations.
Therefore, it causes undesired evaluations in some cases, such as https://github.com/ray-project/kuberay/blob/59503c647d8708e7e70ae8bb0bde83d7c4142465/tests/compatibility-test.py#L153-L154
where it always evaluates the `ray_version` to the initial default value, instead of the value we inject via the env later. 
See more details: https://github.com/ray-project/kuberay/pull/1770#discussion_r1436669602
This PR fixes their values at the beginning of the test script and does not change them after initialization. …
=> [CI] Fix variable initializations used in test case declarations

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/test/e2e/long_running.py, ray-operator/test/e2e/rayjob_suspend_test.go
#1782 mentions that if users don't set `shutDownAfterFinishes`, the submitter Job will become `Complete` after suspension. When we resume the RayJob, a new Kubernetes Job will not be created because one already exists. Note that we currently use the RayJob name for the submitter Job to avoid duplicate creation.
* Kubernetes Job cleanup
* The default deletion policy of K8s Job is `orphanDependents`. Hence, if you delete the Job via the client-go API, the associated Pods will not be deleted. If you use `kubectl` to delete the Job, the related Pods will be deleted.
* `ttlSecondsAfterFinished`
* `suspend`: When you suspend a Job, any running Pods that don't have a status of Completed will be [terminated](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) with a …
=> [RayJob][Status][12/n] Resume suspended RayJob

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_test.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go, ray-operator/controllers/ray/utils/serve_api_models.go
Followup to https://github.com/ray-project/kuberay/pull/1779#pullrequestreview-1798586013. 
- Deletes the SINGLE_APP and MULTI_APP codepaths and unifies them into one codepath.
- Deletes unused dashboard function `GetDeployments`
=> [RayService] Unify multi-app and single-app codepath

ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/go.mod, ray-operator/go.sum
```sh
go get github.com/orcaman/concurrent-map/v2
go mod tidy
```
* Some comments for Golang built-in concurrent map implementation: https://stackoverflow.com/questions/11063473/map-with-concurrent-access 
=> [Refactor] Define the value type of the concurrent map explicitly to avoid type conversion

ray-operator/controllers/ray/rayjob_controller.go
Currently, we set the submitter's `TTLSecondsAfterFinished` to 0 when suspending a RayJob, and we hope it will help us to clean up k8s jobs and pods. However, the submitters can actually stuck like this when it tries to tail job logs but the cluster has gone:
```python
2023-12-30 18:26:20,109	INFO cli.py:36 -- Job submission server address: http://long-running-raycluster-nh7tm-head-svc.test-ns-65xpb.svc.cluster.local:8265
2023-12-30 18:26:21,930	SUCC cli.py:60 -- -----------------------------------------------
2023-12-30 18:26:21,931	SUCC cli.py:61 -- Job 'long-running-r5mrk' submitted successfully
2023-12-30 18:26:21,931	SUCC cli.py:62 -- -----------------------------------------------
2023-12-30 18:26:21,931	INFO cli.py:285 -- Next steps
2023-12-30 18:26:21,931	INFO cli.py:286 -- Query …
```
=> [RayJob] Delete the Kubernetes Job and its Pods immediately when suspending

ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/controllers/ray/rayjob_controller.go
The `suspend` operation should be atomic. In other words, if users set the `suspend` flag to true and then immediately set it back to false, either all of the RayJob's associated resources should be cleaned up, or no resources should be cleaned up at all. To keep the atomicity, if a RayJob is in the `Suspending` status, we should delete all of its associated resources and then transition the status to `Suspended` no matter the value of the `suspend` flag.
There is a breaking change in this PR:
* This PR doesn't send a `StopJob` request to stop the Ray job to simplify logic. Currently, Ray doesn't have a best practice to stop a Ray job gracefully. At this moment, KubeRay doesn't stop the Ray job before suspending the RayJob. If users want to stop the Ray job by SIGTERM, users need to set …
=> [RayJob][Status][13/n] Make suspend operation atomic by introducing the new status `Suspending`

ray-operator/controllers/ray/rayjob_controller.go
Currently, the code paths for `Initializing` and `Running` are strongly coupled. This PR decouples them to facilitate further refactoring and to build a well-defined state machine.
* `Initializing` is responsible for creating the RayCluster, setting DashboardURL, and creating the submitter K8s Job.
* `Running` is responsible for monitoring `JobStatus`.
All existing e2e tests cover this code path.
=> [RayJob][Status][14/n] Decouple the Initializing status and Running status

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
* Currently, there are two paths to transition to the `Suspended` status.
* `Initializing` -> `Suspended`
* `Running` -> `Suspending` -> `Suspended`
* The case "Initializing -> Suspended" is pretty tricky:
* Case 1: Set `suspend` to true before creating the RayCluster.
* The status will transition to `Suspended` directly.
* Case 2: Set `suspend` to true after the RayCluster is created and before the K8s Job creation.
* The status will first transition to `Running` and then to `Suspending`. Additionally, the user must wait until both the RayCluster and the Kubernetes Job are ready to transition to `Running`, which **may take a considerable amount of time** (depending on the time of pulling images).
* This PR unifies the codepath for the status transition to `Suspended`.
* `Initializing` -> …
=> [RayJob][Status][15/n] Unify the codepath for the status transition to `Suspended`

ray-operator/test/e2e/rayjob_cluster_selector_test.go, ray-operator/test/e2e/rayjob_suspend_test.go, ray-operator/test/e2e/rayjob_test.go, ray-operator/test/support/test.go
The current go e2e test doesn't report operator logs and this makes troubleshooting difficult.
This PR introduces a `test.StreamKubeRayOperatorLogs()` helper to stream operator logs back until the bound `*testing.T` ends.
Under the hood, It uses the same API used by `kubectl logs -f`.
=> [CI] stream operator logs from kind in go e2e tests

ray-operator/test/e2e/rayjob_suspend_test.go
This PR provides an end-to-end test covering the happy-path scenario for Kueue. Specifically, it creates a suspended RayJob with `.spec.suspend = true` at creation time (achieved by Kueue using a webhook), resumes it manually, and checks for successful completion.
Closes #1800 
=> [Test][RayJob] Kueue happy-path scenario

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
Unify the codepath for status updates into a single place. The [ReplicaSet source code](https://sourcegraph.com/github.com/kubernetes/kubernetes@9e622d23648f4af4a12835de97484dc0e4859269/-/blob/pkg/controller/replicaset/replica_set.go?L706-L710) has the similar pattern.
=> [RayJob][Status][17/n] Unify the codepath for status updates

ray-operator/config/samples/ray-service.different-port.yaml
As title.
`ray-service.different-port.yaml` is used to demonstrate how to set custom serve port. However, the instruction is not complete.
when running `ray-service.different-port.yaml`, it may appear that everything is functioning correctly. However, the custom serve port is not accurately reflected in the serve health check for worker Pods. The absence of errors is due to the serve app only requiring a minimal amount of CPU resources. Consequently, the worker Pod might not even host a serve replica.
To illustrate this issue, I have created a Ray service similar to ray-service.different-port.yaml, but with a modified serve app configuration ensuring each Pod has one serve replica. As shown in the experiment below, the worker Pod consistently fails the health check because it defaults to …
=> [RayService] Fixed issue where the custom serve port is not reflected in the serve health check for worker Pods

apiserver/Autoscaling.md, apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go, apiserver/test/e2e/cluster_server_e2e_test.go, apiserver/test/e2e/config_server_e2e_test.go, apiserver/test/e2e/job_server_e2e_test.go, apiserver/test/e2e/resources/create_detached_actor.py, apiserver/test/e2e/resources/terminate_detached_actor.py
Cleaning up existing e2e tests
Adding e2e autoscaling test
- [x ] I've made sure the tests are passing. 
- [ x] Unit tests
=> Enhancements to e2e test, adding Autoscaling

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/constant.go, ray-operator/controllers/ray/utils/httpproxy_httpclient.go
Currently, for high availability of RayService, KubeRay checks each serving Pod's HTTP proxy's health at every reconciliation. If not healthy, KubeRay changes the corresponding Pod's label, and that Pod will later not be selected by serve service.
This method has several shortcomings:
- KubeRay may become overloaded due to checking every Ray Pod at every reconciliation, especially if there is a large number of Ray Pods.
- If KubeRay operator Pod fails, high availability will also no longer exist. An unhealthy worker Pod cannot be removed from the serving service!
This PR mainly moves the HTTP proxy's health check to the readiness probe for all worker Pods while still checking the head Pod's HTTP proxy's health at every reconciliation for head Pod. This has several benefits:
- Reduce the …
=> [RayService] Move HTTP Proxy's Health Check to Readiness Probe for Wokers

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_suspended_test.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
https://github.com/ray-project/kuberay/pull/1783#pullrequestreview-1801599906
> Kueue does not admit RayJob with shutDownAfterFinishes = false, so at KubeRay level, we may want to consider this an invalid configuration for suspended RayJobs.
=> [RayJob] Validate RayJob spec

ray-operator/config/samples/ray-service.autoscaler.yaml, ray-operator/config/samples/ray_v1alpha1_rayservice.yaml, tests/framework/prototype.py, tests/test_sample_rayservice_yamls.py
Fix flaky tests introduced by #1808. Note that the RayService was already flaky before #1808, but it became much more unstable after #1808 (failing about 5 times in 6 runs). Although the tests remain as flaky as they were before #1808 even after this PR is merged, it does alleviate the additional flakiness introduced by #1808.
=> [RayService][HA] Fix flaky tests

ray-operator/controllers/ray/rayjob_controller.go
If users create a RayJob with a buggy `entrypoint`, causing the submitter K8s Job to consistently fail, it won't respect the `ttlSecondsAfterFinished` value set by users. 
The submitter Job sends a request to the Ray head to create a Ray job. Due to the buggy `entrypoint`, the Ray job fails immediately, and KubeRay transitions the RayJob status to `Complete`. After `ttlSecondsAfterFinished` seconds following the transition of the RayJob to `Complete`, the RayCluster will be deleted.
The submitter K8s Job will retry 3 times by default. If the submitter Job attempts to send a request to the Ray head after the Ray head has been deleted, it will result in a request timeout and failure. I haven't figured out the exact timeout value, but based on my observation, it's around 1 to 2 minutes. …
=> [RayJob][Status][18/n] Control the entire lifecycle of the Kubernetes submitter Job using KubeRay

ray-operator/Makefile, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/test/e2e/rayjob_test.go
#1831 addresses the case where the Ray head can receive and create the Ray job successfully, but the Ray job fails. In that case, the RayJob can transition to `JobDeploymentComplete` because the KubeRay operator can get the job information from the Ray head and the Ray job is `Failed`, a terminal state.
This PR handles a different case compared with #1831. This PR focuses on the case that the submitter K8s Job can't send a request to the Ray head successfully. Hence, the KubeRay operator can't get any Ray job information from the Ray head, and the RayJob can't transition to the `JobDeploymentComplete` status. This PR transitions the status to `JobDeploymentComplete` when the K8s Job is `Failed`.
Create a RayJob using [this …
=> [RayJob][Status][19/n] Transition to `Complete` if the K8s Job fails

tests/test_sample_raycluster_yamls.py
This PR improves the flexibility of KubeRay in sample YAML tests. Now developers can use Python command's Args to run individual YAML file.
Here's an example:
1. [Default] Run all YAML files.
`python3 tests/test_sample_raycluster_yamls.py`
2. Specified a single YAML file.
`python3 tests/test_sample_raycluster_yamls.py --yaml-file ray-cluster.mini.yaml`
You can also specify multiple YAML files:
`python3 tests/test_sample_raycluster_yamls.py --yaml-file ray-cluster.mini.yaml ray-cluster.external-redis.yaml`
Without this PR, developers have to run all sample YAML files when executing YAML tests, which would be time-consuming and inefficient.
With this PR, they can now specify particular YAML files for testing, significantly reducing the time required for developers. …
=> Improve flexibility in RayCluster yaml test 

tests/test_sample_rayservice_yamls.py
The Zero Downtime Rollout Test is flaky for the following reason:
The current logic for the Zero Downtime Rollout operates as follows:
1. Once the pending RayCluster is ready for service, the RayService Controller updates its status to 'running' and updates the selection label for the serve service.
2. The RayService Controller then waits for 60 seconds before deleting the old RayCluster. This 60-second interval allows time for the serve service to be updated.
However, a critical issue is that the 'running' status merely indicates the readiness of the new RayCluster to serve traffic; it does not confirm that the serve service has begun redirecting traffic to the new RayCluster. As a result, requests sent after the status change to 'running' might still be responded to by the old …
=> [RayService][Hotfix] Hotfix for Flaky Zero Downtime Rollout Test

ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/controllers/ray/common/ingress.go, ray-operator/controllers/ray/rayservice_controller.go
It is highly possible that the built-in ingress support in RayService hasn't been working since the day it was committed.
You can create a RayService with `EnableIngress: true` with [this gist](https://gist.github.com/kevin85421/0ec82f72369ea274687d892735086023). Initially, the RayCluster managed by the RayService will create a Kubernetes Ingress. Once the RayCluster is ready, the RayService controller will attempt to create another ingress. This occurs because both the RayCluster and RayService controllers use `HeadGroupSpec.EnableIngress` to determine whether to create a Kubernetes Ingress. However, the Ingress created by RayService will fail because of the following reason:
```
2024-01-17T08:37:17.539Z	ERROR	controllers.RayService	Ingress create error!	{"Ingress.Error": "admission …
```
=> [RayService] Deprecate the built-in ingress support of RayService

apiserver/pkg/model/converter_test.go, clients/python-apiserver-client/python_apiserver_client/params/environmentvariables.py
After creating a cluster by setting environment variable valueFrom configMap, the cluster gets created correctly and the environment variables are set correctly in the cluster. However, when getting the cluster using the python client, kuberay.get_cluster()
Closes https://github.com/ray-project/kuberay/issues/1804
=> Fixing Python client handling of env from

ray-operator/Makefile
`generate` target should also run `./hack/update-codegen.sh`
=> run ./hack/update-codegen.sh in generate make target

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go
KubeRay has some limitations for the suspend operation. The limitations are a subset of the limitations of Kueue (https://kueue.sigs.k8s.io/docs/tasks/run_rayjobs/#c-limitations). For example, KubeRay allows users to suspend a RayJob with autoscaling enabled, but Kueue doesn't. This PR relocates the limitation check to where the controller validates RayJobSpec, offering a unified code path for better maintainability.
For Kueue-only limitations, the Kueue's validation webhook will complain if users create an invalid YAML.
=> [RayJob][Kueue] Move limitation check to validateRayJobSpec

.buildkite/test-sample-yamls.yml, tests/framework/utils.py, tests/test_security.py
Before this PR, the Ray docker image was manually loaded into the `kind` cluster before running the sample YAML tests.  Some possible reasons for this are:
(1) Save time by preloading the Ray image
(2) Make it easy to configure the Ray version used, by using the RAY_IMAGE environment variable to define the image to be loaded by `kind load`.
But (2) seems to not actually be happening.  The image specified by RAY_IMAGE is indeed loaded by `kind load`, but the Ray images actually used by the sample YAML tests are specified in the sample YAML files themselves, and they don't appear to be overwritten anywhere. So RAY_IMAGE has no effect on the Ray version that actually runs in the test.
To prove this, you can run
`RAY_IMAGE=rayproject/ray:1.0.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 …
=> [CI] Do not load Ray into `kind` cluster

apiserver/pkg/util/config.go, apiserver/pkg/util/service.go, ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/common/route.go, ray-operator/controllers/ray/common/service.go, ray-operator/controllers/ray/common/service_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/constant.go, tests/framework/prototype.py, tests/test_sample_rayservice_yamls.py
Previously, we didn't have a label for querying resources, such as the underlying ray cluster, created by a RayJob, while we had the `ray.io/service` label for querying resources created by a RayService.
We could introduce a new `ray.io/job` label for this purpose, and that would result in having three labels that look similar:
* `ray.io/job`
* `ray.io/service`
* `ray.io/cluster`
However, the current usage of the `ray.io/cluster` label differs greatly from the first two.
After a discussion with @kevin85421, we think we could clarify the usage of the first two by replacing them with the following labels:
* `ray.io/originated-from-name`
* `ray.io/originated-from-type`
Examples:
```sh
ray.io/originated-from-name: myjob
ray.io/originated-from-type: rayjob
ray.io/originated-from-name: …
```
=> Add `ray.io/originated-from` labels

ray-operator/config/samples/ray-job.sample.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
See https://github.com/ray-project/kuberay/issues/1850 for details.
Closes https://github.com/ray-project/kuberay/issues/1850
=> RayJob: inject RAY_DASHBOARD_ADDRESS envariable variable for user provided submiter templates

ray-operator/config/samples/ray-job.sample.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/utils/constant.go
Inject RAY_SUBMISSION_ID env variable for the user provided submitter template to avoid double submission. With the submission ID, the second submission will be rejected by Ray, and users will get the following exception:
```
ValueError: Job with submission_id rayjob-sample-fjnb8 already exists. Please use a different submission_id.       
```
=> [RayJob] Inject RAY_SUBMISSION_ID env variable for user provided submitter template

ray-operator/test/e2e/rayjob_test.go, ray-operator/test/e2e/stop.py
This is the test for #1855.
Closes #1866 
=> [Test][RayJob] Transition to `Complete` if the JobStatus is STOPPED

ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go
=> rayjob controller: update EndTime to always be the time when the job deployment transitions to Complete status

ray-operator/Makefile
Since adding applyconfiguration for generated clients (https://github.com/ray-project/kuberay/pull/1818), code generation has taken longer (~2 mins). We currently run `generate` for the build / test targets and the additional 2 minutes adds up over time. 
This PR removes the `generate` target from build/test targets, removing the 2 min delay. I was initially hesitant about removing this target because it would make it easier to forget code generation. However, I think this mostly mitigated by the fact that we have [checks to verify generated code](https://github.com/ray-project/kuberay/blob/master/.github/workflows/consistency-check.yaml#L30-L36). 
=> Remove generate target from build/test targets

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/test/e2e/rayjob_test.go
When a RayJob is configured with ShutdownAfterJobFinishes=true, Kuberay will immediately delete the associated RayCluster and submitter job once the job completes. Users can tune how long the cluster and submitter job stays around with TTLSecondsAfterFinished. Note that the RayJob resource itself is never deleted automatically, this always needs external action to be removed.
Even without setting `TTLSecondsAfterFinished`, there is very little reason to delete the submitter job. The submitter job usually contains the most useful logs for the job and is not using any cluster resources once completed. In addition, the submitter job will always be cleaned up when the RayJob is eventually deleted due it's owner reference back to the RayJob. This PR proposes to never delete the submitter job …
=> RayJob: don't delete submitter job when ShutdownAfterJobFinishes=true

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/utils/constant.go
Currently, when creating a RayService, two identical serve services are created as shown below:
```shell
kubectl apply -f /home/ubuntu/kuberay/ray-operator/config/samples/ray-service.sample.yaml
kubectl get svc
```
`rayservice-sample-serve-svc` is the original serve service, whereas `rayservice-sample-raycluster-bw4xz-serve-svc` is the serve service exclusively used to support [Raycluster with serve support](https://github.com/ray-project/kuberay/pull/1672). Clearly, the latter one should not be created when creating RayService.
1. Currently, we need to add specific labels and readiness probe for Raycluster created by RayService. However, the `ray.io/enable-serve-service` annotation has been used to determine whether a Raycluster is created by RayService. This method is not always …
=> [RayService] Avoid Duplicate Serve Service

ray-operator/config/samples/pytorch-text-classifier/fine-tune-pytorch-text-classifier.py, ray-operator/config/samples/pytorch-text-classifier/ray-job-v1alpha1.pytorch-distributed-training.yaml, ray-operator/config/samples/pytorch-text-classifier/ray-job.pytorch-distributed-training.yaml
Add a sample RayJob that packages [Fine-tune a PyTorch Lightning Text Classifier with Ray Data](https://docs.ray.io/en/master/train/examples/lightning/lightning_cola_advanced.html) into a single RayJob. 
I plan to use this sample for future documentation with Kueue, but this change could be a good sample on it's own as well.
Part of https://github.com/ray-project/kuberay/issues/1890
=> Add a sample RayJob to fine-tune a PyTorch lightning text classifier with Ray Data

docs/reference/api.md, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/samples/ray-job.sample.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/pkg/client/applyconfiguration/ray/v1/rayjobspec.go, ray-operator/test/e2e/rayjob_lightweight_test.go
Some users are not willing to allocate additional compute resources for the submitter Kubernetes Job. Hence, this PR implements the light-weight job submission which uses a HTTP request to submit the Ray job.
Closes #1558 
=> [Feature][RayJob] Support light-weight job submission

helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml
When listing RayJob with kubectl, only the name and age of the RayJob was printed. This PR adds additional print columns to also print the status, start time and end time of a RayJob.
```
$ kubectl get rayjob
NAME                  JOB STATUS   DEPLOYMENT STATUS   START TIME   END TIME   AGE
rayjob-sample-x98k6                Initializing                                13s
$ kubectl get rayjob
NAME                  JOB STATUS   DEPLOYMENT STATUS   START TIME   END TIME   AGE
rayjob-sample-x98k6                Running                                     70s
$ kubectl get rayjob
NAME                  JOB STATUS   DEPLOYMENT STATUS   START TIME             END TIME   AGE
rayjob-sample-psgrj   RUNNING      Running             2024-02-01T17:55:49Z              46s
$ kubectl get rayjob
NAME …
```
=> [RayJob] Add additional print columns for RayJob

apiserver/pkg/server/ray_job_submission_service_server.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go, ray-operator/controllers/ray/utils/fake_serve_httpclient.go
In #1835, we store the logger in the context, so we no longer need to pass the logger as an argument.
=> [Refactor] Remove any unnecessary logger

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/common/pod_test.go, ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go
This PR ensures consistent use of CRDType instead of string types to avoid potential bugs, addressing the issue described here: https://github.com/ray-project/kuberay/blob/52cb1a13c6749c8473c543a2cad339e145f2dbd2/ray-operator/controllers/ray/raycluster_controller.go#L1059
As shown below, we can successfully detect that the RayCluster is created by RayService:
1. The health check is injected into the readiness probe. 
2. The `RAY_timeout_ms_task_wait_for_death_info` environment variable is set.
```shell
kubectl apply -f /home/ubuntu/kuberay/ray-operator/config/samples/ray-service.sample.yaml
kubectl get pod
kubectl describe $(kubectl get pods -o=name | grep worker) | grep  "Readiness:\|Liveness:"
kubectl describe $(kubectl get pods -o=name | grep worker) | grep …
```
=> Refactor to Ensure Consistent Use of CRDType

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/util_test.go, ray-operator/test/e2e/rayjob_test.go
Without this PR, the KubeRay operator would still create a RayCluster and a Kubernetes Job for the submitter even if `runtimeEnvYAML` is not a valid YAML string. Subsequently, the Ray job would fail, and KubeRay would transition the status to Complete after the submitter Kubernetes Job retries three times. It is wasteful to create a RayCluster and a submitter Kubernetes Job when the Ray job is destined to fail.
With this PR, the KubeRay operator will validate `runtimeEnvYAML` before taking any action, ensuring that no compute resources are wasted.
=> [RayJob] Validate whether runtimeEnvYAML is a valid YAML string

apiserver/pkg/server/ray_job_submission_service_server.go, ray-operator/controllers/ray/utils/dashboard_httpclient.go, ray-operator/controllers/ray/utils/dashboard_httpclient_test.go, ray-operator/test/e2e/rayjob_lightweight_test.go
Continue the #1893, this PR completes the lightweight job submission by adding supports of `entrypoint_num_cpus`, `entrypoint_num_gpus`, and `entrypoint_resources` parameters while generating submission requests.
I also corrected the type of `RayJobRequest.Resources` to `map[string]float32` as suggested in the ray source: https://github.com/ray-project/ray/blob/cfbf98c315cfb2710c56039a3c96477d196de049/dashboard/modules/job/common.py#L353
=> [Feature][RayJob] Support light-weight job submission with entrypoint_num_cpus, entrypoint_num_gpus and entrypoint_resources

ray-operator/controllers/ray/utils/dashboard_httpclient.go
Before #1733, the Ray dashboard required approximately 5 seconds to be ready to serve requests after the Ray head was running and ready. Hence, #1000 increases the timeout of the HTTP client to 2 mins to hotfix this issue. However, if the Ray dashboard crashes, the KubeRay operator will stuck there for 2 mins which is not acceptable.
After #1733, the readiness probe will verify the readiness of the Ray dashboard. Consequently, if the head Pod is ready, it implies that the Ray dashboard is also prepared to serve requests. Hence, we can set the timeout from 2 mins back to 2 seconds.
Deploy RayJob with [this YAML](https://gist.github.com/kevin85421/dc1777bdbbbc762e0ff57831da781cd3) 25 times.
=> [RayJob] Set the timeout of the HTTP client from 2 mins to 2 seconds

ray-operator/config/samples/pytorch-text-classifier/ray-job.pytorch-distributed-training.yaml
Even though Kuberay automatically adds taints for `nvidia.com/gpu`, some of Kueue's features will directly inspect the PodTemplate from the RayJob before the tolerations are applied. This change adds the toleration premptively to optimize Kueue's scheduling logic  
=> add toleration for GPUs in sample pytorch RayJob

ray-operator/controllers/ray/utils/dashboard_httpclient.go
The schema of RayJobInfo is already correct. I have put the [ray source link](https://github.com/ray-project/ray/blob/cfbf98c315cfb2710c56039a3c96477d196de049/dashboard/modules/job/pydantic_models.py#L38-L107.) as a reference on top of the RayJobInfo definition.
=> [Chore][RayJob] Remove the TODO of verifying the schema of RayJobInfo because it is already correct

ray-operator/controllers/ray/rayjob_controller_test.go
The envtest is very messy:
* The `RayJob` spec is very different from the real RayJob YAML file.
* There is no clear goal for the code path that the test wants to verify.
* Many `It` tests are irrelevant, yet we include all of them in a single suite with unnecessary dependencies.
* [Example](https://github.com/ray-project/kuberay/pull/1916#discussion_r1483766017)
* The `ClusterSelector` test has already been covered by e2e tests.
This PR's tests focus on the most common code path of RayJob, i.e., New -> Initializing -> Running -> Complete.
=> [RayJob] Rewrite RayJob envtest

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/utils/util.go, ray-operator/controllers/ray/utils/util_test.go
OpenShift Routes `spec.host` values are a concatenation of Route `metadata.name` and `metadata.namespace`, which can expand beyond 63 characters without care, causing a failure to create the Route.
Closes #1882
=> Fixes to shorten generated Route name with consideration for namespace

helm-chart/kuberay-operator/templates/deployment.yaml, helm-chart/kuberay-operator/values.yaml, ray-operator/apis/config/v1alpha1/configuration_types.go, ray-operator/main.go
Zapr uses structured json logging by default. However in KubeRay we have enabled development mode which enables console logging. While console logging is easier to read during development, structured logging should be used by default in production so that the key/value pairs in the logs can be used for searching.
this is some sample logs with the changes:
```
$ kubectl logs -f kuberay-operator-5987588ffc-4bfdh
{"level":"info","ts":"2024-02-06T17:26:41.668Z","logger":"setup","msg":"the operator","version:":""}
{"level":"info","ts":"2024-02-06T17:26:41.668Z","logger":"setup","msg":"Flag watchNamespace is not set. Watch custom resources in all namespaces."}
{"level":"info","ts":"2024-02-06T17:26:41.668Z","logger":"setup","msg":"Setup manager"} …
```
=> Support json structured logging 

ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go
When `ttlSecondsAfterFinished` is set to 0, the submitter job may fail and retry, even though the RayJob's has JobDeploymentStatus is `Complete` and JobStatus is `SUCCEEDED`. Without this PR, if the Ray job is in a terminal state (e.g. `SUCCEEDED`), the RayJob will transition from `Running` to `Complete`, and check `ttlSecondsAfterFinished` to determine whether is it ready to delete RayCluster or not. However, the submitter Kubernetes Job may fail because it still requires some time to receive the logs from the Ray head, but the head service has already been deleted.
In this PR, RayJob transitions from `Running` to `Complete` if and only if the submitter Job is `Complete` or `Failed`.
* Although all RayJob custom resources have a `Complete` (JobDeploymentStatus) and …
=> [Bug] Submitter K8s Job fails even though the RayJob has a JobDeploymentStatus `Complete` and a JobStatus `SUCCEEDED`

helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, helm-chart/kuberay-operator/templates/multiple_namespaces_role.yaml, helm-chart/kuberay-operator/templates/role.yaml, ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/config/rbac/role.yaml, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/pkg/client/applyconfiguration/ray/v1/rayservicestatuses.go
This PR adds the `NumServeEndpoints` field to the RayService's status. The `NumServeEndpoints` field indicates the number of active serving Ray Pods or the number of Ray Pods selected by the serve service. If a Ray Pod has no proxy actor or is unhealthy, it will not be counted.
This new field can help users and CI tests determine how many Ray Pods are capable of serving, making debugging much easier. This is crucial because, with the high availability feature of RayService, even if some worker Pods become unhealthy, it is hard to tell since everything appears to work just fine on the surface.
```shell
kubectl apply -f /home/ubuntu/kuberay/ray-operator/config/samples/ray-service.sample.yaml
kubectl describe rayservice rayservice-sample | grep "Num Serve Endpoints"
kubectl apply -f …
```
=> [RayService] Add New Status: NumServeEndpoints

.github/workflows/image-release.yaml, .github/workflows/test-job.yaml
The DockerHub bot has somehow been removed from the KubeRay DockerHub account, causing KubeRay CI to fail when pushing images to DockerHub. We can resolve this by re-adding the bot. However, I lack access to set the repository secrets, which means the process could be lengthy and block every PR.
As a workaround, this PR doesn't push images to DockerHub. Instead, it only pushes images to Quay. Next week, I will discuss with the community to determine whether we should support only Quay.
=> [CI] Don't push new images to DockerHub

docs/reference/api.md, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1/raycluster_types.go, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/apis/ray/v1/zz_generated.deepcopy.go, ray-operator/apis/ray/v1alpha1/raycluster_types.go, ray-operator/apis/ray/v1alpha1/rayjob_types.go, ray-operator/apis/ray/v1alpha1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/config/samples/ray-job.sample.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/pkg/client/applyconfiguration/ray/v1/rayjobspec.go, ray-operator/test/e2e/rayjob_test.go
* Initially, `StartTime` refers to the time when the Ray job starts running on the RayCluster. This PR redefines `StartTime` to the time when `JobDeploymentStatus` transitioned from `New` to `Initializing`.
* `ActiveDeadlineSeconds`: Similar to `ActiveDeadlineSeconds` in K8s Job https://kubernetes.io/docs/concepts/workloads/controllers/job/.
* We don't check `ActiveDeadlineSeconds` if the RayJob is in `New`, `Complete`, `Suspending`, and `Suspended`.
* We only check `ActiveDeadlineSeconds` if the RayJob is in the `Initializing` or `Running` state, which may occupy some computing resources.
* If the RayJob passes `ActiveDeadlineSeconds`, KubeRay will transition the status to `Complete`.
=> [RayJob] Support ActiveDeadlineSeconds

helm-chart/ray-cluster/templates/raycluster-cluster.yaml, helm-chart/ray-cluster/values.yaml
This adds a `common` section for values shared between the head and workers and adds an `containerEnv` section to common env vars.
Closes #1934
Manual Tests Run:
- Leaving `common.containerEnv` blank and rendering chart
- Setting `common.containerEnv` and ensuring envs rendered in head, worker and additional worker groups
- Setting `common.containerEnv` and `head.containerEnv`
- Setting `common.containerEnv` and `worker.containerEnv`
- Setting `common.containerEnv` and `additionalWorkerGroups.smallGroup.containerEnv` (With additionalWorkerGroups enabled) 
- Setting `head.containerEnv` only
- Setting `worker.containerEnv` only
=> Add common containerEnv section to Helm Chart

helm-chart/kuberay-operator/crds/ray.io_rayservices.yaml, ray-operator/apis/ray/v1/rayservice_types.go, ray-operator/config/crd/bases/ray.io_rayservices.yaml, ray-operator/pkg/client/applyconfiguration/ray/v1/rayservicestatuses.go, tests/test_sample_rayservice_yamls.py
After this PR:
- `RayServiceAddCREvent` uses `serviceStatus` and `numServeEndpoints` to check if it has converged. This addresses the issue described here: https://github.com/ray-project/kuberay/pull/1823#discussion_r1448271406. Checking `serviceStatus` ensures serve applications within the RayCluster are prepared to handle incoming traffic, and verifying `numServeEndpoints > 0` confirms that the k8s serve service is ready to redirect traffic to the RayCluster.
- `RayServiceUpdateCREvent` also uses `serviceStatus` and `numServeEndpoints` to check if it has converged. This addresses the issue described here: #1838 as `numServeEndpoints > 0` can potentially indicate whether the serve service is ready to redirect traffic.
- `RayServiceDeleteCREvent` checks for convergence based on the …
=> [RayService] Refactor to Rely More on RayService Status in RayService E2E Tests

ray-operator/controllers/ray/raycluster_controller.go
The name of the RayJob controller is `rayjob`, and the name of the RayService controller is `rayservice`. However, the name of the RayCluster controller is `raycluster-controller`.
* Without this PR
* With this PR
=> [Structure Logging][1/n] Make the format of the controller name consistent

docs/reference/api.md, helm-chart/kuberay-operator/crds/ray.io_rayjobs.yaml, ray-operator/apis/ray/v1/rayjob_types.go, ray-operator/config/crd/bases/ray.io_rayjobs.yaml, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_test.go, ray-operator/pkg/client/applyconfiguration/ray/v1/rayjobstatus.go, ray-operator/test/e2e/rayjob_lightweight_test.go, ray-operator/test/e2e/rayjob_test.go, ray-operator/test/support/ray.go
After this PR:
1. There will be two terminal deployment statuses(Inspired by [how K8s jobs define the status](https://sourcegraph.com/github.com/kubernetes/kubernetes@fc7325fbec0fe379694e58b82e09f99f166c5e6d/-/blob/staging/src/k8s.io/api/batch/v1/types.go?L531-533) and [how the Spark operator defines the terminal statuses](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/v1beta2-1.3.8-3.1.1/pkg/controller/sparkapplication/controller.go#L615)): 
- `JobDeploymentStatusComplete`
- `JobDeploymentStatusFailed`.  
2. If RayJob runs into `JobDeploymentStatusFailed`(Inspired by [how k8s job use `reason` and `message` fields](https://sourcegraph.com/github.com/kubernetes/kubernetes@fc7325fbec0fe379694e58b82e09f99f166c5e6d/-/blob/staging/src/k8s.io/api/batch/v1/types.go?L569-574)): …
=> [RayJob] Add JobDeploymentStatusFailed Status and Reason Field to Enhance Observability for Flyte/RayJob Integration

ray-operator/controllers/ray/common/association.go, ray-operator/controllers/ray/common/association_test.go, ray-operator/controllers/ray/raycluster_controller.go
Follow up https://github.com/ray-project/kuberay/pull/1920/files#r1503536623
* Manually test 
* Create a multi-host RayCluster https://gist.github.com/kevin85421/735a6243dbe3ec1fcd37d10e6100f4a8
* 1 head + 4 worker Pods
* headless svc should be created
* The endpoints `raycluster-complete-headless-worker-svc` should have 4 addresses.
=> [Refactor][Multi-host] Create a function to associate RayCluster and the headless svc

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go, ray-operator/controllers/ray/suite_test.go, ray-operator/main.go
Currently, KubeRay log messages lack information about which CR is being processed. Hence, we can't search the logs based on the namespaced name of the CR in the logging infrastructure. This PR adds the context information to the logger: `logger := r.Log.WithValues("RayCluster", request.NamespacedName)`.
* With this PR
```
{"level":"info","ts":"2024-02-27T23:20:02.309Z","logger":"controllers.RayCluster","msg":"Reconciling Ingress","RayCluster":{"name":"raycluster-complete","namespace":"default"}}
```
* Without this PR
```
{"level":"info","ts":"2024-02-28T00:04:17.240Z","logger":"controllers.RayCluster","msg":"Reconciling Ingress"}    
```
* [example log](https://gist.github.com/kevin85421/ec7bcdfdd2f67bcc3e1769d2aee3bd57) (1 RayCluster + 1 RayJob + 1 RayService)
=> [Structure Logging][2/n] Add context to each log message

ray-operator/controllers/ray/raycluster_controller_test.go
All tests in envtest couple together. This PR separates the old tests into 3 categories, autoscaling, static, and suspend. After this PR is merged, I will work on some tests for multi-host.
=> [Refactor] Rewrite RayCluster envtest

ray-operator/controllers/ray/raycluster_controller_test.go
Add envtests for multi-host. This is the follow up for #1913.
=> [TPU] Add envtests for multi-host 

ray-operator/controllers/ray/common/pod.go, ray-operator/controllers/ray/raycluster_controller_test.go
Currently it is possible to specify a namespace in the pod template that is different from the namespace of the RayCluster. I haven't found a use-case where this is needed. This PR disallows namespaces for Pods outside the namespace of the RayCluster.
=> ray-operator: disallow pod creation in namespaces outside of RayCluster namespace

ray-operator/controllers/ray/raycluster_controller.go, ray-operator/controllers/ray/raycluster_controller_fake_test.go, ray-operator/controllers/ray/rayjob_controller.go, ray-operator/controllers/ray/rayjob_controller_unit_test.go, ray-operator/controllers/ray/rayservice_controller.go, ray-operator/controllers/ray/rayservice_controller_unit_test.go
As @astefanutti suggested here https://github.com/ray-project/kuberay/pull/1945#discussion_r1503835776, it could be better to use the `LogConstructor` option to construct a logger because the logger is shared between controller-runtime and the controller itself.
But I then gave the wrong [example](https://github.com/ray-project/kuberay/pull/1945#discussion_r1504214798). Now I would like to fix that.
This PR uses the `LogConstructor` inside the `WithOption` call instead of a `WithLogConstructor`, which will be overridden by the former one, and then removes the no longer needed`RayClusterReconciler.Log`.
The `r.Log` loggers in the tests are also removed since they were already not used in tests previously.
This is what the logs look like, including the reconcileID. …
=> [Refactor][RayCluster] Replace RayClusterReconciler.Log with LogConstructor

.buildkite/setup-env.sh, .github/workflows/actions/compatibility/action.yaml, .github/workflows/test-job.yaml
We are using a very old version of kind in our testing this is causing us to pull a very old image of kind nodes and test against a really old version of kubernetes. Logs below are from `[Compatibility Test - Nightly](https://github.com/ray-project/kuberay/actions/runs/8104366012/job/22151018968?pr=1955#logs)`
```
2024-03-01:00:17:27,958 INFO     [utils.py:356] Execute command: kind create cluster --wait 900s --config /home/runner/work/kuberay/kuberay/tests/framework/config/kind-config.yaml
Creating cluster "kind" ...
• Ensuring node image (kindest/node:v1.21.1) 🖼  ...
✓ Ensuring node image (kindest/node:v1.21.1) 🖼
• Preparing nodes 📦   ...
✓ Preparing nodes 📦 
• Writing configuration 📜  ...
✓ Writing configuration 📜
• Starting control-plane 🕹️  ...
✓ Starting control-plane 🕹️
• …
```
=> Update kind version.

docs/release/helm-chart.md, helm-chart/kuberay-apiserver/values.yaml
I found that the KubeRay API server is currently using DockerHub instead of Quay when I published the Helm charts for v1.1.0-rc.0 (https://github.com/ray-project/kuberay-helm/pull/31/commits/044dbec1b451c29931570e431df371f3fc73fb5b). However, at this moment, we don't publish images to DockerHub.  
=> [release][v1.1.0] Improve release doc and update KubeRay API server chart's repository

helm-chart/ray-cluster/templates/raycluster-cluster.yaml
https://github.com/ray-project/kuberay/pull/1834 added NumOfHosts field to RayCluster WorkerGroupSpec. This PR updates the helm chart to include this field for Kuberay v1.1.
=> Add NumOfHosts to RayCluster helm-chart template
